### ISSUE TITLE
Building and interacting from adjacent tile

### ISSUE THREAD

**Issue by Sommerbo** [TeamPorcupine/ProjectPorcupine#1003]
Toons stand in the target tile when building and in interaction tile when interacting.
This looks odd when building and is logically wrong esp. when building walls, when feeding the power generator it leads to really slow walk when replenish the uranium.

Changing to building/interacting from adjacent tile would make sense.

**Comment by Fatalexceptionz** [comment]
There's already flags in the data for this iirc, they just need to be checked.

**Comment by koosemose** [comment]
This has been implemented. Closing.
