### ISSUE TITLE
Floor tile idea- Keep track of how often it is stepped on

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1004]
I've stated I don't like the floor tile. One thought I just had was to keep track of how often a tile is walked on, and change accordingly. If a tile is heavily used, it will start to look more worn after a while. It seems easy enough to do, and could be a cool effect. Thoughts?

**Comment by Sommerbo** [comment]
I like it. I am a fan of dirty/used space look.

**Comment by Fatalexceptionz** [comment]
Space janitors!

**Comment by kd7uiy** [comment]
That could be an interesting idea... Clean the dirty floor periodically, otherwise, not sure what happens, bad stuff?

**Comment by bjubes** [comment]
Maybe very dirty floors slow movement? Or do a rimworld beauty mechanic? Either way keeping track is a good idea

**Comment by vogonistic** [comment]
Not sure about slowing movement, but it might increase the rate that they get sick, failure rate on things that require concentration (sneezes and stuff) and happiness.

**Comment by kd7uiy** [comment]
Increased chance of tripping?

**Comment by koosemose** [comment]
Rather than tracking how much a given piece of floor is stepped on, how about every time a floor is walked on there is a small percentage chance that it gains a "dirtiness level", less data to track, it would be less deterministic, and it would be relatively easy to have other activities have a higher likelihood of making it dirty (so walking is 1% chance for example, running is 5% chance. Also these are completely arbitrary numbers and examples for illustrative purposes). It would also be possible to have different characters just be generally messier (character with a slob trait for example may double the chances of dirtying the floor).

**Comment by kd7uiy** [comment]
I like the random tracking idea, that makes sense as well.

**Comment by kd7uiy** [comment]
Okay, so let's do this. I believe this would be a good beginner project to do. For the time being, let's have the character call a function each time a Tile is stepped on. That function for now will add 1 to a float value that keeps track of how much a tile has been walked on. We can then enhance this further, as desired, to include random wear and tear, character based wear and tear, etc.

**Comment by Tranberry** [comment]
How do I vote against this? only blood should tarnish the floors.. *I'm trying to make a joke please don't be offended*

**Comment by vogonistic** [comment]
If we are talking about dust, walking on it would probably clean it, or move it to a neighboring tile.

**Comment by kd7uiy** [comment]
That's only for fairly heavy dust. But I'm talking more of the standard wear and tear that tends to happen.

**Comment by vogonistic** [comment]
I was responding to the alternative ideas that were proposed.

I think adding dirt and grime is an easier thing to deal with. If we have wear and tear on the floor, does it eventually break and we have an explosive decompression and does different materials for the floor have different strengths? If we add dirt instead, it we could add a mechanic that make the characters unhappy but with no catastrophic results.

**Comment by Tranberry** [comment]
If we add deterioration of stuff I would like that to be realistic so that the door will fail after a couple of years in game and not like it is in many current games, eg everything is made of paper and break by just existing.. On top of that, the repair of things should not be a click fest.
