### ISSUE TITLE
Pressure door improvements

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#1006]
This relates to the merged PR #976 and is probably already planned and known, but I wanted to list it somewhere. Let me know if it's duplicate info captured somewhere else.
1. The pressure door has no indication if it can be opened or not
2. Path finding still tries to go through the door
3. The context menu needs to be dependent on the mode. "Enable pressure lock" and "Disable pressure lock" vs "Toggle pressure lock"

@koosemose

**Comment by koosemose** [comment]
1. I would like a visual indication at a minimum (red or green light) as appropriate, would of course need to be added to Airlock door sprites. But at the size of the doors that would be relatively subtle, do you have any suggestions on a more overt way to indicate this without being jarring?

2. This is part of the reason I was so interested in #997 So I could more cleanly alert pathfinding if the airlock door will never open (of course pathfinding should still go through it if it can cycle the airlock and it's worth waiting the time for it to do so).

3. I would love to do this, but was not able to find an example of our context menu being able to be dependent on the state of the furniture? Is it capable of doing this, and if so are there any examples present that I could ~~steal~~ take inspiration from?

On top of your suggested improvements, I have a few more that I intend, some of which require more framework elsewhere.
4. Airlock Door should allow itself to close when pressure-locked, as it stands if you're quick on the button you can lock it open by turning on the pressurelock while someone is passing through it.

5. To actually be able to build a proper Airlock, the airlock needs a way to access what furniture is in the room and identify what side of the door should be pumped, preferably without having to search through every tile at least, and preferably not even having to search through every furniture every time it needs to activate a pressure pump.

6. Not directly part of the Airlock door itself, but we of course need a way to pump the air out of a room at a reasonable rate.

**Comment by Grenkin1988** [comment]
@koosemose Are you working on this?

**Comment by koosemose** [comment]
For most of it I'm waiting on other things, at a minimum the air pump, and preferably whatever becomes of RoomBehaviors.

**Comment by mikejbrown** [comment]
Any movement on this?

**Comment by koosemose** [comment]
Somewhat, most work has been tangentially related atm, trying to get the broader airlock behavior functional in #1441
