### ISSUE TITLE
Furniture animation

### ISSUE THREAD

**Issue by Raketfart** [TeamPorcupine/ProjectPorcupine#1009]
I would like to expand the character animation system to be useful to furniture as well.
That would mean the we could:

- use the shader to change color of indicater lights on the furniture.
- Add animation definitions in xml, and lua could just ask to play a certain animation
- Add animation that should observe some value, and change accordingly (like door openness)
- Run an animation when "jobworked" and another when not

These are just some of my thoughts on this - please add ideas and wishes

**Comment by vogonistic** [comment]
We absolutely need this. Blinking lights, power surges through the tesla coils and just indications that things are online and working. My space-lasers will also need to be able to swivel at some point.

**Comment by Ohda** [comment]
Can we use this to lights the rooms with some furnitures like a space lampposts, projector ?

**Comment by Raketfart** [comment]
@Ohda Probably not as a part of this shader/animation system. But we definetly need lighting at some point.

**Comment by sboigelot** [comment]
Furniture animation now exist.
Ligth should be a different topic
