### ISSUE TITLE
3D version of Project Porcupine

### ISSUE THREAD

**Issue by cskiwi** [TeamPorcupine/ProjectPorcupine#1017]
Hi,

I was wondering, if there were persons interested in making a 3D version of the game?
I always liked a 3D game more then a 2D (top down) game.  and I was thinking about how hard it would be to convert it, 

And i think that it shouldn't be that hard to convert. I had in mind only the following steps:

- Replacing the sprites with 3D objects (x and y would still be the same, add a z which value could be '1' on the first version)
- Modify the A* alogritm to allow a x,y and z (again first version could just have a flat world)
- Change the camera controls to allow 3D manipulation
- Change the click functionality

I think the most difficult part would be the mouse (knowing where the user clicked)

Placing of objects shouldn't be a problem as it's still going to be tile based, so 1 tile could only have 1 object

Or am I missing something?

**Comment by UnknownSoldier1** [comment]
I think it would be too late for that, but I don't really see any benefits of making it 3D tbh... And the mouse clicking would be a simple raycast, that would be the smallest issue.

**Comment by cskiwi** [comment]
There are no real benefits, just it's appearance ;)

**Comment by bjubes** [comment]
Honestly, If u want to make a 3D version once the game is actually in a workable state, all the power to you. Thats the beauty of open source. I highly doubt that the official version will have 3D though.

**Comment by kd7uiy** [comment]
It's not too late at all to do it, all that would really need to be re-done is the Sprite Renderer, to put 3-d models instead of sprites. Still, I'd suggest holding off on this for a while.

**Comment by Mizipzor** [comment]
Nope, no interest from my side I'm afraid. :)

But the beauty if Github is that anyone can fork this project and make whatever spin-off they want, 3D being a rather good example. Go for it.

**Comment by alexfriesen** [comment]
You could create a mod for [SpaceEngineers](https://github.com/KeenSoftwareHouse/SpaceEngineers)

**Comment by vogonistic** [comment]
It'd have to be a fork.

If the fork is successful and keep sharing a lot of the engine, there might be a point where we discuss splitting the engine and the game into separate repos, but I don't think there is enough interest right now.

**Comment by bjubes** [comment]
well that seems like a consensus, close this?

**Comment by cskiwi** [comment]
Yep looks like a good idea :)

**Comment by ComputerOverlord** [comment]
So in #1423 everyone prefers 3D... but in this everyone is against it...
