### ISSUE TITLE
Resource packs / themes

### ISSUE THREAD

**Issue by cskiwi** [TeamPorcupine/ProjectPorcupine#1018]
Wouldn't it be fun, if you could have live (or start of a game, and link it to a specific save) switching of resource packs?

They could change the following parts:
- Change the objects(obviously)
- Change the font
- Change the ui
- Change the object names (O2 could possibly change with air-pollution, in a not-space themed resource pack)

This could be combined with resource specific mods (which could be another feature, combine resource packs with modpacks, that can be switched on the fly)

**Comment by Tranberry** [comment]
just start drawing mate, there is nobody stopping you :+1:

**Comment by Grenkin1988** [comment]
Switching - very cool :+1: Live - not very good :-1:

**Comment by cskiwi** [comment]
@Grenkin1988: the live could just be start of a game, so each map has it's own resource pack :)

**Comment by bjubes** [comment]
Techincally mods and resource packs are the same thing, only resource packs would just contain almost no lua or xml files, just art sound and fonts

**Comment by Mizipzor** [comment]
Isnt this better handled by the mods?

**Comment by NogginBops** [comment]
I like the idea of having data like that linked to the save. Recource packs are a good idea if ingame switchable mods are not a thing.
