### ISSUE TITLE
Seasons like system (Beta Angle)

### ISSUE THREAD

**Issue by cskiwi** [TeamPorcupine/ProjectPorcupine#1019]
Another thing that could be added is the idea of Seasons, 

but instead of we moving around the sun, the sun moves around us. this would for example change:
- Temperature
  - This could require specific space suits (that have to be researched?)
  - the type of material in the asteroids at that time (diamond when the sun is very close ?)
- types of gasses that are around 
  - you could use/harvest a specific type of gass when the sun/mars/other planet is close/far ..;
  - those gasses are needed for higher level machinery 
- machines work slower due to the gravity of large planets (and faster when there is no gravitational influence)

and I think you guys could think of more stuff :)

**Comment by Tranberry** [comment]
you are talking about a non- circularized orbit around the closest star right? That would be cool.

**Comment by kd7uiy** [comment]
There are no seasons in space. Some of the other stuff might be considered, but I think we need to think the backstory a bit more carefully first. What exactly are we supposed to be doing? Building an orbiting space station? Free from any object? Something else?

**Comment by Ajapeu** [comment]
Seasons is probably not the best word for it - but is there a logic to a system that would provide "variation" in the environment somehow?

**Comment by Mizipzor** [comment]
Its a neat idea but I think you got it backwards. If there are seasons on this space station then its because the space station changed its orbit. This could be an interesting mechanic where you use fuel to change distance, and temperature, so machines operated differently.

**Comment by kd7uiy** [comment]
For orbiting spacecraft, the closest there is to a "Season" is known as a Beta Angle. Essentially, as the spacecraft orbits the Earth, the angle with respect to the Sun changes. For the ISS, about every 2 months it goes from a max sun to a min sun, changing the thermal properties, etc. This would be a real pain to implement properly, and just make the game confusing I suspect.

An elliptical orbit would periodically pass closer to it's host body. Resources being gathered is unlikely, but it could change the thermal state of the object somewhat.

Disclaimer: I'm a moderator at http://space.stackexchange.com, and have worked with satellites before, so I'm kind of obsessed with such details.

**Comment by Tranberry** [comment]
@kd7uiy with an extreme non-circular orbit wouldn't solar panels be more and less effective?

**Comment by kd7uiy** [comment]
Yes, indeed they would be.

**Comment by vogonistic** [comment]
There could be seasons of a kind since it's cheaper to travel from one place to another in a solar system only at certain times, so the octopi, pirates and traders could come more often during certain parts of the year.

**Comment by kd7uiy** [comment]
It seems the popular thought is to have us in some kind of deep space, like an asteroid belt. It wouldn't be difficult to give an orbit to a few key points, and make events more likely to occur if we are close in the orbit to them.

Slightly more difficult would be the eccentricity of an orbit, which I suppose we could include, but I would recommend being 0. The inclination also wouldn't be that difficult, but I suggest ignoring it entirely, it's not really the focus of the game at all.

Beta Angle only applies if we are orbiting an object, which doesn't seem to be the popular idea for the game.

**Comment by sboigelot** [comment]
Well, this is a future were a future corporation is having a very advance technology and almost all-power.

The ceo of QuillCorp can just be nostalgic of the past season of his home land and decided to heat-up and down the universe at regular intervals. Just for fun and sometimes at random.

hehe, no this is too crasy, but we can see season as something much easier then temperature.

Sometimes, at regular interval, our location in space can be visited by more asteroid crossing our path: "The Stone Shower Season". Sometimes, it could be regular radiation from a nearby pulsar. etc, Season do not have to mean temperature.
