### ISSUE TITLE
Made some characters for fun, had to share.

### ISSUE THREAD

**Issue by Tranberry** [TeamPorcupine/ProjectPorcupine#102]
![q18-basebuilder-characters](https://cloud.githubusercontent.com/assets/16529/17755452/456fa39e-64da-11e6-851a-2d25a2b67aaf.png)

Hope you find them as funny as I did. CC-BY if any one is curious.

**Comment by ComputerOverlord** [comment]
These are REALY good! You need to pull request this sometime!

**Comment by SquareMan** [comment]
Would definitely be a nice addition, even if they aren't usable yet. Someone else could easily come along and make the character's use different sprites.

**Comment by Tranberry** [comment]
These are just placeholder fan-art, I guess the game will have characters that can change clothes and such. Then there are much better ways to make a base character than these _sillynauts_.

**Comment by Tranberry** [comment]
I'll be closing this now I guess

**Comment by satch3l** [comment]
These could definately be inspiration to the final art. I like the idea of the humans having custom spacesuits for spacewalks.
