### ISSUE TITLE
Where is this game set?

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1023]
Okay, so we know the game is in space, but where in space? Are we building on Mars? Asteroid belt? On the Moon? In orbit around Earth? Deep Space? Each of these has different conditions which we should consider the impact of. Perhaps we could even set a config file that allows for setting these options, to give optional play. But in any case, we should at least pick one of these, which will bound the flow of the game considerably. Here's an example of how I think each of these could be different:

* Moon- Mining rocks can produce oxygen, and aluminum is more common. No atmosphere.
* Asteroids- Could go from asteroid to asteroid, collecting materials from there. This seems to be similar to what we are doing now, but a bit more thought might help.
* Mars- Has a non-breathable atmosphere, but could be used as raw stock to produce some.
* Earth Orbit- Have to worry about thermal cycles, not a lot of raw resources available.
* Deep space- No thermal cycles, no solar cycles to worry about, but wouldn't have many resources either.

**Comment by kd7uiy** [comment]
Now that I'm thinking about this more, I think the right idea is to have a series of "worlds", starting from the relatively simple and ending with something quite difficult. This would keep the game interesting as one plays it for longer, changing the items that are useful as one progresses.

**Comment by abackwood** [comment]
So sort of like the persistent world in Dwarf Fortress? That could be interesting.

I've always seen this game as taking place in vacuum space, not on planet surfaces. Where your station orbits is still up for variation. I think we should definitely have ways that your place changes your situation, and thee place is chosen either at game start or can be changed in the middle with great effort.

An important aspect of your place that is important is trade frequency and type. The closer you are to civilisation, the more frequently you trade.

**Comment by vogonistic** [comment]
We should support most of this as parameters to the world generator. Personally, I really like the asteroid belt as a setting.

**Comment by Tranberry** [comment]
I would love if we had a 'galaxy' generator like DF have a world generator and most of these scenarios if not all should be possible with that generator. So I'm basically just supporting @vogonistic with this comment.

**Comment by springmouse** [comment]
you see what i think would be cool and i am just going to let my imagination go wild here, is if we started of in a solar system with lots of points of interest. Each one would have there own map so an example would be an asteroid belt or a gas giant maybe even a warp point where all ships coming to visit must exit and enter from  (there could be more then one) and then the player expends through out the system colonizing it and collecting all the resources they need and building defenses to defend the warp points from pirates and what ever

**Comment by dusho** [comment]
when I saw the game with the skybox, I kind of hoped that you would FTL with your ship in another location, gather some resources, improve your ship, FTL back to station, unload some resources for new devices or new ship construction, FTL somewhere again, have some space fight with pirate ship, loot some and so on.. This would make it different from Rimworld (exploration) but still keep base building, improving and survival.

**Comment by Tranberry** [comment]
@dusho sounds similar to a game called starbound.

**Comment by kd7uiy** [comment]
I've taken some of the key thoughts that I think we all agree on and put them in the summary of the Game Design Document I started on the Wiki, found at https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Design-Doc . We need to better document what is in the scenario as well.

**Comment by Tranberry** [comment]
@kd7uiy can you specify what a scenario in this case is?

**Comment by kd7uiy** [comment]
@Tranberry Just added some to the Game Scenario page, see https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Game-Scenario

**Comment by Fogsight** [comment]
Closer to reality it's either methane-ammonia-water mining operation, cause that's what asteroids mostly are. Or a tourist destination placed in one of the Lagrange points. 

More Sci-Fi-ish would be Babylon 5/DS9 direction. Trade Hub/Diplomatic outpost. Maybe aliens built an initial Hub to communicate with Humans. Or maybe your crew maintaining a neutral station to communicate with Cylons, until Six finally arrives...

**Comment by kd7uiy** [comment]
Asteroids have quite a bit of iron as well, and other valuable materials. Of course, mining in a station doesn't exactly work well. I think the deep space operation would be quite difficult, to say the least, to support any kind of reality, but that might do well for a final test.

**Comment by kd7uiy** [comment]
Per a good discussion on Discord, there are a few possibilities we are working through, which are similar to those discussed here. Some common themes

* We all agree that we should be based on asteroids.
* There is also a desire to not limit the entire operation to a single base, to have some connection to other asteroids, although how is in question.

A few ideas that are more difficult to reconcile

* One big massive base, with occasional missions sent out.
* Start out in a single asteroid, mine it until nothing is left, then use that asteroid in the background for a future colony.
* Start out with one rock, then send missions to get other rocks, until you have a collection. Each rock will have unique resources to unlock new features.

**Comment by koosemose** [comment]
Just to throw in my opinion, here's the gyst of my opinion on the matter (direct copy paste from a discussion on discord:

My "if we can do anything" idea is that basically when you start you are presented with a random star system, you choose where you're going, simplistically there are three "groups" of things, terrestrial (rocky) planets, asteroid belts, and gas giants. Each has their own benefits and drawbacks.

Terrestrials are the easy option, due to broad spectrum of resources, I think Asteroid belt would be next, as there are less broad resources, but better chance of rare stuff and more danger, and then gas giants which are really dangerous, due to gravity, and an assortment of other things.

You get set up in your initial location, going as you can, once you are at a stasis point where you can work on things not immediately affecting your survival, you begin surveying other locations (either via drones, or sending out scout ships) to get an idea at what is at a given location. Research technology to allow your ships to either transit between locations faster or just have longer reach.

Then once you have a worthwhile location, you send an actual party there that can either just gather resources directly or set up an automated base there (or maybe just an entirely new base and start operations from there if that's your preference)

**Comment by kd7uiy** [comment]
Okay, there are 4 ideas that I see constantly discussed, each with their own pros and cons. It would probably be best to ultimately let the player decide which of the options he wants to choose. The ideas are:

* Asteroid Belt
* Planet Side
* Orbiting around a planet
* Deep Space

Of these, the most challenging would be Deep Space, due to the lack of nearby resources. More could potentially be added later on. 

So, let's take someone who is interested in each idea, and discuss how we could make it work. Let's bring what we have to a separate issue for each of the 4 ideas. Then once each of the ideas is a bit fleshed out, let's come back together and see how we can make a somewhat unified game out of the principals that people want to see.

Specifically, let's try to focus on the player experience for each of them, as in, how would they describe the game after they've played it for an hour, in 30 seconds or less.

**Comment by koosemose** [comment]
Orbiting a planet can actually be broken down into two different groups, as orbiting a terrestrial (rocky) planet is vastly different than orbiting a gas giant.

**Comment by kd7uiy** [comment]
This topic has been covered pretty well in the various sub-topics, let's just close this issue for now.
