### ISSUE TITLE
[Suggestion] ULog Channels as enums/static strings

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#1026]
Currently, ULog takes channels as a string, which leads to problems when you don't know all the possible/existing channels, or if you make a typo and open a new channel by accident. This is exactly what enums are meant to solve and i think we should use them instead for both of these reasons.

Since enums map to ints, we could alternatively use a static class to define the channel types. like:

```
public static LogChannel
{
public string Lua = "Lua";
public string World = "world";
...
}
```

**Comment by mikejbrown** [comment]
We could always hack UberLogger to enforce an enum as the channel argument. Otherwise there is really nothing to stop someone from goofing up the channel anyway. Using this `LogChannel` class is an honour system.

Pros: Central list of all channels in use; handy auto-completion
Cons: Yet another boring list thing to keep up to date

**Comment by bjubes** [comment]
i think keeping it up to date would be easy, when you want to log something just hit Go To Declaration and add your own string/enum.

If we use an enum, then we can enforce using only the specified channels, if we use static strings then someone could mess up the system (we could check if the string entered exists in the `LogChannel` class, but this is kinda overkill).

**Comment by mikejbrown** [comment]
Okay. One more question: is there ever a reason to generate channels at run time?

Hmmm... perhaps there is a case to be made for populating channel names from the installed mod list.

**Comment by vogonistic** [comment]
I'm not of a very strong opinion, but I think we can fix whatever problems and typos we have in the log channel names with a small PR.

Per mod channels sounds pretty amazing. Maybe we should export a log function that is unique per mod and uses the name as channel.

**Comment by Grenkin1988** [comment]
At least please add private/public static readonly field to class where you use Log with its chanel name.

**Comment by mikejbrown** [comment]
@Grenkin1988 sounds like a good little Stylecop Saturday style refactor project.

**Comment by BraedonWooding** [comment]
@koosemose still relevant?  Due to your new debugging implementation?

**Comment by bjubes** [comment]
Not really. The current system is fine for now.
