### ISSUE TITLE
Idea: Pirates

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#103]
I realise that this early... But... This just might work..
So pirates come (when everyone is sleeping?) and steal stuff from stockpiles.

**Comment by ComputerOverlord** [comment]
I will remove if you feel this is irrelevant

**Comment by NogginBops** [comment]
I feel that this might be irrelevant at this stage in development. BUT! I do think that these questions are worth considering at a later date. So I would suggest you write these ideas down on a text document and bring them up again when we are at a relevant stage in development.

**Comment by ComputerOverlord** [comment]
Alright. I'll take this down and (hopefully) bring it back.

**Comment by kd7uiy** [comment]
Okay, so it's really weak, but we are starting to put together a few ideas for what this might be like. (#gamedesign, participates myself, @vogonistic @Tranberry @koosemose @powli 

* Pirates could be of really 3 forms. The traditional large ship blasting you to get you to surrender so they can steal all of your stuff.
* Sneaky pirates- Using a small, hard to detect ship, they sneak on board your ship.
* They could be residents of your station already, tourists or the likes.

What will they do?

* Steal stuff
* Most won't be set to destroy anything that doesn't give them an advantage, either in stealing more stuff or in leaving safely.
* Some will be bent on sabotage (Corporate raiders)
* Kidnap people (Hostages?)

Timeline for completion: Not anytime soon. This isn't a core game mechanic, so after those are complete, we can start more seriously figuring out how to include this.

**Comment by sboigelot** [comment]
I would also love to see "trade" ship docking at the player station, but when it opens, boom, plenty pirates!! It would make accepting a ship to dock a potential danger

**Comment by kd7uiy** [comment]
Nice thought, I'll add it to the list when I put it on the wiki!

**Comment by kd7uiy** [comment]
Another thing that pirates might do is assault people. This would probably leave them demoralized, and possibly injured. If they run in to a person, we should probably have an attack of some kind that either hurts or demoralizes the crew (Unless the crew member wins the fight, of course)

**Comment by kd7uiy** [comment]
I've added these details to the [Wiki](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Design-Doc#pirates--tentative-03-build). Let's leave this open for another day, to make sure I have the notes accurate, and then close this issue. Future issues can be opened for more changes.

**Comment by buggy213** [comment]
Having slaver ships that come by which you can use to increase your workforce could be another possibility

**Comment by koosemose** [comment]
This issue has stalled out, and what has came from it has been documented. Closing.
