### ISSUE TITLE
File organization- The Model Folder

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1036]
Okay, the Model folder is pretty out of control. I count over 20 different .cs files in there right now, plus 5 folders. It seems a bit more organization is required. I think we should create the following folders, and use them. Furthermore, I would propose a moderator make the change to lessen the likelihood of conflicts.

* Character
* Job
* Inventory
* Furniture
* Event
* Environment
* World (Can include Tiles and Rooms as well)

That leaves 11 folders, which is probably too many as well, but I don't see a way to do much more grouping than that. Thoughts?

**Comment by vogonistic** [comment]
There is a lot of classes in there that probably shouldn't be there too. How many of them are actually models?

**Comment by Raketfart** [comment]
I think a folder for character would end up with just character.cs (and maybe some animation / event / Needs classes that also belong in Furniture).
I'd prefer to have folders for Areas/Systems like we are mostly moving towards now:
AI
Animation
Event
Entity? (characters/Enemies/furniture/tiles/rooms)
Needs
Power
Quest
Spacetravel
UI

I agree that we have many models that are more like controllers in the models folder (I am guilty of at least the CharacterAnimation.cs file)
