### ISSUE TITLE
Proposal- Blog

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1037]
It might be helpful if we had some sort of a blog, or other means to indicate what the progress is of the game besides just looking at change logs. There's a lot of things that are happening that if one isn't paying attention can pass one by. I'm not quite sure what would be the best way to make this happen, but I wouldn't propose everyone edits it, rather only a few people who are pretty careful at keeping up to date with what's happening.

**Comment by vogonistic** [comment]
I think it'll have more value when things slow down a little but, but I'm a huge fan of the Factorio Friday Facts posts. Here is the one about the GFX pipeline: [FFF 146](https://www.factorio.com/blog/post/fff-146)

**Comment by kd7uiy** [comment]
It might be sufficient to just post something on the official Reddit page, maybe on Fridays as you suggest.

**Comment by kd7uiy** [comment]
I'm going to close this for now, there's just not a lot of traction for it, so...
