### ISSUE TITLE
[BUG] There is a bug in power system

### ISSUE THREAD

**Issue by Grenkin1988** [TeamPorcupine/ProjectPorcupine#1038]
Right now if you add 4 oxygen generators (-1) and one solar panel (+3)
They will work.
This is because right now system does not see 4 objects it see only 1. (`HashSet<Connection>`)
This is because I forgot to `Clone()` `Connection` from one `Furniture` to other

**Comment by Mizipzor** [comment]
Good find.

**Comment by kd7uiy** [comment]
This seems like a relatively easy bug to fix? Might be a good case for the "beginner" tag.

**Comment by Grenkin1988** [comment]
If someone want to do this, I am OK with. But I am going to fix it in the evening.(UTC/GMT +3 hours)
