### ISSUE TITLE
[Bug] SkyBox not working after build 

### ISSUE THREAD

**Issue by Ohda** [TeamPorcupine/ProjectPorcupine#1044]
I was wondering why the skybox is not rendered when the game is builded.

**Comment by mattpott** [comment]
Is this still the case?

**Comment by Ohda** [comment]
For me yes. I build  a PC game but when i run it, there is black background

**Comment by mattpott** [comment]
Can the issue be closed then?

**Comment by Grenkin1988** [comment]
7 days old bug is not good :-(

**Comment by sboigelot** [comment]
I confirm this issue is also happening on my computer.

**Comment by koosemose** [comment]
The LoadSkybox method in World searches for skyboxes to use treating Resources as a normal folder, which it isn't when the project is built. I'm not sure how to mimic the current functionality, doing it properly, without hardcoding the list of skyboxes.
