### ISSUE TITLE
Quests dialog scrolls outside mask

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#1045]
when scrolling in the quest dialog, the content bleeds over the edges of the dialog.
![dialog](https://cloud.githubusercontent.com/assets/7608114/18095493/27584792-6ea5-11e6-9289-dd2b35862faa.gif)
This should be an easy fix (Hint: fix/add  scrollmask)

**Comment by Said6289** [comment]
I noticed this too and tried to fix it. I'm new to the project (and also trying to get back to working in Unity, so I'm having to relearn lots of things) and I'm still trying to get my head around its structure. What's confusing me is the following: In the UI\DB_Quests prefab, where is the RectTransform referenced by QuestItemListPanel (DialogBoxQuests script)?

**Comment by Tritaris** [comment]
#1051 fixes this.
