### ISSUE TITLE
Discussion: Possible sources of raw resources

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#105]
Where do we get resources in space, outside of internal mining drones?

* Asteroids: Metals, Stone
* Comets: Water
* Planets: Anything
* Traders: Anything
* Pirates: Cannibal food

Where else can you get raw resources? There is also a big question on how that would work. Does asteroid mining involve sending a drone that tosses resources at you in intervals, do you send people and drones on missions that bring back bulk items, or do we just stick to how the internal mining drone work?

**Comment by NogginBops** [comment]
@vogonistic An idea I had was that there might be asteroids generated around the map and you could either send out people and drones to mine them or build on or to the asteroid and setup a whole mining operation. But yeah I think this is a question to be considered for the future.

**Comment by vogonistic** [comment]
Maybe an early implementation would just be to spawn asteroid chunks all over the empty space around the starting point. We could start utilizing that as soon as we have:
- navigation in space
- space suites
- airlocks
- mining jobs

This issue could wait, but it's also something that can be useful as a tangental force to drive people to implement the needed features. Right now, it looks like there is a lot of interest and drive, but no list of things that people can jump on.

**Comment by NogginBops** [comment]
@vogonistic What you are saying about there not being a general list of things to do in the future. I think  there where some attempts to make a road map type deal, but I don't think it got very far.

**Comment by SquareMan** [comment]
I like the idea of having natural asteroids generated throughout the map. That would provide a nice way to fill out some of the space (pun not intended) as well as help sell the theme.

Planets would be a cool addition as well but how should that be implemented? Perhaps as a separate map, unless the main map is greatly expanded in size. But then what's to stop the player from just leaving space and colonizing a planet instead? Or should that be the goal? So many questions to answer.

**Comment by vogonistic** [comment]
Correct about the todo list, but other than space suites I don't think those things needs to be deferred into the future.  

- navigation in space could at first be done optimistically by assuming an uncluttered space and moving in a straight line in the direction of the target
- airlocks are just a special door that adds an interesting extension of the o2 handling
- mining jobs can initially work like the internal mining droid, just attached to the asteroids instead

**Comment by NogginBops** [comment]
Maybe just one planet per map. Its not uncommon for a planet to have a plethora of different materials. I mean look at earth, its just a matter of how hard they are to find.

**Comment by vogonistic** [comment]
@SquareMan Planets and other off-map mining missions might initially just be you sending your people away and later they come back, but later we might add functionality to switch between what World is shown while simulating all of the ones that have your people on them.

**Comment by ComputerOverlord** [comment]
Someone needs to add asteroids. Using kenney space shooter pack?

**Comment by satch3l** [comment]
So I've been wondering, is the player situated in a space ship or crashed on a planet? If it is, as I have presumed, the first one I think you are on the right track. 

- Mining droids should be an upgrade, which forces the humans to do spacewalks in order to mine e.g. asteroids at first.

- Oxygen can be extracted by electrolysing water

**Comment by lameox** [comment]
I think there is also merit in discussing how complicated/simple the finished system should get. 
By this i mean stuff like
- How many different base metals/ores/crystals/minerals exist?
- How many tiers of common goods (think electronics/gears/drones) are there?
- What is our aim in terms of progression speed? Does reaching the highest tiers of items take an hour? 3 hours? ten?
- How slow or fast is resource collection?
- Are resources limited or unlimited per map? If they are unlimited, is the unlimited income there from the start or does it require some technology?

I think those are questions we need to decide on before we should talk about our general economy.
Maybe the Economy discussion also deserves a separate issue.

I feel like we should keep the base game on the simpler side. That way we can leave quite a bit more flexibility for the modders to take the game in the direction they prefer.

**Comment by ComputerOverlord** [comment]
Asteroids: #175

**Comment by WardBenjamin** [comment]
Map Generation: #306

**Comment by vogonistic** [comment]
How do we add more resources and make them more interesting to get?

**Comment by kd7uiy** [comment]
I think we covered this better in issues like #1060 #1070 #1076 and #1078 . We should add somewhat scrap of incoming ships blown to pieces, but I think this might be better covered in those issues.

**Comment by WardBenjamin** [comment]
Agreed.

**Comment by Tranberry** [comment]
are you adding to the wiki @kd7uiy ?

**Comment by kd7uiy** [comment]
Sure. https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Resources
