### ISSUE TITLE
[Bug] Insta-Smelting

### ISSUE THREAD

**Issue by SquareMan** [TeamPorcupine/ProjectPorcupine#1050]
If you build a metal-smelter, save the game, then load that save, that smelter will smelt things instantly.

Update: by doing some looking at save files, it appears this is caused because Metal Smelter furniture params are saved properly, but not loaded at all.

**Comment by koosemose** [comment]
Yup, this is a known bug, fixed by #819, no furniture properly loads its parameters, however it's been stuck waiting for a consensus to be reached on a naming convention.

**Comment by SquareMan** [comment]
Okay my bad. I was working on dropping excess character inventory as well as fixing a few other things when I came across this.

**Comment by koosemose** [comment]
Nah, it's cool mate, better safe than sorry... it's not like there's an exhaustive list of all bugs that someone knows about and/or has submitted a fix for.
