### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1060]
This one has been bothering me a bit, but it's starting to get to be more of an issue. Let's talk about mining.

In deep space, the only source of resources is power from the Sun, trade, and resources gathered from asteroids and planetary surfaces. Putting a "Mining Drone" inside of a ship doesn't really make sense at all. It would make sense to put one of these on an asteroid.

What I'm thinking is that we might need to keep track of a resource layer of some kind, and either have a bonus in production if using an asteroid, or only allow production on such types of surfaces. Having a few loose items on the surface does make some kind of sense, but drilling would get more. They might even be tapped out eventually.

The same kind of thing applies to producing atmosphere, in reality you can't produce something from nothing. I know that hyper-realism isn't the goal, but mining a spacecraft without consequences in deep space seems a bit far fetched...

**Comment by koosemose** [comment]
The idea behind the Mining Drone isn't so much that it's the mining drone itself you're placing, but a mining drone control station. But having variance based on the environment could still be good (farther from asteroid it there's a longer time to get the resources, closer and your station faces greater danger of some sort), and having a chance of either the drone or the control station being damaged (or lost in the case of the drone) and needing repaired/replaced.

And actual O2 generation is surprisingly efficient, with relatively little lost (create O2 from water, scrub the CO2 from the air, combine and split and such with the hydrogen from O2 creation, back to O2 creation). It's actually not a very lossy system, but it would be nice if we had a system of actually needing a CO2 scrubber that could feed water back into the O2 gen, and needing a basic supply of Nitrogen (it's used even less).

**Comment by kd7uiy** [comment]
Producing O2 from water, atmospheric CO2, etc, makes sense. I think the Oxygen Compressor makes it without input resources, if I recall. 

CO2 scrubbers, however, aren't really on topic for this thread.

**Comment by dusho** [comment]
ye, I didn't get the mining drone device at all.. I thought it is some kind of placeholder to generate ore, to test smelting and construction...
maybe it would be nice to have some kind of 'prospecting' of asteroids, finding different minerals, placing mining stations at those spots and extracting raw ore from it? And yes, you can deplete the repository, find rare minerals and stuff..

**Comment by koosemose** [comment]
CO2 scrubbers are kind of on topic if they feed into the system that allows an O2 generator to function.

But yeah, in the tutorial videos quill definitely gave the idea that it was supposed to be a control station for a drone. More complexity in all the aspects is certainly things we should look to doing in the future.

**Comment by sboigelot** [comment]
I had the same concern as @dusho since the beginning, it seemed weird to me and more like a placeholder.

I did read in many issue the idea of having a solar system view. We could on that view send our drones in mining mission without having to actually move our base.

For instance, sending the drone mining an specific moon as we know from survey that that moon contain a high quantity of metal, or ice water.

This would allow and explain the switching of resources being mined by the drones and also allow for a lot of fun events, like drones being raided, or local inhabitant of the moon complaining about the capture of their citizen (yes, our tripod drones found a lot of water in theses skin-like walking bags)

**Comment by WardBenjamin** [comment]
Synopsis of Discord discussion:

Mining would progress from people -> drones -> more automated stuff.

As @koosemose said, the current "Mining Drone" would basically become a control station, where you would sit and operate drones. 

The drone controller would be upgraded to have more drones, to be operated automatically, etc.

Drones, upgraded separately from the controller, could be damaged if being operated automatically, and you would have to recover them to keep them. You could also break them down into their raw components. 

Damaged drones could also be worldgen.

**Comment by vogonistic** [comment]
I might be on the more extreme side, but I want to micromanage the mining and select what areas to mine. I also want to be able to mine in multiple z-levels a'la DF. 

I like the ability to build a mining drone, as long as it moves on the map just like a character does. There can be a control station that you build to control one or many drones and automates the mining for the people who want that.

But if we only have a single z-level, the asteroids won't feel like asteroids but flat discs.

**Comment by kd7uiy** [comment]
I'm going to say the same thing here that I did on chat. I think we have a few different ideas for what this should look like. Let's see if we can get a few prototypes of what is proposed. These don't have to work, some kind of a sketch would help, but I suggest at least a sketch of some kind.

**Comment by kd7uiy** [comment]
First of all, let's look at a real asteroid. This particular asteroid is the smallest ever photographed up close, [25143 Itokawa](https://en.wikipedia.org/wiki/25143_Itokawa)

![hayabausa_image_of_the_asteroid_itokawa](https://cloud.githubusercontent.com/assets/5951269/18151400/f0ad7866-6fbc-11e6-83cd-24bff74f0a5f.jpg)

For me, it seems like it's an irregular shape, with most of the individual locations being relatively equal. There isn't anything really jutting out of it.

Next, let's look at a larger variety of asteroids. This particular image shows all asteroids we've photographed close up, as of November 2010 Credits: Montage by Emily Lakdawalla. Ida, Dactyl, Braille, Annefrank, Gaspra, Borrelly: NASA / JPL / Ted Stryk. Steins: ESA / OSIRIS team. Eros: NASA / JHUAPL. Itokawa: ISAS / JAXA / Emily Lakdawalla. Mathilde: NASA / JHUAPL / Ted Stryk. Lutetia: ESA / OSIRIS team / Emily Lakdawalla. Halley: Russian Academy of Sciences / Ted Stryk. Tempel 1, Hartley 2: NASA / JPL / UMD. Wild 2: NASA / JPL.

![asteroids_comets_sc_0-000-100_2010_2](https://cloud.githubusercontent.com/assets/5951269/18151484/7bd14760-6fbd-11e6-8893-0d094aade2df.png)

Most of these are probably bigger than we want to target, I suspect 1 km would be the largest of these we want to target. 

We could handle the Z by having the asteroid be stacked with different layers. Digging one reveals the layer beneath it, until we come to the other side. This seems simpler to me than the more complex things we have been discussing, like a 3-D map or otherwise.

**Comment by vogonistic** [comment]
I'm not sure what you think of as 3D vs stacked layers, but the way I'd solve it is by decoupling the tile array from the world and add a middle class to encompass the level and then just have multiple of those. It's a stack of layers, but since they are oriented in z axis, it's also 3D in a way.

**Comment by kd7uiy** [comment]
Okay, let me see if I can recap this all. If I sense a general agreement, then I'll include it as a part of the Game Design wiki pages, at a spot that I'm not sure where to yet.

1. Resources shouldn't come from no where, metals, air, etc should all come either from mining, or from external shipments, or the external atmosphere, if there is such.
2. It seems ideal to have some kind of 3-d like mining capability, most likely in multiple layers.
3. We should leave the current system in place until such time that we have the upgraded system in place and relatively well tested. We might consider lowering it's power somewhat in the mean time, however, to encourage resource gathering.

That sound about right?

**Comment by koosemose** [comment]
I still like the mining drone as a combination slow source of resources and a way to "scout" an area before mounting a full expidition (somewhat more interactive than it currently is, some degree of choosing a where, and the person working it mattering in how well of an idea of the place they get)

**Comment by kd7uiy** [comment]
@koosemose I don't disagree with that. Hmmm. Let me add in a statement.

4. The effectiveness of mining will be random per block. Each block type will have more of some mineral than others. The type of block can be sensed with the proper tools, but is not automatically known.
