### ISSUE TITLE
[Proposal] Steering Comittees

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1062]
The more I think about it, the more I'm convinced we should have some kind of steering committees for each of the areas of interest, especially those that help guide the overall direction of the game. Note the choice of Steering Committee, indicating they help guide the direction of the project, but aren't the overall say in the project.

This is a really rough sketch, but here goes:

There should be a number of committees. Periodically, each committee will be re-formed, in ways I'm still working on. A few thoughts:

* Periodically, an Issues post is made for people to nominate themselves to the steering committee. This issue list ideally contains the nomination of each individual. Some period of time is made to allow for nominations, perhaps a week?
* Each person who is interested in being a part of the committee will respond to that issue, indicating why they thing they are a good fit.
* Everyone can make a thumbs up/down on the candidates. If they get more thumbs up then down, then they are considered voted in.
* One of these people, perhaps the person with the most votes, is considered the leader of the committee.
* The committee ensures there are standards to contribute, and is the ultimate ensurer that the standards are met, however, they should discuss any proposed standards with the community prior to implementation. 
* A committee member can be kicked out by a majority vote of the committee, by Quill, by common agreement via an issue post, or by a majority vote of the leads of the steering community.
* The committee's main job is to maintain the Wiki pages devoted to their area, including the roadmap sections for that area, and the guidelines for that section.

A council of the steering committee leads can assist in issues that require more than one team to discuss something. This committee is nominally lead by Quill. It shouldn't convene very often.

The committees should be something like as follows:

* Test- Responsible for ensuring all PRs are good.
* Game Design- Responsible for the story, writing, etc. This may drive desired game mechanics as well.
* Architecture- Responsible for coding standards, file formats, etc
* Art- Responsible for all creative things, UI, Artwork, Sound, etc.
* Documentation- Responsible for keeping the history of what is happening, blogs, website, etc. Does not include Quill's videos, or anything he does along those lines.

**Comment by vogonistic** [comment]
This seems heavy handed for an early project. Are you suggesting it for later in the project or now?
