### ISSUE TITLE
Game Design Committee

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1065]
I would like to organize a group of people who is interested in getting the design aspects of the game figured out. Among these would include the following (Including a few questions where these issues have been discussed, if applicable):

1. General gameplay #1060, #1023, #1019, #996 #387
2. Story- #776 #431 
3. Game Mechanics- #613, 
4. Roadmap #601 #228  (This might get pulled in to another team eventually, but for now, I think it's a good place to be. Our contribution would primarily be on features to be included, and much less on other topics. )

This team would be responsible for identifying Game Design issues, both existing and ones that should be resolved, helping to come to a consensus, and updating the wiki after an agreement is reached. A few things this team isn't responsible for, for those less familiar with game design:

* Artwork
* Anything directly related to code
* Bugs in existing game play

Note that all decisions will be made via the Issues, as is currently done, this team will just be focused on the Game Design issues. We can even start our own channel in Discord, but it will be opened to anyone who wishes to join.

What I would like to see is who is interested in being a part of this team? No programming experience is required, although it would be helpful. If everyone is okay with it, for the time being I would like to lead this group, because I've had a fair amount of experience doing Systems Engineering on large scale software projects, although I'm certainly willing to let others take the lead if there's someone willing and able to do so better than I.

**Comment by sboigelot** [comment]
@kd7uiy great initiative, I would be happy to join this group, this is the part of the project and collaboration that interest me the most.

**Comment by NogginBops** [comment]
@kd7uiy  I would like to join! The game really needs some thinking in the game play and game design department.

**Comment by vogonistic** [comment]
The channel `#gamedesign` has been created on Discord.

**Comment by kd7uiy** [comment]
For now, I'll suggest a few things.

1. Continue to let me know here who is interested.
2. Let's also brain storm what topics we need to discuss. I'll keep a list of them that we can refer to when required.
3. Look at all of the linked issues above, and let's see if we can get some resolution to them.

**Comment by koosemose** [comment]
I'm always interested in discussions of game design. But we should be certain not to restrict the game too much from natural development.

**Comment by Ralathor** [comment]
I would definitively be interested.

**Comment by kd7uiy** [comment]
Of note is there is now a tag Game Design for any issues associated with Game Design. We haven't retroactively added this to old issues, but please visit this tag and provide feedback to these issues.

**Comment by sboigelot** [comment]
can we tag #776 & #105 as game design too?

**Comment by sboigelot** [comment]
The following issue should probably be tagged with [game desing]

#1040 - Improving character statistics 
#1030 - [Discussion] Time 
#1029 - Character Consumables
#1019 - Seasons like system (Beta Angle) 
#1004 - Floor tile idea- Keep track of how often it is stepped on
#996 - Gameplay: What level of micromanagement do we want?
#983 - Stockpile enhancements
#982 - [Enhancement] Quillcorp Newspaper/Announcements
#776 - [Discussion] Economy (with connected story element
#704 - Pipes and Vents
#613 - Orbital height as a game mechanic? 
#566 - Proposal: Minimap _(not sure for this one)_
#536 - Discussion] Technology research 
#521 - Starting furniture/ ship size 
#431 - [Discussion] Storyline! 
#283 - New Characters
#268 - Discussion on how to handle gear such as a spacesuit 
#103 - Idea: Pirates

We should probably avoid to spawn new game design discussion before closing some of theses.

**Comment by kd7uiy** [comment]
Disagree with 983, 1004, 982, 704, 566, and 268. Those seem to be feature
based, or UI based. The others would be good to include.

**Comment by sboigelot** [comment]
@kd7uiy I updated the list, I'll keep on this separate comment the disagreed upon list (just to avoid re-speaking about them later)

> - [ ] #1004 - Floor tile idea- Keep track of how often it is stepped on
> - [ ] #983 - Stockpile enhancements
> - [ ] #982 - [Enhancement] Quillcorp Newspaper/Announcements
> - [ ] #704 - Pipes and Vents
> - [ ] #566 - Proposal: Minimap _(not sure for this one)_
> - [ ] #268 - Discussion on how to handle gear such as a spacesuit

**Comment by sboigelot** [comment]
I've updated the wiki with this list https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Gameplay-Discussions

Let's try to keep it up-to-date all together and report our final decision there.

**Comment by kd7uiy** [comment]
I don't know what else there is to really say here, so I'm closing this for now.
