### ISSUE TITLE
RoomChanged event

### ISSUE THREAD

**Issue by svmnotn** [TeamPorcupine/ProjectPorcupine#1071]
We need an event to be fired whenever a room is changed, be it removed, added, or whatever else. So far the idea is having a `RoomChanged` event that would contain what happened, most likely represented by an enum so something like:
```c#
enum RoomChange {
   Created,
   Destroyed,
}
```

we could have different variants for `Split` and `Joined` or simply pass more information about the result of what has taken place. I will get around to doing this shortly so for now this will be the tracking issue, feel free to attempt to influence my PR before it is made. :D

**Comment by vogonistic** [comment]
I think we need 4 events:
- Created
- Split
- Joined
- Destroyed

For `Split` we need to know who we split from and `Joined` we need to know who we joined into (the room that is left behind after the join).

Btw, this system is there to help with the upcoming Job System. If we have a job queue per room, we need these events to be able to migrate jobs to the new appropriate queues. The PR is already huge so we are trying to create PR's that might be useful for other things separately.

**Comment by koosemose** [comment]
I also think a room should be alerted when its furniture changes... but that's only applicable if a room is keeping track of its furniture in the first place, which is somewhat of a separate matter.

**Comment by vogonistic** [comment]
After a brief discussion on the Split and Joined events, we decided to have a discussion that is at least short, or medium long, on if it's worth having those extra events. They don't exist in underlying code and distinctions aren't always clear.

**Comment by koosemose** [comment]
But would it be beneficial to have things done more in that way? Particularly Joined. For example, one notable issue is that currently when two rooms are joined one's atmosphere overwrites the other, that really needs changed (along with other considerations when joining rooms) Would that be enough to justify a Joined event, since it would be more of a distinction from creating a room?

**Comment by vogonistic** [comment]
We just have to make sure we cover all the edge cases. With split events, we have the same problems right? But do we send the event to both of the rooms and keep a reference to the original room, even though all tiles have already been moved away to the new rooms?

**Comment by vogonistic** [comment]
In the 4-event system, `Created` is entirely when it was created in space (or split from room 0) and `Destroyed` would only be when it is opened to space (or joined with room 0). Everything is really join and split events, but there is a question on who gets them and what objects do we need to keep.

**Comment by svmnotn** [comment]
@vogonistic is that how the system is supposed to work? Because as per #1072 the `Created` and `Destroyed` kinda always happen, without regards to whether it was also a `Split` or `Join`. However talk over in the PR seems to be going in the direction of a `RoomManager` to handle all that.

**Comment by Grenkin1988** [comment]
I think we events like `Created Destroed Split Joined` must be part of `RoomManager` that really needs to.created.
`Room` itself could have `Changed` with information about `Furniture` changes in `Room` There were topics about room should know what is in it.

**Comment by TomMalbran** [comment]
I think that we can close this now.
