### ISSUE TITLE
Someone take over the wall sprite

### ISSUE THREAD

**Issue by Spool5520** [TeamPorcupine/ProjectPorcupine#1077]
So I've been incredibly busy with work and my own game and don't see myself having the time to do what I wanted to do for this game. Mainly making the different types of walls. If someone would take over the task that would make me very happy. I love getting emails about the updates and seeing this game grow. Just wish I had the time to help more :(

**Comment by Tranberry** [comment]
I wish you well, and a safe _return_ to this project!

**Comment by Spool5520** [comment]
Thanks :)
