### ISSUE TITLE
Where to suggest names?

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#1087]
Title pretty much sums it up. I heard Quill was taking suggestions.

**Comment by vogonistic** [comment]
Names for what and where did you hear it?

**Comment by ComputerOverlord** [comment]
Names for Project Porcupine, and Patreon

**Comment by Grenkin1988** [comment]
You are killing me. Names for what? Furniture, class, event, model, folder, son? ...

**Comment by sboigelot** [comment]
I think @ComputerOverlord is speaking about this https://www.patreon.com/posts/state-of-ludum-c-6527874

> We are so very close, I think, to unleashing Project Porcupine onto Github so that you people can start hacking away at it in a collaborative manner (by the way: still open to suggestions about what to call our game!)
_Quill18_

**Comment by ComputerOverlord** [comment]
Right from a post:

> 1 -- The Name

Project Porcupine was always meant to be a codename. It's a terrible, non-descriptive title.  Before we create the git repo and (most likely) a community website with a discussion forum, we need to pick an actual name for this thing. Ideally it should give a hint as to what the game is (e.g. Dwarf Fortress / Kerbal Space Program / Prison Architect), but something that just sounds cool and space-y is also good.

Note that we can differentiate the tile/base-building engine from the game itself.  For example, there's no reason that the "Porcupine Engine" couldn't be used by someone to make a fantasy-world base-building game.  Basically, everything we've done up until now is the engine work. 

Anyway, post names at me here in the comments on on twitter (@quill18) or email (quill18@quill18.com) -- I'll try to collect them all for a strawpoll.

**Comment by vogonistic** [comment]
👍  closing this issue since it was answered.
