### ISSUE TITLE
Wanted- Cat Herders- Art, Issues, Code Architecture, Testing, maybe more?

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1088]
First of all, let me define a cat herder. A Cat herder, for the benefit of this site, is a person who takes responsibility to make sure that some aspect of this project is developed. They provide guidance, make sure the issues are discussed, and try to find consensus in the areas. They don't have any real power, per say, but make sure that everything gets done in that area, and help to figure out what the community desires. If there are multiple people who want to be a particular herder, we'll deal with that, but for now, we just need a few people to step up and help the community figure out that particular area. 

Right now we have two people who are listed as Cat Herders,

Game Design- Myself
Wiki- longtomjr

There are a few more positions that I see a use for a cat herder. I'm sure there are other areas as well. Reply here if you are interested in being a cat herder for a particular area, give your qualifications if any for such, and generally speaking why someone should accept you in that area. If there aren't any objections after a while, we can give you the title, however, don't feel like you need to wait for that to start getting the feedback you need.

* Art- Takes charge of setting all art standards, reviews art based PRs and ensures that such PRs are reviewed by others to ensure standards are met.
* Issues- Goes through old issues primarily and pokes them if they seem to be ready to close. 
* Code Architecture- Sets coding standards, file formats, file organization, etc.
* Testing- Makes sure that all PRs are tested. Really this should be a team of people, the more the better, but the Herder will give some organization to that team.
* Localization- Ensures that all localization issues are managed.
* User Interface- What will the game's interface be like?

So, who is interested in taking more responsibility with this project to ensure we continue to make progress?

EDIT: 

Just a few additional thoughts. A Cat Herder doesn't have to approve all ideas. If you have a relatively small idea, feel free to just code it up as normal. If it's a larger idea, post an issue to make sure everyone is on the same page. All this is is a means to have someone who is there to make sure all of the issues are discussed and documented, not the final authority in all things in that area.

**Comment by sboigelot** [comment]
I wouldn't mind going though old issues and notify the one that could be closed (or close them even maybe).

**Comment by Tranberry** [comment]
Anyone applying for the **Art** part in this please join [ #art on discord](https://discord.gg/3sUMk) where I believe all currently active people making art are active some hours of the day. (We are mainly using text to chat)

**Comment by bjubes** [comment]
Ill take testing, I just made Travis CI unit tests for the project ( #1094 ) and I'd love to see them  take the load off of gatekeepers. Also ill continue testing out PRs when I get the chance

**Comment by kd7uiy** [comment]
I don't know what else there is to say on this, so I'm going to close it.
