### ISSUE TITLE
[Bug ? Build failure on VS] Error	5	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement

### ISSUE THREAD

**Issue by sboigelot** [TeamPorcupine/ProjectPorcupine#1095]
![image](https://cloud.githubusercontent.com/assets/6545998/18217267/311ee722-715c-11e6-9a74-670df216a526.png)

Error	5	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	D:\git\ProjectPorcupine\Assets\Editor\SchedulerEditorTest.cs	220	22	ProjectPorcupine.CSharp.Editor

**Comment by sboigelot** [comment]
Related to #998

**Comment by Grenkin1988** [comment]
![schedulereventsdonotmodifyeventslistduringupdatetesterror](https://cloud.githubusercontent.com/assets/2979432/18217491/cee6f59a-7165-11e6-8edc-4b6c554b49aa.jpg)
The same for me

**Comment by Mizipzor** [comment]
Can we just remove evt3 until it's properly fixed? Just to get it to compile again?

**Comment by Grenkin1988** [comment]
I fixed compiler error #1096
