### ISSUE TITLE
TODO and idea list

### ISSUE THREAD

**Issue by BeefEX** [TeamPorcupine/ProjectPorcupine#11]
I think, there should be some kind of TODO list, or list that anyone working on some feture can write down what is he working on, so when somebody else wants to start woking on something, he will no that nobody else is working on it already.

**Comment by NogginBops** [comment]
That is kind of what the issues are made for. You create a issue of a thing that should be done. You assign an assignee(s) and let them work on that thing. And then the assignee creates a pull request for that branch.

**Comment by quill18** [comment]
A Wiki page could be created with a general roadmap -- but yes, Issues are definitely where specific items should be listed and discussed, and I think it's going to be sufficient for the first while at least.  Marking this as closed for now.

**Comment by tomdjones** [comment]
Generally, [Trello](https://trello.com/) is a nice todo-web-app. A vote system can be used to let the devs vote for different features.

**Comment by BeefEX** [comment]
Trello is exactly whar I meant, but I agree that issues are right now sufficient for this purpose.

**Comment by RodRitter** [comment]
Having external platforms isn't great for a project that is this new. Especially since new people are looking to contribute right away. They need a central place to collaborate.

**Comment by BeefEX** [comment]
Good point.

**Comment by satch3l** [comment]
Yeah I was also about to suggest creating a design document. However, is this something we all should help create or have Quill create a framework before everyone jumps in and say what they want?

**Also some things to think about** (taken from Wikipedia)

> The purpose of a game design document is to unambiguously describe the game's selling points, target audience, gameplay, art, level design, story, characters, UI, assets, etc. In short, every game part requiring development should be included by the developer in enough detail for the respective developers to implement the said part. The document is purposely sectioned and divided in a way that game developers can refer to and maintain the relevant parts.
> 
> The majority of video games should require an inclusion or variation of the following sections:
> 
> Story
> Characters
> Level/environment design
> Gameplay
> Art
> Sound and Music
> User Interface, Game Controls
> 
> This list is by no means exhaustive or applicable to every game. Some of these sections might not appear in the GDD itself but instead would appear in supplemental documents.
