### ISSUE TITLE
Tasks should be added as a "Snake" [Easy]

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1100]
When building square shapes, like a huge patch of floors, the build pattern is really inefficient. The tiles should be added as a "snake", for even rows they should go from the bottom up, for odd rows from the top down. This would make building such shapes vastly more efficient. I know the job system is going to be re-written, but it helps to queue the jobs in the right order first, which this will reduce movement time considerably.
![gif](https://cloud.githubusercontent.com/assets/5951269/18221838/862a66a0-7153-11e6-8eef-efccdf203432.gif)

**Comment by jaselito** [comment]
Agreed and implemented... creating a PR for this.

**Comment by sboigelot** [comment]
Is this the solution, or should character prioritize tasks similar to the higher priority then they pick but closer to them?

**Comment by kd7uiy** [comment]
It is a solution, although I suspect the improved job manager would do
something better, this wiki improve it for now. Also, it should require
less sorting.

**Comment by jaselito** [comment]
Yeah, I also see this as something provisional... a better job system should consider the distance to the tiles when deciding what to do first.

**Comment by kd7uiy** [comment]
I still think it will help somewhat with the job manager, as this will put the jobs in a way that should be pretty quick to optimize, but yeah, the manager should help too.
