### ISSUE TITLE
New loglevel in UberLogger

### ISSUE THREAD

**Issue by Sommerbo** [TeamPorcupine/ProjectPorcupine#1104]
@vogonistic and me where thinking of ways to declutter UberLogger (henceforth called UL) and to make the log more useful.
One thing that happens a lot is that `Debug.ULogChannel` is used as a debug channel which is understandable and technically correct, but it is also used for regular log-messages which is more inline with how it should be used in my opinion. So @vogonistic came up with two new commands to be implemented in UL, this new commands are to be used exclusively for debugging so that `Debug.ULogChannel` is used for, well logging not debugging. Effectively this creates a fourth loglevel

`ULogDebugChannel(channel, message)` used to log debug information
`ULogSetDebugEnabled(channel)` Turns on debug-logging, with out it debug messages would be discarded.

Any thoughts on this, could it be done better/smarter?

**Comment by vogonistic** [comment]
The only thing that could be better would be a really cool way to turn on a debug channel in the UI or with compile time flags, but I don't know how to set those in Unity and MonoDevelop.

This is a feature I'd love to see.

**Comment by Sommerbo** [comment]
I was planning on ignoring debug channel when a stand alone build is created. Also life got in the way but I will start on this today or tomorrow.
