### ISSUE TITLE
[BUG] Heater don't receive power anymore.

### ISSUE THREAD

**Issue by Ohda** [TeamPorcupine/ProjectPorcupine#1106]
I little bug in the power sytem. since #1079.

Heater not working anymore because it don't receive power. 
This is true with an inputRate of 1 instead of 4 (the actual value of master) and a lot of power available.

By the way accumulator looks awesome !

**Comment by Grenkin1988** [comment]
Going to look at this later.

**Comment by Grenkin1988** [comment]
The issue is that Heater do not have Update function, just
```
-- This function gets called once, when the funriture is isntalled
function Heater_InstallAction( furniture, deltaTime)
    -- TODO: find elegant way to register heat source and sinks to Temperature
	furniture.EventActions.Register("OnUpdateTemperature", "Heater_UpdateTemperature")
	World.Current.temperature.RegisterSinkOrSource(furniture)
end

-- This function gets called once, when the funriture is unisntalled
function Heater_UninstallAction( furniture, deltaTime)
    -- TODO: find elegant way to unregister previous register
	furniture.EventActions.Deregister("OnUpdateTemperature", "Heater_UpdateTemperature")
	World.Current.temperature.DeregisterSinkOrSource(furniture)
end
```
That mean that you just need to place heater, and it works by default.

**Comment by Grenkin1988** [comment]
@FilippoLeon @abackwood Somebody need to force heater to react on power situation.

**Comment by koosemose** [comment]
Heater appears to function properly with power now. Closing.
