### ISSUE TITLE
[Questions] [Newbie] Wiki ettiquete

### ISSUE THREAD

**Issue by crafty-geek** [TeamPorcupine/ProjectPorcupine#1107]
I'm effectively self-assigning #1090 (hauling, stockpiles, and inventory management), in all but GitHub's official assignment system (why Github's own [issue 153](https://github.com/isaacs/github/issues/153) hasn't been dealt with yet, I don't know).  This is a significant enough task, I'm wondering:

- [x] Is it worthy of listing on the roadmap somewhere? **_Yes_**
- [x] If so, what heading should it go under?  Character (hauling), or Furniture and Inventory? **_Tentatively F+I_**
- [x] Is it milestone 0.1 worthy? _**No.**_
- [x] How verbose/concise/bulleted-list-y should such an addition be? _**Added as written in issue circa 9/3/16**_
- [x] Should there be some sort of a wiki-ettiquette guide (perhaps on the Standards and Conventions page)?  Perhaps just linking to this issue for now? _**Follow best guess for now**_
- [x] Is roughly the below roadmap-ready verbosity/conciseness and formatting?

> ---

* Hauling Revamp - _@crafty-geek, assistance welcome_

> Attempting to revamp how hauling jobs work, to:
  * Make characters prefer filling up stockpile slots with some of the same item to putting it down on an empty slot
  * Minimize/optimize the search space for dump-inventory type tasks
  * Make characters prefer to carry full loads in one trip, rather than making many trips carrying partial loads
  * Make characters look around their path for nearby to-be-stockpiled inventories of whatever they're carrying, and if there's room in their personal inventory, grab the stuff.
   * Considering other cases where "targets-of-opportunity" pathfinding might be useful; potential refactor into the pathfinding code rather than the inventory manager...

> See #1090

> ---

edit: checklist-ified questions, copied over draft onto wiki

**Comment by koosemose** [comment]
Probably shouldn't add it to the Milestone 0.1, we need a static target for milestones to help guide development, and if the Milestone is added to, it spoils its function as a target. I would leave it up to Gatekeepers if this is viable as a MIlestone 0.1.

In the meantime it would probably be useful for us to have a page to track things people are working on.

**Comment by crafty-geek** [comment]
No need for a page to track what people are working on, just need people
who can assign issues to use that system - see #1090's most recent comment,
which links to a post on the specifics of what level of mod-ish-ness is
needed to assign.

--
Alexander Barbe

**Comment by longtomjr** [comment]
@crafty-geek Thanks a lot for considering using the Wiki!  
Dont be afraid to add to this page https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Roadmap.

We really need to start with a better system, but for now please assign yourself there :)

**Comment by crafty-geek** [comment]
Thanks for the input, posted the draft.

Wiki-etiquette guide question and verbosity question still to be answered, so not gonna close myself; feel free to branch them off into a new issue and close this one, if a different convo is better for those qs.

**Comment by longtomjr** [comment]
I see no problem at all exept that the issue number is not hot linked. (unfortunately you need to do that manually in the wiki).
Further a guide to wiki ettiquete might be good, but atm I feel like you just use the formatting style used on the page or on the rest of the wiki.

**Comment by crafty-geek** [comment]
fixed hotlinking, thanks for checking

**Comment by crafty-geek** [comment]
and "follow the formatting style you see" answers the last q, closing.
