### ISSUE TITLE
[WIKI][Roadmap] Issue to clean up the roadmap

### ISSUE THREAD

**Issue by longtomjr** [TeamPorcupine/ProjectPorcupine#1108]
First of. I want to ask all of you to use the wiki to assign jobs to yourself and to look for stuff to do that needs to be done.  
Secondly: If you have done something that you assigned to yourself on the wiki and it has been merged, please mark that as done and reference the PR and the Issues around that job.  

Now for what this post is really about:  
Everyone that has open assigned jobs on the [Roadmap](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Roadmap) I will ping here and if you can provide me with what is going on with that assignment it will help me a lot :)
@Dustinwloring1988
@TheAkashicTraveller
@racerand, @svmnotn
@FilippoLeon  , @gunthergun, @BeefEX
@sboigelot

**Comment by sboigelot** [comment]
See #1075 for more detail about my current tasks.

**Comment by crafty-geek** [comment]
Just self-assigned #1090 on the wiki, I've spec'd out how I plan to approach the job in the issue.  In terms of "what is going on with that assignment", I'm maybe 5% complete so far - a lot of undocumented functions involved that I'm having to wrap my head around (and document best I can in another branch of my repo).

**Comment by longtomjr** [comment]
Thanks @sboigelot and @crafty-geek :)

**Comment by kd7uiy** [comment]
Why do we have two lists of 0.1 milestones? https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Milestone-0.1 vs https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Roadmap shows to different lists for the same thing...

**Comment by longtomjr** [comment]
Milestone 0.1 is a link, the rest is misc jobs ;P

**Comment by Sommerbo** [comment]
I will start work on #1104 soon unless any one objects and has a better idea, while not directly impacting the game good tools make everyone happier and more productive.

**Comment by bjubes** [comment]
how is code driven UI done? We are heavily relying on prefabs, not code.

**Comment by Tranberry** [comment]
@bjubes maybe we should have an activity minimum for claiming stuff? like at least a response in a week or so, or it will be unassigned..

**Comment by TomMalbran** [comment]
I am working towards #772. I started moving the loading of XML and Lua files to the ModsManager, and adding the capability to mod more of the files. Once everything is loaded from ModsManager I will make the folder switch and then start working on a package file

**Comment by dusho** [comment]
is there some issue that discusses how the game should 'play' in this 0.1 milestone ?
like have some complete chain for production and requirements set up.. have some goal and stuff that will help test most of the things we have?
E.g.:
Main quest (0.1): build FTL engine, power it and leave this system
Proposed changes:
- new furniture - FTL engine, requirements for build fairly high: (100 steel plate, 100 copper plate), to power FTL need 50 power cells
- power generator uses power cell instead of raw uranium 
- power cell (1x) is created from 3x uranium, 2 steel plate inside Power Cell Press (already in game)
- to get new crew mate you need to build and power cloning pod (2x power cell in input will create a clone and turn cloning pod into rubble - one time usage)
- introduce have rubble inventory

Does that sound ok? Any other ideas?

**Comment by kd7uiy** [comment]
I would hold off on the FLT engine. I like the other ideas, although I'm  not quite sure what you mean by rubble inventory.

**Comment by dusho** [comment]
rubble.. same as in rimworld (I hope it's called like that)
basically when your machine breaks, you are left with pieces of junk, that you have to cleanup if you want to use that space.. plus you can recycle some junk (metal junk) into some useful metal..

**Comment by kd7uiy** [comment]
Ahhh, okay, makes sense. I've been thinking something similar, but I didn't have it framed the same way as you.

**Comment by vogonistic** [comment]
I wouldn't add anything new to 0.1, just make sure the current machines work and have up to date graphics. Then we can close it and make up a 0.2 that is closer to something playable.

I'm hoping that 0.2 will be mostly about making the UI to control the game makes more sense. Keyboard shortcuts, designed menus, nice sprites for buttons and an overview of the current characters that you can click on to jump to them.

Any additional balancing we want to do would also be a good fit, and per tradition the milestone would probably be making up a small fraction of the actual PR's coming in, so we'd still get a bunch of other things in.

**Comment by dusho** [comment]
ok
was just thinking to have something 'complete' but minimalistic so that release (binaries) can be played by other people with some sense of goal.. to get more feedback from people
often you will get better feedback and insight from people not involved in game (as we already are)

**Comment by vogonistic** [comment]
If you really want a goal to build for, there is a cloning pod already implemented. 

I understand what you are going for, but there are so many things that need to happen for it to be playable that it doesn't matter too much on 0.1 if there is a goal to build against or not. 

There isn't any plans for a final quest for 0.1. It's more of a technical milestone to help us finish some small aspects of the engine. I assume that even though you asked that, you've read the post and wiki on the milestone. 

Help us finish the milestone and then we can discuss the next one which hasn't been defined yet.

**Comment by longtomjr** [comment]
Can we all agree that if someone was not active for a month that I can move their *unofficial* roadmap entries to a stasis page? At the current time the Roadmap is full of things that is not worked on actively and may give the impression that someone else is working on it.

**Comment by longtomjr** [comment]
Did what I could. Closing this down now. Thanks for the replies and advice!
