### ISSUE TITLE
[Bug] After loading a save, cannot place any furniture

### ISSUE THREAD

**Issue by mbstraus** [TeamPorcupine/ProjectPorcupine#1117]
This looks to be only a problem after loading a save.  Regardless of where you try to place a new piece of furniture, the system prevents you, citing that there is no floor tile underneath.

![image](https://cloud.githubusercontent.com/assets/434820/18228822/00a618d4-721c-11e6-8516-4515a14b9b76.png)

That was off of the branch that I'm currently working in, which I didn't touch anything with regards to this... however I switched to my master and got it up to date, and I am actually just straight up unable to load anything.  It just starts spewing null reference exceptions after loading up a save.  Is anyone else seeing this or am I just going crazy?

**Comment by bjubes** [comment]
I get tons of exceptions on load too
