### ISSUE TITLE
[Discussion] Switch from Managers to Services and move to a new folder

### ISSUE THREAD

**Issue by TomMalbran** [TeamPorcupine/ProjectPorcupine#1140]
If we stay with the current folder structure (Controllers, Models, Utilities, UI) that tries to mimic the Controller Model architecture, we should think about a new layer that goes between a Controller and a Model. 

In another project I work with I have an extra layers between the controller and the model. The controller is an interface between the ui/view and the next layer, and the model just models an entity. So there is a missing piece that can manage models and/or provide services to the controller, which in other architectures is called a Service. Our manager are mostly Services in that way.

I think that we should make a Services folder, move the managers there, and change the class names to ___Service. We could go for manager, but I think that Service is a better name.

That architecture also specifies a Repository layer which holds the Models, but for now I am not sure if we need to go deeper.

**Comment by sboigelot** [comment]
Service is a better name for me too.

**Comment by akomm** [comment]
The manages are actually a mix of repositories and services. 

- Repositories: Hold a set of models. Query API if needed, add/remove API.
- Services: implementation of reusable code/logic to operate on a model or a set on models, should actually not hold any state information.
- Controllers: handle (user) interactions. Know what to do, but not HOW to do (services job)
