### ISSUE TITLE
Black outlines for wall sprites

### ISSUE THREAD

**Issue by jaselito** [TeamPorcupine/ProjectPorcupine#1142]
This is something that has been bugging me... in order to be consistent with the rest of the artwork, I think  the wall sprites should also have a black outline... I did a little editing in GIMP to show you a before and after of what I mean (tried to do it in-game by modifying the actual sprite but couldn't get the outlines in the right places... maybe someone more familiar with the configuration of the wall sprite?)

Before: 
![wall sprites no outline](https://cloud.githubusercontent.com/assets/21699103/18234940/960bad14-72d8-11e6-82d6-65a116fb1ce7.png)

After:
![wall sprites outline](https://cloud.githubusercontent.com/assets/21699103/18234943/9d2aea74-72d8-11e6-96bc-f8c7ba2f679d.png)

The actual outline should be thicker than what I did here and maybe even have some antialiasing, but you get the idea... (this should also apply to the doors btw)

Any thoughts?

**Comment by bjubes** [comment]
I see what you mean, the outine feels more in line with our style to me, but i'm no artist. I wouldn't make the outline any thicker.

**Comment by koosemose** [comment]
Wow, adding the outlines improves those much more than I thought it would.

**Comment by kd7uiy** [comment]
I agree, this looks like a huge improvement!

**Comment by jaselito** [comment]
@bjubes The outline should be thicker in order to match the width of the black lines in the other items.  I think consistency is important.

One other thing, I experimented with some shading, I think it also adds a lot to the feeling of the game:

![walls - shaded](https://cloud.githubusercontent.com/assets/21699103/18238101/e363713e-72fe-11e6-96de-55152d221c5c.png)

Of course, something like this should only be implemented after a consensus is found on the illumination direction (in this example it would be from the top left).

**Comment by quill18** [comment]
The shaded version adds a TON of clarity and "physicality" to the visuals. I'd say both the outlines and the shading are a big improvement.
