### ISSUE TITLE
[Bug] Lua wonkiness

### ISSUE THREAD

**Issue by buggy213** [TeamPorcupine/ProjectPorcupine#1147]
The MoonSharp interpreter vomits out errors:

Stack trace:
ScriptRuntimeException: cannot access field powerValue of userdata<Furniture>
MoonSharp.Interpreter.Execution.VM.Processor.ExecIndex (MoonSharp.Interpreter.Execution.VM.Instruction i, Int32 instructionPtr)
MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop (Int32 instructionPtr)

Steps to recreate: 
-Hover over any piece of furniture

**Comment by mikejbrown** [comment]
Should mention that the power overlay needs to be on to reproduce this.

**Comment by mikejbrown** [comment]
@Grenkin1988 The bug seems to have been introduced in #968. Still trying to track it down but something in there broke the power overlay.

**Comment by Grenkin1988** [comment]
I will take a look at this.
