### ISSUE TITLE
Character: Should we use state machine, components or keep it as is

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#1150]
I'm working on a better job management system, but have gotten to a point where I have a lot of refactoring around the systems. One place in particular that has complicated logic is Character which needs refactoring in order to support adjacent tile pathfinding, job dependencies, more structured need support and in the future threat and fighting behavior.

I tried refactoring Character to components, but couldn't come up with a good model to balance conflicting actions, so I've started a new branch where I'm refactoring it into a FSM. I'm nowhere near done with it, but so far it feels like the best approach. It fits well with something like Rimworld behavior where you might be entirely focused on working for working unless there is an attack or a need that needs to be taken care of.

The way I would do it is for each state (`WorkState`, `IdleState`, `MoveState`, etc), would have an optional parameter to a state that we want to switch to after it's done instead of falling back to the base logic. That covers sub-actions for Work and Needs as an example. 

Needs and Fighting would be a little bit different in that they would be checked at an interval while the current state is executing. If they want to, they can interrupt the current state and take over.

What do you guys think? Am I trying to overthink it? Is it a good model? Bad model? Lay it on me before I spend too much time I don't have on it.

**Comment by Grenkin1988** [comment]
I've never used state machines, but this is the first time I participate in game development.
I heard that state machine is very good approach for game development

**Comment by dusho** [comment]
I think I used light version of state machine in every LD game I made. It was really the best way how to handle character stuff and animations related to that..

**Comment by koosemose** [comment]
Keeping it as is should definitely be off the table, and buried in the backyard. 

My one and only problem with FSM is it always seems complex, and I worry it may be hard for those not familiar with them to do any kind of interaction with them...

**Comment by Ohda** [comment]
I don't already have found the time to read it but it looks like a cool introduction about State Machine :
http://gameprogrammingpatterns.com/state.html

**Comment by sboigelot** [comment]
I use a lot of FSM in my daily work. And mostly, no-one understand them.
FSM can be an obscure black block doing some kind of vodoo magic. 
And the people I'm working with are high skill persons with years of experience.

I think we should either:

- Avoid FSM as they may add complexity for new developers
- Create our own very simple implementation of FSM, straight forward and where we can easily add states and transitions.

**Comment by koosemose** [comment]
Even though I was one to bring up the issue of FSM potentially being hard to understand, I also don't want the project to suffer from trying to keep things accessible for new developers, (Maybe someone convince @quill18 to do do a tutorial on at least a basic FSM, so we have something to point people at?)

**Comment by sboigelot** [comment]
I see no problem about implementing a very simple FSM. I suppose @vogonistic, you already have a draft. Maybe you could share it in a WIP PR so we can make up our mind?

**Comment by Sommerbo** [comment]
I think FSM is a good idea and it could be a good idea for a video. FSM are tricky but a very good tool in games development.

**Comment by vogonistic** [comment]
I think that maybe the best first action is to make my branch at least look like it's working so that everyone can see it. Then we can discuss if it has merit or will turn into a ball of unmaintainable code. I'll try to get to that point tonight.

**Comment by Raketfart** [comment]
I love using FSM - especially for characters. When character behavior becomes more complex, I think we will benefit greatly from using FSM.

**Comment by Skalicon** [comment]
@Ohda thanks for the link, this article is really good.

**Comment by vogonistic** [comment]
I think the implementation in #1219 is close enough to where we can make a decision on if it's a desirable way to go or if we just take some lessons learned from it and refactor it another way. The PR kept growing at an alarming rate so I don't want to go much further without a discussion on it.

**Comment by Raketfart** [comment]
I think it looks great, and it's easier to pinpoint problems in AI behavior this way. 
I vote yay on the fsm.

**Comment by sboigelot** [comment]
FSM looks great for me too.

**Comment by koosemose** [comment]
Closing as FSM has been implemented for characters
