### ISSUE TITLE
Changing UI: A guide (Do we have one?)

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1162]
For the first time in a long time, I'm looking to change a UI element. I'm actually not really sure how to do it. Looking at the current canvas, there's almost nothing there. It seems like this should be some kind of a guide, or something, to making this a bit easier. At the very least, putting steps on the Wiki could be helpful. I'll figure out how to do it, but I suspect it'd be rather difficult for someone who is new to figure that out, as it stands now, and the guide we have should make that clear. Or maybe it is and I'm just completely missing it...

**Comment by mikejbrown** [comment]
It's not just you.

**Comment by kd7uiy** [comment]
Always nice to realize I'm at least not the only ignorant one...

**Comment by bjubes** [comment]
maybe this will help??
https://github.com/TeamPorcupine/ProjectPorcupine/wiki/How-does-it-work%3F#adding-ui-dialog-box

**Comment by kd7uiy** [comment]
That's close I think, but not quite. And it wasn't really that obvious of where to go. Still, I'm heartened to learn there's at least something along those lines on the wiki... Maybe we could make a "How To" page for the wiki?

**Comment by bjubes** [comment]
we have "how does it work", but it didn't really catch on
