### ISSUE TITLE
[Bug] with commit Headline Generator- basic version (#1033)

### ISSUE THREAD

**Issue by mattpott** [TeamPorcupine/ProjectPorcupine#1171]
Currently there is a bug with the text box created from this not being removed from the screen despite being invisible I am unable to click on the ground underneath where the text box was.

The bug only appears when tested with maximise on play is enabled.

**Comment by koosemose** [comment]
It's present even when not maximised, it's just that you're less likely to click on the box which is much smaller.

Also a bug that it is so much larger when the game is maximised

**Comment by kd7uiy** [comment]
I believe I've fixed this, by setting the interactable flag to false when the dialog isn't present.
