### ISSUE TITLE
Build menu doesn't have names of furniture

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#118]
In the current master branch the build menu doesn't add the furniture name to its corresponding UI button.
![capture](https://cloud.githubusercontent.com/assets/7608114/17759066/80afb7c2-64c2-11e6-9c1b-d4d618b4083b.PNG)

**Comment by Dormanil** [comment]
Seems like there are some errors in the new localization code.

**Comment by bjubes** [comment]
yes I'm also getting spam from the log with warnings along the lines of "no translation for furniture floor". It happens when i load the path finding test and then try to build furniture.

**Comment by ComputerOverlord** [comment]
That's... an odd bug.

**Comment by RodRitter** [comment]
Yea its a really annoying bug. Can't do anything until its fixed.

**Comment by relinu** [comment]
There's no gameobject with the new localizationLoader on it, just add it to the controller parent or any other object

**Comment by vogonistic** [comment]
I can verify that adding the LocalizationLoader script to a GameObject works. 

I think the localization needs to display a better default value if there is a missing translation, which is probably going to be the case for any modded items when people are playing unusual translations.

**Comment by UnknownSoldier1** [comment]
Okay that seems to be a bug in my localization code. GitHub has made some problems before, I'm going to look what that is. I think it might be a broken prefab, but I'll see.

**Comment by UnknownSoldier1** [comment]
So, I made a pull request (hopefully) fixing this issue. For now, as @vogonistic already said, just add the LocalizationLoader to any GameObject as a temporary fix. Hope @quill18  will merge the pull request ASAP.

**Comment by UnknownSoldier1** [comment]
Closed my pull request as it's being fixed in #127 already.

**Comment by bjubes** [comment]
thanks for the fix! Make sure to test your Changes before you submit a PR from now on as I imagine it's hard for quill to extensively test each one on his own

**Comment by bjubes** [comment]
I'll close this when a PR is accepted that fixes this issue

**Comment by Mizipzor** [comment]
@bjubes You shouldnt have to. Whoever fixes the bug should in the commit message write "Fixed #118" and this would automatically be closed when the pull request is merged.

**Comment by bjubes** [comment]
Right forgot about that. Github is so smart
