### ISSUE TITLE
Scheduler- Add an option to not save event on load

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1180]
Some events, such as the HeadlineGenerator, really shouldn't be saved, as they interact with UI elements. There should be an option to not save those types of events. Related to #1175 .

**Comment by mikejbrown** [comment]
Loading is also somewhat broken in that CSharp event prototypes do not get automatically reloaded. This is a separate issue...

**Comment by mikejbrown** [comment]
Should be simple enough to add a property `bool IsSaveable` or the like to `ScheduledEvent` and check that in the `Scheduler.WriteXml`.
