### ISSUE TITLE
Repatriate localisation file or not

### ISSUE THREAD

**Issue by sboigelot** [TeamPorcupine/ProjectPorcupine#1197]
Some time ago the localisation file have been moved to a different repository:

https://github.com/QuiZr/ProjectPorcupineLocalization/tree/Someone_will_come_up_with_a_proper_naming_scheme_later

This has been done at a time where localisation was new, a lot of PR were coming in and the gatekeeper were overflowed by them.

But currently it force everyone that add a single line of text to do it in a different PR, on a different repo.

Is this still something we want?

**Comment by bjubes** [comment]
I think that we should eventually put them at TeamPorcupine/ProjectPorcupineLocalization so it is logical where the localization is while separating code from translation for gatekeepers and those following the repo.

**Comment by mikejbrown** [comment]
What about making it a git submodule?

**Comment by bjubes** [comment]
only downside to submodule is it requires the extra command to sync and update it, and there are a lot of git beginners in this project. It didnt work to well with uberlogger #641

**Comment by sboigelot** [comment]
We should maybe just keep the en_US default in this repo at least
So we can make complete PR

**Comment by koosemose** [comment]
Yeah, having at least the default en_US in this repo would be good, much easier to set what the default text should be from which other text should be based.

**Comment by vogonistic** [comment]
I agree that the en_US translation should never be missing. I've emailed @quill18 and asked him to add the repo under `TeamPorcupine` as well.

**Comment by Sommerbo** [comment]
I agree with @sboigelot, en_US should be in the main repo.

**Comment by dusho** [comment]
anything new about this? I was wondering why my localization for en_US got lost.. guess it's still not part of main repo?

**Comment by bjubes** [comment]
I assume were waiting on quill to make the localization repo. We don't want to add the file yet in case the version in this repo differs from Quizrs version.

**Comment by QuiZr** [comment]
I've marked @quill18 sevral times when making my issue and then pr about this but got no answer so I left this as a "[temporary](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/Scripts/Localization/LocalizationDownloader.cs#L48)" thing  I've also noticed some bugs in that code so I will fix them in 2 or 3 days.

About that en_US - I think that all localization files should be attached when making a build - in travis or something.

**Comment by kd7uiy** [comment]
I vote for moving it all back to the main repository. I think an admin might be able to pull in the commits that have been made to give credit where credit is due, but there's only 26 commits and 2 contributors to the other repository, not enough to keep them separate if you ask me.

**Comment by TomMalbran** [comment]
My vote is also to move it all back to this repository. It was done at a time when the project was new, everyone wanted to contribute and localization is the easiest to do. But a this time is harder to add localization and we end up with string that aren't even localized to english. We might actually have an issue to localize all the new strings into the other languages.

**Comment by Tranberry** [comment]
at least the en_US/default localization should be on this repo.

**Comment by bjubes** [comment]
if we move it back to the main repo then we can't use the "branch name for game version" convention that is set up currently. this prevents version 0.2 from overwriting 0.1 localization when someone hasn't updated, so if we move it back into the main repo we need to create a different system that accomplishes this task

**Comment by TomMalbran** [comment]
When we make the 0.1 release it will have all the features included in 0.1 with all the translations. You cant change it after that. Even if it was in a release branch, it will have the 0.1 version until the 0.2 release. We start working on 0.2 in master, we just change it. Master will have all the uptodate localizations. We then launch 0.2 with all the localizations for 0.2 (the localizations are done before the release). And when you download 0.2 you get the localizations that you need. For this early releases it wont matter if the localizations are not fully uptodate, since is just for testing. But when we get to a big release that is stable, we make sure that all the localizations are uptodate, and we can remove the ones that are too old and not updated.

**Comment by bjubes** [comment]
but when we go to 0.3 can we ensure that 0.2 and 0.1 localization are preserved? The last stable ones will be, but what about legacy support for the ones before that? 
would that require remembering the specific commits tagged for each version in the stable branch?

**Comment by TomMalbran** [comment]
You can download any old version from a zip which will have all the content, as each can be a different release, and we will not change them. The master will have the new development, and the release branch the latest version. From where we can add some fixes.

You can have the same issue as how you download the code from 0.1 when we are at 0.3

**Comment by bjubes** [comment]
got it. Im down for whatever in terms of where localization is stored as long as the new way has all the same features and perks of storing it in a separate repo/ the current implementation

**Comment by kd7uiy** [comment]
I think the issue of maintaining versions is much easier if you have everything in one repository. To me, that's another good argument to moving it all back here...

**Comment by koosemose** [comment]
Closing as at least us_english has been repatriated.
