### ISSUE TITLE
Furnitures with Animations reset to base sprite when furniture is placed adjacent.

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1198]
This is actually two (presumably related) bugs.

First, the furniture preview is based off of the base sprite of a furniture (So the sprite with the same name as the furniture), this is most obvious when placing a power generator, as it will show the No Texture pink square, since none of its sprites use the same name as the furniture ("Power Generator" vs. "Power-Generator-01" through "Power-Generator-04".

Second a furniture will reset to its base sprite (So for the power generator it will be no texture pink), when a furniture is placed adjacent to it, and will stay that way until something changes it (changes state, or changing during an animation).

The first is an easy fix, just by changing the name of the idle state sprite to match the name of the furniture, though perhaps it might be preferred to use the idle state sprite as the base sprite if it exists. The second I'm not sure how it would need fixed, though it is less of a problem if the base sprite is the idle state, at least with our currently animated sprites (it's either idle, in which case changing to idle is unnoticeable, or it's animating in which case it will only flash idle for a moment, and go back to animating), but the flicker seems undesirable, and if we ever have multiple states on an item that aren't animated (for example, a trash bin that shows as either empty or full), it will stay as whatever sprite matches the furniture name until a state change happens.

**Comment by Raketfart** [comment]
Whoops. I'll take a look at this. Probably all my fault.
