### ISSUE TITLE
Antialiasing

### ISSUE THREAD

**Issue by jaselito** [TeamPorcupine/ProjectPorcupine#1213]
I've been working on #1142.

Got the sprite done, but somehow when I load it into the game, the rendering artifacts get way worse than normal (lines appearing and disappearing at the boundaries between connected sprites, especially when zooming). Weirdly, this over-the-top artifacting only happens if the sprite has the black outlines, if I export it without the outlines, the artifacts are just the usual.  

Anyway, the situation can be (mostly) resolved by deactivating antialiasing in the quality settings, which actually leads me to question why it's set in the first place.  Since this is a 2D game using unrotated quads, is there a point to having antialiasing activated and even offering an antialiasing dropdown in the in-game settings?  So far I can see, there's no real benefit to the visuals when using an antialiasing setting, only detriment (i.e. rendering artifacts).

I propose that we deactivate antialiasing in Edit->Project Settings->Quality and remove the antialiasing dropdown from the in-game quality settings.

Further down the line we should consider creating a pixel perfect camera.

**Comment by kd7uiy** [comment]
Unities Anti-Aliasing is famously poor... I know of at least 1 issue being tracked to improve it, see https://issuetracker.unity3d.com/issues/anti-aliasing-causes-text-to-have-artifacts

**Comment by jaselito** [comment]
Yeah, we're lucky that we can afford disabling antialiasing with a project like this.  Imagine the pain for people working with 3D stuff...

**Comment by jaselito** [comment]
Ok, since no one has raised any objections I'm going to go ahead and implement this.
