### ISSUE TITLE
Crewmembers sometimes go missing on reload.

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1222]
Saved a game with 4 crewmembers, on reload I only have 2. It happens consistently with this save. It's always the same crew going missing, quill18 and Tranberry. They will also not load if transposed into another save. I'm not sure what makes them different, so hopefully other's will be able to spot something I couldn't

https://gist.github.com/koosemose/df8771f261edade4a1b888d1fbd6851f

**Comment by kd7uiy** [comment]
Is that a sign of things to come for Quill and Tranberry?

**Comment by kd7uiy** [comment]
What I noticed right away:

    <Character name="Quill18" X="57" Y="52" Z="0" needs="Oxygen;404:Sleep;36:" r="0.2762249" b="0.7909456" g="0.06331599" rUni="0.8882179" bUni="0.8882179" gUni="0.8882179" rSkin="0.9294118" bSkin="0.654902" gSkin="0.7490196">
    <Character name="Tranberry" X="57" Y="52" Z="0" needs="Oxygen;376:Sleep;569:" r="0.7160394" b="0.2299454" g="0.798802" rUni="0.6293229" bUni="0.6293229" gUni="0.6293229" rSkin="0.9607843" bSkin="0.7960784" gSkin="0.8509804">

Note that the X and Y are exactly the same. I suspect that is somehow responsible for the issue, although I'm not in a position to test it out at the moment.

**Comment by koosemose** [comment]
So there are two issues that I've managed to hit here apparently. First is Inventory loading, it's causing a character to not be loaded ( If we take powli's stuff, quill comes back ), it's possible this is related to what is fixed in PR #1206.

I suspect you're right as to the cause of Tranberry's disappearance, at least indirectly, if I change his coords to not be on the bed he comes back. I don't currently know if it is solely an issue with 2 characters in one tile, or more particularly 2 characters in one tile with a bed.

**Comment by mikejbrown** [comment]
Maybe later we can add a space rapture event (only happens if you're in good with a religious faction).

**Comment by kd7uiy** [comment]
LOL. Sounds like a great idea mid-game, but a poor idea between saves...
