### ISSUE TITLE
More organic movement

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#123]
Yes, I belive a form of A* should be used, but it looks wierd how characters move when going diagonally. A* should be used when, for some reason, you have a maze. Moving in straight lines should be used when moving to something in the same room with NO walls in between.

**Comment by Dormanil** [comment]
No, I can't agree with this proposal. I am personally very fine with our DF-style more strongly tile-based approach to character movement.

**Comment by ComputerOverlord** [comment]
Okay then... Closing...
