### ISSUE TITLE
Deconstructing mine ore?

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1237]
I just noticed that I could deconstruct mine ore. That seems a bit odd to me... It seems like the deconstruct option for the ore should be the same as the mining option, convert it in to something more useful.

**Comment by Ohda** [comment]
This PR take care of this https://github.com/TeamPorcupine/ProjectPorcupine/pull/1221

**Comment by TomMalbran** [comment]
I noticed that a couple of days ago, so I made a PR to fix it for ore and for future non deconstructible furnitures.

**Comment by kd7uiy** [comment]
That's what I get for not checking the PRs carefully. Nice catch!
