### ISSUE TITLE
Dialog box manager, available in lua?

### ISSUE THREAD

**Issue by frankitox16** [TeamPorcupine/ProjectPorcupine#1242]
Hi! I was trying to make a filter option for the stockpiles, and looking at the lua code there was a TODO that talked about interacting with the UI... I thought about allowing dialog boxes to be called by lua functions, yet there're some changes that need to be made to the dialog box manager not just to allow loading from the resources folder, but also from the streaming assets. Should it be this way? Do we need to add this feature (custom modded dialog boxes)?

**Comment by TomMalbran** [comment]
Yes. The it should totally be able to open a DialogManager from Lua, will be really needed for modders, and can be used for our furniture and other needs.

In my opinion the DialogManager should have a CreateDialog method where you pass some required content and you get some type of DialogBox instance which would have methods to open it, close it, and events for Opened, Opening, Closed, Closing (that can be both as events and as lists of lua functions).

As for the content, it could require some values, like title, dimensions, buttons (each with an Clicked event) and a prefab for the content (to be fully code driven it could be some Xml, but that might make it really hard).

But it might need to be generalized to work with all the current dialogs and any new ones, so so things might be changed.

**Comment by frankitox16** [comment]
They should also have a generic return value, such as DialogBoxResult, in order to be more flexible

**Comment by sboigelot** [comment]
The DialogBoxResult is added since #1195 but ony the are you sure is returning one.

**Comment by frankitox16** [comment]
Issue closed as this is going todo be added in #1470
