### ISSUE TITLE
Inventory doesn't serialize locked state

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#1247]
It was discovered on #1228 that Inventory doesn't store locked state, which means that after loading a game, all the hopper inventory for furniture gets picked up by characters to feed other furniture or stockpile it.

It should be written and read from xml with the other parameters.

**Comment by dusho** [comment]
this issue actually isn't fixed by #1228 . I think it will be fixed with some other new PR

**Comment by sboigelot** [comment]
I think it was an auto-close due to merging a PR, or a mistake on my part

**Comment by mikejbrown** [comment]
Is this still a bug?

**Comment by dusho** [comment]
I think so.. yes.

**Comment by pderuiter77** [comment]
or otherwise this report would be.. closed? 
or you know, download the latest build and try?
or is that too cynical? :)

**Comment by koosemose** [comment]
#1228 did in fact fix this, so this has been fixed for the past month. Closing
