### ISSUE TITLE
[Bug] Building through walls

### ISSUE THREAD

**Issue by Raketfart** [TeamPorcupine/ProjectPorcupine#1248]
It seems that characters can build furniture through diagonal walls. He was pathfinding down there, even though he wouldn't be able to walk through the diagonal walls.

![bug](https://cloud.githubusercontent.com/assets/7031323/18403368/a12d0944-76e4-11e6-9a29-7f878da8f0d2.png)

**Comment by kd7uiy** [comment]
I can't reproduce this bug... 
![capture](https://cloud.githubusercontent.com/assets/5951269/18404649/dac3f198-76b9-11e6-8760-cca6f57c5953.PNG)

**Comment by Raketfart** [comment]
Hmmm weird. Now I can't reproduce either. 
- maybe this was while testing #1219
