### ISSUE TITLE
AI and Inventory System donations?

### ISSUE THREAD

**Issue by philipguin** [TeamPorcupine/ProjectPorcupine#1249]
Hi! I don't have much spare time, but I have some code I'd love to donate if y'all were willing to accept it. Essentially, I have a rules-based AI system that handles priority and mutually exclusive "resources", and a general-purpose inventory system reminiscent of Monster Hunter or Minecraft.

It's written in Java, and it's not much code, so it should be a cinch to port over. The inventory system is thoroughly unit tested, works via an "InventoryCollection" interface, supports stacking and inventory transfers, arbitrary constraints, and some serialization. The AI system is basically two small files establishing an algorithm with a clean interface - the abstraction should be useful for individual characters determining what jobs they should be doing, evicting some jobs in favor of others, etc. I've attached the relevant files below.

I'm not sure if anyone here is willing to do the integration work, or if the code is even desired, so please let me know! I imagine it would help out a lot.

[ProjectPorcupineCodeDonation.zip](https://github.com/TeamPorcupine/ProjectPorcupine/files/465228/ProjectPorcupineCodeDonation.zip)

**Comment by sboigelot** [comment]
Hello @philipguin 

Thanks for your interest in the project. I had a look at the code you provided, and I don't think it would be interesting for this project as we already have a different implementation of those system.

But this may be interesting for a aspiring java game developer. You should really create a public repository on github and host the code in a more proper way then a zip file. It may help someone one day!

I will close this issue for now, and I hope we will see you around. Even if you don't have time to code, your opinion on the game will will already be great. Feel free to try it whenever you get bored at home and want a free cool game ;)

**Comment by philipguin** [comment]
Thanks for the timely response, no hard feelings. If you change your mind (e.g. gameplay requirements expand to require multiple item types in one inventory, like a chest), you're more than welcome to any of the code I provided. And you're right in that hosting it separately might be a good idea, it's something I should start thinking about with much of my code.

Have a great day!

**Comment by sboigelot** [comment]
Have a great day too, and keep the community posted if you desire to share more, your code was looking very good ;)
