### ISSUE TITLE
StyleCop rules and var usage

### ISSUE THREAD

**Issue by dusho** [TeamPorcupine/ProjectPorcupine#1251]
Was just hit by [StyleCop] tag and going through the list I was wondering about some rules:

**System using directives must be placed before all other using directives**
there is already rule to keep it in alphabetical order and Organize using -> sort usings does that.. can we remove this rule and keep only alphabetical one?

**The body of the if statement must be wrapped in opening and closing curly brackets.**
so it wants me to create from 

```
if (IsWorkshop)
    workshop.Update(deltaTime);
```

code like this:

```
if (IsWorkshop)
{
    workshop.Update(deltaTime);
}

```

is there point for this? One liners are often used for events.. and with extra 2 lines it's getting longer. Usually good habit is to fit one method on one screen so you don't have to scroll around if method has some tough logic inside.. so having rules that force you stretch your methods is not a good rule, I think

**general (not a StyleCop) one is not use var**
What is the reasoning behind this? We are already using LUA that also doesn't work with explicit types. And I think everyone uses some smart editor here (MonoDevelop or VS2015) that ships with Unity. Using 'var' is faster to write code and lines are usually shorted and don't need splitting.
`foreach (var toConsume in flaggedForTaking)`
vs.
`foreach (KeyValuePair<Tile, int> toConsume in flaggedForTaking)`
or
`var flaggedForTaking = new List<KeyValuePair<Tile, int>>();`
vs.
`List<KeyValuePair<Tile, int>> flaggedForTaking = new List<KeyValuePair<Tile, int>>();`

**Comment by UnknownSoldier1** [comment]
AFAIK the reason why StyleCop doesn't like one liners is that if you want to add more code to the if statement, it's a lot faster and you don't have to add brackets first.

**Comment by TomMalbran** [comment]
And if you add more code inside the if and you forget to add the brackets, you can end up with a bug that might be difficult to track.

**Comment by dusho** [comment]
hm.. ok. That makes sense. Never seen bug like that, but I guess some people may encounter it..
What about **usings** and **var** rule..

**Comment by sboigelot** [comment]
The way I see the **var** rule, it's to be stay beginner friendly. It's easier to understand for someone that doesn't code all the time and doesn't know that the var will be a typed variable once compiled.

**Comment by koosemose** [comment]
usings I agree with you on, having both one seems a little excessive to me.

However, with var, the difference between C# and Lua, is that despite var, C# is still explicitly typed, var just sets the type based on what's returned. While there are ways to see what a variable is, unless it's an obvious type (such as string, int, float, etc..) it's still not immediately obvious what type something is.

**Comment by Grenkin1988** [comment]
How me personally:
**Use `var` when evident**
and this means:
![image](https://cloud.githubusercontent.com/assets/2979432/18409910/c9612062-775c-11e6-9771-b139ea542e80.png)
should look like this:
![image](https://cloud.githubusercontent.com/assets/2979432/18409914/df84d0f0-775c-11e6-8f28-86996a7d0b41.png)
My reason for this: When I read code I do not what to hover over method or collection to see what type is there.

**Comment by TomMalbran** [comment]
You usually don't get bugs, but it can happen. There are or might be beginners here, and {} makes things easier. I like {} even on 1 liners. What I dont like is to have them always on their own line and an extra line under. But I can get used to it.

Using I am not sure. Probably because System is the most important. Alphabetical is for order. What I would actually want is a warning on not used usings.

The issue with var is that you might not always know the type of the variable. Notice that we also see lots of code in Github for PR where we don't have the help of IDE. In some cases and some coders won't have an issue, but there are cases were it might be an issue or for less experienced coders.

**Comment by dusho** [comment]
also I have a feeling that 
**System using directives must be placed before all other using directives**
works against
**Using directives must be sorted alphabetically by the namespaces**
So we should pick just one

Regarding **var**, I think how @Grenkin1988 used it should be acceptable.

**Comment by koosemose** [comment]
If this were a project with single developer or a small team, I would agree with you, however that is not what we are, consistently enforcing a rule that is based on the judgement of the individual developer, with as many people as we have, particularly many beginners, is going to be inconsistent at best.

**Comment by bjubes** [comment]
the only one i would consider discussing is the using directives, the others have been explained and enforced by quill. using var/type or brackets/not are not very important in the grand scheme of the project, but suck up a lot of time if we don't choose a convention and just stick to it. For now we have a convention of being explicit in both cases. is that the best standard? maybe. Does it matter enough to have a huge discussion in which 50% of people will be upset either way? no.

**Comment by sboigelot** [comment]
As @bjubes pointed. We all will dislike at least one of the rules :package: 

@dusho Tell us if you feel we can close this issue ;)

**Comment by dusho** [comment]
well even current master has like 10+ StyleCop warnings on alphabetical order of usings.. if we ignore it now and keep collecting those warnings it will be harder later on to actually fix your relevant ones
So please make decision at least for those usings.. I think I can like with other StyleCop things.. and use **var** in beginner and readiness friendly manner

**Comment by sboigelot** [comment]
Can you post us your stylecop report, is my stylecop miss-configured?
I only see 3 violation on master:

------ StyleCop completed ------

========== Violation Count: 3 ==========

**Comment by dusho** [comment]
Severity	Code	Description	Project	File	Line
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Scheduler\ScheduledEvent.cs	12
Warning	CS0169	The field 'CharacterSpriteController.skinColors' is never used	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Controllers\CharacterSpriteController.cs	30
Warning	CS0414	The field 'DialogBoxJobList.waitPeriod' is assigned but its value is never used	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\UI\DialogBox\JobList\DialogBoxJobList.cs	28
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\Character.cs	15
Warning		SA1202 : CSharp.Ordering : All private methods must be placed after all public methods.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\Character.cs	541
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\EventAction.cs	12
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\Furniture.cs	13
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\Inventory.cs	13
Warning		SA1505 : CSharp.Layout : An opening curly bracket must not be followed by a blank line.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\Inventory.cs	134
Warning		SA1508 : CSharp.Layout : A closing curly bracket must not be preceded by a blank line.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\Inventory.cs	136
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\Prototypes\XmlPrototypes.cs	13
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\Room.cs	13
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\Tile.cs	14
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Models\World.cs	14
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\PowerNetwork\Connection.cs	12
Warning		SA1210 : CSharp.Ordering : Using directives must be sorted alphabetically by the namespaces.	ProjectPorcupine.CSharp	D:\coding\unity3d\GIT\ProjectPorcupine\Assets\Scripts\Scheduler\Scheduler.cs	16
Warning		Trying to access non-existent key: 'pressure_locked'. Probably a Lua problem.	Solution 'ProjectPorcupine' ‎(3 projects)	Assets/UberLogger/UberLogger.cs	505

**Comment by Grenkin1988** [comment]
@dusho You have not latest maste

Here errors that I have:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		SA1202 : CSharp.Ordering : All private methods must be placed after all public methods.	ProjectPorcupine.CSharp	D:\Development\GitHubRepository\ProjectPorcupine\Assets\Scripts\Models\Character.cs	541	
Warning		SA1505 : CSharp.Layout : An opening curly bracket must not be followed by a blank line.	ProjectPorcupine.CSharp	D:\Development\GitHubRepository\ProjectPorcupine\Assets\Scripts\Models\Inventory.cs	134	
Warning		SA1508 : CSharp.Layout : A closing curly bracket must not be preceded by a blank line.	ProjectPorcupine.CSharp	D:\Development\GitHubRepository\ProjectPorcupine\Assets\Scripts\Models\Inventory.cs	136

**Comment by dusho** [comment]
weird.. I just synced, reloaded all, and still see it
well those using really are not sorted alphabetically .. but do fulfill that system usings are first.. then user ones sorted..
so do I have some wrong settings on StyleCop ? how come those 2 rules are not fighting each other on your machines..

**Comment by sboigelot** [comment]
The only project enforced stylecop rule in SettingsStyleCop file seems to be 

    ```
    <Rule Name="UsingDirectivesMustBePlacedWithinNamespace">
          <RuleSettings>
            <BooleanProperty Name="Enabled">False</BooleanProperty>
          </RuleSettings>
        </Rule>
```

The others may be local configuration?

**Comment by Grenkin1988** [comment]
![image](https://cloud.githubusercontent.com/assets/2979432/18413718/8d4fbdec-77b9-11e6-8acc-66f57b8f6c58.png)

**Comment by Skalicon** [comment]
It is extremely lazy and counter productive to work against the type safe language you are developing by using var, whether it is obvious or not the type used at declaration, later in the future or further down in the code it won't be. Don't be lazy, it's not that hard to define you variables property and It IS the best coding practice.

**Comment by mikejbrown** [comment]
As much as I love dynamically typed languages (i.e. languages built from the ground up on that principle), `var` feels to me like bolted on syntactic sugar to give the faux feeling of dynamic typing in a statically typed language, which is just... awkward. If you know the type, write it. If you don't know the type use polymorphism, templating or interfaces to make explicit that you depend on behavior, not implementation (aka "duck typing," aka the best thing about python).

**Comment by Grenkin1988** [comment]
Actually `var` is not just cosmetics for C#.
There is such thing as **anonymous types**.
And `var` is a way to declare such types.
Example:
```
var item = new { Name = "Name", Value = 12 }
item.Name...
item.Value...
```

**Comment by pderuiter77** [comment]
That is a valid example, but pointing out the exception only enforces the rule :)

Disclaimer: In my own code i use var often. Probably too often :)
