### ISSUE TITLE
Trader names always empty

### ISSUE THREAD

**Issue by buggy213** [TeamPorcupine/ProjectPorcupine#1255]
Exactly as the title says. In this example, the prototype being loaded is Wire Inc. , with only 2 potential names, but the end result is a list with 4 empty strings. Relevant image from TraderPrototype.cs
![projectporcupine2](https://cloud.githubusercontent.com/assets/9620842/18413203/e5b641d6-7755-11e6-8d12-f06a9aba46c7.png)

**Comment by bjubes** [comment]
duplicate of #978

**Comment by buggy213** [comment]
Um what? Isn't that issue about grouping furnitures inside build menu?

**Comment by Tranberry** [comment]
I'm confused.

**Comment by buggy213** [comment]
Lol oops. I was looking at a different issue

**Comment by Grenkin1988** [comment]
PR #1257 fixes this
