### ISSUE TITLE
Astros only bring Ice to Stockpiles

### ISSUE THREAD

**Issue by Sommerbo** [TeamPorcupine/ProjectPorcupine#1274]
Even after all ice have been collected no other resource is gathered.

**Comment by sboigelot** [comment]
It's not a bug but a feature :p You have to mine the ores now, it think. Rigth click -> Context Menu -> Mine

**Comment by Sommerbo** [comment]
I feel silly now!

**Comment by Tranberry** [comment]
Well the ice should also be mined, that's the bug imo. And if not a bug it is bad UX.
