### ISSUE TITLE
Settings not being saved

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#1275]
After making changes to settings and saving, they are reverted immediately (never taking effect).
![settings](https://cloud.githubusercontent.com/assets/7608114/18419752/2b67ffb4-7830-11e6-9798-cbd167c9e390.gif)

The save button used to cause a small lag spike due to writing to file, this has seemed to disappear as well.

**Comment by sboigelot** [comment]
This should be fix in #1271

**Comment by koosemose** [comment]
This has been fixed, possibly from #1283. Closing
