### ISSUE TITLE
Split walls onto separate 'Construction' object or go ECS

### ISSUE THREAD

**Issue by pderuiter77** [TeamPorcupine/ProjectPorcupine#1291]
The problem: 
In other threads there is talk about being able to move furniture. Since walls are also furniture at the moment, implementing logic to do this is harder. 
Beside that, tables etc, should not be crafted where they are installed, while walls should. 

The solution:
A new type of object : ConstructedObject. This would be walls and anything else that is 'bolted into place'.

The InstalledObject should be created at i.e. a metal workshop, then moved and installed. This means moving furniture doesn't mean destroying it, but actually just moving it. This also means furniture can be moved by i.e. rapid pressure changes.

**Comment by pderuiter77** [comment]
Sorry..lousy phone.
Since a wall has other properties as a table , i thInk it would be beneficial to split them. Constructions are the permanent kind, while installed objects are the placeable kind

**Comment by abackwood** [comment]
What is functionally different about the two that warrants separate classes?

**Comment by pderuiter77** [comment]
One is permanent, the other isnt. If you want i.e. vents, and onlly place them in walls its easier to restrict vents to construction objects than to determine per furniture type.

**Comment by abackwood** [comment]
So you cant deconstruct walls ever? That seems harsh O_o

Bear in mind that real-world semantic classes of objrcts dont translate 1:1 to programming classes. Just that a table and a wall are obviously very different objects doesn't mean they are so different in game.
Also worth thinking about that splitting into two classes means you need a common superclass for whenever systems are indifferent between the two, and you can then only count on common interface between the two. Inheritance is a pain to deal with and unless there's a very different way they operate that cant be covered by Lua and XML I think it'll make things a lot harder for no reason.

**Comment by pderuiter77** [comment]
Of course you can. Look at DF for instance. Constructions have certain properties / 'behaviour' that sets them apart from regular installed objects. And you shouldnt be using inheritance but components. Noy saying a full blown ECS is needed, but putting behaviour in separate classes and adding those classes to your objects is the way to go for a data heavy game. 
this of course would move it away from being beginner friendly..

**Comment by vogonistic** [comment]
I think the problem here is that the proposal needs a lot more information so that we understand what you think needs to be done and the benefits and drawbacks of changing it.

**Comment by pderuiter77** [comment]
I'll get on it in the morning :)

**Comment by pderuiter77** [comment]
I updated my starter comment :)

**Comment by TomMalbran** [comment]
I actually think that we need to go in the other direction, since Walls have nothing special, we need a component for Installable furniture. I think that the component approach would work better, and we already have some like the Parameters, EventActions, Animations, Workshop, (Jobs) that deal with specific things about the furniture, and we can keep adding more to simplify the Furniture class.

**Comment by pderuiter77** [comment]
Walls have nothing special? 
- Walls are what defines a room 
- If we get around to wiring, that would go through walls
- If we get around to vents etc, that would go in walls

And even then, the use of components / (i assume you mean ECS like?) doesn't preclude making walls a ConstructedObject. Could you explain how these 2 approaches are mutually exclusive?

**Comment by TomMalbran** [comment]
Walls and doors and mining rocks define a room. And we can even have some furniture that could replace a wall and still define a room.

Wires are placed on a tile, can go under the floor or inside a wall, but for our perspective is almost the same. But then most of the logic is in the wires, not in the Walls. You just need to know that the furniture is a Wall.

Big vents can also just replace Walls, and enclosure a room. And smaller ones than could be placed on a wall, can be more like a Utility. But then again, they just need to know that they are in a wall, the wall doesn't care if it has a vent or not.

I don't mind having classes, but we can't just slip in 2, we would need lots. A Workshop is totally different than a Wall or a Furniture. A Door could be treated as a furniture, but then has properties like a Wall and it also acts as an entrance / exit. A mining wall, would be different than a wall, but it can still enclosure a room. Most classes will share several similar methods and between different classes. So then you could define a class by its components, or you can have one class, and depending on the xml load the required components.

And then you have the modding aspect. Someone could come and make something totally unique, and we can support that if we treat all of our furniture in a moddable approach.

**Comment by pderuiter77** [comment]
I agree about the component part. I suggested it myself :)

And we won't need lots of classes. A workshop is just a zone with furniture. Or even just furniture with actions. 

But if we go full blown ECS / components, that makes this game a lot less beginner friendly.
More moddable definetely, and i'd love to have this, but do we want this game to evolve into something more complex?

The door example is indeed the perfect example of something not just being a constructed and not just being an installed object. It would be an object with i.e. an OpenableComponent, AirLeakComponent, etc.

**Comment by TomMalbran** [comment]
ECS might not be beginner friendly, but inheritance will stay short into solving the issue when we want to share behaviour between different classes, which we will.

**Comment by pderuiter77** [comment]
I agree, but i think this decision is a bit bigger than the both of us. I think Quill should say if he wants to go this direction

**Comment by TomMalbran** [comment]
Quill decided not to go into a inheritance approach when he we adding doors and went with the current parameters / lua functions approach. Which is working well, since it allow us to implement lots of furniture types using the params and the lua functions.

**Comment by pderuiter77** [comment]
If you use components, you could steer away from the unsafe parameters and use actual properties. 
We could start doing this without using a full blown ECS at this point. 
If we keep the components simple for now. Are in other words, make sure you only need 1 component for a behaviour, you could make systems that wouldnt be too hard to understand.

**Comment by vogonistic** [comment]
We might need to split furniture into separate objects by interfaces, subclassing or components, but this particular use case I don't think warrants it. 

That some furniture can be reinstalled somewhere else or is considered bolted in just needs a bool or a flag since it doesn't really change anything else with how it behaves when it's installed. The room flood fill just needs to check for something so that it knows that it behaves like a wall with regards to room division. 

There is also nothing that prevents us from creating walls at a workbench and have then installed if we want to.

**Comment by pderuiter77** [comment]
Which is why i came wih the components idea 3 post in :)

And i hope we dont go the subclassing way

**Comment by pderuiter77** [comment]
Should i close this and make a componen/ecs topic? It is the preferrable route compared to subclassing imo

**Comment by vogonistic** [comment]
Yes, close this and create a new discussion, but make sure you are using examples that are real problems for this codebase.

**Comment by pderuiter77** [comment]
I wanted to keep it simple.

**Comment by vogonistic** [comment]
It's good to use a clear and concise problem, but it has to be an actual problem.
