### ISSUE TITLE
Bug on master - Character list in World is null?

### ISSUE THREAD

**Issue by sboigelot** [TeamPorcupine/ProjectPorcupine#1305]
`NullReferenceException: Object reference not set to an instance of an object
World.TickEveryFrame (Single deltaTime) (at Assets/Scripts/Models/World.cs:184)
TimeManager.InvokeEvent (System.Action`1 eventAction, Single time) (at Assets/Scripts/Controllers/TimeManager.cs:190)
TimeManager.Update (Single time) (at Assets/Scripts/Controllers/TimeManager.cs:131)
WorldController.Update () (at Assets/Scripts/Controllers/WorldController.cs:142)
`

![image](https://cloud.githubusercontent.com/assets/6545998/18493571/81bd12d6-7a11-11e6-9a20-e6c8ddaa054d.png)

![image](https://cloud.githubusercontent.com/assets/6545998/18493583/925617fa-7a11-11e6-88e6-70aeb7e06b4e.png)

**Comment by sboigelot** [comment]
Can anyone reproduce this issue?

**Comment by sboigelot** [comment]
(playing in 3 times speed for 1 minute trigger it for me)

**Comment by sboigelot** [comment]
The world have all field set to null, this seem related to the doors?
![image](https://cloud.githubusercontent.com/assets/6545998/18493823/d472756a-7a12-11e6-9a0c-4e31385dcc15.png)

maybe related to #1296 ?

**Comment by sboigelot** [comment]
Disabling the autosave seems to fix it. (Comment everything in DoAutosave() )

**Comment by sboigelot** [comment]
Ok I can't reproduce it anymore (even while re-activating the auto save).

If you can reproduce it, keep us informed.

**Comment by koosemose** [comment]
Starting to look into it, I can get it triggered, and seeing if I can track it down more specifically.

**Comment by koosemose** [comment]
It seems to be somewhere in the xml serialization, I think, it happens when you manually save a game as well.

**Comment by TomMalbran** [comment]
I think I know what it is. Making a PR soon.

**Comment by koosemose** [comment]
I hope you're right, because what I'm seeing doesn't make a bit of sense to me.

After saving, every time the following code is ran:
```
    public void TickEveryFrame(float deltaTime)
    {
        // Change from a foreach due to the collection being modified while its being looped through
        for (int i = 0; i < characters.Count; i++)
        {
            characters[i].Update(deltaTime);
        }
    }
```
When character.Count is first encountered, characters is null, but if you then step into the loop characters is no longer null, and continues to be fine as the loop finishes.

**Comment by TomMalbran** [comment]
I attached the events from the empty constructor, which might be called by the Xml serializer, attaching events to an empty world. I tested the fix and it saves fine, both manually and from the autosave.

There is also an error when loading a save.

**Comment by koosemose** [comment]
@TomMalbran if you're not able to track down and fix the loading bug, please open an issue describing what you know of it, so others can look into it.

**Comment by TomMalbran** [comment]
I believe I know what it is. Trying to find the easiest way to solve it.

I also happens when loading a new world.
