### ISSUE TITLE
No spaces in prefab names!

### ISSUE THREAD

**Issue by NogginBops** [TeamPorcupine/ProjectPorcupine#131]
Currently there are prefabs in the main branch that have spaces in their names. Unity will not recognize those files as prefabs and will throw an error. This needs to be clearly stated in the contribution guidelines to avoid further mishaps.

**Comment by Mizipzor** [comment]
I think it's implied. It doesn't really make sense to list everything that Unity already requires. If we add something to the contribution guidelines it should be requirements on top of those or where we deviate.

**Comment by NogginBops** [comment]
@Mizipor Yeah I agree, but somehow that made it into the master.

**Comment by Mizipzor** [comment]
@NogginBops Which means someone should probably have done more testing. Or, rather, I don't think these mistakes are prevented by being in a list somewhere. Typos and stuff happen. :)

**Comment by NogginBops** [comment]
@Mizipzor True. But it needs to be fixed nonetheless.

**Comment by Mizipzor** [comment]
So this issue should address the specific instance(s) where it needs to be fixed, rather than describing the general problem. How else would we know when to close it?

**Comment by NogginBops** [comment]
@Mizipzor Absolutely. Though I'm a bit confused now that I have opened the project on my other computer as it seems to have no problem with the spaces. Could this be something related to unity version on configuration?

**Comment by Mizipzor** [comment]
Possibly. I'm afraid I don't know.

**Comment by NogginBops** [comment]
Well its seems to work so I will close this issue
