### ISSUE TITLE
Using composition over inheritance for moddability

### ISSUE THREAD

**Issue by pderuiter77** [TeamPorcupine/ProjectPorcupine#1310]
When we want this game to be moddable, most people think of it in terms of inheritance. I'd like to make a case against that, and for composition.
Why would we want that? Well, imagine you have the following classes:
- Lamp. Obviously, gives off light. derives from installedobject
- Bush. Something you place for beauty. derives from installedobject
- Enemy. A pirate. Derives from character. can attack.

But now i want an enemy robot with builtin light. Or a sentient thorn bush that can attack you.
If you want to do this using inheritance, things get real messy, real fast.

If, however, you go the composition way, you just have 1 class: Entity. Anything in the world is an entity. But the behaviour / characteristics are in components. 
A light component. A beauty component. An attack component. An AI component.

I hope you can see, that this way, we can just bolt on the stuff we want, without making a huge mess.
A robot that can light its own surroundings? That's an entity with AI and light component.
A thorn bush with an attitude? Entity with AI, light, attack and beauty.

You can do this for as much or as little as you like. We could make the tiles themselves entities. Or we use it just for characters / inventory / installed objects. 

I'll leave you with some links to articles about Entity Component Systems. There are several ways to implement this, so i hope we can leave any specific implementation details to later after we decide to go this route.

Edit: Best article imo: http://t-machine.org/index.php/2007/11/11/entity-systems-are-the-future-of-mmog-development-part-2/

Edit: A full fledged implementation (No i don't think we should take it quite this far atm) https://github.com/sschmid/Entitas-CSharp

https://en.wikipedia.org/wiki/Entity_component_system
http://www.gamedev.net/page/resources/_/technical/game-programming/understanding-component-entity-systems-r3013
https://www.raywenderlich.com/24878/introduction-to-component-based-architecture-in-games

**Comment by sboigelot** [comment]
Entity system are great, a lot of time but also dangerous. I wouldn't make every tile an entity as it would be super costly in cpu cycle and mem usage.

Consider that for each tile you would have to cycle through each behavior (or component) of the entity on each action/method on the tile. That's a lot of cycle.

I would agree to change some things to a more entity-like system but not everything. And also, not everything being the same entity. We should have a different entity root for the furniture and the character for instance.

**Comment by pderuiter77** [comment]
> I wouldn't make every tile an entity

I agree, but for other reasons :) Everyone talks about performance before you even know it's an issue. You don't cycle through each component each tick. You do update each system each tick. Each system can decide if it wants to update each tick (and for a lot of systems i don't think that's needed). 

> And also, not everything being the same entity

Bye bye sentient plant. I see no reason why you should make that distinction. An entity isn't even a class. It's just an identifier.

**Comment by sboigelot** [comment]
What is for you the difference in extensibility between the event system + lua function we provide now and a complete entity system?

> An entity isn't even a class. It's just an identifier.

Well this highly depends on your implementation. The default implementation of unity is class base.

**Comment by pderuiter77** [comment]
em..Unity doesn't do ECS. At least not in the correct way. That has been acknowledged by people in the industry (and no, i don't have examples from the top of my head, just look around).

Besides, The whole ECS is not part of unity perse, more of the model side of things.. which leaves you free to do whatever. Just make a SystemController : MonoBehaviour. That is your connection to Unity, and you can take it any place you want from there. 

I agree that an entity being a class or not depends on implementation, but would suggest going with the pure identifier part, since an entity as class is no more than a component list. 

The difference in extensibility i have shown with my examples. Besides that, if you have to make a custom lua script for everything that opens, etc. you're repeating yourself. Putting it in a separate component means you get consistent behaviour.

**Comment by sboigelot** [comment]
> Besides that, if you have to make a custom lua script for everything that opens

It's not the case for now, they share the same lua method.

I'm not 100% against it, I'm just against making it the default and enforcing it. I think there is a middle ground between ECS and a more classic. (But I agree with the fact that inheritance is bad and to avoid, mostly but not always)

**Comment by pderuiter77** [comment]
I agree, going full fledged ECS might be a bit much. You could have a specific LuaComponent if you need specific custom functions, although i'm not sure why we don't make an API that can be used by custom assemblies, but that's a discussion for another time :)

**Comment by vogonistic** [comment]
I disagree that the implementation details don't matter until we've made a decision. That is like buying a car based on the description of what we could do it it. On top of the question below, I want to know more about how it would actually work inside this game. 

1. What are you proposing rewriting into using the component system?
1. How does it affect the ability to make mods?
1. Lots of people come here from the YouTube tutorial series, is this going to be easily understandable to them and other beginners. 

The reason we care and ask about performance is that we've already twice had issues with things doing too much on the update tick.

**Comment by pderuiter77** [comment]
1. At first all objects (InstalledObject, Inventory)
2. It makes it easy to combine (existing, C# coded) wanted behaviour instead of DIY in lua. 
3. no, which is why i suggested in my other (closed) thread to let Quill decide if this is a direction we want to go

**Comment by vogonistic** [comment]
I would love to see a functioning component system in action, but if it removes the ability to add new behaviors by modders and it's a fundamental departure from how things work, I'm going to vote no for now.

Is there a middle ground where we don't have to rewrite everything?

At some point (off this thread), I would love to hear how choosing upholstery is the same as a technology that functions completely differently and breaks two existing goals.

**Comment by pderuiter77** [comment]
Cant resist. The upholstry is entity as class or id. A detail that doesnt chang the fundamental choice of components or not.

We could start with installedobject as entity, gaining a list of component?
