### ISSUE TITLE
Furniture loss of power event

### ISSUE THREAD

**Issue by Raketfart** [TeamPorcupine/ProjectPorcupine#1312]
I don't know much about our power system, so this might already exist in some form.

For our furniture, I think it would be usefull to have a Lua function we can use when furniture is losing power.  Both for controlling what happends when losing power, and for setting a "power off" animation.
Then we could control that the oxygen compresser maybe leaks oxygen, when not powered.

Right now, it seems OnUpdate isn't called when power is out. Could we add two new actions that are called once?
<Action event="OnPowerOn" functionName="TurnOn" />
<Action event="OnPowerOff" functionName="TurnOff" />

Or maybe just add this as a separate poweroff update?
<Action event="OnUpdatePowerOff" functionName="OnUpdate_NoPower" />

Or is there a smarter way?

**Comment by dusho** [comment]
you want separate animation for power off state? isn't there overlay when power is off? shouldn't all furniture fallback to idle state.. or you just want to define somehow what is the default animation for furniture (that will also be used for powered off furniture)

**Comment by Raketfart** [comment]
There is an overlay for power off, but Lua can't switch to an idle state, because OnUpdate is not called. And I would imagine that furniture would behave differently when losing power. Maybe the clone dies in the cloning machine.

**Comment by dusho** [comment]
ah ok.. cause mostly on power off things can go into idle state (if defined) as default
additionally event can be triggered (if lua wants to override it)

**Comment by Raketfart** [comment]
I could easily make the animation return to default (idle) state, but I imagine that having control over this i Lua would be nice. I can make a PR with the suggested change.

**Comment by TomMalbran** [comment]
Sure we can add more events triggered when the furniture looses its power and when the power is really low, and any other event we need. Those are easy to add.
