### ISSUE TITLE
Working furniture from outside of the furniture

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1315]
Currently all of our furnitures have their JobSpotOffset within the bounds of the furniture, and while this makes sense for some furniture, it doesn't make as much sense for other furniture to stand on top of it while you work it. 

The system as is handles JobSpotOffsets outside the furniture just fine, but for optimum appearance and user experience a few changes would need to be made. 

The first is to not having the mouse "grab" furniture by it's JobSpotOffset (as this just looks silly when that offset is outside of the furniture), this is an incredibly easy change (just removing the lines of code that check for JobSpotOffset and center the furniture being placed on that, it will return to the default of being placed by the center). 

The second is to have furniture make sure its JobSpot is clear, which is still fairly easy, I've already implemented it in a test branch (currently only checking that it is clear of furniture, it should also check for pending jobs that would interrupt, but highly doubt that check would be any more difficult).

The third is simply showing some indicator of where the JobSpot is, though perhaps only if it isn't inside the furniture (I'm not absolutely sure which is the best option, only show when outside of furniture, or always show).

Later of course, when we have chairs and things we will need to alter the check to only check for furniture that isn't those types of things that would be allowable.

Thoughts on implementing more support for JobSpots outside of the furniture?

**Comment by TomMalbran** [comment]
I think that is basically it. Is what Quill talk about in his videos but never got to implement.

Another thing that we might think of is the spawn job spot, which could later be outside the furniture, and we could make it spawn in some sort of stockpile furniture. Similar could be with an input spot.

**Comment by Raketfart** [comment]
Yeah, spawning onto a conveyor belt. Automation here we come

**Comment by dusho** [comment]
if the furniture uses workshop functionality, you can define input/output slots wherever (offset from origin of furniture)

**Comment by Raketfart** [comment]
Will we need to take that into account when placing the furniture, so you don't spawn on top of a wall or something?

**Comment by dusho** [comment]
no, not when placing.. I was thinking about that.. but it can happen that you will place furniture and then place the wall or other furniture where output slot is
so currently workshop just doesn't provide any output if output slot is not available (Factorio style)

**Comment by koosemose** [comment]
Not talking about the Input/Output, but where a furniture is worked from.

**Comment by TomMalbran** [comment]
I know that you aren't. But the same logic can be applied to all 3 spots.

**Comment by koosemose** [comment]
Ahh, didn't notice that agreement with the main point was apparently so quick that the discussion moved on to other related things, lol.

**Comment by TomMalbran** [comment]
One more thing. We might also need to check when placing other furniture if it is on the job spot of a furniture already placed or that will be placed after completing a pending job, and only allow it if what is being place is a chair of some kind.

**Comment by koosemose** [comment]
Another good point.

Also what are thoughts on allowing to work spots to overlap. It makes sense from a believability standpoint, where each one is accessible, but probably not at the same time, though our current implementation would be perfectly happy letting two crew stand in the same tile to work 2 different furniture.

**Comment by TomMalbran** [comment]
I wouldn't mind if they overlap, but I wouldn't allow 2 characters be standing on the same tile. When they move is fine, but when they don't they should reserve the tile.
The chair might look wrong though, since I don't that we will prevent the rotation.

But for output, it might not work unless we have a stockpile furniture that holds more than 1 inventory.

**Comment by koosemose** [comment]
2 character not working from the same tile/standing in the same tile will have to be handled from elsewhere, I'll go ahead and continue the work on what I've got going right now, and we can go from there.

**Comment by TomMalbran** [comment]
Yes, the Job system might need to handle that. If the tile is occupied by another character, then it can't do the job.

**Comment by koosemose** [comment]
Implemented by #1352, any suggestions for further improvements can be discussed in another issue.
