### ISSUE TITLE
Thermal Diffusivity

### ISSUE THREAD

**Issue by Geoffrotism** [TeamPorcupine/ProjectPorcupine#1320]
the diffusivity attribute of an object on z lvl 0 is being applied to all z lvls.
![image](https://cloud.githubusercontent.com/assets/5430964/18525551/f8e41570-7a8a-11e6-97ce-ad4a2ac10ee6.png)
![image](https://cloud.githubusercontent.com/assets/5430964/18525565/05137d4a-7a8b-11e6-83ed-ea58a5d6b5e3.png)

**Comment by koosemose** [comment]
There's a good chance the issue is in the overlay only showing the first z-level rather than Thermal Diffusivity only using first Z-Level.

**Comment by Tritaris** [comment]
Currently the `Temperature` class only works on the first z-layer. its not setup for using more than one z-layer at the moment.

**Comment by Geoffrotism** [comment]
I've worked a Long time on making the whole thing 3D. The lua problems are for the overlay.lua and for furniture.lua.

**Comment by koosemose** [comment]
I can sort out the overlay side of things, just needed to make it pass the current layer in, just need GetThermalDiffusivity and GetTemperature to accept a z coordinate and do something with it.

**Comment by Geoffrotism** [comment]
want me to create a PR? not really sure how i share what I have so far.

**Comment by Geoffrotism** [comment]
actually, think i've got it.

**Comment by koosemose** [comment]
If you can sort out letting the temperature system handle z-layers, I'll go ahead with putting in a PR to get the overlay to handle Z-Layers, and then once your PR is in I can follow it up to make sure the temperature related overlays properly use Z.

**Comment by Geoffrotism** [comment]
@koosemose changes fixes this issue.
