### ISSUE TITLE
Pathfinding FPS slowdown

### ISSUE THREAD

**Issue by Geoffrotism** [TeamPorcupine/ProjectPorcupine#1321]
When a character has a job (taking something to the stockpile for example) and then ALL routes to that stockpile are blocked with walls, the FPS drops to 2 for me. when another job (within reach) is created. the FPS jumps back up to 60 and work resumes. Once that task is done the FPS drops again.

**Comment by vogonistic** [comment]
If we decide to go with #1219, this should be fixed. It'd be great if you could test it there.

**Comment by sboigelot** [comment]
@vogonistic tapping the character in the ship at startup drop the FPS from ~76 to ~20 using #1219 
A big improvement already.

![image](https://cloud.githubusercontent.com/assets/6545998/18528996/99bb7782-7acb-11e6-84c9-11f49b8eeb7b.png)

**Comment by vogonistic** [comment]
Interesting, I'll add that as something to investigate before I turn off `WIP` on it.

**Comment by kd7uiy** [comment]
Try out #1342 as well, it should help some.

**Comment by Geoffrotism** [comment]
Im going to consider this one closed. We can reopen another later if need be.
