### ISSUE TITLE
Planned Airlock Functionality

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1328]
In the most basic form an airlock should prevent air from being lost as crew exit the base. This is currently possible in an extremely simplistic form (two airlock doors, and a pump keeping the room a vacuum, with the outer door pressure locked). 

For a more properly functional airlock, it should function with both doors pressure locked, never opening a door with the rooms on either side having different pressure, and preventing any rushes of air. So when the inner door needs opened, it will pump the air inside up to 1 atm pressure (assuming that is the pressure inside the base), the crewmember enters, and then when they need to exit the base it should pump the air back out. 

Optimum functionality (most likely for a later version than 0.1) should have some sort of queuing system to prevent crew from fighting over rather air needs pumped in or out (creating a deadlock), and just for more generally efficient use of the airlock.

The base things needed for a fully functional airlock is a door that can be pressure locked to only open when the pressure is equal on both sides and doesn't leak air, a pump that can pump air in or out of the airlock, and some form of room behavior that can be used to designate a room to function as an airlock, and ensure that it has access to the required items ( 2 airlock doors and a pump at a minimum ), and can be used to handle the interactions between the airlock door and the pump ( primarily activating the pump in such a way to bring the pressure to the proper level to allow the door to open ).

The airlock door is in and can be pressure locked, and the pump is in and functional as well. All that is needed is a Room Behavior of some form. 

As the room behavior/designation is what still needs implemented that will be my primary focus on discussion. 

I think the code for controlling the airlock door should live in the Room behaviors, rather than in the door and pump, as that makes the most logical sense, though I am not absolutely certain at this time if all of the relevant code can function solely from the Room Behavior side. The specific details of implementation will depend on what exactly will work. 

For a first pass for 0.1 Room Behaviors will most likely be assigned purely on a room by room basis, with the possibility for rooms behaviors being able to be designated to a limited area of the room to be investigated in the future. 

Room Behaviors should probably follow a similar prototype system as most of the rest of our system is, with similar Lua hooks, a dictionary of Furniture, keyed by what purpose it serves, and Parameters for any other arbitrary information that needs to either be available to Lua or stored.

What other functionality might be needed for RoomBehaviors (and possibly an alternative name) to implement an airlock, and potentially be useful for other RoomBehaviors than airlock, though initial development will likely focus on what's needed for airlocks, with other things either implemented if they're "adjacent" to airlock functionality, as possible, or just delayed for future refinements.

**Comment by pderuiter77** [comment]
This discussion sounds familiar..

**Comment by koosemose** [comment]
This is more focused on specifically implementing the functionality to make a fully functional airlock. Room Behaviors are just a part of that, and as I mentioned in the original post on this issue, designating areas within a room (or zones as you call them) can be looked at for future expansion.

**Comment by pderuiter77** [comment]
But room behaviour is new as well, so why not do it properly right away?

**Comment by koosemose** [comment]
Well for one, there hasn't been an agreement that that is in fact "properly" as of right now, and there's less overall work required if we implement room behaviors on a per room basis for now, and later expand to a customizable area, than there would of doing the more complex customizable area and then having to trim it down and alter it to function for a per room basis.

If you have some ideas on how exactly to implement a customizable area that can handle potentially irregularly shaped rooms without being a pain for a user to make use of them, feel free, I'd be happy for someone else to take up the implementation.

**Comment by Geoffrotism** [comment]
I like the idea. Two doors and a vent- won't open unless pressure is equal. Would be interesting to see characters get locked out if power failed. That's all I have on the subject unfortunately. Implementation- I don't exactly like zoning it as an airlock. I want to get away from the prison architect zone everything feel. if the doors simply checked either side to determine pressure and only opened if they were equal would be fine. Then just have a special vent type? It takes from @koosemose idea and I think just naturally works.

**Comment by koosemose** [comment]
We already have the doors that pressure lock as you mentioned and a vent to do the pumping, the issue, and the reason we need some kind of room designation, is that the door needs to be able to communicate with the pump, and the simplest method of doing that is to have some form of room behavior.

It *might* be feasible to have a room check if it qualifies for being an airlock when an airlock door is placed or something else, but that, like custom sized room behaviors is a more complicated behavior that will require a much more complex setup.

**Comment by vogonistic** [comment]
Unless someone has a great suggestion for custom zones and are willing to implement it, I vote we move forward with room-based solutions.

**Comment by koosemose** [comment]
Closing as completed
