### ISSUE TITLE
A video i made for the game. kinda of a "trailer" 

### ISSUE THREAD

**Issue by TheAvaren** [TeamPorcupine/ProjectPorcupine#1377]
https://youtu.be/UIKgPoq1b2s

**Comment by Raketfart** [comment]
Very cool. And no ingame footage like a true tripple-A game trailer ;)

**Comment by sboigelot** [comment]
Cool :) What is the music, is it usable with our licences?

**Comment by TheAvaren** [comment]
The music was created by @Geoffrotism he made the sound file and it and kinda just explicitly used it without his permission but that's ok, i got permission to use it after i made the video

**Comment by sboigelot** [comment]
Yep I just saw it on discord :) very good news

**Comment by mikejbrown** [comment]
Nice vid, but I'm not sure what the "Issue" here is! :grinning: So I made a link to the trailer on the wiki and am closing this for now.
