### ISSUE TITLE
[Bug] Vent is showing wrong graphic

### ISSUE THREAD

**Issue by NogginBops** [TeamPorcupine/ProjectPorcupine#1384]
Vents show the wrong open/closed graphic.

The lua code is doing the right thing and the sprites are defined correctly. I already checked. ;)

Showing that it's closed but it's actually open:
![image](https://cloud.githubusercontent.com/assets/3778357/18610037/5ee645a4-7d11-11e6-9c26-f548ee189aed.png)

And closed but showing that it's open:
![image](https://cloud.githubusercontent.com/assets/3778357/18610039/763ff33a-7d11-11e6-9491-db0e5468a1dd.png)

**Comment by jaselito** [comment]
Should be a simple matter of changing the xml file... will fix.

**Comment by NogginBops** [comment]
@jaselito This is not the fix. The xml is right, it's how the openness value in the furniture is mapped to the sprite that is wrong.

**Comment by jaselito** [comment]
Ooops... you're right...

**Comment by jaselito** [comment]
So... hope I did it right this time :P

**Comment by jaselito** [comment]
This actually will be fixed by #1380
