### ISSUE TITLE
No Inventory MaxSize records

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1395]
While working on #1393 I discovered there doesn't seem to be a way to get the MaxStackSize from code for inventory. It seems there should be prototypes of Inventory similar to the prototypes for Furniture. I'm not going to do that in #1393, it includes more than it should already, but it's something we should consider for the future. Or maybe there is something and I'm just missing it...

**Comment by vogonistic** [comment]
I don't understand what you mean. You can fetch `character.Inventory.MaxStackSize`. Do you mean there is no way to set a different `MaxStackSize` for when it's carried by a character?

**Comment by kd7uiy** [comment]
When creating a material, from where do you get the max stack size
initially?

**Comment by gunthergun** [comment]
InventoryCommon should handle prototypes for inventory in world there should be an inventoryprototypes

**Comment by TomMalbran** [comment]
You can get it like this: ```PrototypeManager.Inventory.Get("Raw Iron").MaxStackSize```.

InventoryCommon and Inventory should be merged. @Grenkin1988 was working on that.

**Comment by sboigelot** [comment]
It is set in the ctor by ImportPrototypeSettings

**Comment by kd7uiy** [comment]
Ahhh, got it! I thought there must be a way somehow, but thanks for the information!

I agree that the InventoryCommon merging in to the Inventory seems like a good idea.
