### ISSUE TITLE
Git Newb questions

### ISSUE THREAD

**Issue by Raketfart** [TeamPorcupine/ProjectPorcupine#140]
Having never used Git in a team before, I'm a little clueless here. Sorry if these questions are a bit dumb.

1. I have a pull request pending. Do I just wait for a merge before deleting this branch?
2. I'm not sure when to pull from TeamPorcupine/Master to my fork. Can this mess up my pending pull request?
3. With currently 21 pull requests pending, it seems like I'm working on an outdated version of the project already. It's a little much to remember which files are affected in these 21 pull requests, and what things may already be changed. How is this normally handled in a collaboration like this? Can I pull these requests to my fork somehow, or is that a no-no?

**Comment by emilkris33** [comment]
1. DO NOT DELETE your branch before the PR as been accepted. Once it is accepted it will tell you on the PR page that is safe to delete. Until the just keep the branch around and do your new work on another branch.
2. Definitely pull all changes from TeamPorcupine/Master to your master and then to you branches. Then check if your code still works with the TeamPorcupine/Master. TeamPorcupine/Master contains the current common version of the project and it is important that we whenever possible pull from it. That way we have the biggest chance of catching conflicts.

**Comment by emilkris33** [comment]
3. This is a lot more difficult to answer but in general keep working form the current TeamPorcupine/Master. The best you can really do is look at the list of pull request and try to work on different things than what they do. Then when they get accepted you can pull from TeamPorcupine/Master and try to integrate with it then.

**Comment by Mizipzor** [comment]
@emilkris33 Did you just answer #1 twice? If that wasnt your intention you should edit your initial post and not make a new one, markdown doesnt allow you to start a numbered list on 3.

**Comment by Raketfart** [comment]
Thanks for the replies, I'll try to get the hang of this. 
I've pulled to my master, but now I can't leave my branch. It says I haven't committed various license txt files, and I won't commit these files, as they are not part of my changes. I'll just wait for a merge.

**Comment by Mizipzor** [comment]
@Raketfart what do you mean by you cant leave your branch? Is it because you have "staged" changes? That's a Git concept you should look up. Your changes to your files can either be staged or unstaged and you should be comfortable moving between them.

**Comment by relinu** [comment]
Thta's the same issue as i am having, apply the changes to your master. Later you can rebase your PR and force push wihtout the 5  license files

**Comment by Raketfart** [comment]
I haven't changed these txt files, and don't want to risk accidentally adding these files to my PR.
I'll experiment with staging and rebasing with other test branches at some point.

I'll close this for now - thanks for all your replies.

**Comment by Mizipzor** [comment]
Is it because the line ending commits? If so I believe it will be fixed by #143.
