### ISSUE TITLE
Contributor script should include localisation repository

### ISSUE THREAD

**Issue by sboigelot** [TeamPorcupine/ProjectPorcupine#1401]
Contributor script should include the contributor from the localisation repository

**Comment by kd7uiy** [comment]
If you point me to that repository, I'll add it in tomorrow.

**Comment by bjubes** [comment]
https://github.com/QuiZr/ProjectPorcupineLocalization/tree/Someone_will_come_up_with_a_proper_naming_scheme_later
this will be a temporary change however, eventually the localization repo will belong to TeamPorcupine

**Comment by kd7uiy** [comment]
Okay, so it seems that the API doesn't support getting the commit list from a branch, it has to be from the master node... I can do it by reading each one of the commits one by one, but that will be a bit more difficult...
