### ISSUE TITLE
Why is localization in a separate repository again?

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1402]
I've known for a while that the localization was being done in a separate repository. I just looked at that repository, and noticed it has 26 commits, with 2 contributors. It seems like the activity isn't enough to justify a completely separate repository now. Why is it a separate thing again? https://github.com/QuiZr/ProjectPorcupineLocalization/tree/Someone_will_come_up_with_a_proper_naming_scheme_later

**Comment by mikejbrown** [comment]
See #1197. Since this is essentially a duplicate I'll close this for now.
