### ISSUE TITLE
RoomEnclosure furniture causes adjacent rooms to become Room 0 when built

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1405]
When any furniture marked as Room Enclosing is placed all adjacent rooms become Room 0, this happens both when directly placing in dev mode or when built by a crew member.

**Comment by mikejbrown** [comment]
Confirmed on master. Starting to bisect.

**Comment by koosemose** [comment]
I strongly suspect it is #1072 (Room Events), reverting this change on a test branch fixes the problem. Digging into the code to see what specifically causes the problem.

**Comment by mikejbrown** [comment]
Confirmed.
```
0d3bbd244536137d5fb6aa99e0f2ab3859afe933 is the first bad commit
commit 0d3bbd244536137d5fb6aa99e0f2ab3859afe933
Author: Victor M. Suarez <svmnotn@gmail.com>
Date:   Sun Sep 18 20:07:04 2016 -0400

    RoomEvents as per #1071 (#1072)

    * RoomEvents

    * add comments

    * fix comments

    * apparently stylecop is fine with this

    * fix comments

    * fix some log spam
```

**Comment by koosemose** [comment]
Interestingly enough, it does just fine splitting a room off from the outside room, if you separate an area from the outside it get's properly assigned as a room.

**Comment by koosemose** [comment]
I think I figured it out... It was in fact only doing it when you were splitting the outside room because that's exactly what it was being told to do. Submitting a fix momentarily.

**Comment by mikejbrown** [comment]
Good debugging. :tada:

**Comment by koosemose** [comment]
Thanks... though it's at least half luck that I happened to try create a room split from the outside room, that was the key to finding what went wrong.
