### ISSUE TITLE
[bug] placing any object that creates heat is bugged

### ISSUE THREAD

**Issue by Geoffrotism** [TeamPorcupine/ProjectPorcupine#1406]
Error thrown when placing a heater or RTG

> chunk_1:(673,4-63): cannot access field GetSize of userdata<ProjectPorcupine.Rooms.Room>
> UnityEngine.Debug:LogError(Object)
> UberLogger.Logger:ForwardToUnity(Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:506)
> UberLogger.Logger:Log(String, Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:452)
> Debug:ULogErrorChannel(String, String, Object[]) (at Assets/UberLogger/Debug.cs:322)
> LuaFunctions:Call(String, Object[]) (at Assets/Scripts/Models/Functions/LuaFunctions.cs:89)
> LuaFunctions:CallWithInstance(String[], Object, Single) (at Assets/Scripts/Models/Functions/LuaFunctions.cs:119)
> EventActions:Trigger(String, Furniture, Single) (at Assets/Scripts/Models/Events/EventAction.cs:134)
> <RegisterSinkOrSource>c__AnonStorey1B:<>m__2D(Single) (at Assets/Scripts/Models/Area/Temperature.cs:109)
> Temperature:ProgressTemperature(Single) (at Assets/Scripts/Models/Area/Temperature.cs:260)
> Temperature:Update() (at Assets/Scripts/Models/Area/Temperature.cs:99)
> World:TickFixedFrequency(Single) (at Assets/Scripts/Models/Area/World.cs:156)
> TimeManager:InvokeEvent(Action`1, Single) (at Assets/Scripts/Models/Events/TimeManager.cs:198)
> TimeManager:Update(Single) (at Assets/Scripts/Models/Events/TimeManager.cs:142)
> WorldController:Update() (at Assets/Scripts/Controllers/WorldController.cs:143)

**Comment by mikejbrown** [comment]
This also seems to have been caused by #1072 (c.f. #1405 for other bug) @svmnotn @koosemose.

**Comment by koosemose** [comment]
This one should be an easy fix. The lua code wasn't updated when room was changed. Line 445 of Furniture.lua needs changed to `    pressure = tile.Room.GetGasPressure() / tile.Room.TileCount`

**Comment by Geoffrotism** [comment]
there are actually a few places in that doc that room.GetSize() appears.

**Comment by mikejbrown** [comment]
Yeah I'm on it.

**Comment by Geoffrotism** [comment]
Now i am receiving this error:

> chunk_1:(445,4-65): attempt to call a number value
> UnityEngine.Debug:LogError(Object)
> UberLogger.Logger:ForwardToUnity(Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:506)
> UberLogger.Logger:Log(String, Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:452)
> Debug:ULogErrorChannel(String, String, Object[]) (at Assets/UberLogger/Debug.cs:322)
> LuaFunctions:Call(String, Object[]) (at Assets/Scripts/Models/Functions/LuaFunctions.cs:89)
> LuaFunctions:CallWithInstance(String[], Object, Single) (at Assets/Scripts/Models/Functions/LuaFunctions.cs:119)
> EventActions:Trigger(String, Furniture, Single) (at Assets/Scripts/Models/Events/EventAction.cs:134)
> <RegisterSinkOrSource>c__AnonStorey1B:<>m__2D(Single) (at Assets/Scripts/Models/Area/Temperature.cs:109)
> Temperature:ProgressTemperature(Single) (at Assets/Scripts/Models/Area/Temperature.cs:260)
> Temperature:Update() (at Assets/Scripts/Models/Area/Temperature.cs:99)
> World:TickFixedFrequency(Single) (at Assets/Scripts/Models/Area/World.cs:156)
> TimeManager:InvokeEvent(Action`1, Single) (at Assets/Scripts/Models/Events/TimeManager.cs:198)
> TimeManager:Update(Single) (at Assets/Scripts/Models/Events/TimeManager.cs:142)
> WorldController:Update() (at Assets/Scripts/Controllers/WorldController.cs:143)
>

**Comment by mikejbrown** [comment]
What are you doing to get this? And are you on master or my PR branch #1407?

**Comment by Geoffrotism** [comment]
Master with the LUA file changes. if youre not getting errors in your PR then thats my fault for being impatient :)

**Comment by mikejbrown** [comment]
Are you doing Room.TileCount or Room.TileCount()? TileCount is a property now, not a method.

**Comment by Geoffrotism** [comment]
youre a smart man. my mistake. now the error msg makes sense.
