### ISSUE TITLE
Labeling of Issues

### ISSUE THREAD

**Issue by lameox** [TeamPorcupine/ProjectPorcupine#141]
I think we should decide on some labels we might use for tagging our issues. This should help us organize them once we have a larger number of issues. 

I think we could use this Issue to decide on a Initial set of tags we might use. I will update this post to contain all proposed Labels.

Some obvious ones that come to mind are:
- Discussion
- Enhancement
- Bug
- Help wanted
- Up For Grabs
- For Beginners => Should serve as a good entry point for a newcomer to the project as discussed in #72 
- Question

Additional Proposed Labels:
- Lua
- C#
- Modding
- Git
- Prio A/B/C

Thoughts?

**Comment by Raketfart** [comment]
Seems reasonable. I don't know if Lua/C# labels are relevant

**Comment by lameox** [comment]
Good Call. Also a Modding label

**Comment by Tranberry** [comment]
@Raketfart while I haven't made my mind on the matter - I believe it could be useful for asking help with coding lua/c#.

**Comment by Mizipzor** [comment]
Yes, this absolutely needs to happen!

**Comment by Koljenka** [comment]
@lameox maybe put a "git" label in there to so if people have a problem with git they can label it too.

**Comment by lameox** [comment]
@Koljenka sure thing

**Comment by SanteriHetekivi** [comment]
Some priority or importance tags would be good, so most critical ones can be listed and fixed first.

**Comment by lameox** [comment]
Added Prio A/B/C to OP

**Comment by quill18** [comment]
Added: lua / c# / modding / git / for beginners / high priority   -- many of the others are available by default.

Annoyed that Github doesn't allow users to self-label their posts. I get the logic, but I think the wins would be bigger than the losses.  Oh well.

Perhaps people can tag their posts with a desired label in [square brackets] and Collaborators can update the posts as appropriate (assuming it's an issue/PR that will stick around for a while).
