### ISSUE TITLE
Animated character - is it to early?

### ISSUE THREAD

**Issue by Tranberry** [TeamPorcupine/ProjectPorcupine#142]
I want to try my hand at making a a place-holder character that is animated. But I would like to know what the community have to say on that topic.

Is it just a waste of time or would it be a good thing to chisel out now?

---

If I was to start I would make something similar to these #102 exploded and animated with the animator feature of unity, but I could also try some hand-drawn static animation (sprite-sheet).

**Comment by Raketfart** [comment]
I think it's fine to work on it now. 
I would prefer sprite-sheet animation, as it's more in line with the rest of the project, using png and xml files. It would not depend on Unity very much, and allow for easy modding.

**Comment by Mizipzor** [comment]
If you want to do it then do it. Animations should be implemented completely separate from any game logic (at least in this game) so it's never too early (nor too late):

**Comment by Tranberry** [comment]
@Raketfart That was my guess (and fear). That will take days to make* compared to the unity animator way.

`*` looking ok'ish.

@Mizipzor I think Raketfart has a valid point in not using prefabs(animator), and frankly I don't think I will spend time on that then.

**Comment by Raketfart** [comment]
If you want, I'll do some spritesheets for you.

**Comment by Tranberry** [comment]
@Raketfart  I would like that

**Comment by Raketfart** [comment]
Here is a modified version of KenneyNL's sprites. It's still very much placeholder art, but should be enough to get us started.

Here is a preview (with background)
![preview](https://cloud.githubusercontent.com/assets/7031323/17773714/faef85fc-654f-11e6-997a-abc35ca5d0fe.png)


This is an xml file, containing coordinates (I couldn't attach .xml directly):
[p1_front_animated.txt](https://github.com/TeamPorcupine/ProjectPorcupine/files/424842/p1_front_animated.txt)

Here is the png file. I hope you can flip the east facing parts for west facing parts. Otherwise I'll add those.
![p1_animated](https://cloud.githubusercontent.com/assets/7031323/17773513/23369100-654f-11e6-9229-1e7b5850ec92.png)

Not sure how you want the xml file to describe the animation, but I'll leave that up to you.

**Comment by Tranberry** [comment]
I'd say that is exectly what I wanted to do, now it's simply adding stuff over this to change the sprite. I wonder if we should dive into clothes and 'wearables' and how that will work.

**Comment by RodRitter** [comment]
Those are pretty cool. I don't see why you can't add it as a Unity animated sprite.

**Comment by Tranberry** [comment]
@RodRitter I'm not sure that you are talking about my comment on unity animator or not. But this is a pre-made sprite not using unity [Animator] at all, it's much harder to do imo but you don't have to make a prefab.

**Comment by RodRitter** [comment]
What do you mean? You literally add the png and let Unity automatically slice it up. Then you drag in the frames you want as an animation. It will create an animation for it.

**Comment by Tranberry** [comment]
unity Anima**tor** not animat**ion**. Eg the state-machine animation editor.

**Comment by Sommerbo** [comment]
Using Unitys animator would produce a Asset-file that isn't moddable. And since moddablity without Unity is one stated goal it would be counterproductive to add unmoddable animations.

**Comment by RodRitter** [comment]
Sorry, I never read your comment properly. I still think it will be nice to add an animated character for now (even if it's un-moddable).

**Comment by Tranberry** [comment]
No worries, but this @Raketfart animation will be moddable.

**Comment by Raketfart** [comment]
@Tranberry He should at least be able to take off his helmet when indoors :-)
Maybe this is for a later version of the animation system, but the helmet spritesheet could easily be seperate from the character spritesheet.

**Comment by RodRitter** [comment]
Oh right. Then that's awesome. I need to really read the full thread before I post comments.

**Comment by BeefEX** [comment]
Can I claim the animation controller please. Or is somebody ellse already working on it?

**Comment by Raketfart** [comment]
If any of you want, here is all 3 spritesheets. Character with helmet, Character without helmet, and the helmet in seperate files. 

[p1_animated.zip](https://github.com/TeamPorcupine/ProjectPorcupine/files/424924/p1_animated.zip)

Maybe animationspeed should be in the xml file, so 2 step animation could easily be replaced by 4 step animation.

**Comment by BeefEX** [comment]
will work on this. thanks for idea

**Comment by Mizipzor** [comment]
@Raketfart add the spritesheet yourself and make a pull request to @BeefEX's fork. That way you get proper attribution, something that I think is important. If he adds them, it looks like he made them.

**Comment by Raketfart** [comment]
@Mizipzor That sounds awfully complicated for a git-rookie who only uses the GUI client. I don't really care about getting credit for this, as this is only placeholder graphics.

**Comment by Mizipzor** [comment]
@Raketfart I suppose that is up to you, but I would take this opportunity to learn Git. :) Isn't learning the point of this? And, for the record, is it not complicated at all.

**Comment by Raketfart** [comment]
@Mizipzor Yeah, I'm trying to learn Git, but right now the various txt files are messing up my GUI client. I'll wait for some of these PR to get merged, as that should hopefully fix it. Then I'll definetly experiment more.

**Comment by Mizipzor** [comment]
@Raketfart Good call. Keep track of #143.

**Comment by Tranberry** [comment]
I'm not going to upload/pull anyone else work if that is what you are talking about @Mizipzor . I would use this as a base animation sheet to make my own characters if I was going to upload/pull anything.

**Comment by BeefEX** [comment]
After thinking a bit, i decided that i will just use the current system for loading sprites. But than you have to specify attributes of the furniture or character in the XML file, whitch will cause this sprite to show up. Do you agree with this idea?

**Comment by BeefEX** [comment]
This way it would be possible to you same system for both static images and animations.

**Comment by Tranberry** [comment]
I'm for trying to stay on the current path as much as possible, small incremental changes seems to be the best way.

**Comment by BeefEX** [comment]
Thats how i think too. Just got idea on how to implement it without breaking current system. :smile:

**Comment by Raketfart** [comment]
@Tranberry @BeefEX I'm not sure if you're both working on this, but just to be clear - you are welcome to use these graphics in your PR's with animation controllers. Doesn't have to slow you down, by having to wait for a merged PR from me.

**Comment by Tranberry** [comment]
@Raketfart I'm using your spritesheet for reference, I'm pretty new to 2D animation the classic way so your work helps a lot, thanks again!

**Comment by BeefEX** [comment]
@Tranberry so you are working on animation controller too?

**Comment by BeefEX** [comment]
@Tranberry or are you just making animations?

**Comment by Tranberry** [comment]
No go ahead, I'm not claiming anything. Currently I'm testing different ways to animate this kind of character.

**Comment by BeefEX** [comment]
Got animations working on doors. I will go sleep now and tomorrow I will finish it for characters too.

**Comment by Raketfart** [comment]
I added the graphics to PR #444

**Comment by vogonistic** [comment]
Who is interested in working on animating the sprites now that we have them?

**Comment by Raketfart** [comment]
I think @BeefEX is working on it.
If he's not, I'd like to give it a go.

**Comment by Tranberry** [comment]
![18plus_01](https://cloud.githubusercontent.com/assets/16529/17872865/76efbdbe-68c2-11e6-9747-1fcae2d398d3.png)


How will this system work, I mean we will want clothing and other changes to the character.

**Comment by vogonistic** [comment]
Someone please tell me that we can easily layer sprites on this guy

**Comment by Raketfart** [comment]
Wow - nice job @Tranberry!
I think the helmet can easily be seperate as it is en the current build, and the body will probably have to be clothes and walkcycle. 
Maybe color variations could be done in code, if the image is loaded in layers.

@vogonistic We can easily layer sprites on that guy. (maybe. I hope.)

**Comment by Raketfart** [comment]
I hope I'm not stepping on any toes here. I know BeefEx is working on animation, but I couldn't wait, so I made a CharacterAnimation in PR #669.
Sorry

**Comment by Raketfart** [comment]
I have an idea for changing colors. I'm still working on it, but essentially this can replace any color in the sprite with the "charactercolor". This could replace the blue color with any other color. The only drawback, is we have to limit this to a couple of fixed colors that can't be used elsewhere (like greenscreen).
We could have a maincolor, hightlightcolor and shadowcolor that gets replaced.

I made a very fast example here: 
![colorchange](https://cloud.githubusercontent.com/assets/7031323/17891590/2913aa1c-693d-11e6-9a17-b1523e1b2cb2.jpg)

**Comment by Tranberry** [comment]
![pixelatedspacefarerspritesheet](https://cloud.githubusercontent.com/assets/16529/17893460/16ac3d40-6946-11e6-8b42-93535548f4ed.png)


First 'final' draft, if anyone wants to play with it. No masking layers yet (I'm on lunch might take some time).

**Comment by Raketfart** [comment]
I do! But this image is 786x786, so larger than the 512x512 original spritesheet. 
What pixelPerUnit should it use? 
Or is the character just supposed to be a bit larger?


You don't have to make a masking layer, we just define your colors like this, and the blue line will be replaced:
        Color32 fromColorMain = new Color32(71, 86, 163, 255);
        Color32 fromColorLight = new Color32(142, 154, 212, 255);
        Color32 fromColorDark = new Color32(42, 56, 126, 255);

**Comment by Tranberry** [comment]
I'll fix that. 
![pixelatedspacefarerspritesheet](https://cloud.githubusercontent.com/assets/16529/17894310/3d1973b4-6949-11e6-8806-f1ff14d5106b.png)

**Comment by Raketfart** [comment]
This looks SOOO cool. Good job @Tranberry 
![colors](https://cloud.githubusercontent.com/assets/7031323/17895041/088f350e-694c-11e6-8e3f-7f2bfb3b8411.png)

Is it possible to have this guy without helmet in this spritesheet, and then the helmet in a separate spritesheet but same locations as now? Then he can remove the helmet when indoors.
Or is it easier to just have two spritesheets - one with helmet, and one without?

**Comment by Tranberry** [comment]
I'm on it! (helmet-less character)

**Comment by Raketfart** [comment]
I just changed the recoloring to using a shader, which was much faster.
The way that works, is the shader ONLY looks at the red value, if they match, it replaces the color.
So for example any color with red 151 will be replaced by charactercolor
It's almost done!

**Comment by quill18** [comment]
:+1:

**Comment by Raketfart** [comment]
Maybe we can close this issue now.

**Comment by Tranberry** [comment]
Now  that I back I can clean up my mess myself
