### ISSUE TITLE
ASCII Mode For Toasters

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#1423]
I heard Quill say, during LD36, that Project Porcupine could be made ASCII...
An obvious example is copper coils would be orange "@", and floors are grey bakground?

Is this actually doable, or... worth it?

**Comment by ComputerOverlord** [comment]
We could also ask moddellers to make a 3D version.... Stonesence for Project Porcupine!

I got this idea from #1269 When I found it hard to see the entire shape of the asteroid

**Comment by mikejbrown** [comment]
I might be possible to "fake" console mode with a sprite sheet relatively easily, but I'm not an art guy so...

**Comment by pderuiter77** [comment]
It would have no real impact on performance though :)

**Comment by kd7uiy** [comment]
Doable- Yes. Worth it- Not in my opinion...

I'd rather go 3-d!

**Comment by sboigelot** [comment]
I don't see the point neither, but it would be easy to do.

**Comment by ComputerOverlord** [comment]
Alrighty Then! CLOSIN' TIME
