### ISSUE TITLE
Temperature effects? [IDEA?]

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#1424]
You could overheat 😈 or freeze 😨 
😆 
Is this in there?

**Comment by Geoffrotism** [comment]
Im currently working on heat #298 and #1326.

**Comment by mikejbrown** [comment]
Any reason to keep this open?

**Comment by Geoffrotism** [comment]
I'll add it to the wiki if you want to close this
