### ISSUE TITLE
Missing English translations

### ISSUE THREAD

**Issue by mikejbrown** [TeamPorcupine/ProjectPorcupine#1425]
These are just the ones I found in a ~minutes play through. Feel free to add any others you find. (I am not expecting a separate issue for each language. This is only because en_US is the default and all keys should be there in the repo.)

- [x] Translation for Empty in en_US language failed: Key not in dictionary.
- [x] Translation for Floor in en_US language failed: Key not in dictionary.
- [x] Translation for Ladder in en_US language failed: Key not in dictionary.
- [x] Translation for furn_metal_furnace in en_US language failed: Key not in dictionary.
- [x] Translation for furn_vent in en_US language failed: Key not in dictionary.
- [x] Translation for util_power_cable in en_US language failed: Key not in dictionary.
- [x] Translation for util_water_pipe in en_US language failed: Key not in dictionary.
- [ ] Translation for  in en_US language failed: Key not in dictionary. (hmmm... not sure why this one was trying to access an empty key...)

**Comment by mikejbrown** [comment]
Should add to v0.1 milestone?

**Comment by svmnotn** [comment]
probably, we probably want to look at that whole system before doing anything else

**Comment by svmnotn** [comment]
I believe at some point we were considering not having an en_US and just using the xml data as a deafult/fallback (so the xml for tiles would include the human en_US name). But I don't think that ever got much farther than a thought.

**Comment by svmnotn** [comment]
Also I believe we are still waiting for quill to make a locale repo under the organization.

**Comment by mikejbrown** [comment]
@svmnotn I just merged #1418 so en_US is now in the main repo. :D (Thanks @sboigelot!)

And I think having fallback defaults for en_US in the xml makes sense.

**Comment by koosemose** [comment]
Added a PR for some of these, I'm not entirely sure why the floor tiles are looking for Empty, Floor, and Ladder, as that's not what's defined for them in the xml... presumably they don't properly make use of the translation keys?

**Comment by mikejbrown** [comment]
Merged in #1427 which fixed some of the above and a few I had missed in my quick play through. Thanks @koosemose!

**Comment by mikejbrown** [comment]
@koosemose #1429 fixes the localization issue for Empty, Floor and Ladder.

**Comment by mikejbrown** [comment]
Tracking down the empty key one is turning out to be a pain...

**Comment by koosemose** [comment]
Perhaps the deconstruct furniture button? Is it done proper-like? It comes up when the construction menu comes up, so it has to be something there, and all of the furnitures, utilities, and tiles have localization codes, so unless maybe it's something with the filter, I would think it almost has to be the deconstruct button.

**Comment by mikejbrown** [comment]
It also happens when you open up the settings menu (only if you haven't open construct first -- the error msg is only written once and then the key is added to a set of known missing keys).

**Comment by jaselito** [comment]
The empty key one is due to the button prefab used in the construction dialog (Assets -> Resources -> UI -> MenuLeft -> ConstructionMenu -> Button), whose text child has an empty string and a TextLocalizer component attached to it. The TextLocalizer tries to find a localization entry for this empty string when the prefab is loaded as a resource. 

Same thing happens with the options dialog and the button prefab it is using.

**Comment by mikejbrown** [comment]
@jaselito Thanks. I'm not a UI guy, so maybe you can think of a way to fix this? I thought of maybe putting a default "button_text_missing" text on the prefab which would localize to a useful error text on the button itself in an angry red font, but when I tried quickly I could not get it to work (as in I couldn't get the default text to go away even when I thought I was explicitly clearing it).

**Comment by jaselito** [comment]
Hmmm I would've thought setting a default text would've soved it...  I'll give it a go, though I find myself struggling with UI as well (among other stuff :grin:)

Just to make sure, I don't know how localization is being dealt with right now... can I add my own keys to the en_US.lang file?

**Comment by mikejbrown** [comment]
@jaselito 
> Just to make sure, I don't know how localization is being dealt with right now... can I add my own keys to the en_US.lang file?

Yes, please do. Keep it up to date anytime you need a new key. en_US is now included in the main repo precisely so you _can_ do that.

**Comment by jaselito** [comment]
In the ConstructionMenu script the following assignment can be found a couple of times:

`gameObject.transform.GetComponentInChildren<TextLocalizer>().formatValues = new string[] { LocalizationTable.GetLocalization(proto.LocalizationCode) };`

Maybe I'm not understanding something, but shouldn't the right side be assigned to the text field of the TextLocalizer, not to the formatValues field?  The text component is the one holding the localization key, isn't it?

**Comment by jaselito** [comment]
On closer inspection, shouldn't it be assigned to the defaultText field?

Gosh, the localization logic is giving me a headache :P

**Comment by jaselito** [comment]
It seems to me that if I replace all instances similar to 

`gameObject.transform.GetComponentInChildren<TextLocalizer>().formatValues = new string[] { LocalizationTable.GetLocalization(proto.LocalizationCode) };`

with similar instances to 
```
TextLocalizer textLocalizer = gameObject.transform.GetComponentInChildren<TextLocalizer>();
textLocalizer.defaultText = proto.LocalizationCode;
textLocalizer.UpdateText();
```
and assign a default string to the text in the button prefab everything works...

This way is how I think it should be, but I'm not sure I wouldn't be breaking anything else... maybe someone with more knowledge of localization can comment.

**Comment by mikejbrown** [comment]
@QuiZr ^^^

**Comment by jaselito** [comment]
Btw, I think you can check off the translations for Empty, Floor and Ladder now that #1429 has been merged.

**Comment by QuiZr** [comment]
No idea - I sadly don't have much time to contribute (:/) + I haven't made that localization system (only downloader + minor fixes).

**Comment by UnknownSoldier1** [comment]
@jaselito  By looking at your code, the best thing would be

`gameObject.transform.GetComponentInChildren<TextLocalizer>()
.UpdateTextCustom(proto.LocalizationCode);`

**Comment by koosemose** [comment]
If I remember correctly the reason for using the formatValues array was for things where the localization key for the object isn't everything, such as how the furniture buttons used to be, they would say, for example, Build Oxygen Generator, and originally we would just append the locale for build to the front... which is wrong because word order is going to be different in some languages, I think the formatValues is the solution to that, allowing the language to also feed in a string with the appropriate places for object's translated name to go, so we weren't forcing everything into english word order, which would be wrong for some languages (and the longer text we start having to have translated with some word arbitrarily inserted into it, the more languages trying it the old way without formatValues will be).

**Comment by jaselito** [comment]
@UnknownSoldier1 Thanks! Would that preserve the information after a language change, though? Anyway, the point is moot after koosemose explained the rationale behind using the formatValues.

@koosemose I see... the best solution then would be to set the button text to a key that points to a "{0}" value in the language file... will try.

**Comment by jaselito** [comment]
Ok. PR #1450 should allow us to finally check that last item in the list off!

**Comment by UnknownSoldier1** [comment]
@jaselito No, it would not preserve that information. As I have seen by looking through the code, I forgot to implement an override for the default text as soon as it gets updated by UpdateTextCustom(...). I might (if I have time) make a PR to fix this. AFAIK, right now it would change it's text to what was there at the beginning when the language is being changed. I haven't checked that though, I might be wrong.

**Comment by jaselito** [comment]
@UnknownSoldier1  Yeah, that's what I see happening as well.  I agree that an override for the default text   would be needed.

**Comment by koosemose** [comment]
The last missing translation should be fixed.

**Comment by mikejbrown** [comment]
There's still the missing key in the settings menu.

**Comment by koosemose** [comment]
Ahh, didn't realize that was a separate one, I would assume the same thing would fix it.

**Comment by UnknownSoldier1** [comment]
@jaselito I made a small PR (#1454) to fix the issue with the default text.

**Comment by jaselito** [comment]
:thumbsup:

**Comment by mikejbrown** [comment]
On current master I still get
```
Translation for  in en_US language failed: Key not in dictionary.
UnityEngine.Debug:Log(Object)
UberLogger.Logger:ForwardToUnity(Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:504)
UberLogger.Logger:Log(String, Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:452)
Debug:ULogChannel(String, String, Object[]) (at Assets/UberLogger/Debug.cs:233)
ProjectPorcupine.Localization.LocalizationTable:GetLocalization(String, FallbackMode, String, String[]) (at Assets/Scripts/Localization/LocalizationTable.cs:146)
ProjectPorcupine.Localization.LocalizationTable:GetLocalization(String, String[]) (at Assets/Scripts/Localization/LocalizationTable.cs:64)
ProjectPorcupine.Localization.TextLocalizer:UpdateText(String[]) (at Assets/Scripts/Localization/TextLocalizer.cs:64)
ProjectPorcupine.Localization.TextLocalizer:Start() (at Assets/Scripts/Localization/TextLocalizer.cs:111)
```
when opening the settings menu.
