### ISSUE TITLE
[BUG] For some reason on the current master the en_US.lang file gets deleted when build!

### ISSUE THREAD

**Issue by gunthergun** [TeamPorcupine/ProjectPorcupine#1431]
After the game runned once the en_US.lang file is gone and deleted. Is this only on my unity or is someone else experiencing the same ?

**Comment by NogginBops** [comment]
It could be the localization script that is deleting it.  Have you checked in there?

**Comment by mikejbrown** [comment]
Does #1430 fix it?

**Comment by gunthergun** [comment]
Yes @mikejbrown that fixes it. It was the localisation downloader seeing the en_US.lang files on startup and deleting them. 1430 fixes this. Thank you :) 👍
