### ISSUE TITLE
Sound Requests

### ISSUE THREAD

**Issue by Geoffrotism** [TeamPorcupine/ProjectPorcupine#1433]
I'm creating this to have a unified location for all sound requests (music is different).
Please leave the name of the object you want to have the sound applied to (can be multiple), and then a short description of what you think it should sound like (ex. hammer on metal).

Creation sounds (when an object is placed):

Event sounds (ex. explosion):

Other:

**Comment by Jaytheway** [comment]
Also to be more organized, I've made a spreadsheet. I suggest everyone using this, improve it or make a better one. It would help to keep everything organized. https://docs.google.com/spreadsheets/d/1TXwJnrMUbtvmQkYY0zqw5KlBm-eqd-JOlEiWSUjAbOo/edit?usp=sharing

**Comment by Geoffrotism** [comment]
wonderful. ill add this to the wiki as well.

**Comment by bjubes** [comment]
FYI its view only so only you can edit it. Not sure if you intend to invite people as they request or if its a mistake

**Comment by Jaytheway** [comment]
You definitely can edit using this link, I just tested it. Try it again, tell me if it's working. I might open it for everyone otherwise. Intended to make it editable for everyone who has this link.

**Comment by bjubes** [comment]
Now i can edit it

**Comment by Geoffrotism** [comment]
closed in favor of #1535
