### ISSUE TITLE
Comment Re-vote- Should all public functions be required to have documentation?

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1434]
Okay, so we are discussing the results of the comment usagage issue thread, #1126,, and it seems that we didn't have a very clear set of criteria. Clearly proposals 1 and 4 were the two highest voted. We've been dissecting these two at Discord, and have come to a few conclusions. First of all, both have in common the following, which will be enforced immediately:

1. Code should be clearly readable. This includes using descriptive names, functions, classes, and minimizing comments inside of functions.
2. Comments should explain what something does, not how it does it.
3. Private methods are option to have summary comments added. 

What is different between the two?

1. All public functions documented vs only "key" files.
2. Comments should be enforced by Stylecop.

I'm proposing that we set up re-vote between those two very specific ideas. 24 hours will be done as before from the submission. Vote on this comment.

:+1: means that:

1. All public functions shall be documented.
2. Stylecop will be enforced.

:-1: means:

1. Only "Key" classes require public documentation, although it is welcome everywhere.
2. Stylecop not enforced (Unless it can be selectively enforced on key classes)

The voting starts now, and will end at 2130 UTC 9/21/16.

**Comment by longtomjr** [comment]
PINGS: @TomMalbran @koosemose @mikejbrown @Dormanil @svmnotn @sboigelot @rafaeu749 @powli @bjubes @Tranberry @gunthergun @Ohda

**Comment by kd7uiy** [comment]
For reference, it is possible to set up selective rule enforcement with Stylecop. See https://stylecop.codeplex.com/wikipage?title=Using%20File%20Lists . So we could define a certain number of classess that are considered key, and add those to the enforcement list, without making everything be enforced.

**Comment by mikejbrown** [comment]
Tagging question because... duh. Tagging high priority because this is time limited. NOT tagging discussion because _this is not a discussion thread_. Vote your preference or abstain.

**Comment by sboigelot** [comment]
This is confusing, I want to vote:

1.1 All public functions should be documented.
2.2 Stylecop not enforced

**Comment by kd7uiy** [comment]
I guess figure out which is more important to you, Stylecop be not enforced, or all public functions be documented? The main point from what I understood of making all of the public functions be documented was to allow for stylecop enforcement, which allows one to more easily figure out what files are missing documentation.

**Comment by sboigelot** [comment]
The the sentence should be:

1.1 All public functions **have to be** documented (or must)

Should is conflicting with the stylecop enforcement

**Comment by kd7uiy** [comment]
I'll use the word Shall, per many years of dealing with requirements in a Systems Engineering approach;-)

**Comment by sboigelot** [comment]
Well then I vote for **should** and not enforced. as per my confused emoticon. Beside the fact that I think we shouldn't force packaged vote, I truly believe that not all public method have to be documented, as sometimes there are extremely obvious. But I agree that public method _should_ be documented if there is any possible confusion.

Adding a comment of top of `public int Integer.Multiply(int by)` of 3 line explaining that this method return the multiplication of the current integer by the parameter is as bad and redundant as duplication of code

**Comment by sboigelot** [comment]
I don't see any mention of stylecop in the original proposal 1 & 4

> 
> Proposal 1
> 
> This is what is required to have a PR be merged:
> 
> Summary on top of all public properties and methods.
> Description of Parameters of Methods.
> Comments inside of methods is discouraged - Code should be readable and speak for itself!
> Summaries for private methods and fields is not required but may be added.
> Summaries for constructors is not needed but it is a good idea to add for complex constructors. Remember: Comments is not a tutorial. It should describe its function and not how it works!

> Proposal 4
> 
> This is what is required to have a PR be merged:
> 
> Use descriptive names for variables, functions, and classes.
> Use summary documentation for all public functions in central functions (Scheduler and Furniture, for instance)
> Comments should explain what something does, not how it does it.
> (stolen from @kd7uiy)

**Comment by Tranberry** [comment]
@longtomjr ^

**Comment by mikejbrown** [comment]
@sboigelot You can change your vote on the top post (click once to add a symbol / click again to remove). I recommend you do so to ensure correct counting. Don't want another result getting tossed out.

**Comment by sboigelot** [comment]
@mikejbrown thanks I know, the problem I have is between the original post of the proposition an the re-post in the new ticket. Everyone voted for 2 options, and the second round is to determinate which one of theses two option wins but add extra content in both that were not there before.

**Comment by bjubes** [comment]
@sboigelot i would go for thumbs down then, that way stylecop isnt brought into the mix and we as gatekeepers can lean in whatever direction we prefer. If you want a method to be commented, then you can add it to a PR using the new PR editing features.

**Comment by longtomjr** [comment]
@sboigelot proposals was open, The reason we are voting just for these 2 is that it was a virtual tie between just those 2

**Comment by NogginBops** [comment]
I think that these kinds of ideas are a bad idea. I think votes in this manner should not be done. They feel really flimsy and everyone is confused. We need a more straitforward voting process. I know that everyone wants to make decisions really fast but with things like votes I think it would be beneficial to allocate a bit more time to them.(the votes)

I kind of like the idea Facebook uses; code wins arguments. What they mean is that rather than spending days in discussion, just code it because working code is more convincing than just theory.

**Comment by longtomjr** [comment]
@NogginBops We have had this topic open for a long time now. Also, this is the 2nd vote we have on this and the results will show the best consensus we can get. We can string this out further but if you go read the discussion about this you will find that rather than proposing solutions we tried to find fault in each others paradigms. There is no use in discussing this further.  

There is  also no reason to be confused, this is as clear as it gets. Vote 1 or vote 2. If you don't care, don't vote. Also, this is a vote, can we please take the discussion about voting elsewhere.

**Comment by dusho** [comment]
With public methods commented it also means all passed parameters, right? Will StyleCop also enforce valid comments for parameters?

**Comment by longtomjr** [comment]
@dusho yes, There is a StyleCop Rule for parameters

**Comment by sboigelot** [comment]
Then I'm really against it. You could disable the stylecop rule for comment on parameters. Also there is not enough detail included in the propositions to take decision.

**Comment by mikejbrown** [comment]
Voting has closed. Results : 8 :+1: --- 6 :-1:

**Comment by mikejbrown** [comment]
Just tested and... I can still change my vote even though the topic is closed. We ***REALLY*** need a better system for voting.

**Comment by mikejbrown** [comment]
Locking seems to lock the vote counts but I can still edit the comments.

**Comment by vogonistic** [comment]
We are discussing a ranked voting system. https://github.com/SpaceKrakens/Ranked-Vote

**Comment by mikejbrown** [comment]
There is an option which has been discussed a little [over here](https://github.com/TeamPorcupine/ProjectPorcupine/issues/1058#issuecomment-248352715). Specifically, the CIVS maintainer seems [favourable to Github integration](https://github.com/andrewcmyers/civs/issues/11) for their service, which is already established. It already has a proven and secure back end. So I would suggest working with that project if possible (don't know for sure if it is). It might be much easier to write a glue layer or some kind of plugin than a brand new system.
