### ISSUE TITLE
3D mode

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#1435]
This is practically an extension of #1423. On the 3D Branch, of course.

**Comment by ComputerOverlord** [comment]
Heck, a 3D mode could allow for ISO!

**Comment by bjubes** [comment]
duplicate of #1017. please see responses there.

**Comment by ComputerOverlord** [comment]
It's a dupe? :P okay... CLOSIN' TIME
