### ISSUE TITLE
LICENSE file is incomplete. (NOT CRITICAL)

### ISSUE THREAD

**Issue by SanteriHetekivi** [TeamPorcupine/ProjectPorcupine#1436]
LICENSE file contains following row:
`{project}  Copyright (C) {year}  {fullname}
` - [LICENSE](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/LICENSE)
Not critical, but I was updating my own licenses and noticed this, when I got to my fork of the project.

**Comment by mikejbrown** [comment]
Huh... wonder how that happened. Oh well, easy enough fix. Added to v0.1 because I guess it probably makes sense to.

Question (IANAL): do we update LICENSE for non-code assets, mods etc. that might need different licensing?

**Comment by koosemose** [comment]
That is not a section we're supposed to fill in, it is instructions to anyone making use of the license on how to show an appropriate copyright.

**Comment by mikejbrown** [comment]
Just read the file & it's true. Nothing to fix here. Keeping this open for now because of my question above.
