### ISSUE TITLE
[Feedback] Generic component system for furniture systems/power/gas/temperature/...

### ISSUE THREAD

**Issue by dusho** [TeamPorcupine/ProjectPorcupine#1437]
So when checking 0.1 milestone I noticed thing that needs implementation : "Atmosphere requirement for some buildings"
When trying to come up with some system I though it could be made somehow generic and use it also for  current power and gas systems. More generic implementation could unify some definitions and provide more possibilities for modders.
Here is how the definition in XML would look like (still just early version, names not final):

``` xml
<!-- need power to work -->
<Environment>
 <Operation name="running">
    <Requires name="power" minValue="1"/>
 </Operation> 
</Environment>

<!-- need power and oxygen to work -->
<Environment>
 <Operation name="running">
    <Requires name="power" minValue="1"/>
    <Requires name="o2" minValue="1"/>  
 </Operation> 
</Environment>

<!-- generator -->
<Environment>
 <Operation name="running"> 
    <Requires name="o2" minValue="2"/>
    <Requires function="PowerGenerator_HasFuel"/>
    <Provides name="power" value="1" conduitType="cable"/>
 </Operation> 
</Environment>

<!-- oxygen generator -->
<Environment>
 <Operation name="running">
    <Requires name="power" minValue="1"/>
    <Provides name="o2" value="0.16" conduitType="tile"/>
 </Operation> 
</Environment>

<!-- heater -->
<Environment>
 <Operation name="running">
    <Requires name="power" minValue="1"/>
    <Requires name="o2" minValue="2"/>
    <Provides name="temperature" value="1" conduitType="tile"/>
 </Operation> 
</Environment>

<!-- something that needs oxygen to build and converts N2 to O2 (plant?) -->
<Environment>
 <Operation name="build">
    <Requires name="O2" maxValue="10"/>
 </Operation> 
 <Operation name="running">
    <Requires name="N2" minValue="1"/>  
    <Provides name="O2" minValue="1" conduitType="tile"/>   
 </Operation> 
</Environment>
```

These are some example definitions that can be used for different furniture types. 
Does this look ok? And covers all we need? Are there any other ideas how to solve this?
Any feedback is welcome.

**Comment by TomMalbran** [comment]
I like the idea of having generic components to handle Power, gas and temperature for different types of furnitures and being able to just set them in the xml, instead of adding more Lua functions. But I am not sure if it can all be in one component. For requirements it might be doable, but I am not sure how it will work for providers (maybe for Power and Temperature might work since there are better systems for those, but there isn't one for Gasses).

I am thinking that this will allow us to replace the Oxygen Generator Lua function with that xml and make it generic so that it can work for any gas. If so, then it should probably be a different component that handles the Gas generation, or a system that handles gasses like the power one.

**Comment by dusho** [comment]
I imagined that gas would work same as temperature.. at least spreading and containment, but maybe not.
And yes, hopefully it can reduce the code duplication in LUA, with ability to still do something special if needed.

**Comment by TomMalbran** [comment]
We could start reducing some Lua code by adding systems/components. The Lua code would then be used for special furnitures, but not generic ones.

I like the idea, but I am not sure how it can be generic when we have different systems for Power and temperature and none for Gases. If it can't be done generic, it would also be fine to have a component for each system, but generic for every furniture.

**Comment by dusho** [comment]
sure.. that can work too.. we can define types we have in code (power, temp, gases, ... ) and map them to some types in XML in generic way (guess using key words)

**Comment by koosemose** [comment]
I should note that the oxygen generator already works with any gases, that was why the function was the more generic OnUpdate_gas_generator, until it got changed.

**Comment by pderuiter77** [comment]
love the idea of using components, like has been suggested in other threads before :)

**Comment by dusho** [comment]
After discussion on discord, here is another attempt with using components 
```xml
<!-- needs electric power to run -->
<Component name="PowerConnection">
	<Requires power="electric" rate="1"/>
</Component>

<!-- gives electric power and some capacity -->
<Component name="PowerConnection">
	<Provides power="electric" rate="2" capacity="4"/>
</Component>

<!-- oxygen generator -->
<Component name="GasConnection">
	<Requires power="electric" rate="1"/>
	<Provides gas="O2" rate="0.16"/>
</Component>

<!-- requires O2 income and some threshold -->
<Component name="GasConnection">
	<Requires gas="O2" rate="0.16"/>
	<Requires gas="O2" threshold="20"/>
</Component>
```

also Workshop changed to component for now, and more things that can be extracted later
```xml
<Component name="Workshop">
	  <ProductionChain name="Power Cell Pressing" processingTime="5">
		  <Input>
			  <Item objectType="Uranium" amount="3" slotPosX="0" slotPosY="0" />
			  <Item objectType="Steel Plate" amount="2" slotPosX="1" slotPosY="0" />
		  </Input>
		  <Output>
			  <Item objectType="Power Cell" amount="1" slotPosX="2" slotPosY="1" />
		  </Output>
	  </ProductionChain>
</Component>
```
Furniture.cs will then have probably (only one type allowed?):
`Hashset<Component> components;`

**Comment by dusho** [comment]
Another potential component (used for mining, harvesting, ... ):
```xml
<Component type="Collectable">
    <RequiresAction>Mine</RequiresAction> <!-- enum: Mine, Harvest, ...-->
    <Provides>        
         <Item type="Raw Copper" amount="1" minAmount="1" maxAmount="2" />      <!-- either exact amount or range-->        
    </Provides> 
    <UseSprite name="copper_ore" asOverlay="true"/>  <!-- name is not required, can be combined with animator-->
    <ParameterDefinitions>
        <ItemType name="item_type" />
        <YieldAmount name="yield_amount" />
    </ParameterDefinitions>
</Component>
```
this would require to have extra furniture defined for every type of mine, but would also allow modders to easily add/edit/remove new features to it.. like changing visuals by amount of mined (harvested) stuff, have animated mine spot, hook some extra events (furniture events covers that, ... )

**Comment by Geoffrotism** [comment]
How many things are we going to be able to mine? would it make sense to have a separate file?

**Comment by dusho** [comment]
Well currently it's Iron, Copper, Uranium and Ice. But yes, once we have some harvest-able things, it may be nice idea to have extra .xml (Collectable.xml ?)
btw. is collectable good word to cover mining and harvesting? or is there a better one..

**Comment by koosemose** [comment]
If you go ahead with this, I'd prefer to have it done in such a way that we can still have a "generic" minable, so that we can perhaps have the best of both worlds. If a modder or developer wants to have a new resource that's mined and does nothing else special, still be able to have it fed into world gen as just a generic resource to generate using basically the current method (i.e. drop not defined for the object in xml, but rather by the world generator when it's placed.. or by the worldGenerators xml rather.)

**Comment by dusho** [comment]
ok, sounds fine. Then it should look like
```xml
<Component type="Collectable">
    <RequiresAction>Mine</RequiresAction> <!-- enum: Mine, Harvest, ...-->
    <Provides>        
         <Item type="Raw Copper" amount="1" minAmount="1" maxAmount="2" relSpawnChance="10"/>      <!-- either exact amount or range-->        
         <Item type="Raw Iron" amount="1" minAmount="1" maxAmount="2" relSpawnChance="10"/> 
         <Item type="Uranium" amount="1" minAmount="1" maxAmount="2" relSpawnChance="3"/> 
    </Provides> 
    <UseSprite name="copper_ore" asOverlay="true"/>  <!-- name is not required, can be combined with animator-->
    <ParameterDefinitions>
        <CurrentItemType name="item_type" />
        <CurrentYieldAmount name="yield_amount" />
    </ParameterDefinitions>
</Component>
```
I will also redo the Animator component, will rename it to Visuals (will get rid of unity component warning, yey!), and put functionality from furniture GetSpriteName there.. and make it more flexible - possibly to support some overlays as well..
so e.g.:
```xml
<Component type="Visuals">
    <GetSpriteName forType="astro_wall" /> 
    <GetSpriteName fromParameter="item_type" /> 
    <GetSpriteName fromFunction="OreMine_GetSpriteName" />
    <GetOverlaySpriteName fromParameter="OreMine_GetSpriteName" />
    
    <UseAnimation name="idle">
        <Requires>
            <Param name="cur_processed_inv" condition="IsZero" />
        </Requires>
    </UseAnimation>
    <UseAnimation name="running">
        <Requires>
            <Param name="cur_processed_inv" condition="IsGreaterThanZero" />
        </Requires>
    </UseAnimation>
</Component>
```

**Comment by koosemose** [comment]
Not quite what I was thinking.... but I suppose it would work... 

Just in case what I was thinking is feasible, it was something along the lines of rather than having a possible Drops tag or Provides, simply having something along the lines of <WorldGenBased> for provides and then worldGenerator would have an ore chance, and when it came across a WorldGenBased Collectables (perhaps Harvestable would be a better term?) it would set a param for the type of ore to drop (which could also be used to affect visuals), including the possibility for none (Allowing it to mimic the current astro_wall functionality more closely, but still giving the possibility of certain harvestables to behave differently

**Comment by dusho** [comment]
aaah.. I see.. I totally missed worldGenerator.xml where stuff is defined already. with chances, that is why I put all into Collectable (yes, Harvestable is better, I guess.. or Resource component?)
will rethink it now..

**Comment by Geoffrotism** [comment]
I'm partial to calling them Resources as well. Harvestable sounds like a method that returns a Bool.

**Comment by dusho** [comment]
for other components we have haves like Workshop, PowerConnection, Visuals (to be).
What about calling this Drop - (Drop component), is more generic..
Then what about this structure, furniture:
```xml
<Furniture type="common_mine">
    <Component type="Drop">
        <RequiresAction>Mine</RequiresAction> <!-- enum: Mine, Harvest, ...-->
        <PossibleDrops>
            <Item type="Raw Iron" source="iron_ore">
            <Item type="Ice" source="ice_block">
            <Item type="Uranium" source="uranium_ore">
        </PossibleDrops>
        <ParameterDefinitions>
            <CurrentItemType name="item_type" />
            <CurrentYieldAmount name="yield_amount" />
            <CurrentSourceType name="source_spot" />
        </ParameterDefinitions>
    </Component>
    
    <Component type="Visuals">
        <GetSpriteName forType="astro_wall" /> 
        <GetOverlaySpriteName fromParameter="source_spot" />
    </Component>
</Furniture>
```
Then in WorldGenerator.xml:
```xml
<Resources>
    <Resource sourceType="common_mine" dropType="Raw Iron" min="5" max="15" weightedChance="50" />
    <Resource sourceType="common_mine" dropType="Ice" min="5" max="10" weightedChance="15" />
    <Resource sourceType="common_mine" dropType="Uranium" min="5" max="15" weightedChance="35" />
</Resources>
```

**Comment by BraedonWooding** [comment]
@dusho @koosemose this seems like it's been implemented?

**Comment by dusho** [comment]
yes, guess it was.. we can still make new issue if other components are needed/proposed
