### ISSUE TITLE
Changing language yields exception after loading saved game

### ISSUE THREAD

**Issue by jaselito** [TeamPorcupine/ProjectPorcupine#1448]
After starting the game, loading a save and then switching between different languages in the settings dialog I end up getting the following exception:

```
MissingReferenceException: The object of type 'Text' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
```

**Comment by TomMalbran** [comment]
That seems like an issue with a static class that is keeping reference to an old instance of the class that holds references to removed objects. We had an issue with other static classes a few days ago, so now the WorldController has a Destroy method that destroys them before reloading. But not all of the classes, just the ones we found to have issues. There might be an issue with one of the Localization classes, or another static class. But I can't be sure where it is without doing some digging. Check the stacktrace and try to follow it to a static class, which will need to be destroyed before the game reloads.

**Comment by jaselito** [comment]
Sorry, this is way over my head... is this the stack trace you're referring to?

```
MissingReferenceException: The object of type 'Text' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.EventSystems.UIBehaviour.IsActive () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/UIBehaviour.cs:22)
UnityEngine.UI.Graphic.SetVerticesDirty () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:100)
UnityEngine.UI.Text.set_text (System.String value) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Text.cs:141)
ProjectPorcupine.Localization.TextLocalizer.UpdateText () (at Assets/Scripts/Localization/TextLocalizer.cs:49)
ProjectPorcupine.Localization.LocalizationTable.LoadingLanguagesFinished () (at Assets/Scripts/Localization/LocalizationTable.cs:83)
ProjectPorcupine.Localization.LocalizationLoader.UpdateLocalizationTable () (at Assets/Scripts/Localization/LocalizationLoader.cs:44)
ProjectPorcupine.Localization.LocalizationTable.SetLocalization (Int32 lang) (at Assets/Scripts/Localization/LocalizationTable.cs:73)
DialogBoxSettings.OnClickSave () (at Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs:80)
DialogBoxSettings.<OnEnable>m__6F () (at Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs:112)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:153)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:630)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:765)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:53)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:35)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:44)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:52)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:269)
UnityEngine.EventSystems.EventSystem:Update()
```

**Comment by koosemose** [comment]
That would be the LocalizationTable, which is only accessible through the LocalizationLoader, which is a monobehavior on the Controllers gameobject... which it probably shouldn't be if at all possible.

**Comment by Geoffrotism** [comment]
This error pops up when changing languages without saving as well.

**Comment by BraedonWooding** [comment]
This could be solved with my proposed implementation of issue #828 .  This is where I suggested a singleton based approach where it wipes all controllers but a main one that's only job is to instantiate the others and to make sure we don't double load levels.  This could be extended to hold localization instances and since it would wipe them upon level load it would be able to fix this issue.

**Comment by Ohda** [comment]
Does this still an issue ? For the introscene i need to add this in SceneController when loading a new scene.
ProjectPorcupine.Localization.LocalizationTable.UnregisterDelegates();
It may have fix that issue.

**Comment by Geoffrotism** [comment]
Can be closed. Tested by loading save, changing languages, then hitting save options.
