### ISSUE TITLE
Time for GameEvents continues regardless of game speed or being paused

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1451]
As it stands GameEvents is a monobehavior attached to the Controllers gameobject, so it gets its update from that, rather than TimeManager, which would prevent it from continuing to spawn events when paused.

**Comment by jaselito** [comment]
I'll take  a shot at this...

**Comment by TomMalbran** [comment]
I will be working on this soon, since I also want to move the game events to the PrototypeManager, for easier loading.
