### ISSUE TITLE
Some Languages Require RTL

### ISSUE THREAD

**Issue by DrPigi** [TeamPorcupine/ProjectPorcupine#1456]
Hey! I was going to correct the he_IL (Hebrew) translation - and then I noticed - that there is a problem. A few languages like Hebrew, and arabic, write from right to left. So for some reason, unity displays - siht ekil (like this). I'm not that good of a programer - but I think there should be someway to specify RTL or LTR. Until then hebrew and arabic are basicly meaningless.

**Comment by bjubes** [comment]
I would go one step further and say that the whole UI should be mirrored 
[kinda like this](https://material.google.com/usability/bidirectionality.html#). obviously just getting the text to display in the right order is the first step but I think mirroring is the proper long term solution

**Comment by bjubes** [comment]
Are you sure your still getting this bug? The Hebrew is RTL for me, and its identical to how its typed in the localization file.
![capture](https://cloud.githubusercontent.com/assets/7608114/19014891/ff987d5e-87c6-11e6-95cf-2e9657bf0cca.PNG)

**Comment by DrPigi** [comment]
xD lel no. The problem is, your text editor doesnt support RTL too. The word is "מאגר" and not "רגאמ"
And I'm using the beta 5.5

**Comment by DanielNetzer** [comment]
any Israeli is working on that? cause I might be able to help with that
part (Israeli here).

**Comment by bjubes** [comment]
@DanielNetzer @DrPigi  I just made a quick pr to fix this, you can test it and give any suggestions since I don't know hebrew.
