### ISSUE TITLE
Make Saving Asyncronous

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#1459]
Currently saves can take a very long time and in a build will cause the game to temporarily crash, causing windows to report the program has stopped responding.
 We need to give a "Saving..." indication and then write to file outside the main thread, even if the game is stuck at "Saving..." until it finishes.

Same goes for loading

**Comment by QuiZr** [comment]
Well, this won't be as easy as I thought :/
![image](https://cloud.githubusercontent.com/assets/9101486/18902282/2f14a6ec-8552-11e6-9371-e384cd1f1ba2.png)

**Comment by bjubes** [comment]
are you using a coroutine or another implementation?

**Comment by NogginBops** [comment]
Doen't nätter, you cant do `Camera.main` in any other place than the Main thread

**Comment by bjubes** [comment]
im pretty sure a coroutine is on the main thread, it just yields each frame.

**Comment by sboigelot** [comment]
@bjubes is correct, coroutines are only in the main thread

**Comment by kd7uiy** [comment]
This could be dangerous... To do it properly, we'd have to create a memory snapshot of the entire game state, or else risk saving at seemingly random times.

One thing we could do to speed up the save process would be to zip the save files. It should be possible,..

**Comment by UnknownSoldier1** [comment]
Also I would say that XML is a rather strange format for saving savegames. With a custom format we could make the savegame files smaller probably. And I don't know how fast the XML Writer is, but maybe a custom format would save faster too.

**Comment by kd7uiy** [comment]
Compression isn't really that difficult, except for the fact that Unity doesn't support the native C# compression... There are options that I'm looking in to, however, and I think this will help!

**Comment by DanielNetzer** [comment]
why not use json and System.IO?

**Comment by kd7uiy** [comment]
Json uses less memory, but it really doesn't matter which path we go, either is an improvement.

**Comment by QuiZr** [comment]
On my machine serializing world etc takes ~58ms, writing to hdd takes 19ms. Zipping is possible (because we already have SharpZipLib for unfamous LocalizationDownloader) but it would just take longer. I can move the writing to hdd operation on a separate thread and that's the only easy fix that I see here. As @kd7uiy said we would need to create a snapshot of current world&stuff and then launch a separate thread.

**Comment by kd7uiy** [comment]
I like the idea of moving the hdd operation to a separate thread, but still doing the serialization on the main thread.

Zipping could still be a good idea, but we could delay it given that change.

**Comment by QuiZr** [comment]
I can do that but in 2 days - https://hacktoberfest.digitalocean.com/ :P

**Comment by bjubes** [comment]
we don't need to speed up saving for this to work. Just prevent the user form playing the game until it saves. 
* Player hits save
* pause game and show a wait dialog
* wait for serilzation to finish while showing a loading wheel type indicator on screen 
* when done serializing, give the user control again

**Comment by mikejbrown** [comment]
Does #1496 close this?

**Comment by QuiZr** [comment]
Nope - only a little bit. We still need to do something like @bjubes said.

**Comment by mikejbrown** [comment]
K - also adding to v0.2 because this probably isn't that far off.

**Comment by koosemose** [comment]
Closing this, as it has been implemented so far as I can see, and the remaining aspect is loading, which is in another issue.
