### ISSUE TITLE
Construction menu scroll barg

### ISSUE THREAD

**Issue by Jaytheway** [TeamPorcupine/ProjectPorcupine#1466]
There is a Bug in the Construction menu. When you hold scroll field (not the handle) and move mouse down it sometimes scrolls up and when you move the mouse up it scrolls down. It happens not all the time though, you kinda have to hit the right spot.

**Comment by Geoffrotism** [comment]
Been testing this. There are two functionalities here. if you click on the actual scroll bar it works as desired but the scroll bar is very thin. The problem arises when you end up accidentally clicking and dragging on the construction panel that holds the furn items. I will probably end up making the scroll bar clickable area wider and maybe leaving a gap between it and the actually menu.
