### ISSUE TITLE
Room connections

### ISSUE THREAD

**Issue by mattpott** [TeamPorcupine/ProjectPorcupine#147]
I was thinking of creating a Graph of rooms and how they are all connected to each other. 

This would be used in the future for allowing gas pressure to be dispersed through out the space station as well as an optimisation for the A* path finding.

My current idea as each room being a node and the doors being edges.

The graph would be updated when there is a flood fill for a new room by adding a new node and looking for any furniture that IsEnterable (i.e a door) to create an edge.

**Comment by emilkris33** [comment]
This is definitely how we will want to eventually optimise pathfinding. So i you think you can do it I say go for it

**Comment by vogonistic** [comment]
@mattpott I was thinking about this as well. Have you figured out how you want to go about doing it? If you want to split the work or want someone to review it, I'm available.

**Comment by mattpott** [comment]
I have an idea and would cherish the opportunity for somebody to look over my code. I will try and get the basic idea together today and tomorrow.

General idea:
During the flood fill is to keep track of the room edges
Then check the room edges to find doors
Check each door to see if they lead to a new room
Create a graph of rooms being nodes and doors being edges

**Comment by Mizipzor** [comment]
Are all rooms constructed? If we only have floors, walls and doors this can become rather easy to solve. RimWorld has large uneven outside areas which means it has to do tessellation to get "rooms", something that is surprisingly difficult.

**Comment by mattpott** [comment]
@Mizipzor  It shouldn't matter if there are constructed or not, as you are just looking for furniture that can enclose room and also isEnterable != never.

**Comment by Mizipzor** [comment]
It does matter. Rooms inside the base are probably rather small, and are great for segmenting the map and speed up pathfinding.

My concern is if there is a large open area, like RimWorld, you need to handle that. Say the workers can leave the base and go outside to harvest asteroids or something. What if that outside is huge, maybe even limitless. If you just make the outside one large room, you end up doing a a very expensive search across many tiles in that room.

To handle this you need to find a way to segment this large area, without walls or furniture. This process is called tessellation. 

Does it make more sense now?

It obviously doesnt need to happen right now. Maybe its not even possible to go outside yet, and even if it is, maybe were fine with slow pathfinding at the moment, as long as it works. But it is absolutely something that has to be addressed if we intend to run path finding "outside".

**Comment by mattpott** [comment]
I think so but I don't think we do the flood fill on the outside room anyway. So you should never need to check the outside room as any door that leads from inside to outside would work both ways.

**Comment by Mizipzor** [comment]
So youre saying that there wont be pathfinding outside? Or, that the outside will be no room (which is  functionally the same as one large room)?

**Comment by mattpott** [comment]
Sorry, I am not sure I explained my self well. I won't be doing another flood fill but just adding on to the one already done when a room is created. The only reason this is necessary is to find the doors that connected rooms.

I appreciate the feedback and questioning it helps me understand what I am trying to do as well.

**Comment by vogonistic** [comment]
@mattpott Have you had any time to work on this?

**Comment by mattpott** [comment]
I have the basis for this but I haven't had a chance to test it out and am currently away from my computer until Wednesday.

**Comment by vogonistic** [comment]
I believe it's Wednesday in most time zones, how are things going? :) I highly recommend you make sure you can rebase or restart now, because this project is changing quickly.

**Comment by mattpott** [comment]
Hi, things are going well. I have only just gotten internet again so I am starting again.

**Comment by vogonistic** [comment]
Excellent! We need this desperately, so don't hesitate to reach out for help figuring things out. We have a pretty active Discord chat. Link is in the readme.

**Comment by mikejbrown** [comment]
Could be closed?
