### ISSUE TITLE
Repetitve Saving in Settings

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#1474]
While trying to make saving asynchronous I came across another issue. After pressing save, each setting in the dialog is set via a call to `Settings::SetSetting` However, each one on these calls in turn calls `Settings::SaveSettings`. That specific function writes the xml, which means when we press save each setting causes a write call, so settings is written and overwritten 7 times in one frame. This is likely the cause for the lagspike during saving settings

**Comment by mikejbrown** [comment]
I imagine it would probably work fine to make `Settings` a cache by making `Settings::SaveSettings` twiddle a "dirty" flag and spawn a deferred `writeSettingsToDisk` (or whatever) event using the `Scheduler`. `writeSettingsToDisk` would only actually do anything if the cache is dirty (and then mark it clean, obviously). This way a maximum of one write to disk happens per frame.

**Comment by zwrawr** [comment]
I've got a fix for the save settings ( sets a flag which a scheduledevent checks). But that doesn't fix the lagspike. It seems the lag is because all the localisations get reloaded (http://prntscr.com/cp1ww0) , there's no need to load these more than once. I'm going to look into this and then make PR that fixes both of these issues.

**Comment by zwrawr** [comment]
This line seems to be what is causing the lag spike. 
[LocalizationTable.SetLocalization](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/Scripts/Localization/LocalizationTable.cs#L73 )
when ever you set the localisation it reloads all of the .lang files. These files should never change once the game has started so we shouldn't ever need to reload them. So it should be safe to remove this call to update the localization table, right?

**Comment by mikejbrown** [comment]
I'm not the localization expert, but that sounds reasonable @zwrawr. You could always just try it :grinning:. The only catch I would imagine is if `UpdateLocalizationTable` fires an event that tells something in the UI to redraw.

**Comment by bjubes** [comment]
Yep assume the Lang files don't change. If we want to allow them to change we can add a seperate reload option akin to reloading a mod which will inevitably take longer

**Comment by mikejbrown** [comment]
I reckon #1490 and #1501 close this. Feel free to reopen if you need.
