### ISSUE TITLE
Space ship

### ISSUE THREAD

**Issue by satch3l** [TeamPorcupine/ProjectPorcupine#148]
If you are supposed to be alone and stranded on a space ship should'nt the space ship be randomly generated? Otherwise, I imagine, you have a set amount of space inside an empty space ship to build walls and such. Everything else outside is space.

I'm just confused on what direction we are taking this game, and want to know what you think?

**Comment by emilkris33** [comment]
The way i imagine it you are on a space station that you are building.

**Comment by bjubes** [comment]
Yeah I was imagining like the iss, your above a planet in orbit. But no official plan for the game has been created yet

**Comment by vogonistic** [comment]
Since we are going to need a lot of resources, maybe the ship crashed/landed on an astroid in the belt?

**Comment by NogginBops** [comment]
@vogonistic Crashed into a asteroid perhaps?

**Comment by vogonistic** [comment]
I like crashing. Scatters things so nicely.

**Comment by vogonistic** [comment]
I'm closing this. Lets move more discussion to #431
