### ISSUE TITLE
Placing walls yields error

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#1480]
Placing a wall anywhere causes this error :`'oldRoom' still has tiles assigned to it. This is clearly wrong.`

Callstack:
```
UnityEngine.Debug:LogError(Object)
UberLogger.Logger:ForwardToUnity(Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:506)
UberLogger.Logger:Log(String, Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:452)
Debug:ULogErrorChannel(String, String, Object[]) (at Assets/UberLogger/Debug.cs:322)
ProjectPorcupine.Rooms.RoomManager:DoRoomFloodFill(Tile, Boolean) (at Assets/Scripts/Models/Area/RoomManager.cs:246)
FurnitureManager:PlaceFurniture(Furniture, Tile, Boolean) (at Assets/Scripts/Models/Buildable/FurnitureManager.cs:88)
BuildModeController:DoBuild(Tile) (at Assets/Scripts/Controllers/InputOutput/BuildModeController.cs:171)
MouseController:BuildOnDraggedTiles(DragParameters) (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:429)
MouseController:UpdateDragging() (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:325)
MouseController:Update() (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:129)
MouseController:<MouseController>m__1B(Single) (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:61)
TimeManager:InvokeEvent(Action`1, Single) (at Assets/Scripts/Models/Events/TimeManager.cs:198)
TimeManager:Update(Single) (at Assets/Scripts/Models/Events/TimeManager.cs:125)
WorldController:Update() (at Assets/Scripts/Controllers/WorldController.cs:146)
```

**Comment by koosemose** [comment]
It does this in non-dev mode as well. I think this is intentional, from what I can tell the old room no longer gets its tiles taken away so that the new room/rooms can properly get a copy of the old room data, and have it properly adjusted. If I am understanding what is going on correctly, the bug isn't so much that "oldRoom" still has tiles assigned to it, but that it reports it as an error still despite it being intentional.

**Comment by bjubes** [comment]
from what the comments in the code say, the room should be deleted during the frame and then recreated. if this error is occurring then the logic in the code doesn't match the logic in the comments. Either way this has to be looked at and redone

**Comment by koosemose** [comment]
I'm reasonably sure the comments need changed... when I was mucking around in there I wasn't confident enough in my understanding of what exactly was going on to change the comments to fit... or the error checking, I'll see if I can take a fresh look at it specifically to sort it out in a couple days, if whoever initially did the changes to room logic (I think the changes were made when the Room Manager came about) isn't still around and/or doesn't step up to sort out the comments.

**Comment by bjubes** [comment]
I'm pretty sure those comments are from the orignal project, so they are probably outdated

**Comment by mikejbrown** [comment]
`git blame` :wink:

**Comment by koosemose** [comment]
Nope, I was wrong the check in UnassignTile got inverted and was returning when the tile was in the room, rather than when it wasn't. Fix incoming

**Comment by koosemose** [comment]
That should fix things, if someone else could double check the PR to make sure it didn't break anything else that I haven't noticed...
