### ISSUE TITLE
Update contributor list

### ISSUE THREAD

**Issue by mikejbrown** [TeamPorcupine/ProjectPorcupine#1485]
We should have an up to date contributor list when v0.1 is tagged. This is super easy, just need to merge in a commit after doing
```sh
$ ./Scripts/Contributor_Name_List.py > Assets/StreamingAssets/Data/CharacterNames.txt
```
right before tagging. I'm just making an issue because otherwise it's sure to be forgotten.

**Comment by bjubes** [comment]
currently this is the only item left in the milestone since everything else is bumped to 0.2. Does that mean were ready to do this?

**Comment by mikejbrown** [comment]
@bjubes maybe wanna close #1476? I kinda just want it for the stats geeking, but it's not really needed.

**Comment by bjubes** [comment]
personally i dont think we need #1476, so you can close it if you want

**Comment by mikejbrown** [comment]
Oh, I meant merge, sorry.

**Comment by bjubes** [comment]
okay either way haha
