### ISSUE TITLE
ProjectSettings and Build settings

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#1488]
As 0.1 nears, I thought now would be a good time to put an offical version number on the project as the bundle identifier. However we currently gitignore `/[Pp]roject[Ss]ettings/ProjectSettings.asset` which contains information including:

- build version
- Company Name
- Application Name
- Game Icon
- Whether fullscreen/native resolution are on by default (we keep track of this in settings.xml, so no real worries here)

As a result, none of this information exists on git and can be changed in the official project, only locally. Im sure ProjectSettings is ignored for good reason (please state it if you know specifically), but how are we going to ensure that the above stays consistent when the game is built if its not tracked by git?

**Comment by TomMalbran** [comment]
Adding ```/[Pp]roject[Ss]ettings/ProjectSettings.asset``` to ```.gitignore``` came from issue #17 and then was added in a PR by Quill.

**Comment by bjubes** [comment]
I remember that issue #96. The problem is that Projectsettings contains information we want ot standardize as mentioned above, but also contains information (i think its the window layout or something like that) which we don't want in the repo. Sadly there is no way to ignore half of a file.

**Comment by mikejbrown** [comment]
Makes sense to try figure this issue out before v0.2, so added it to the milestone.

**Comment by koosemose** [comment]
From what I can tell ProjectSettings.asset is almost entirely information we want to be able to standardise, the only thing that it did and I think was the reason it was ignored in the first place was of someone makes changes using a different version of Unity, and we should really try to be using a consistent version of Unity as is, and if someone isn't it should be up to them to not commit their projectSettings and us GKs to try not to merge PRs with accidentally added ProjectSettings (there should be minimal situations in which we need to actually change it, mostly company/product data, and api compatibility, and those only need to change once).

I move that, if no one disagrees, we re-add ProjectSettings. Thoughts on this @mikejbrown  and @bjubes ?

**Comment by bjubes** [comment]
does it also include editor window layout and size? I thought that was an issue as well but I could be wrong

**Comment by koosemose** [comment]
From my understanding it doesn't, it just stores things you set in Edit->Project Settings, plus a productGUID string which may be specific to each unity version. And looking through the file, I can't see anything that suggests layout to me, the closest is defaultHeight and width, which I presume are the default resolution for a standalone build

**Comment by bjubes** [comment]
I'm good with adding it. worse comes to worse we just remove it again later.

**Comment by bjubes** [comment]
closing for now, will reopen if adding ProjectSettings causes any unexpected issues.
