### ISSUE TITLE
Rooms spanning multiple levels, and enclosing rooms vertically.

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1491]
Currently rooms only care about their floor on room creation, if a floor tile is removed, the room stays intact, and if a "room" is built with a hole in the floor it will be outside, regardless of what lies beneath.

Optimally a hole in the floor should either expose the room to space, or join it to the lower room.

What about going up? Having some type of separate "roof" tile seems needless tedium, and having to build a floor on the next level up feels awkward (In addition to problems on the top level, either enclosed rooms can't be built on top level or the top level is special and doesn't require roofs built with floor, which seems inconsistent).

Perhaps, at least at initially, we just have "magical" roofs if the room above is room 0, we treat it as enclosed, as though it had a roof, but if the room above is an actual room, we merge them as one would expect.

**Comment by bjubes** [comment]
we may also want a furniture such as staircase or elevator that connect rooms between levels

**Comment by NogginBops** [comment]
I like the idea of a staircase, but it's easy to do. Just check if the tile in the layer below is in a room.

**Comment by koosemose** [comment]
I think I have an angle on this, but it's going to take some more work, I've got to rework how room floodfill works, because currently, it relies on the tile being null (which no longer has an effect, because GetNeighbors was changed to not return null, though I'm trying to make that optional), or a floor tile being empty to determine if it's hit the outside room and not floodfill the entire map, being able to have rooms span vertically of course requires it to flood fill through empty floors, and removing that check of course causes it to floodfill the entire map (and take an eternity to finish). 

So now, I've got a function in Tile which returns true if it has an unimpeded path straight down to null (map edge), and use that to check if it's a space that's outside. Doing it this way causes a "magic roof" on the top level, which I would consider desirable until we have a more intelligent way to handle roofs/ceilings. This will however start causing issues if we ever have a map which is mostly covered by tiles (such as an asteroid that fills most of the map or a planetary map. I may be able to have it also look up in such a way to preserve the magic roof and which will at least help on a planetary map, but it could still cause issues if you end up with a large hollowed out asteroid, we'll have to see if that becomes an issue. 

Currently, something in the changed code causes old rooms to not be deleted (but only when vertically joining rooms) as used to happen, I'm not sure exactly what/why this happens atm, but hopefully it's something fixable.

If anyone has other suggestions on how you can determine from a tile during floodfill, that that tile should be part of Outside and floodfilling can be bailed from.

**Comment by koosemose** [comment]
Alright, I have a working version of this, just waiting on #1521 to be merged, as it relies on some of the methods implemented there.
