### ISSUE TITLE
Localization not being updated when saving settings

### ISSUE THREAD

**Issue by mikejbrown** [TeamPorcupine/ProjectPorcupine#1499]
Go to the settings menu and change the language to anything. Then apply or save. There are no errors, but the new language is not applied.

Noticed by @TomMalbran

**Comment by koosemose** [comment]
Assuming things didn't go horribly wrong, from git bisect I get:
```
d383f11e8866d82d2a561f3918e99c51e57bdf21 is the first bad commit
commit d383f11e8866d82d2a561f3918e99c51e57bdf21
Author: Zak <zwrawr@gmail.com>
Date:   Tue Oct 4 23:50:45 2016 +0100

    Optimize saving Settings (#1490)

    * optimizes saving settings

    All settings now get saved after the schedualar calls save rather than
    when ever a setting changes. also fixes an issue where setting the
    localization reloads all .lang files

    * Updated ScheduleEvent => ScheduledEvent

    * adds ScheduleSave() method
```

so #1490 ?

**Comment by koosemose** [comment]
And it looks like that PR pulled out the updating of languages from the Localization table and just didn't reimplement it anywhere.

**Comment by bjubes** [comment]
maybe its because it schedules an event which doesn't get run before the construction menu is opened?

**Comment by mikejbrown** [comment]
That's right. It's changing the settings but not calling `UpdateLocalizationTable`. Those two lines in `LocalizationTable.cs` could probably go back where the were. The issue wasn't that they were being called from there, but that settings were being saved multiple times per frame.

**Comment by koosemose** [comment]
Yeah, that seems to do it, but something else at some point in time seems to have broken setting localization when the game is first started.
