### ISSUE TITLE
Need to add a "Develop" branch - Important for versioning 

### ISSUE THREAD

**Issue by RodRitter** [TeamPorcupine/ProjectPorcupine#15]
Im not sure if this is necessary, but usually a project of this scale has a "develop" branch that we can submit pull requests to. This way, when you want to release a new version (ie. 0.1.1), then you can merge the develop branch into the master branch.

**Comment by svmnotn** [comment]
Also making the master branch non push-able is a default for me almost, that makes it so that only PRs can alter master. Not sure if it really is all that helpful if only @quill18 has push access but as the project grows that may become something useful.

**Comment by svmnotn** [comment]
Might want to also look at having something like [Travis CI](https://travis-ci.org/) building the project so that master can also require status checks which makes sure that master always builds. Also no pushes can go directly into master with that requirement.

**Comment by misspellted** [comment]
As someone who works in software engineering that started off with _just_ a master branch, yes please! Having a develop branch is a great way to synchronize all efforts (feature/bugfix/hotfix... gitflow anyone? :smile:) and have a buffer between released (master) and currently accepted work (develop).

**Comment by RodRitter** [comment]
Gitflow for the win! :D

**Comment by quill18** [comment]
Protecting the master branch is probably a good idea, but the master branch IS going to be the "develop" branch for a good long time.  We're miles from a vaguely playable/stable release -- there would be zero meaningful difference between the two.

**Comment by misspellted** [comment]
Well, as long as we are aware of the plans, I am cool with it :+1:

**Comment by RodRitter** [comment]
Too much excitement for this project. We all just want to do all the things now! :smile:

**Comment by quill18** [comment]
Closing this for now -- but we will definitely revisit organizing the branches into at least a "master" and "develop" (and maybe "experimental"?) before we ever drop a Version 0.1 -- though I still expect that to be a couple months off.
