### ISSUE TITLE
StyleCop

### ISSUE THREAD

**Issue by Mizipzor** [TeamPorcupine/ProjectPorcupine#151]
What does people think of [StyleCop](https://stylecop.codeplex.com/)? Code style checker. Can be run from within MonoDevelop as an [addin](http://addins.monodevelop.com/Project/Index/54). It allows you to specify your code style (like those in the contribution guidelines) and have the editor mark the lines where you deviate from that style. Ever wondered if your code looks like it should? You should be able to click a button and be told.

I'm currently tweaking its settings (which would live in a settings file in git), disabling most things as it can be way more strict than we want. Should also be noted that this would not be required to make pull requests, but it would be the easiest way for the author to make sure he conformed to the style.

**Comment by Tranberry** [comment]
There could probably be a guide in the 'contributing.md' with how to set this up to work with the guidelines of this project?

**Comment by BeefEX** [comment]
As he said you would only set the settings sile path to the file in the github repository.

**Comment by vogonistic** [comment]
Closing this issue since we've already merged StyleCop settings.
