### ISSUE TITLE
Folder Location for Health Script

### ISSUE THREAD

**Issue by MANDAL0R3** [TeamPorcupine/ProjectPorcupine#1514]
As of right now i cannot think of a good folder to put the Health script that i made for https://github.com/TeamPorcupine/ProjectPorcupine/pull/1508. It doesn't seem right to make a folder just for one script but that may be the way to go. Any feedback is welcomed 

Some current ideas for its folder are.

- Models/Damagable 

- Models/Misc

- Script/Utilities

**Comment by mikejbrown** [comment]
My votes:
- Models/Damageable/
- Models/Health/

**Comment by MANDAL0R3** [comment]
I kinda like Damageable more then Health
