### ISSUE TITLE
DialogboxSettings error if FPSCounter is hidden.

### ISSUE THREAD

**Issue by Ohda** [TeamPorcupine/ProjectPorcupine#1526]
There is a bug on the dialogbox settings panel coming from this line : 

`public void OnEnable() { 
      fpsObject = FindObjectOfType<FPSCounter>().gameObject; 
...`
The issue is that fpsObject will be null if the fpsobject is inactive.

I think this is a hack, but when our WorldController initialize the scene, it will always activate the FPSCounter (even if set to false on the settings).

I think the proper solution is to keep a reference to the object before hidding it, so the DialgboxSettings panel will be able to active/desactive it properly but i'am not sure where to do that.

This is another issue i'am facing with the intro scene setup. Any help welcome !

You can add thoses lines on the worldController on start and open the dialogsetting to reproduce on master if your preference say to disable it : 
GameObject` fpsCounter = FindObjectOfType<FPSCounter>().gameObject;
fpsCounter.SetActive(Settings.GetSetting("DialogBoxSettings_fpsToggle", true));`

**Comment by frankitox16** [comment]
How do I recreate this issue? When I try todo save I have the missing reference exception you mentioned in other issue, but no null reference exception...

**Comment by koosemose** [comment]
This should be fixed due to the FPS counter having been replaced with custom work, and implemented in a way that doesn't run into this issue.
