### ISSUE TITLE
Limiting amount of Autosaves and ordering of save files

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1529]
Currently our autosave system will just keep making new files (I'm currently up to 225 just from testing various things) and orders them by creation time. 

The potentially large number of autosave files (I imagine it will only grow larger during actual play), plus ordering by creation time makes it impossible to have regularly used save files, as they will quickly get pushed down by autosaves, in addition to the (in my opinion) general undesirability of having 200+ autosave files. 

To remedy this, I propose solving this from two directions, first is limiting the number of autosave files, to a number set in settings (with a proposed default of 5), and when you have this many it will replace the oldest when saving. The second direction would be simply sorting save files (in load and save, and anywhere else they may appear in game) by LastWriteTime, so that your more recently saved to files will be at the top.

On a related note, I would like to know what people think of autosaves being suffixed with the time and date of the autosave, rather than a number (this would also imply explicitly deleting the oldest save file after a successful save, since the actual filenames won't be reused).

I've already started on an implementation of this, as I'm assuming this won't be controversial, but would like to get input as to details (and ensure my assumption is correct). This implementation doesn't include changing the suffix of autosaves, as that may be a less generally agreed upon thing.

**Comment by mikejbrown** [comment]
It might be nice to have the load dialog box show the last modified date and time in the file list, so it wouldn't have to be part of the file name and you also get it for regular save files.

**Comment by Ohda** [comment]
Mabye even 1 or 2 autosave file only. My thinking is about when you open the load panel, you don't want to see a list full of autosave so you need to scroll down to access you last manual save.

For the date in the name, i definitly want to see the date in the UI but mabye not in the file name.

**Comment by koosemose** [comment]
As a user I (very slightly) prefer the date-time in the file name, mostly because when you have rotating autosaves, the number is mostly meaningless. But it's an extremely minor preference.

It should be trivial to show save date-time in the file select, I think it currently shows creation time, so just a simple switch of method used should do it.

For me, I feel like 5 is a better default number of saves, so that there's a better chance of having an autosave to go back before something terrible happens. Though it might be particularly nice (but beyond the scope of what I'm implementing) to have autosaves "roll up" under a single entry that can be expanded.

On a semi-related note, it might be nice for the scheduler to have a way to have scheduled events that aren't affected by pausing (and even better if they could also no be affected by increased/decreased gamespeed, as, in my opinion, autosaving shouldn't be based on in game time (and definitely should be able to happen while paused, since you can make changes while paused).

**Comment by mikejbrown** [comment]
> On a semi-related note, it might be nice for the scheduler to have a way to have scheduled events that aren't affected by pausing (and even better if they could also no be affected by increased/decreased gamespeed, as, in my opinion, autosaving shouldn't be based on in game time (and definitely should be able to happen while paused, since you can make changes while paused).

Great idea. Should make that a separate issue.

**Comment by bjubes** [comment]
I think doing auto save with a 1-5 in the name makes the most sense. Doesn't the date and time appear in the load dialog next to it anyway? also its obvious from the order which autosaves are most recent.

**Comment by koosemose** [comment]
@mikejbrown Yeah, I'll look into a separate issue for that once I stop messing with the autosaving in general, trying to clean up some of the underlying issues that are brought to light by being able to actually set the related settings (since I've got to make a setting for maxAutosaves, I didn't see a reason not to go ahead and put in a setting for autosaveInterval, rather than letting it just be hidden in the settings file).
