### ISSUE TITLE
furniture type naming scheme... again.

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1539]
According to the current Contributing guidelines, furniture types (and other things of a similar nature) are supposed to be named as type_material, or for something that produces something whatItIs_whatItProduces.

However, that's quickly breaks down if you have multiple types of furniture that do similar things. For example, we have three ways to generate power. Solar Panels, the Power Generator (fission reactor), and the RTG, they all DO the same thing, and Produce the same thing... so by that scheme they should all be Generator_Power... Or perhaps you change it to type, so we have SolarPanel_Power, PowerGenerator_Power (FissionReactor_Power might be slightly better), and RTG_Power. What purpose does having _Power on the end serve, even if you break the technical wording of the guidelines. Or something like the Metal Smelter Smelter_Metal? That just seems like it's just complicating things for the sake of it. Even Wall_Steel serves no real purpose, it's not like we're sorting anything anywhere by their types so that that serves some form of purpose, if we're grouping things we want to do it more explicitly than by what they happen to be named and have some things manage to be in the right spot due to the naming scheme.  How about Airlock Doors, are the Door_Airlock (of course with the naming scheme that implies they're made of airlocks), or AirlockDoor_Steel? If we're naming them this way so they can be sorted, shouldn't airlock doors be at least in the same vicinity as Doors?

As an replacement proposal, I would just say to keep it simple, and have the type as a keyed version of what it is. Steel Wall is SteelWall (or perhaps steel_wall) Airlock Door is AirlockDoor. At the most IF an item could concievably have subtypes then the subtype could be a postfix, so perhaps in the case of wall it would in fact be Wall_Steel, but I don't see a really good reason for that, if we want to group similar objects together in some way we should just have a direct way of doing it, rather than naming things awkwardly.

Though to be honest even though it's unnecessary, I kind of liked the furn_SteelWall style that wall has, and just use the object type as a localization code for furnitures (and other such things), but that could of course be handled by localization code returning it prefixxed with furn_.

**Comment by dusho** [comment]
with the categorization (for building stuff) maybe we can get away from having unique names? It will be a problem to keep unique names if you want to have open modding anyway.
So we can have wall and wall.. but one from folder structures/steel/ , other from structures/wood/ .Then we can make name out of it like structures_wood_wall to have it in game unique.. 
modded things will get some prefixes from author of mod or something

**Comment by bjubes** [comment]
I think just underscoring the actual name is the best way to name. Its simple, it makes them unique, and theres no confusion.
steel wall? `steel_wall`
mining drone station? `mining_drone_station`
and then prefix mods with modname_modauthor or something to that effect

**Comment by BraedonWooding** [comment]
The only problem would be modding conflicts, but as bjubes said we could do something like 'myFirstMod/Braedon/mining_drone_station'.  I think if we placed slashes between the mod name, author, and object/furniture, then if we had multiple TYPES of steel wall it could work like 'baseGame/baseAuthor/steel_wall/red'  That could also correspond directly to a file address?

**Comment by koosemose** [comment]
My only issue with doing that automatically is that it makes it hard for a mod to intentionally overwrite, for example, steel walls. While they could technically have there mod be direct modifications to our files, that feels messy. Plus I really don't like the idea of it causing base game stuff to be more complicated to refer to, such as core/TeamPorcupine/mining_drone_station.

I would rather we leave the keys as is, and when we get to the stage of actually having mods, leave it up to the modders to add identifying prefixes to their new objects (and encourage them to do so), and those who choose to ignore the recomendation, well it's their own fault if something get's overwritten.

**Comment by BraedonWooding** [comment]
Fair Point, it's not very relevant currently anyway
