### ISSUE TITLE
"abandoned their job" when trying to create a new stockpile in an unreachable place.

### ISSUE THREAD

**Issue by Jaytheway** [TeamPorcupine/ProjectPorcupine#1545]
When trying to put a stockpile in an unreachable place it throws out a billion of `...abandoned their job.` messages and therefore drops FPS. It also happened when my stockpile was full, there was resources on the ground and I placed a new stockpile. But this time it wasn't so bad as when the stockpile job was in an unreachable room. 

![untitled](https://cloud.githubusercontent.com/assets/22476284/19420293/11f31816-93f1-11e6-9366-a06bbd7b7033.png)

**Comment by koosemose** [comment]
This is the same bug as #1536 the job/character system doesn't handle it well when a job is unreachable.

**Comment by bjubes** [comment]
closed by #1580
