### ISSUE TITLE
Settings saving/applying Indicator with saving as background thread

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1556]
### Problem
- When applying/saving settings it takes a considerable amount of time (2-3 seconds) this seems to be from the localistation class.
### Steps to reproduce the behavior
- Save/Apply (both with changes and without)
### Suggested Change
- We implement a saving indicator (just a swirling circle or anything) to indicate that the class is saving, then we disable interaction (so the user has to wait, but we cause the game to 'freeze' and buttons still animate but don't do anything and music plays...)
  *\* Note: Gifs don't play in github ughh.  **

So open this link for a cool sciency one I found (we could even just do a spinny circle idk this just looked cool): 
https://s-media-cache-ak0.pinimg.com/originals/90/80/60/9080607321ab98fa3e70dd24b2513a20.gif
### Why is this important?
- Its significant cause you don't always know if the app is doing anything or crashing, and this saving indicator is just a nice way to demonstrate that 'harder' work is being done that will take a short time. If its going to take longer than ~3 seconds we should have an eta/progress bar (as per common time standards).

**Comment by bjubes** [comment]
Saving is done on the main thread as of now. So when the game seems like its crashed, its actually crashed. This is even more apparent when loading/saving the world. Some of the work is done on a separate thread for saving but its not totally asynchronous so it still causes the program to hang.

**Comment by BraedonWooding** [comment]
Oooh cool hehe.  This is related to #1593.  I'm currently working on like 3 different pretty big PRs so I'll put this on the list, and if someone else doesn't come along and decide to add this I'll deal with it when I get to it 😄.

**Comment by BraedonWooding** [comment]
No longer needed new system is fast enough.
