### ISSUE TITLE
Can't Complete Quests

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1559]
### Expected behavior
- Once you have filled the Quest requirements it should disappear and give out rewards.
### Actual behavior
- Just prints out error and hangs

```
chunk_1:(19,4-62): cannot access field CountFurnitureType of userdata<World>
UnityEngine.Debug:LogError(Object)
UberLogger.Logger:ForwardToUnity(Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:506)
UberLogger.Logger:Log(String, Object, LogSeverity, Object, Object[]) (at Assets/UberLogger/UberLogger.cs:452)
Debug:ULogErrorChannel(String, String, Object[]) (at Assets/UberLogger/Debug.cs:322)
LuaFunctions:Call(String, Object[]) (at Assets/Scripts/Models/Functions/LuaFunctions.cs:100)
QuestController:IsQuestCompleted(Quest) (at Assets/Scripts/Controllers/Events/QuestController.cs:66)
QuestController:CheckAllAcceptedQuests() (at Assets/Scripts/Controllers/Events/QuestController.cs:43)
QuestController:Update(Single) (at Assets/Scripts/Controllers/Events/QuestController.cs:33)
TimeManager:InvokeEvent(Action`1, Single) (at Assets/Scripts/Models/Events/TimeManager.cs:198)
TimeManager:Update(Single) (at Assets/Scripts/Models/Events/TimeManager.cs:142)
GameController:Update() (at Assets/Scripts/Controllers/GameController.cs:77)
```
### Steps to reproduce the behavior

*\* Note: This can be before/after actually building the requirements **
- Step 1: Click Quests
- Step 2: Choose any quest (press accept)
- Step 3: Error will appear within 5 seconds

### Note
This is going to stay flagged as a bug, despite the knowledge of the entire system being broken and requiring complete re-structure.  Just so this stays at the back of peoples minds.

**Comment by bjubes** [comment]
I suspect the quest system hasn't been updated to know about the furniture manager since it's asking world about furniture directly. This is part of the problem with refactoring. the c# is refactored but the Lua remains out of date

**Comment by frankitox16** [comment]
I think that the quest system is a bit out of date... needs a bit of love honestly :smile:

**Comment by Geoffrotism** [comment]
I'm not really sure quests are in-line with the way our project is going anymore. If they were more like... demands, from QuillCorp i could see them working. QuillCorp presumably funded our excursion. It's only right that they start making demands of us some amount of time after the start. This should be a new thread but I'll start it here in case we do want to get away from the quest system:
- we have to send them X amount of resources to HQ
- Send our top officer to help defend the HQ from worker strikes (the redshirt dies ofc)
- have a profit margin exceeding X (QC needs to be able to tax us maybe?)
- have X number of paintings of the CEO Quill18 up at any point of time.
