### ISSUE TITLE
In-Game Dev Console

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1562]
**Create Pull Request**
### Previous Efforts

Okay so I've heard a decent amount of discussion on needing something like this.  I've actually built ones in the past that are extremely modular (just like my PerformanceHUD PR) so they shouldn't affect current code and all you do is call a method to add a function call.  It also will have autocomplete and so on.  
### My Proposal

I'm happy to build one based of this for Project Porcupine, with the ability to add commands via C# and LUA.  However, I'm raising this issue as a discussion on how commands should be implemented so I can build it with this in mind, for example should UI elements be openable by said Dev Console and so on?
### Related
#1555 (Quick Action Bar) - this is related as it has been discussed and it seems to have similar functionality as my proposal, however I'm presuming it won't have Dev Functionality???

Regardless, comment your opinions on this below :D

**Comment by ComputerOverlord** [comment]
Isn't there already TECHNICALLY one?

**Comment by BraedonWooding** [comment]
No there isn't, there was a planned one that was never pulled in and I think the person left.

**Comment by Tranberry** [comment]
couldn't this be tied in with #1555 ?

**Comment by BraedonWooding** [comment]
Put it in related already, this is more a discussion on the dev side rather than the user side.

**Comment by Tranberry** [comment]
Sorry, I don't understand what you mean.

**Comment by BraedonWooding** [comment]
I'm going to throw something together that fits this description and we can go from there :D
