### ISSUE TITLE
[Bug] Deconstruction of Metal Furnace spawns a billion of steel plates

### ISSUE THREAD

**Issue by Jaytheway** [TeamPorcupine/ProjectPorcupine#1567]
Start a new game, build Metal Furnace, deconstruct Metal Furnace -> billion of steel plates spawns rapidly fast + Error messages: `NullReferenceException: Object reference not set to an instance of an object`

![untitled](https://cloud.githubusercontent.com/assets/22476284/19591382/6a17a07a-977f-11e6-91e6-b715983629ba.png)

**Comment by koosemose** [comment]
Fixed by #1568
