### ISSUE TITLE
What Volume settings should we have?

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1581]
Currently we have controls in settings for master volume, and music, which of course aren't hooked up to anything.

However it is theoretically possible to have an arbitrarily large number of different volume settings. What should we actually have? How far should we break it down? Keep in mind the more different volumes we have, the more space is taken up in the settings menu (and it's fairly large as is).

The simplest of course is to only have a generic "Volume" setting which controls everything. From there we could have "Sound" and "Music" (and we could have "Master" but that seems less important with only two other volumes, but could still be useful potentially). Or we could break it down further, to something like "Music", "UI", "Game Sounds", and "Master". "Game Sounds" could always be broken down farther, but at this point we already have 4 volume settings, and much more breaking down and we are going to end up with an unreasonable amount of volume settings.

**Comment by Geoffrotism** [comment]
Master, Music, Game Sounds, Alerts/Events are what i would want at least. I'm not opposed to UI being separate, but it could be thrown under Game Sounds if need be.

**Comment by koosemose** [comment]
I personally like UI separate because it serves a different purpose than Game Sounds. 

So with your breakdown (which I like) + UI:

We would have Music, which of course just sets a generalized tone, Game Sounds which gives you information in an ambient sort of way, Alerts which (obviously) directly alert you to information incoming, and UI which primarily serves to give a gives a sort of gives the user a sense of solidity to interaction with the UI.

Each fulfills a separate purpose, and I think allows a pretty good separation of sound types (and let's those of us who dislike sounds on UI interaction in general to turn the things off ;D )

**Comment by bjubes** [comment]
I don't think space on the settings menu is a problem either. we can always change its layout to a multi paged tabbed style interface like most games. besides, where will we fit huge UI additons like keybindings in the future?

**Comment by NogginBops** [comment]
@bjubes Behind scrollbars! Or just make a full-screen config screen... maybe for tabs? There are a lot of options! :D

**Comment by Geoffrotism** [comment]
I'm definitely partial to a separate audio tab and hotkeus tab (scrollable).

**Comment by BraedonWooding** [comment]
Well I like that since for my developer console I needed a few different settings (attached image, and yes its weirdly positioned behind elements but that's cause small screen I think, it uses the same code as settings just with a few minor alterations).  So doing the tabs we could have a general, video, audio, hotkeys and developer tab.

![screen shot 2016-10-27 at 10 44 48 am](https://cloud.githubusercontent.com/assets/22880786/19749201/d349a9e6-9c32-11e6-9f11-684aca3c04c8.png)
