### ISSUE TITLE
Only Construction Button in Builds

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#1591]
Instead of looking like it does in the editor, the menu in a build has only the construction button

### Steps to reproduce the behavior
 Build game and run. I ran the game at 1440x900 res.

Image:
![capture](https://cloud.githubusercontent.com/assets/7608114/19871025/7fbcf54e-9f89-11e6-8d6a-7d71b320b214.PNG)

Update: Null Argument Exception coming from somewhere inside [DialogBoxManager::LoadModdedDialogBoxes](https://github.com/TeamPorcupine/ProjectPorcupine/blob/9d071b29636630bb449a931c6fdd067c087d7285/Assets/Scripts/UI/DialogBox/DialogBoxManager.cs#L167)

**Comment by koosemose** [comment]
This is what I get from output_log.txt on a build (or rather what I get that is an error which I don't usually see in editor), seems like something in the loading of Modded Dialog Boxes is to blame.
```
ArgumentNullException: Argument cannot be null.
Parameter name: key
  at System.Collections.Generic.Dictionary`2[System.String,DialogBox].set_Item (System.String key, .DialogBox value) [0x00000] in <filename unknown>:0 
  at DialogBoxManager.LoadModdedDialogBoxes () [0x00000] in <filename unknown>:0 
  at DialogBoxManager.Awake () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

**Comment by ryan3127** [comment]
Correct me if I am wrong but is DialogBoxManager::LoadModdedDialogBoxes referencing itself? If DirectoryInfo dialogBoxPathInfo =  new DirectoryInfo(dialogBoxPath); then will it error because both are the same thing?? Do you know what I mean

**Comment by bjubes** [comment]
no, that line is simply instantiating a new DirectoryInfo object for the path given. its converting a string _dialogBoxPath_ into a new object _dialogBoxPathInfo_ that holds the information about that path. However, if dialogBoxPathInfo was null, then it may raise an error, but dialogBoxPath always exists and points to the UI folder inside StreamingAssets.

**Comment by koosemose** [comment]
Turns out this is a ridiculously easy fix. TestDB.xml has `encoding="Windows-1252`, which apparently fails on standalone build for some reason (even on windows). Changing it to `encoding="utf-8"` fixes this bug.
