### ISSUE TITLE
[BUG] FMOD can not load in mac OSX

### ISSUE THREAD

**Issue by zmox** [TeamPorcupine/ProjectPorcupine#1597]
I'm using max OSX , Unity 5.4
when I play in editor,  console output error:

   `DllNotFoundException: fmod64`

**Comment by koosemose** [comment]
Hi, can you please test #1598 to see if it fixes the issue? I don't have access to a mac to be sure.

In case you need it, directions for testing a PR are here: https://github.com/TeamPorcupine/ProjectPorcupine/wiki/How-to-Test-a-Pull-Request
