### ISSUE TITLE
More info in Readme (current state of project, brief description, where this should be going)

### ISSUE THREAD

**Issue by JakubSzczerbinski** [TeamPorcupine/ProjectPorcupine#16]
I didnt watch any of video series about this game, but i want to contribute anyway. This requires more info what should be done, what is done ( i would rather do some coding than watch entire series ). I think this would be useful to a lot of people that want to contribute outside of quil18's channel.

**Comment by quill18** [comment]
A strong roadmap will probably be developed over time, but right now that's mostly the role that Issues are playing.
