### ISSUE TITLE
Should item (furniture, utility, etc..) Name be removed?

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1608]
I don't think the Name in the various Prototype classes actually serves a purpose, it basically functions as a US english translation of the type, and I suspect leads to confusion at times of which to use, type or name, and may also end up being used where a Localization should be used. Additionally there is the oddity and potential confusion of the Name property returning the Name set in xml (which may or may not match the localization for that item), and GetName() returning the Localization code.

I propose we fully remove Name from those prototype classes which have it and their xml, and anywhere in code that uses Name be changed to use Type.

**Comment by bjubes** [comment]
I agree. This gets confusing and eventually has to be paved over into type anyway to localize things.

**Comment by Geoffrotism** [comment]
+1
