### ISSUE TITLE
Settings UI Redesign

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1615]
WIP (started as of 25/11/2016):
Since this has two sections (an art/cosmetic side) and a practical side (which has been already outlined).  I'm going to build something that focuses on the practical with a **Proposed** art theme.  Then people can ask for adjustments, or overhauls to the theme.  Should follow a similar coding practice to the DevConsole (inheritance is key, but flattened significantly).

We need a settings UI overhaul, based upon previous issues and discussion (I've included all the ones I could find the rest are hidden or are discord chats), this is what I think would benefit us the most.

![image](https://cloud.githubusercontent.com/assets/22880786/20005850/9dee245e-a2e8-11e6-9d72-ece4cb1714a1.png)
Excluding the colour scheme and look (just more focusing on the positioning of the main buttons), I think this would benefit us the most, the left row of buttons that we would have would be something like: Graphics, Sound, Controls, Gameplay, Developer, --Mods--, Hotkeys.  --Mods-- would just be all the various mod settings that the mod author can create (a standard in most games that we should 100% include) and each mod would get their own button most likely (we could either have a scrollview or just squish the buttons, or just if it gets too big have a 'more' button to open a context like menu).  Sound settings wise we agreed on Master, Music, Game sounds, Alerts/Events, UI.   Graphics would just contain our current graphics settings (resolution, graphics options, possible shadows/other rendering things in future, fullscreen toggle - could be a dropdown of fullscreen, windowed, borderless windowed, UI Skin, V-Sync), Controls is different the hotkeys since I would presume that controls is more like mouse speed, and UI sensitivity?  Hotkeys on the other hand would just be all the keybindings and would need to feature at least one alternate and main key (with two alternates and one main being a preferred choice).  Gameplay would be stuff like, Language, Autosave stuff...  Developer would be the developer settings that my dev console PR adds (#1569) - shown below.  As well as other developer features that may be introduced in the future.
![image](https://cloud.githubusercontent.com/assets/22880786/20006060/ea2e1666-a2e9-11e6-88e1-4dd1eac78550.png)

### Relevant Issues/PRs
#1562, #1569 #1581

**Comment by bjubes** [comment]
Regardless of the look, it needs to be much more programmatic than the current settings window. All of the labels should be populated using scripts so they are easy to localize. It would be amazing if there was a way to also define the actual settings in code as well, something like: `SettingsDialog.AddSetting(name, parent, checkbox) `

**Comment by BraedonWooding** [comment]
Mmm, well I like the idea of a programmatic settings window (especially for mods), but I'm not so sure about the defining in code bit, it just leads a bit too much to startup scripts, meaning if they don't get run then you miss out certain settings and it kinda removes modability a little?  Also it's a little unclear, about what settings key that is referencing and whether or not to add a new key and whats the default value and so on.  Maybe to reflect that in a json/xml file would be safer?

**Comment by bjubes** [comment]
Yeah json would probably be better. I really don't mind how its done, so long as the settings window isn't one giant prefab that is completely inaccessible through code (what we have now).

**Comment by BraedonWooding** [comment]
Yep, it definitely needs to be accessible, probably more in line with my FPS Performance HUD, where you can make custom elements, and then it reads it from a json file for which ones to display.  This however will require a new Settings.json file so I'll hold off this for a small amount of time (since there are a few PRs that already make small changes to Settings.json and we should let them go through before we add more), than I'll make up a UI and see if people like it.

**Comment by BraedonWooding** [comment]
I will begin this, and create a basic PR (like what I did with the devConsole), I'm planning for this to be done in 1-2 months (akin to DevConsole).
