### ISSUE TITLE
Button - build furniture prefab breaks Unity for me

### ISSUE THREAD

**Issue by TheRiven** [TeamPorcupine/ProjectPorcupine#162]
Ok somehow this prefab crashes unity for me, I can only run Unity when it is removed otherwise it has some sort of issue and refuses to load the scene. I assume no one else is having this?

I'm guessing I might have messed up with git... somewhere but not sure how as it all seemed fine.

Any ideas why this might be and how I might go about correcting it?
I have tried pulling the latest Master copy and still have no luck.
I tried messing around with the git stuff to try and rollback but I am not sure if it actually did anything and it still did not fix it.

Is there a way to just blitz everything I have and restore from the Project master to see if that fixes it?

**Comment by bjubes** [comment]
To "blitz" you can go try 
git checkout master
git reset --hard upstream/master

If you see the latest commit as the same as what is listed on the official repo it worked. this will delete all local changes that are not committed so make sure you aren't working on anything.

**Comment by TheRiven** [comment]
Well... I am on the latest commit but unfortunately it has not fixed the issue.
Still crashes on load while I have that prefab in there but loads when I take it out. :confused:

**Comment by NogginBops** [comment]
@TheRiven I had the same problem in #131. I'm thinking it has to do with the unity version.

**Comment by TheRiven** [comment]
@NogginBops you mentioned an error in that one, were you still able to load unity?

**Comment by TheRiven** [comment]
or more to the point, what unity version were you running on that machine and what one are you running now?

**Comment by NogginBops** [comment]
@TheRiven  I was able to load unity but first loading another project first and then from that load this project. I was using 5.3.4f1.

**Comment by NogginBops** [comment]
It works for me on my other computer which is running on 5.4.0f3.

**Comment by TheRiven** [comment]
Hmm I assumed I was up to date but I am running 5.3.5f1 and the the website is showing 5.4 so my updater must be lying to me, maybe updating will fix my problems.

**Comment by TheRiven** [comment]
Yup updating seems to have stopped the crash, thanks @NogginBops for pointing me in the right direction!
