### ISSUE TITLE
Can't create Steel Wall 

### ISSUE THREAD

**Issue by hcorion** [TeamPorcupine/ProjectPorcupine#1621]
### Expected behavior

Crew Member goes and builds the wall.

### Actual behavior

A green wall highlight is placed but the Crew Members do not build it.
If you first build some new floors outside the original building, and try to place the Steel Wall on that, you can't even get the green highlight to stay and you get a wonderful error:
```
NullReferenceException: Object reference not set to an instance of an object
BuildModeController.DoBuild (.Tile tile) (at Assets/Scripts/Controllers/InputOutput/BuildModeController.cs:194)
MouseController.BuildOnDraggedTiles (.DragParameters dragParams) (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:429)
MouseController.UpdateDragging () (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:325)
MouseController.Update () (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:129)
MouseController.<MouseController>m__20 (Single time) (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:61)
TimeManager.InvokeEvent (System.Action`1 eventAction, Single time) (at Assets/Scripts/Models/Events/TimeManager.cs:198)
TimeManager.Update (Single time) (at Assets/Scripts/Models/Events/TimeManager.cs:125)
GameController.Update () (at Assets/Scripts/Controllers/GameController.cs:77)
```

### Steps to reproduce the behavior

- Step 1: You need to have developer mode turned off for the bug to show up
- Step 2: Load a new world.
- Step 3: Attempt to build a wall.
- Step 4: Presto! The Crew Members forgot how to make walls! (gif below)

### Specs

`git describe --tags`  v0.1-62-g07b1e81
MacOS Sierra 10.12.1 
MacBook Pro 13-inch early 2015
Unity 5.4.2f2
Visual Studio Code as text editor

Gif:
![projectporcupine](https://cloud.githubusercontent.com/assets/9814000/20173538/8fdd0538-a6ee-11e6-92cf-3484a1d19ab4.gif)

**Comment by Geoffrotism** [comment]
Walls have to be built on floors

**Comment by Geoffrotism** [comment]
Note: If you build Flooring in Dev Mode, then turn off Dev Mode and place wall, will work.

**Comment by bjubes** [comment]
Do you have spare steel plates around? In the gif I don't see any

**Comment by koosemose** [comment]
Whoops, I broke it.

I overlooked the job completion code for tiles (and utilities) in #1575 and they were still nulling  pendingbuildjobs, which is now a hashset, instead of removing themselves... fix incoming.

**Comment by hcorion** [comment]
Woops, yes @bjubes I don't know how to play the game yet. 😛

**Comment by koosemose** [comment]
Yeah, the lack of building the walls in the base are due to lack of plates, but outside is because a thing I overlooked.
