### ISSUE TITLE
Improve LocalizationDownloader.cs file extension detection.

### ISSUE THREAD

**Issue by hcorion** [TeamPorcupine/ProjectPorcupine#1624]
Hi everybody. 
In `/Assets/Scripts/Localization/LocalizationDownloader.cs` there is a check starting on line 272 for a bunch of file extensions and I was encountering some problems because Mac's crappy .DS_Store file was screwing it up and throwing the very useful error `SOMETHING WENT HORRIBLY WRONG AT DOWNLOADING LOCALIZATION!`.

As a temporary fix, I just added another && statement to it, but after adding that it's getting quite long.

At the very least I'd like to add a more informative error, something that includes the file extension that is causing the problem.

The comments explaining the if statement aren't very good either: 
```
// If there are files without that extension then:
// a) someone made a change to localization system and didn't update this
// b) We are in a wrong directory, so let's hope we didn't delete anything important.
```

Why in the world would it be in the wrong directory? What kind of change to the localization system would be enough to justify having an error check for it? The only case I can think of is if we changed formats, but even then, it would be goofy to think that the person making these changes would automatically assume that the code can handle anything you throw at it.

Also, if we do want to keep the error, I'm thinking a switch - case would be a cleaner format.
Example: 
```
switch (file.Extension)
    {
        case ".lang":
        case ".meta":
        case ".ver":
        case ".md":
        case ".DS_Store":
            break;
        default:
            break; //Throw error here
    }
```

**Comment by hcorion** [comment]
Ok I'm tagging @bjubes because I heard he knows more about the translation code.

**Comment by hcorion** [comment]
and @QuiZr because he originally wrote the code.

**Comment by QuiZr** [comment]
This whole class is a 100% mess and should be burned (or moved to another assembly and then cleaned).

**Comment by UnknownSoldier1** [comment]
IMO this entire localization download is a way too complicated system anyways, I just don't see the point of putting it into a completely different repository. It just confuses people (especially new contributors).

**Comment by hcorion** [comment]
@UnknownSoldier1 I thought about this as well, however it does make it easier for when we release binaries, the people can have translations always update

**Comment by hcorion** [comment]
@QuiZr Ok, do you have any ideas for improving it? I think I'd like to tackle improving it.

**Comment by hcorion** [comment]
Or perhaps we want to switch to an official tool? Like weblate or Pootle?

**Comment by hcorion** [comment]
Ok. I'm going to ask this to be closed and open a more specific topic about LocalizationDownloader.cs in general.

**Comment by hcorion** [comment]
Ok, moving discussion to issue #1627. can a gatekeeper close this issue?
