### ISSUE TITLE
Improve LocalizationDownloader.cs

### ISSUE THREAD

**Issue by hcorion** [TeamPorcupine/ProjectPorcupine#1627]
As some may know LocalizationDownloader.cs is a mess. (located `/Assets/Scripts/Localization/LocalizationDownloader.cs`)
This is an issue to discuss potential solutions.

Here are some solutions I can think of:
- Instead of downloading a .zip and moving it around, we just download config.xml, parse the languages in that, and then download the files individually.
- Move to a proper translation engine like weblate.
- Just download config.xml and en_US, then when the user changes their language, download that specific language.

I'm thinking number 3 is the cleanest solution. That way we won't need to package all of the locales, we can just have one. By downloading config.xml we can have the list of available languages, and by downloading en_US we can have a default language to work with. This will be slower the more translations we have to update, but I think it's a good tradeoff, being that (almost?) nobody is going to need ALL of the translations.

Pings: @QuiZr

**Comment by hcorion** [comment]
Some extra notes: We also now have NewtonSoft.json, use this for parsing.

**Comment by hcorion** [comment]
another thing to discuss, if we're going to use option 3, do we want to check against the latest commit, or check the sha1 for each file for updating?

**Comment by hcorion** [comment]
O I've done more reading. Apparently once you've built the game you can't write to StreamingAssets. Apparently Application.persistentDataPath is the better location.

**Comment by bjubes** [comment]
Option 3 is a step backwards from offline play. what happens if I want to switch languages while offline? Also StreamingAssets **can** be written to after building. Its what the localization system does currently.

I think your first bullet is the best approach. And yes, config.xml should be eventually converted to JSON

**Comment by hcorion** [comment]
@bjubes not on iOS and android

**Comment by BraedonWooding** [comment]
We aren't building it with mobile in mind.

**Comment by BraedonWooding** [comment]
I'm pretty sure that was established a while back in an issue that we aren't saying no to mobile but we aren't intending to build for it, since its too hard to upload and manage multiple platforms (and authenticate with things like the app store/google play)

**Comment by UnknownSoldier1** [comment]
If I would have the choice I would just put the entire localization system back in this repository, it's easier for new contributors and since we don't have any voicelines or anything like that it doesn't take up more space either.

**Comment by bjubes** [comment]
I prefer separate repo so that when in production it's easy to push seperate updates to the localization without having to make it seem like a seperate build/release in github

**Comment by hcorion** [comment]
Ok, let's stick with seperate repo for now. We'll have to get @quill18 to move it to the official TeamPorcupine repo at some point or another.

**Comment by hcorion** [comment]
Alright, here is an interesting idea. I'd like your input @QuiZr . The GitHub api has a way to get all of the files changed since a date. I could record a date along with the sha of commit in config.xml and then check if the current sha is equal to current master, if it doesn't we can then get the files that were changed, and download only them rather than updating everything.

**Comment by hcorion** [comment]
Ok, I'm going to start implementing the things I posted above. I'll create a WIP PR for people to track soon.

**Comment by BraedonWooding** [comment]
Sounds fair, seems you got approval.  Maybe make a checklist so people can know what's implemented (if there are multiple parts).

**Comment by bjubes** [comment]
if you want, you could also potentially use the diffs/patch of each commit and apply it to the localization files, similar to how git does a fast-forward merge. Not sure if this is easy to do, or a better approach than what you commented, but throwing it out there anyway.

**Comment by hcorion** [comment]
Yeah I considered that and actually found a C# class that uses the diff to patch the file but I think it adds too much complexity for now.

**Comment by hcorion** [comment]
Another question, what about using something like https://rawgit.com to download the files from the repo? It has a cdn option and would most likely be faster than using raw.githubusercontent.com

**Comment by BraedonWooding** [comment]
@hcorion @koosemose PR closed so this should also be closed since this is an implementation issue relating to the PR.
