### ISSUE TITLE
Gatekeeper activity and merging PRs

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1628]
Gatekeeper activity has waned drastically, with myself and bjubes being the only recently active Gatekeepers, and as my own PRs linger for a long time span due to Gatekeepers avoiding merging our own PRs except in the case of fixes to bugs on master and very small PRs, I find my own interest waning as I can't easily build off of features implemented in my own PRs, and even working in the same areas of code can cause an endless amount of conflicts with my own PRs or reimplementing a minor feature that was included in another PR just so things work consistently.

That being the case, I will be beginning to merge my own PRs, though I still intend to leave them in PR form for a reasonable amount of time for any issues with the code that I may have overlooked to be be brought to light. This will both help keep me invested in the project so I can continue effectively serving as a Gatekeeper, and allow me to more easily contribute to the project. If the state of Gatekeeper activity changes I will revert to previous behavior.

During this time, I would appreciate a greater level of overview and testing from other contributors on my own PRs, so I can do my best to ensure I am merging the best code I can.

**Comment by vogonistic** [comment]
It makes sense to me. It's important not to lose all the momentum when there is a small set of developers. I wish I had more time, but family will take up all of it for a while longer. Keep up the good job!

**Comment by BraedonWooding** [comment]
Yep, it makes sense to me too.  You are doing great!  We are gaining more of a following (after losing a little), and this is just the nature of open source sadly.  I think that maybe leave a few days (like you said) for people to raise comments, and if it's a simple thing (moving assets around, or uncommenting code) then just merge it whenever really.
