### ISSUE TITLE
Implementing a new Logging solution.

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1642]
Uberlogger was originally implemented to solve two primary problems. First was that a large mass of debugging messages about what is going on made it hard to find any one particular debug message. Second was that the large amount of debugging messages causes a lot of slow downs that gives a false impression of the game's performance.

Uberlogger only succeeds at the first, and in that it still doesn't handle it in the best way possible (having to have a separate window from the default, which causes a lot of confusion, particularly for new developers on the project, many of which I don't think are even aware uberlogger has a different console.

The second it doesn't do anything for, as debug messages are still printed to the default console regardless of what channels are being viewed on the uberlogger console.

I believe we may need a custom solution (or if anyone has any suggestions for a solution that more fully fills our needs). Rather than a separate console with separate controls, I believe we need to have a logger that either prints or doesn't print a debug message to the standard console depending on rather or not its channel is turned on. This does have the downside of your channel selections only taking effect on new messages generated since you set them (so if you miss a message because its channel is off, it's gone forever). However, it will prevent performance being hampered by debugging messages.

While we could just remove most debugging messages that are printed that are just informative, we are still in an early stage of development where things may often go wrong with an already implemented system and it would further hamper development time if debugging messages for a given system had to be implemented every time an error occurred.

Of course, on top of that, we would also need/prefer a Unity UI to set what channels are active, rather than having to toggle some variable or preprocessor directive, and have it remove itself from the callstack (so double clicking on the error properly takes you to the actual error, not the logging code)

**Comment by hcorion** [comment]
+1 this needs to be done.

**Comment by hcorion** [comment]
Perhaps a custom implementation, or a layer over UberLogger (or just a hack implementation) that checks if the info debugging is wanted. IMO general debugging should be disabled by default but warnings and errors enabled by default. General and Warnings should also probably be disabled in actual builds.

**Comment by hcorion** [comment]
I was also having a lot of trouble with UberLogger and Visual Studio Code because when I clicked the error it just took me to the file, not the line of the error, which annoyed me so I just used the default console and occasionally used UberLogger to see if I could scrounge up anything useful.

**Comment by koosemose** [comment]
The vsCode thing *may* just be unity (I'm not sure, I only use it for Lua), but it does leave a lot to be desired, particularly since it apparently doesn't do anything to the callstack (causing double clicks to take you to uberlogger), has issues with multiline logs, and for good measure tends to silently fail when called from a thread.

Vog hacked together a half decent one in Pathfinder.cs because there is so much logging in there. But it's not generalized and has to be turned on with a preprocessor directive.

**Comment by hcorion** [comment]
@koosemose It does what it should with the normal console, so I think it may just be the combo of VSCode plugin and poor interaction with UberLogger.

**Comment by longtomjr** [comment]
Ok, I did a little bit of research on this, and this is basicly just to share a bunch of options and some implementations we might find useful.
### Unity ScriptReferance 
* [Logger class in Unity](https://docs.unity3d.com/ScriptReference/Logger.html)
* [Page for LogFormat](https://docs.unity3d.com/ScriptReference/Debug.LogFormat.html) - This can be useful for better formatting of messages using RTF.
* [Debug class in Unity](https://docs.unity3d.com/ScriptReference/Debug.html)
### Base .net
* [MS Build Utlis](https://msdn.microsoft.com/en-us/library/microsoft.build.utilities.logger.aspx) - I dont see this as a solution, but might as well link.
* [NLog](http://nlog-project.org/) - [On Github)[https://github.com/NLog/NLog]
### Custom Implementations for unity
* [Custom Implementation / Wrapper](http://blog.puzey.net/simple-better-unity-logging/)
* [Another custom implementation with clicking implemented*](https://github.com/Valian/UnityDebugger)

*With that I mean that when you click the error it will jump to the correct line in your IDE linked with Unity.

**Comment by koosemose** [comment]
@longtomjr Thanks for that.

Honestly the last one looks like at least a good basis to build a custom implementation off of. Just need to add some form of channels on top of it and preferably some Editor UI to control said channels.
