### ISSUE TITLE
Project Porcupine doesn't compile on Unity 5.5

### ISSUE THREAD

**Issue by hcorion** [TeamPorcupine/ProjectPorcupine#1655]
Hi all, 
in Assets/Scripts/UI/InGameUI/PerformanceHUD/MemoryPerformanceComponent.cs it doesn't compile on Unity 5.5.0. Unity changed the namespace of the Profiler class as mentioned on the release notes: 
> Profiler: Profiler class moved from UnityEngine namespace to UnityEngine.Profiling

The obvious solution would be to just add UnityEngine.Profiling, however this doesn't exist in versions before Unity 5.5.0, so it throws an error. 

Here are the solutions I can think of:

- We just stick with 5.4, and everybody who upgraded can either install 5.4 or just edit the file locally.
- We move to 5.5 and force everybody to upgrade.
- We add an if preprocessor check like 
```
#if UNITY_5_5_OR_NEWER
      using UnityEngine.Profiling;
#endif
```

**Comment by bjubes** [comment]
I think the best thing to do is set a day in the future to "officially" upgrade the project. That gives everyone time to download the new version and address the potential hiccups that i mentioned here #1652. For now, a preprocessor check is probably best so it works on both versions.

**Comment by hcorion** [comment]
Ok, so then, the question is:
What day and how should we alert our devs of this day?
I was thinking maybe adding a large header to the readme like this: 
# Project Porcupine will migrate to Unity 5.5.0 on December 31st 2016, be sure to update your unity installation.

**Comment by hcorion** [comment]
I can add this to my 5.5 PR.

**Comment by BraedonWooding** [comment]
Personally 31st is fine (and you could even do dates prior to then, like the 20th).

**Comment by BraedonWooding** [comment]
Btw @hcorion change the title since in the end we decided on having both (for a little while then switching over), so maybe call it something like Unity 5.5 Migration :D.

**Comment by BraedonWooding** [comment]
Much better title :D
