### ISSUE TITLE
What settings options should we have?

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1658]
This is to have a discussion on what options should be implemented, currently the settings menu supports multiple segmented 'categories' (like sound, video, general...) as well as 'headings' (like 'Advanced' / 'Basic' Video settings).  Below will be a table of current options (I'll update as people suggest).  These won't be implemented in my current PR however they will be implemented in another one (which may be made parallel or concurrently to the current one).

### General
Autosave | Localization
-----------|--------------
Interval | Language
Max Files | Auto-Update

### Sound
| Volume | Advanced |
| --------- | :-------: |
| Master | Sound Device
| Music | Locational Sound
| Game |
| Alerts |
| UI |

### Video
General | Advanced | Window
---------|------------|---------------
UI Skin  |                  | Mode
Quality  |                  | Resolution
V-Sync
. | Particles  
. | Shadows 
. | Buffering 
. | AA             

### Developer
General                    | Console              | Utilities
----------------------|-------------------|----------------------
Developer Mode     | Scroll Sensitivity | Performance HUD
Logging Level         | Time Stamps       |
. | Enable                 |
. | Font Size             |

**Comment by hcorion** [comment]
As I already noted in my PR #1647 enabling or disabling the automatic updating of the localization is also a setting that is needed.

**Comment by hcorion** [comment]
Perhaps logging level as well, say General, Warning and Error.

**Comment by BraedonWooding** [comment]
Yep good ideas :D

**Comment by koosemose** [comment]
Audio channels present in code are: Master, UI, Game Sounds, Alerts, and Music.

I'm not entirely certain if logging level is the sort of thing that should be in the in game options...

**Comment by BraedonWooding** [comment]
Maybe in developer?? idk we may implement a in game logger later?

**Comment by hcorion** [comment]
I was thinking it would be useful for debugging releases. If we get a user who can reproduce an issue successfully in a release, we can ask them to set debugging to general and then send us the log.

**Comment by koosemose** [comment]
For that purpose, perhaps we should just leave it a simpler "Logging", ignore the setting in a debug build, since relevant info may not come from error channel, and it would be easier for us to just tell them to turn on logging, rather than "Turn on X Logging Level, and Y Logging Level" and so on

**Comment by bjubes** [comment]
you forgot language selection, but im not sure what category it belongs in

**Comment by BraedonWooding** [comment]
Or we could have it so that it logs it to a 'log file' like a text file (if you have that option on).  It would make it 'slower' but we could just log it before the crash?

**Comment by koosemose** [comment]
By default, if you do Debug.Log or any of its variations it logs to a log file, however, if we're putting in enough information to be useful for debugging, it would slow gameplay down tremendously.

**Comment by hcorion** [comment]
By default in a release it logs everything to ProgramName_Data/output_log.txt, by default we would just have only warnings enabled, but in the GUI we could like I said enable general or warning debugging, or as @koosemose suggested, we could have a simpler on off setting.

**Comment by bjubes** [comment]
With the new localization downloader we will need an "update localization" button to one off check for updates when automatic ones are disabled.

**Comment by BraedonWooding** [comment]
Yep already in the list automatic localization.

**Comment by BraedonWooding** [comment]
I'm going to be implementing this (should be relatively quick).
