### ISSUE TITLE
Load Starting Area from a save file

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1662]
Currently the starting area is generated directly from the data in WorldGenerator.xml, however it is formatted oddly, meaning special handling needs to be done if any new features are implemented that would need to be present on world generation. Additionally it flips the Y coordinate, from what it is in game, which can be somewhat unintuitive.

I propose, rather than having the starting area defined in the WorldGenerator.xml, it instead direct to a file (stored in streaming assets, rather than the standard save location) which uses the same format as a save file (most likely with some information stripped out, such as characters for example), this would allow us to use the same code as is used to load worlds from save (possibly with special handling somewhere to handle it being offset). 

This would accomplish several things, first it would make it unnecessary to implement loading the starting area separately, making it easier to modify the starting area. Second it would allow the start area to be designed in game (though the save file would have to be manually moved to streamingAssets), and make it quite a bit easier for modders to create modded worldGenerators (possibly allowing worldGenerators to be part of scenarios). Note: designing the starting area in game relies on removing MinEdgeDistance, as proposed in #1660.

As a preliminary step, I have already added the ability to set the size of a new world from a dialog (a very badly put together dialog for the time being), and also to turn off asteroid generation, this is to allow simple conversion of the current starting area to a .sav file to be used as the starting area after changing it over. The variable size world will presumably stay in (hopefully with a better UI), The asteroid generation may or may not stay in, possibly moving to a setting in the world generator.

Future steps that I intend (though for a later PR, and almost certainly not the PR that will come from this assuming it is met with general approval) would be the ability to choose from multiple worldGenerator data files. With the data currently in worldGenerator.xml, this would allow worlds with different density of asteroids (or at least generating them on a different scale), more or less resources (possibly leaving some resources out), a different starting area, and different starting money.

**Comment by dusho** [comment]
Sounds fine. Would nice start for creating demo and some parallel scenarios for gameplay,

**Comment by BraedonWooding** [comment]
I agree with dusho

**Comment by koosemose** [comment]
So, to report on some unforeseen issues: The most reasonable way to load the starting area from savefile, I believe, is the simply create a new World, use its ReadJson, and in some fashion get the world data from that. The problem of course is that that sets and access a few of the static Instance variables (things like World.Current, and subscribing to things in TimeManager) which of course creates an issue in the main World. I can in theory work around that by having parameters passed which tells it not to do those things, and just pass those values down the line to where they're needed, or have a way to add a "tile offset" in ReadJson, and have that passed down the line in some fashion, so things are offset to the proper centered position.

I don't consider either of these satisfactory, and the proper approach, I believe is to move everything out of World that isn't actually part of the actual world, presumably into WorldController. I'm not sure if this would cause any further issues, and it may require creating an additional layer for things that are currently in WorldController (something like StarSystemController perhaps?) that contains everything applicable to a given playthrough.

**Comment by dusho** [comment]
another layer is ok.. not sure about name StarSystemController.. sounds too specific and maybe misleading (if you want only one layer about worlds, that are in same system).. maybe something like OverWorldsController ?

**Comment by koosemose** [comment]
I'm not sure how StarSystemController is too specific or misleading. The game at most is going to take place in a single star system. While the more generic GameController could be applicable (and some stuff could be put in there as well), we will eventually need somewhere that stores all the info about the star system.
