### ISSUE TITLE
Door graphics behavior is hardcoded

### ISSUE THREAD

**Issue by emilkris33** [TeamPorcupine/ProjectPorcupine#167]
The FurnitureSpriteController has some hardcoded behavior related to doors. (Rotation and animation)
In ran into this in #166 when implementing a different door(airlock) and for now I have just made a dirty fix to make it work.

Ideas for how this should be generalised? Or someone who is/will work on it?

**Comment by BeefEX** [comment]
I am woking on animation controller right now. It will fix this.

**Comment by Raketfart** [comment]
I've done some work on this, and have some speculation in #85

**Comment by vogonistic** [comment]
I believe this has been fixed, right? Reopen the issue if it hasn't.
