### ISSUE TITLE
Can't build stockpile anymore

### ISSUE THREAD

**Issue by hcorion** [TeamPorcupine/ProjectPorcupine#1689]
This is a regression and it happens in both developer mode and normal mode.

### Expected behavior

Builds a stockpile

### Actual behavior

nothing happens visually after you let go of the mouse. However, it does throw a nice error: 

```
NullReferenceException: Object reference not set to an instance of an object
ProjectPorcupine.OrderActions.Build.CreateJob (.Tile tile, System.String type) (at Assets/Scripts/Models/OrderActions/Build.cs:45)
BuildModeController.DoBuild (.Tile tile) (at Assets/Scripts/Controllers/InputOutput/BuildModeController.cs:158)
MouseController.BuildOnDraggedTiles (.DragParameters dragParams) (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:433)
MouseController.UpdateDragging () (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:325)
MouseController.Update () (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:129)
MouseController.<MouseController>m__0 (Single time) (at Assets/Scripts/Controllers/InputOutput/MouseController.cs:61)
TimeManager.InvokeEvent (System.Action`1 eventAction, Single time) (at Assets/Scripts/Models/Events/TimeManager.cs:198)
TimeManager.Update (Single time) (at Assets/Scripts/Models/Events/TimeManager.cs:125)
GameController.Update () (at Assets/Scripts/Controllers/GameController.cs:77)
```

### Steps to reproduce the behavior

- Step 1: Attempt to build a stockpile, it's actually quite simple.

### Specs
Output of `git describe --tags`:  `v0.1-108-gaf271bb`
Unity version: 5.5.0f3 running on Mac OS Sierra 10.12.1

**Comment by BraedonWooding** [comment]
Sounds like a problem from #1640 (Purely due to them both being about orderActions)

**Comment by hcorion** [comment]
I was told to tag @dusho as it is assumed that your PR has something to do with this.

**Comment by BraedonWooding** [comment]
Hehe lol the double tag :P.

**Comment by BraedonWooding** [comment]
@koosemose suggested it could be JobTime (since stockpiles have a 'null' jobtime in xml which should be treated as a 0 job time but maybe the new system doesn't handle that?).

**Comment by koosemose** [comment]
It appears it is stockpile not having a jobTime that does this. Changing to 
```xml
        <OrderAction type="Build">
            <Job time="0" />
        </OrderAction>
```
fixes it.

I am not submitting a fix at this time, as I would like to pose the query if we should mimic the old behavior, in that an empty orderAction is treated as having jobTime 0, and have the code changed to handle that, or treat it as right and proper that jobTime *must* be included and change the xml.

**Comment by BraedonWooding** [comment]
I would say that it definitely seems like its jobTIme due to the code below (it xml if you have a setup like this an the object doesn't exist it will be set to null):
```
[Serializable]
public class JobInformation
{
    [XmlAttribute("time")]
    public int Time { get; set; }
...
}
```
I would say that we really should have defaults for variables like jobTime, since if you don't have a jobTime it makes sense you wouldn't include it since really 0 job time is not a 'time' to complete its more like saying it doesn't have a time to complete cause its instant aka like if it was equal to null; if you get what I mean.

**Comment by dusho** [comment]
ah ye, sorry... It shouldn't be a problem to have default instance of JobInformation is there isn't any, default value for int (Time) will then be 0. Will create a fix PR when I get home..

**Comment by koosemose** [comment]
No problem, that's the great thing about a group project like this, you don't have to be expected to find every little bug or whatnot, there's plenty of other eyes on to pick up every little detail. :D
