### ISSUE TITLE
Be on the lookout for places where HashSet can be used over List

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1694]
There are many places in PP where List is used as a default, however in many of these places order doesn't matter, and there's not a need to access the contents by index. For code that is ran only occasionally and/or on small Collections, this is fine. 

However, there are some places where using a HashSet over a List can make very obvious notable differences such as the massive difference made by the changes in #1691, and the lesser difference from #1693. Changing furnitureInvisible and furnitureVisible to a HashSet caused a drop from ~100ms spent just maintaining the list of which furniture was in view and which wasn't to ~8ms, which results in a very obvious increase in the smoothness of the game running, similarly the changes in RoomManager causes less loss of frames when placing walls.

I would appreciate assistance on locating similar areas where such change outs could be made, as a few changes to HashSets where a List isn't really needed can give massive benefits in the right areas (ran frequently and/or large containers), without increasing code complexity with a very simple change.

**Comment by dusho** [comment]
not related to this, but performance. Newest master has some heavy lag spikes for me. I tried to go back to some commit from december 5th, lags were still there, but just minimal and less often.
To check the lags I just grab scroll bar in construction window and move it up and down.. when lag happens, bar gets stuck for a moment and then jumps to mouse position..
Anyone else experiencing this?

**Comment by bjubes** [comment]
I definitely seen more lag recently. Often I have to force quit unity when entering play mode because it just hangs indefinitely.

**Comment by koosemose** [comment]
Some of the more recent lag is due to idle character wander and I've been working on pinpointing other sources, along with brainstorming other ways to make things more generally efficient.

If you guys can do a bit of targeted profiling (using Profiler.BeginSample) to narrow down what specifically is causing the issues, that may help targeting some of the more prolific causes.

**Comment by hcorion** [comment]
I was noticing that a lot of our lag was due to the lua scripts, we should migrate some of the performance ciritical parts to C#.

**Comment by dusho** [comment]
@bjubes I had this problem and it got resolved after updating to Unity 5.4.3

Those lag spikes indeed occur in some kind of fixed frequency. Will try that Profiler - never used that before...

**Comment by koosemose** [comment]
@dusho Since you haven't used it before, just some basic instructions (so you don't have to dig around for basic usage details): Surround a piece of code with `Profiler.BeginSample(<string Containing name for section of code>)` and `Profiler.EndSample()`. Then that section of code will show up in the profiler under that name. Also in the profiler there is a little search bar, if you do a search for the name you chose it will kind of highlight what parts that code is responsible for in the graph. And if there's multiple related pieces of code, if you give them all similar names (for example when trying to narrow down the problems with IdleState, I used Idle1, Idle2, and so on) then you can just search for the common part (so for me I search for "Idle") and it will highlight all of them, helping to narrow in on the frames where it's problematic.

If it doesn't highlight them in the graph, it's usually because it is such a tiny part of it that it's just not visible... which of course probably means it's not the problem you thought it was.

**Comment by dusho** [comment]
@koosemose cool... thnx for info
just from switching on profiler I saw some scary times for GC.Collect
![image](https://cloud.githubusercontent.com/assets/12616499/21244657/efba6d78-c31e-11e6-8c85-d3616822356d.png)
maybe we need to introduce some generic pooling?

**Comment by koosemose** [comment]
Wow! I didn't realize quite how bad performance was for some other people...

Unfortunately, to the best of my knowledge (which is admittedly rather limited when it comes to the profiler), that much of your issues being in the garbage collector makes it rather hard to narrow down what exactly is causing the issue (what's generating the objects that need destroyed), but I do have a suspicion. Foreach loops are rather notorious in Unity for generating a lot of extra objects that then need to be garbage collected, and we use foreach rather liberally in our code

**Comment by hcorion** [comment]
It starts lagging really bad when you enable the profiler.

**Comment by koosemose** [comment]
You haven't turned on deep profiling have you?

**Comment by BraedonWooding** [comment]
I think we have converted all the lists required to hash sets.
