### ISSUE TITLE
State Unity version in documentaion

### ISSUE THREAD

**Issue by zwrawr** [TeamPorcupine/ProjectPorcupine#17]
The version of unity that contributors are using should be standardised and listed in the documentation. This is currently a non-issue but will be come important in the future when updates and new version of unity are released.

**Comment by quill18** [comment]
Good point.

Luckily, we aren't heavily using very many Unity features -- we aren't even dependent on scenes or prefabs.  Heck, the few prefabs we have could probably be deleted from the project and the gameobject could be built in script.

You should be able to build the program as long as 2d Sprite Rendering and the UI system is present (4.6?) -- though it's possible that 4.6 would allow you to use functions that are deprecated in 5+.

Still, it might be good if we secured ourselves by picking the latest stable version (5.4) and saying that it needs to build in 5.4 to be a valid patch.

**Comment by misspellted** [comment]
That sounds like an Eclipse .project file or an IntelliJ .idea file... which, managing local project settings, is added to the repos I work in.

**Comment by SquareMan** [comment]
Yeah, i don't think that the projectsettings file would have any impact on the playability of the game, or being able to build it. It should probably be ignored, we could always bring it back later if we for some reason need it.

**Comment by misspellted** [comment]
Having just imported the project for the first time after installing Unity for the first time on Ubuntu... I'd vote including both ProjectSettings.asset and ProjectVersion.txt inclusion in the .gitignore file:

![ubuntu540p1vswinmac540f3](https://cloud.githubusercontent.com/assets/16412448/17722535/c428a8dc-6400-11e6-971d-6c51629fc063.png)
