### ISSUE TITLE
Construction Filter no longer working

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#1700]
### Expected behavior
typing  into the filter in the construction menu should search for furniture that matches the string and remove others from the list.

### Actual behavior
nothing happens. This feature was working at some point so if anyone has a guess of when it regressed or can find  the commit/PR that broke it by bisecting please post it.

**Comment by koosemose** [comment]
Well, I can't say when it broke, but I can tell you that it was a relatively recent PR, checking on my local master, it still works on there, and it was last updated to #1659 ( 95b3a4482bc926059e4f4b6d1b8e5599afa3f683 ). It's entirely too late in my day to want to do bisecting, but that should at least be a decent starting point of a good bisect.

**Comment by koosemose** [comment]
I suppose I shouldn't be surprised... it's the PR that was doing stuff in the area of the menus and such, #1640

**Comment by koosemose** [comment]
I've found the issue (the Filter function isn't being called at all when the input field changes), however I can't fix it at the moment due to issues with Unity 5.5
