### ISSUE TITLE
Unity 5.5 isn't reliable enough to switch to at this time.

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1707]
I've spent the past several days attempting to use PP with Unity 5.5, and have had constant problems, from mysterious error messages whose stacktraces seem to indicate that they're normal Unity processes going wrong for no reason that can be diagnosed (since it's internal), to a near complete inability to interact with any UI elements in the editor, visual glitches in the editor itself(most notably appearing to do the "burn in" effect when moving things around, as though it weren't properly redrawing the newly revealed areas), needing to manually install an assortment of things to get monodevelop to actual launch. 

These are just the issues that come to mind due to being the ones I've experienced in the past several hours, there have been many more. The only benefit I'm aware of that Unity 5.5 brings, that in any way affects our project is having integration with VSCode, which doesn't really affect the project itself and I don't feel it outweighs the issues it brings.

At most, at this point in time, we can have the various workarounds that make the project functional in 5.5 (such as the ifdef required to access the Profiler from code), but I don't think it should be the primary version for our project, and we shouldn't do a wholesale update unless a new version brings something which actually benefits the project as a whole (and is proven reasonably stable).

**Comment by hcorion** [comment]
I've been using 5.5 with PP and haven't noticed those problems, but as they are problems I think it would be a good idea to remove the 5.5 migration notice in the readme, and perhaps stall the upgrade until a 5.5 bugfix release is out.
