### ISSUE TITLE
Notice: Saves and Setting file have moved.

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1734]
As the projectSettings for Company name have (finally) been set, saves and settings are no longer in the same location.

They have moved from DefaultCompany\ProjectPorcupine to Team Porcupine\Project Porcupine (in your User profile directory in AppData\LocalLow\ in case you weren't previously aware of where they were stored)

Mac of course would be moved as well, presumably with similar sorts of name changes, though I'm not sure exactly on the Mac directory structure.

**Comment by BraedonWooding** [comment]
Maybe add to the readme?
