### ISSUE TITLE
Justification for InventoryCommon

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#1735]
We've had InventoryCommon in the code for quite some time, and as best I can tell it basically functions as a class to be Prototypes for Inventory, unlike every other prototypable which is its own prototype. I don't see the point of having it separate, it effectively just duplicates some of the code in Inventory, seemingly to no gain.

Can anyone see or come up with a reason that InventoryCommon is useful in some fashion and shouldn't be removed (with Inventory moving to serve as its own prototype)?

**Comment by dusho** [comment]
if it's cleanup and it's not needed anymore, I would would say go for it and remove it
maybe only during removal you will notice that it is still used for something

**Comment by koosemose** [comment]
No it's used... I just don't think it needs to be used, it's basically just Inventory with methods removed,

**Comment by BraedonWooding** [comment]
Yeh remove it, its 'questionable coding' for it to remain just a copy + paste with a few select removals.  Unless we want to bring in more furniture class hierarchies (which I think we should avoid) it should be a furniture and not some duplicate code.
