### ISSUE TITLE
[Discussion] Need system upgrade

### ISSUE THREAD

**Issue by Dan54** [TeamPorcupine/ProjectPorcupine#1753]
Some possible features:

- JSON need file
- Needs can have a probability of being on a new character
- make existing needs work (add LUA)

**Comment by dusho** [comment]
that is some confusing topic name :) maybe try Update for Need system ?

**Comment by koosemose** [comment]
Existing needs *do* work, so I'm not sure what you're talking about there, and needs are on all characters... 

As far as changing needs over to JSON, that *is* the plan however the entire prototype system needs changed over, there was someone who was working on that, but they haven't been heard from in a while, so I suppose we can assume they either changed their mind or got bored and moved on.
