### ISSUE TITLE
Problems with doors

### ISSUE THREAD

**Issue by BeefEX** [TeamPorcupine/ProjectPorcupine#176]
I am creating "animation" system whitch will be defined in XML. I order for it to work i need to access the furnParameters from other class, so i created simple function that returns it. But while testing with doors the openness parameter was only getting values 0 or 0.175481456 (or simillar numbers). Does anyone know what can cause this?

**Comment by emilkris33** [comment]
@BeefEX If you can point me at the branch your working in and the file where you are doing it I would gladly have a look.

**Comment by BeefEX** [comment]
@emilkris33 i cant find it :D on web versions it simply isnt there
I probably fixed it any way thanks

**Comment by emilkris33** [comment]
@BeefEX You need to select the branch in the client and push the sync button for it to who up on github

**Comment by BeefEX** [comment]
@emilkris33 stupid me, forgot to publish it :D
