### ISSUE TITLE
Jobs can be defined on top of each other

### ISSUE THREAD

**Issue by emilkris33** [TeamPorcupine/ProjectPorcupine#181]
When you have placed a multitile furniture job it is possible to create more jobs overlapping it. And you can place multitile jobs overlapping existing jobs. As shown in the picture:
![image](https://cloud.githubusercontent.com/assets/1301554/17785356/af6eb022-6580-11e6-87e0-3b6482905364.png)
I am working on a fix for this

**Comment by ComputerOverlord** [comment]
Ooooh.. That's not good...
