### ISSUE TITLE
Standards for variable naming/formatting

### ISSUE THREAD

**Issue by behindcurtain3** [TeamPorcupine/ProjectPorcupine#182]
Has there been any discussion on standards for this? Looking through the code it is a complete mix of lowercase, uppercase, public and private variables (some properties also). Does anyone have any suggestions on how this could be handled the best (and consistently) going forward?

**Comment by ComputerOverlord** [comment]
For when quill finds this...
testVar
TestVar
or testvar?

**Comment by BeefEX** [comment]
@behindcurtain3 most of this mess if by @quill18 himself :smile:

**Comment by OzieGamma** [comment]
Related to #151

**Comment by lameox** [comment]
I suggest we use the Microsoft Coding Conventions for everything C# Related
which means:
```
//camelCasing everywhere
//descriptive names for variables/methods
//fields, properties and methods should always specify their scope, aka private/protected/internal/public

interface ISomeInterface{ } //Interfaces starting with a captial I

class Class { //class names Uppercase

   private int _memberField; //fields start with an underscore and should be private if possible

   public int MemberField { get { return _memberField; } } //Properties should be captialised

  // Functions should be capticalised
  // Function parameters should be camelCase
   public void SomeFunction( int functionParameter ) 
   {
      int myLocalVariable = 0; //local variables should also be camelCased
   } 

   public event SomeEvent; //Events should be capitalised as well 
}
```

I think this would be the easiest as we could just link the MSDN Style Guide for our Contributors.
Also i think its the prettiest way :D

**Comment by OzieGamma** [comment]
@lameox MS code style has braces on the next line:

```csharp
class Class
{ // On this line
}
```

**Comment by behindcurtain3** [comment]
@BeefEX I don't want to point fingers :D @lameox I like those conventions as that is what I use in personal projects.

**Comment by lameox** [comment]
@OzieGamma oh shit yeah. Will edit

**Comment by BeefEX** [comment]
@behindcurtain3 i dont like them but still use them @D

**Comment by Mizipzor** [comment]
StyleCop, in #158, complains if you name something incorrectly.

**Comment by satch3l** [comment]
Isn't code standars mentioned in the readme or contribution files? 

Differentiations may be leftovers from earlier in the development. However I'm sure those will be changed in the future.

**Comment by lameox** [comment]
Well it says 
> We have standardized on Microsoft's C# Coding Conventions and General Naming Conventions, with a few exceptions.

>Avoid using 'var', even when the type would be clear from context. Verbose typing is best typing.

However the Codebase aas it currently stands does not really adhere to those standards. I think we should at least open an Issue to go over the Code and reformat it, and after that drop the 
> with a few exceptions 

bit. That way we have a clear definition and nobody has to guess what the exceptions might be. Other than that you are right. quill basically decided already.

**Comment by Dormanil** [comment]
That "with a few exceptions" was about 
> Avoid using 'var', even when the type would be clear from context. Verbose typing is best typing.
Not about the current code base not actually adhering to these standards yet. 

But we definitely should go over the current code and refactor our fields, properties, and methods.

**Comment by lameox** [comment]
Yeah i get that but its still ambigously worded and could be taken another way imo. 
Would you open the Issue for it?

**Comment by Mizipzor** [comment]
Using the StyleCop rules I've been going through all it brings up, and its quite a lot. I'm not sure how to go about it, I did plan to just do it all in one commit but I think it gets too big.

**Comment by lameox** [comment]
Well i think we should wait for the current wave of issues to be mergeb before we change any code on that scale. This would break more or less all open PRs. Thats why i would just open an issue for now.

**Comment by Dormanil** [comment]
My new PR should at the very least help alleviating that problem in the future, I think.

**Comment by lameox** [comment]
Looks good!

**Comment by OzieGamma** [comment]
@Mizipzor 
From personal experience, you're better off having a lot of warnings than to wait

**Comment by behindcurtain3** [comment]
@Mizipzor I just tried out StyleCop and you are right it has a **lot** of warnings. Might be better to do one file at a time vs doing all at once.

**Comment by lameox** [comment]
Well if we update the codebase now and then merge some open pull requests we will get more then a few warnings. it is better to wait for the next round of merges and then start imo. that shouldn't take too long either as quill has been relatively active.

**Comment by OzieGamma** [comment]
I suggest to activate StyleCop in one PR. We can fix files when we changed them. That’s what we do at work and it works great.

**Comment by koosemose** [comment]
@lameox  Do you have a link to the MSDN Style Guide? Because the only things I can locate (by googling "MSDN Style Guide") makes no mention of starting with an underscore, and says very little about any other naming conventions. The closest other things I can locate are for frameworks, or their internal style guide.

**Comment by lameox** [comment]
@koosemose we disccussed it a bit more in #192 
you can look it up there

**Comment by vogonistic** [comment]
Lets complicate the discussion. What about Lua?

**Comment by lameox** [comment]
Good point. I have only ever written some lua for the minecraft computercraft mod so I have no idea about best practices conventions or even what the lua authority (like microsoft is for .Net tech) would be. Im currently at work so can't really look it up though. Does anyone have a initial style guide we could modify/discuss?

**Comment by Mizipzor** [comment]
Since the pull request was merged, are we continuing the discussion here? @quill18 made one last comment that maybe we should reserve the underscore prefix for fields that shouldn't be touched directly. I would advice against that since it would it impossible to automate a style check. And that's something I find really helpful in young projects like this that evolve very rapidly. Maybe underscore for private fields but not for public fields? Oh, and for the record my personal preference is no prefix at all. ^^

**Comment by lameox** [comment]
@Mizipzor i agree with you on not screwing with the automated style checking. However i find it easier to reason about some code like 
```csharp
void SomeFunction (int a)
{
    int b = a + 3;  // i immediately know a and b are in a local scope
    //loads of code here
    _c = b + a; // i can immediately see that I am modifying state of my class
    a = 0; // i can be sure i dont modify state of my class
}
```
While this might now be a big advantage i often found it useful when debugging and refactoring as i did not need to look at a given variable and determine what scope it was in by looking at its definition.

**Comment by Mizipzor** [comment]
@lameox I think you misunderstood me. I personally prefer to have a prefix on fields. My point was that i has to be clear and well defined. I would strongly advice against doing a rule that says you need the prefix if _this kind if field_ is used in _this kind of way_. I'd argue that if you can't make it a StyleCop rule, it's not defined well enough.

This is one of the holy wars, _everyone_ has their preference and trying to make everyone agree is completely pointless. The best we can do is to make the rules clear to everyone. There has to be zero room for interpretation.

**Comment by lameox** [comment]
@Mizipzor Yeah we are kinda arguing the same case i guess. I think we can leave this Issue open for a while and if nobody objects we just define the current proposed set as a rule

**Comment by bjubes** [comment]
I think that naming of variables and functions should be regulated, but does it really matter if a class has a curly brace on the same line or next line?  It's very clear either way and unity chooses the former when it creates new files Anyway

**Comment by Mizipzor** [comment]
There are many, many reasons why sticking to a code style is beneficial.

1. It prevents people going back and forth constantly changing a method they work on to fit their personal style.
2. If you read a lot of code in the project you get used to reading (and writing) that style, making both easier.
3. If two people write the same code and write it in the same way, merging is easier.
4. Good rules can be checked automatically, removing the need for looking at that aspect during review of pull requests.
5. (And this is the big one) it removes the need for threads like these with the endless discussions where it's impossible to make everyone happy.

It shouldnt be a matter of making the code look as good as possible, but to make the rules as clear and well defined as possible. By defining all aspects as part of a style, names braces and all, it removes the room for interpretation.

**Comment by vogonistic** [comment]
Adding reference to #291, which I think is the wrong way to go about fixing it.

**Comment by Mizipzor** [comment]
Especially since this discussion is still ongoing.

**Comment by behindcurtain3** [comment]
Quill did accept the PR to update the style guidelines, although he hasn't commented on any of the proposals or discussion.

**Comment by Grenkin1988** [comment]
LINQ Queries - should we use them as:
```
var seattleCustomers = from cust in customers
                       where cust.City == "Seattle"
                       select cust.Name;
```
or
```
var seattleCustomers = customers.Where(cust => cust.City == "Seattle").Select(cust => cust.Nsme);
```
I prefer methods call.

**Comment by lameox** [comment]
I vote for the second version, aka Method Calls

**Comment by vogonistic** [comment]
I second method calls. What's the interface to support LINQ queries in something like InventoryManager?

**Comment by Mizipzor** [comment]
@Grenkin1988 Now were talking. :)

Normally I would go for both, whichever is more readable at the time. But, as I've said before, for this project I think it's much more important that this is super well defined rather than objectively good. 

I vote for method calls.

**Comment by Grenkin1988** [comment]
How many votes we need to include this to our standart? :-)

**Comment by Mizipzor** [comment]
When @quill18 votes, I suppose its the only vote that counts. XD

Maybe its time to throw in the towel and create a wiki page for a code standard, since we already deviate from the Microsoft one and might to do on more points. And this distinction on linq is not in the Microsoft standard as far as I know.

**Comment by koosemose** [comment]
While I'm not familiar with LINQ at all (other than that it appears to basically be SQL but in c#?), I think, as a standard I prefer the second, as it seems most similar to standard c# (and therefore may be less intimidating to novices). (Even though I prefer the SQLishness of the first, since that's what it basically seems to be functioning as)

**Comment by behindcurtain3** [comment]
I also prefer the method calls. @Mizipzor a wiki page is a good idea.

**Comment by Mizipzor** [comment]
@koosemose "sql in c#" is a very good comparison. Look it up, linq is awesome. :)

**Comment by Mizipzor** [comment]
Just checked the [coding conventions](https://msdn.microsoft.com/en-us/library/ff926074.aspx) (search for LINQ) and it looks like the documentation assumes only the former style exists. :P

**Comment by bjubes** [comment]
To keep things simple, is it possible to say that we accept the Microsoft standard but would allow people to deviate in certain ways (linq and if statements with bracket on the same line)? Or is it better to have just one way?

**Comment by vogonistic** [comment]
In my experience deviations leads to people changing things just to make it look better to them, which leads to the other group "fixing" it again. If we have one standard we might be able to test for it in in a CI build and auto-reject PR's that don't follow those rules.

**Comment by Mizipzor** [comment]
Indeed, deviations must be avoided whenever possible! Especially for this project.

**Comment by Mizipzor** [comment]
@bjubes That has been my main argument all along. Dont spend times on this just pick one well defined set of rules and stick to that. In the contribution file we link to the Microsoft style and list one deviation. Now, there might be more deviations added to that list, even though I dont like it. I'm currently experimenting with listing the entire Microsoft style in brevity, with our deviations included. But it's getting rather long. :/

**Comment by Grenkin1988** [comment]
Also would be very good to have access modifiers explicitly specified everywhere

**Comment by Mizipzor** [comment]
@vogonistic I missed your last sentence there, its a great point and I couldnt agree more. But for another reason, though auto checking pull requests is great. I argue that if your rule is not so well defined that it can be expressed in code, then its not clear enough and open to interpretation and should be changed.

**Comment by vogonistic** [comment]
@Mizipzor We can test case, whitespace, indentation and case in automagically, but we are never going to be able to test if something is described well, but getting some automatic testing is great and then we are just going to have to have code reviews to catch the rest, like we are trying now.

The further this discussion goes, I'm starting to agree that we should avoid deviations if possible.

@Mizipzor What are the current deviations that have been discussed other than the underscore prefix, that I personally don't like much.

**Comment by Grenkin1988** [comment]
How about for private filelds use PascalCasing as for propertiels.
And for fields backing properties use PascalCasing starting with v
```
private int PrivateField;

public int Property { get { return vProperty; } }
private int vProperty;
```
I have such standart at work :-)

**Comment by behindcurtain3** [comment]
@vogonistic The deviations so far are I think: underscore prefix, not using `var` and possibly LINQ method calls.

**Comment by Mizipzor** [comment]
@Grenkin1988 No, that prefix indicates that its a special type of field, as compared to a regular field. This is a case of hungarian notation which is prohibited by the Microsoft standard.

You also open up a can of worms of definitions. What if I use that field for more stuff, like a method that doubles it and returns it. When does the field stop being _only_ a backing field? Or, should this syntax be used for _any_ field that is returned by any property?

This becomes especially bad for this project as its targeted towards beginners. Suddenly you cant just create a field. Depending on how to field is going to be _used_ you must name it differently. And suddenly you have to understand how properties relates to fields and all the definitions I mentioned above.

Any benefit you would gain by doing this is by far outweighed by the problems it causes. And, does it _really_ matter if a field is a backing field? Cant we just declare that a field is a field and omit this rule entirely?

For the record, where I work we use `m_` prefix for private field and `s_` for static fields. No public fields allowed. I dont like that either, but at least I dont have to look at the rest of the class to figure out how the field should be named.

**Comment by Grenkin1988** [comment]
@Mizipzor Actually the reason for v- in front of backing fields is just because without it you backing field would have the same name as it's property. (If use PascalCasing for private fields)

**Comment by Mizipzor** [comment]
Ah, I missed that. I was so dead set on using the lower case for fields. I was so sure that that also was the Microsoft standard but I looked it up:

> Names of Fields
> The field-naming guidelines apply to static public and protected fields. Internal and private fields are not covered by guidelines, and public or protected instance fields are not allowed by the member design guidelines.
> ✓ DO use PascalCasing in field names.
> ✓ DO name fields using a noun, noun phrase, or adjective.
> X DO NOT use a prefix for field names.
> For example, do not use "g_" or "s_" to indicate static fields.

I dont know why it only addresses public and protected fields. But I agree they should be in PascalCase. We might want to clarify this to include private fields.

We also see that prefixes are, again, explicitly forbidden.

**Comment by Grenkin1988** [comment]
@Mizipzor But as I said, without prefix property and its back field would have same names :-)

**Comment by WardBenjamin** [comment]
Note that this says "internal and private fields are not covered by guidelines" so we need our own interpretation. for private fields, whether they "back" a public Property or not, I suggest prefixing with an underscore like @lameox suggested earlier. PascalCasing is good for public interfaces, though.

**Comment by Mizipzor** [comment]
Only if it is a public field. And its true, a public field is pretty much indistinguishable from a property. I dont know why they choose to simply omit rules for private fields. To me its obvious that it matches the property name but first character in lower case. But I suppose according to Microsoft we can choose whatever we want. Maybe it's even up to whoever made the class (though I disagree with this). 

As long as no prefix is used.

**Comment by Mizipzor** [comment]
@WardBenjamin it also says not to use prefixes.

**Comment by WardBenjamin** [comment]
While it does say not to use prefixes, it does say that private fields aren't covered by these rules. We basically have to come up with our own rules for them. It's up for debate :stuck_out_tongue:

**Comment by Mizipzor** [comment]
And you dont think basing the name on something as flimsy as whether the field is a backing field or not is a good idea? To me its obvious that a field will become or stop being a backing field in a pull request and the name is forgotten to be updated. Because to know who probably have to look at the rest of the class. Which is why is troublesome to enforce. Not to mention if we would want to automate that check.

**Comment by WardBenjamin** [comment]
I think that's not a good idea, but I do think that *all* private fields should be prefixed like that.

**Comment by vogonistic** [comment]
Didn't Quill use lowercase (I mean `camelCase`) names for internal variables and `PascalCase` for public ones? Can't we just stick to that and drop the prefix discussion?

**Comment by Mizipzor** [comment]
@WardBenjamin At least prefixing _every_ private field is a more rigid rule. :)

**Comment by Grenkin1988** [comment]
@vogonistic No, he use camelCase for everything except Properties.

**Comment by Mizipzor** [comment]
@vogonistic We could, yes. I'm probably one of the few that find this interesting to discuss. :)

The problem with not having a style clearly stated somewhere (anywhere) leads to people suggesting a change in style like [this](https://github.com/TeamPorcupine/ProjectPorcupine/pull/248).

**Comment by behindcurtain3** [comment]
We could go back and forth on prefixes forever. I think what we have in the CONTRIBUTING.md example is good (not perfect but no one will ever agree 100%). It does go against the standard by using prefix but that does have some benefit as well. And there is nothing to say we can't have our own standard modified from Microsoft's.

**Comment by Grenkin1988** [comment]
@behindcurtain3 
>  And there is nothing to say we can't have our own standard modified from Microsoft's.

Actually we can :-)  But we do not have time to agree on all cases.

**Comment by Mizipzor** [comment]
It's true that we should aim at ending this discussion and settle on something. Preferably an existing style with as few deviations as possible. However, a lot of the back and forth in here has been regarding interpretations of the Microsoft style. And if the rules arent clear, whos interpretation wins? 

I think I want to again suggest relying on StyleCop, it does claim it enforces the official Microsoft style. The awesome thing here is that there is absolutely no room for interpretation. You run the tool on your file and you know instantly if its good or not.

If we want to deviate from that style it would be a matter of enabling or disabling certain rules. Which is obviously a much easier discussion to have rather than trying to decide how, why and to what extent we should deviate.

Not to mention that checking the style is automatic. It is excellent for this project since it's aimed at beginners. They can sit on their own and almost brute force the style and until their code is accepted. And dont feel the rejection when the pull request is not accepted because we don't like how it looks.

**Comment by vogonistic** [comment]
This looks like the discussion ended, reopen if relevant.
