### ISSUE TITLE
List MonoDevelop/Visual Studio settings to produce compatible code

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#20]
This came up in PR #19 and should probably go in CONTRIBUTING.md

**Comment by jokoho48** [comment]
Tabs are horrible for github and Tools because every device and tool show tabs in a different way. the most common way to dont get in this issue is using 4 spaces for 1 tab. all teams i work with commit to this "rule"

**Comment by quill18** [comment]
Yup yup -- I'm actually just looking at what happens if MonoDevelop gets reset to default and how closely that parses with the most referenced style guide (https://msdn.microsoft.com/en-us/library/ff926074.aspx), which does suggest have "tabs" map to 4 spaces.

**Comment by quill18** [comment]
Looking to standardize on this (which should be the default in Visual Studios as well):

![screen shot 2016-08-16 at 8 03 22 pm](https://cloud.githubusercontent.com/assets/777633/17719999/920fb534-63ec-11e6-8903-3725f2cd05b0.png)
![screen shot 2016-08-16 at 8 03 36 pm](https://cloud.githubusercontent.com/assets/777633/17719998/920cff6a-63ec-11e6-8f76-0ac7a5fa0c9d.png)

**Comment by quill18** [comment]
Comment now or forever hold your peace. :)

**Comment by vogonistic** [comment]
👍  on converting tabs to 4 spaces.

**Comment by quill18** [comment]
For the record, I still think having braces on the line AFTER the if statement is as ugly as sin.  But I like standards.

**Comment by Dormanil** [comment]
Can we, unlike the referenced style guide, keep strong explicit typing? 

I personally find `var` horribly confusing, especially when it's not about string literals or integer literals.

**Comment by quill18** [comment]
@Dormanil Where's the "million times THIS" upvote on Github?  I agree -- explicit typing adds a LOT to clarity. Doubly so on group projects.

**Comment by vogonistic** [comment]
So the rules so far:
* Microsoft Visual Studio settings
* Convert tabs to spaces, 4 spaces per tab
* Strong explicit typing

I would also add something like this:

If uncertain, follow these guidelines:
* Make your code look like it fits with the code around it
* Make sure you review your diff before creating a pull request

**Comment by svmnotn** [comment]
Any guidelines on whether commits should be squished for a PR?

**Comment by quill18** [comment]
@svmnotn I have forced squashing setup for pulls into the main repo.  If anyone has a strong reason why this should not be, let me know, but it seems to produce a much nicer history -- and individual little commit messages can remain present in the description.

**Comment by vogonistic** [comment]
I vote squash and rebase before creating a PR.

**Comment by svmnotn** [comment]
@quill18 I did not know that github had added that... so nice. I totally agree as my question was made in reference to squashed commits being just generally nicer on the history (Although I do prefer slightly larger amounts of commits if what is being merged is on the scale of a whole sub-system).

**Comment by quill18** [comment]
Please sanity check https://github.com/TeamPorcupine/ProjectPorcupine/pull/24

**Comment by vogonistic** [comment]
I'm not a fan of forcing all opening braces `{` on a new line, otherwise it looks good to me.

**Comment by Dormanil** [comment]
Well, having the MonoDevelop C# coding policy be Visual Studio-style forces opening braces on a new line. 

I personally prefer it that way actually, so a vote seems like a smart idea to me here.

**Comment by SquareMan** [comment]
I would also like to vote for keeping opening braces { on the same line just because it reduces the number of unneeded lines in the files. It makes it a bit easier to scroll through and see important stuff.

**Comment by Dormanil** [comment]
So three in favour of opening braces `{` in the same line to one in favour of putting it in a new line, if I am counting correctly?

**Comment by quill18** [comment]
I'm a fan of it too, but it's a pain to say "Visual Studio Default except for 10+ spots where you have to configure your editor to use the same line braces for if, namespace, class, etc..."

It's a lot simpler and less error-prone to tell people to use one simple setting ("Microsoft Visual Studio" default).

If only this were the sort of situations where editor settings could be included in the git repo. :(

**Comment by quill18** [comment]
On the other hand, what if we say "K&R style", but with "Convert tabs to 4 spaces".

That's kind of what we're going for.

**Comment by quill18** [comment]
![screen shot 2016-08-16 at 9 07 49 pm](https://cloud.githubusercontent.com/assets/777633/17721096/86f76a30-63f5-11e6-85db-c9341585b16c.png)
![screen shot 2016-08-16 at 9 07 55 pm](https://cloud.githubusercontent.com/assets/777633/17721097/86f98b8a-63f5-11e6-82f3-9e1cb26d32db.png)

**Comment by SquareMan** [comment]
Not sure if I understand those screenshots correctly, wans't to the point TO put the braces on the same line?

**Comment by quill18** [comment]
Switching to K&R changes it for ifs.  Nothing else, apparently.

**Comment by SquareMan** [comment]
I'd rather it be consistent throughout than have a jumbled mess. Visual Studio policy for ease of use it is then i guess.

**Comment by Dormanil** [comment]
It also changes a bunch of other stuff, like `Unix/Mac` line endings, not `Native` like in Visual Studio's and `120 columns` instead of `80 columns` desired text width.

**Comment by quill18** [comment]
I'm just going to go with Visual Studio for now, which will help deal with people who develop in VS.  Git itself should be responsible for sanitizing line endings for your platform.

**Comment by vogonistic** [comment]
Have you guys ever tried if it's worth sharing custom policies? I've never tried it since I'm new to Unity, but it seems like we might be able to force the policy we want on anyone who edits with Mono Develop.

There is a menu item called `Custom Policies...`. If you create a new policy, edit the source options and then export it to the project, it seems to make this change to `ProjectPorcupine.sln`, which is currently not in the project.

```diff
+       GlobalSection(MonoDevelopProperties) = preSolution
+               Policies = $0
+               $0.CSharpFormattingPolicy = $1
+               $1.IndentSwitchBody = True
+               $1.BeforeMethodDeclarationParentheses = False
+               $1.BeforeMethodCallParentheses = False
+               $1.BeforeConstructorDeclarationParentheses = False
+               $1.NewLineBeforeConstructorInitializerColon = NewLine
+               $1.NewLineAfterConstructorInitializerColon = SameLine
+               $1.BeforeDelegateDeclarationParentheses = False
+               $1.NewParentheses = False
+               $1.SpacesBeforeBrackets = False
+               $1.inheritsSet = Mono
+               $1.inheritsScope = text/x-csharp
+               $1.scope = text/x-csharp
+               $0.TextStylePolicy = $2
+               $2.FileWidth = 120
+               $2.EolMarker = Unix
+               $2.inheritsSet = VisualStudio
+               $2.inheritsScope = text/plain
+               $2.scope = text/x-csharp
```

**Comment by vogonistic** [comment]
I don't know what the side effects of adding `ProjectPorcupine.sln` is, or if there are other unintended side effects with this. Just wanted to put it on the table since it might remove the need for the statistically most likely first comment on most PR's. (Please fix the indentation, braces, ...)

**Comment by henninglive** [comment]
We also need to find standardized style for XML and Lua. Indentation is currently a problem, we currently using a mix of spaces and tabs.

**Comment by Mizipzor** [comment]
> @quill18 I have forced squashing setup for pulls into the main repo [...] it seems to produce a much nicer history.

Can we reopen this? The above wasn't really discussed and hasn't been enforced in the recent merges. I agree on this, the history becomes much, much cleaner. Need help documenting or explaining rebasing? I can help.
