### ISSUE TITLE
Character always tries to haul first item stack defined in lua

### ISSUE THREAD

**Issue by Ceddini** [TeamPorcupine/ProjectPorcupine#205]
I added my own resource just for fun and saw that it doens't pick up my resource after the character created it's first full stack. Then I changed the order for the item filter in lua to have my own item at the beginning. That worked, but now it doesn't pick up the steel plates!

![lua](https://cloud.githubusercontent.com/assets/21086465/17791920/51b26816-659e-11e6-986b-b38924283292.JPG)
There you can see my initialization of the item filter for the stockpile.

![char-wants-first-resource](https://cloud.githubusercontent.com/assets/21086465/17791935/61fd4e02-659e-11e6-936b-7aa3f7a995c9.JPG)
Here is an image of him/her just standing around doing absolutely nothing.

![char-stops-at-first-resource](https://cloud.githubusercontent.com/assets/21086465/17791957/7c48ea1e-659e-11e6-832c-7af762bb39a9.JPG)
That is the console output, which makes me come to the conclusion that he always tries to insert the first item he/she found in the filter and if he/she isn't successful he just tries again.

**Comment by Sommerbo** [comment]
This probably due to the jobs system is very basic.

**Comment by ComputerOverlord** [comment]
Quill needs to add multi-resource support. Or someone else.

**Comment by koosemose** [comment]
The job lies in a combination of Character.cs and Path_AStar.cs. The character only asks for the first item from desired inventory, it needs to ask for all desired inventory, and then Path_AStar, needs to check if any item in that list is in the current space being searched's inventory.

**Comment by vogonistic** [comment]
Is this still an issue?

**Comment by mikejbrown** [comment]
Fixed by #670

**Comment by kd7uiy** [comment]
@vogonistic This issue should be closed.

**Comment by Mizipzor** [comment]
Ha! I'm faster!
