### ISSUE TITLE
NullReferenceException when clicking the "build" button

### ISSUE THREAD

**Issue by jakebacker** [TeamPorcupine/ProjectPorcupine#207]
`NullReferenceException: Object reference not set to an instance of an object
FurnitureBuildMenu.Start () (at Assets/Scripts/UI/FurnitureBuildMenu.cs:34)`

The "Null Reference" seems to be that a TextLocalizer does not exist on the game object when it is trying to be accessed. This prevents the "build" button from working.

**Comment by UnknownSoldier1** [comment]
This issue has already been addressed in #171 , seems to be an issue with Unity versions below 5.4.

**Comment by jakebacker** [comment]
Ok, the name threw me off when I was looking if it was posted already :p
