### ISSUE TITLE
Translation for (something) failed: Key not in dictionary warning is spammed in console

### ISSUE THREAD

**Issue by jakebacker** [TeamPorcupine/ProjectPorcupine#209]
![temp](https://cloud.githubusercontent.com/assets/14339279/17792775/d006a1ce-6570-11e6-9b70-7c9cc043796a.PNG)
This picture should explain it.
Notice the 2086s on the right

**Comment by GamerInspired** [comment]
I got that earlier however when trying to recreate it later, I couldn't. If I remember correctly it was the "floor".

**Comment by jakebacker** [comment]
If I just click on the game screen anywhere, it starts happening

**Comment by NogginBops** [comment]
The line is defined here:
![image](https://cloud.githubusercontent.com/assets/3778357/17793059/ef5c1afc-65a4-11e6-9212-b9072845c499.png)

It's nothing serious, it just spams the crap out of the log...

**Comment by jakebacker** [comment]
It _could_ cause slowness in the editor but it is not going to be much slower. Milliseconds if even.

**Comment by svmnotn** [comment]
@jakebacker there is no translation for floor but the CurrentSelection script looks for one

**Comment by quill18** [comment]
My #239 PR added localization for tiles (en_US anyway), which resolves the spam for now. 

I wouldn't just outright remove the logging message. Most likely what should happen is that the warning should be changed to use the new logging ( #185  ) on a low-priority level that won't result in console spam except on the most verbose level.

**Comment by vogonistic** [comment]
Closing in favor of #745
