### ISSUE TITLE
Settings XML file

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#21]
There would be value in writing an XML file to set up a scenario. It could include the world size, required life support settings, etc. It could allow for scenarios, or just be a foundation for setting certain items to be included. 

It might be worth having a separate settings file, for things that aren't likely to change from run to run. Cursor icon would be one such example, I'm sure that others could be derived as well.

**Comment by zwrawr** [comment]
Future key bindings could also be saved in this file #13 , as well as game language etc. 

There wouldn't be any need for these to be edited outside of the game , so playerprefs may be a good solution.

**Comment by frankitox16** [comment]
What about making it an .ini file? Like, that's the purpose of that file extension.

**Comment by kd7uiy** [comment]
I would still have the settings editable. Using an .ini file might be a good idea for that.

For the scenario, I suspect the more versatile XML file would be useful.

**Comment by svmnotn** [comment]
Using .ini is not that great an idea as the format is not well defined, maybe something more like toml, json, or even XML.

**Comment by Sommerbo** [comment]
I would go with xml over an ini-file.  Ini-files are outdated and no native interface exist in C# to access them. While using playerprefs is easy it makes editing settings outside the game difficult as you have to access the registry. And editing the settings might be crucial if for instance the game doesn't launch properly.

**Comment by meisme** [comment]
In issue #25 Quill mentions that we should standardize on a single language for text-based data files, though as of yet it's possible that it will end up being something other than XML. But if the settings are stored as a file it should probably be in whichever format we end up with.

**Comment by vogonistic** [comment]
While it doesn't cover everything yet, there is a settings.xml now from #401
