### ISSUE TITLE
UI Report - issues with localization

### ISSUE THREAD

**Issue by frankitox16** [TeamPorcupine/ProjectPorcupine#212]
So, as I mentioned in #22 I was trying to move the UI to the streaming assets folder... It should end up with something like the attachment, yet there's the issue of the localization scripts (don't want to take apart the great job the guy who implemented that did) so, what should I do? I was thinking on adding the extra tooltips when mouse hovering buttons and using those text files, but I wanted to check if it was allright for everyone.

![The view](https://cloud.githubusercontent.com/assets/15928972/17793118/766df3b4-657b-11e6-8c9b-759a384c5aef.png)
![Folder distribution](https://cloud.githubusercontent.com/assets/15928972/17793123/79caa200-657b-11e6-930e-ee503c3eb2e5.png)

`

**Comment by svmnotn** [comment]
Tool-tips would be the best way to go

**Comment by vogonistic** [comment]
I'm closing based on age and inactivity.
