### ISSUE TITLE
Enemies / Catastrophes ?

### ISSUE THREAD

**Issue by amensch00** [TeamPorcupine/ProjectPorcupine#213]
As of there is no official Feature Plan for this game, I suggest adding
Meteoroids into the game. Possible ideas for Meteoroids:

- Resources / Rare Minerals
- Catastrophes (?)

Any suggestions / ideas to add to it ? Is it too early to implement it ?

**Comment by BeefEX** [comment]
In my opinion it is tooo early to implementing stuff like this.

**Comment by NogginBops** [comment]
I think that it's a good idea to think about. I mean it has to be thought about sometime anyway. Though I do think that that discussion should be around a general roadmap for the project at the moment.

**Comment by bjubes** [comment]
I think this is a good idea but hard to implement not code wise but because we currently don't have enough "game" to implement a catastrophe. For example what would happen? The mining drone would explode(no fire implemented yet), no players would take damage(health is in its infancy or still In a PR) and then you would have to build another, which currently costs no materials

**Comment by NogginBops** [comment]
#175 already contains asteroids.

**Comment by BeefEX** [comment]
@bjubes health is in PR by me :D

**Comment by relinu** [comment]
There aren't many ressources atm (so the only thing meteors would drop are metal plates ) and atleast there should be mining

**Comment by vogonistic** [comment]
I don't think it's to early to talk about what it could mean. We have PRs for health, gas leaks and asteroids. 

Maybe someone needs to write a PR that allows furniture to start burning and eat up the O2 in the air, but it would also have to include mitigation, which is probably just creating a job. I wouldn't spend too much time on prioritization until we have a better job system figured out.

Another PR would be being hit with a meteor that punches a hole in an outside wall. It would add an air leak to the wall until it's fixed which would be a new job.

**Comment by relinu** [comment]
I thing there should be a eventsystem, events are declared in xml and could have a lua script which could be executed if certain requirements are meet

**Comment by BeefEX** [comment]
Very nice idea, I would work on that but I have work right now, but I can do it after I finish my current work.

**Comment by koosemose** [comment]
Another important question that this brings up, is if events such as these will be purely text describing what has happened, and then showing the result, or would the player actually see it happening. For example with a meteor strike, would there just be a popup saying it happened and then they see a section of wall with a leak, or would they actually see something zooming in and hitting.

It may not be the same for all events, the meteor, one could argue would be too fast to actually see anything, but other slower paced events might be different, such as traders or new crewmates, if they just spawn at the nearest airlock, float in from offscreen, or there is an actual graphic of a little shuttle coming in and dropping them off, similarly with any kind of pirates/raiders, do they have a ship or do they float in from off-screen?

**Comment by relinu** [comment]
@BeefEX hav you already started working on it? or are you still working on animations?

**Comment by BeefEX** [comment]
@relinu still working on animations, i am stuck on some problems :/

**Comment by NogginBops** [comment]
@BeefEX I will be available in a few minutes if you want any help or tips.

**Comment by BeefEX** [comment]
@NogginBops posted issue #265

**Comment by relinu** [comment]
Didn't know what to do so I implemented the eventsystem myself ^^' Hope it's ok  #270

**Comment by BeefEX** [comment]
@relinu why it wouldt be :D

**Comment by vogonistic** [comment]
Do we keep this issue open for discussions or close it?

**Comment by kd7uiy** [comment]
I vote for keeping this one open for now.

**Comment by Ohda** [comment]
I'd like to see the attack of the space procupine invaders before dying

**Comment by sboigelot** [comment]
We can probably close this issue as the discussion moved to #1070

**Comment by vogonistic** [comment]
I don't think those are the same discussion since this one is on dangers. Did you tag the right issue?

**Comment by sboigelot** [comment]
@vogonistic hem this is a confusing one: the title is about Enemies and danger but the description is about meteroids and raw resources.

The next line is just a suggestion:
@kd7uiy you should probably spawn a new issue about danger and risk in space instead of this one. I feel this issue is too wide and the discussion already split in 2 directions.

I'm open to keep it open, but I would rather close it and create more focus discussion on the 2 different topics.

**Comment by vogonistic** [comment]
I can close this if you or someone else open a new one, @sboigelot.

**Comment by sboigelot** [comment]
@vogonistic no prob, I will do one if @kd7uiy doesn't have time. I would still prefer him to do it has he is far better at that kind of description then I am. Let's leave him a day or two to react. I'll keep an eye on this issue and take action if nothing happens. (I poked him on discord)

**Comment by sboigelot** [comment]
@vogonistic #1098 is up, we can close this issue. Thanks @kd7uiy
