### ISSUE TITLE
Comments , specifically XML Documentation Comments

### ISSUE THREAD

**Issue by zwrawr** [TeamPorcupine/ProjectPorcupine#214]
There is currently some use of this within the existing comments, especially use of 'summary'
Using this would help us generate documentation in the future. I think it would be useful to add summary , param and returns to all public functions.
  
*See [Recommended Tags for Documentation Comments (C# Programming Guide)](https://msdn.microsoft.com/en-us/library/5ast78ax.aspx) and [How to: Use the XML Documentation Features (C# Programming Guide)](https://msdn.microsoft.com/en-us/library/z04awywx.aspx) for details on XML Documentation*

**Comment by BeefEX** [comment]
We should use this, after few months without this, it would be total mess.

**Comment by bjubes** [comment]
I agree, especially with more and more people adding their own code. its important to have some way to document what has changed so that if someone doesn't watch the project for two days they aren't left 100% clueless.

**Comment by Sommerbo** [comment]
Good comments are essential. And triple slash just above functions generate outline that is easy to fill in and is then used by intellisense, at least in Visual Studio.

And with this many programmers each programmer must comment their code or else as BeefEX says it will be a total mess.

**Comment by BeefEX** [comment]
I will do this for sure :D

**Comment by Sommerbo** [comment]
Someone (Quill18?) should go through the existing code and summary/descriptions for all existing functions. Quill18 is the original programmer and as such he should do it, but  since we have the videos I am guessing almost anyone could do it. Maybe by checking out a single file at a time to break up the job into smaller chunks.

**Comment by zwrawr** [comment]
@quill18 has enough to do , I guess a few people could each take one of the scripts folders and work their way threw them.

**Comment by quill18** [comment]
My **plan** is to add a summary comment to everything -- I did it on Character.cs while we were deciding on a coding standard.

Now...when I will actually find the time to do that is anyone's guess.  The last three days have been very focused here on Github.  I **need** to spend Friday recording videos (Prison Architect & a tutorial for quill18creates), and Saturday & Sunday are heavily committed to livestreaming.

Zero complaints if someone else takes on the task.

**Comment by Mizipzor** [comment]
I specifically disabled the "method must be documented" rule in StyleCop. I thought we didnt want that. I can re-add it, but it tends to generate a lot of bogus comments since some methods are trivial and its hard to come up with documentation that isnt obvious.

**Comment by sboigelot** [comment]
We can probably close this issue as the discussion continue in 601
