### ISSUE TITLE
Problems with searching for inventory to fulfill Job

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#246]
I'm not entirely sure if this is something recent, or if it only recently became obvious due to the Asteroids PR adding widely spread out plates so it becomes obvious over the long trip, but currently it appears that the Character never recognizes that he already has a path to a tile that contains the inventory that the Job wants, causing a new Path to be generated every frame, and it the slowdown from Pathfinding becomes very obvious.

The problem seems to rely on line 269 of Character.cs:
`if (pathAStar != null && pathAStar.EndTile() != null && pathAStar.EndTile().inventory != null && (pathAStar.EndTile().furniture != null && !(myJob.canTakeFromStockpile == false && pathAStar.EndTile().furniture.IsStockpile() == true)) && pathAStar.EndTile().inventory.objectType == desired.objectType)`
it seems to always return false, I'm currently trying to sort out and figure at what point it fails but that's a very complex conditional, and I'm slightly worried I'll misparse something and bork something else up.

**Comment by koosemose** [comment]
I think I have it sorted out, but it seems to make it all the more convoluted, and I'd appreciate if someone could check my work before I make a PR out of it. 

The problem is that if it's not picking up from a furniture (i.e. a stockpile) then this will return false, and get a new path, which takes a while if it's far. What I've got for now is:
`if (pathAStar != null && pathAStar.EndTile() != null && pathAStar.EndTile().inventory != null && ((pathAStar.EndTile().furniture != null && !(myJob.canTakeFromStockpile == false && pathAStar.EndTile().furniture.IsStockpile() == true)) ||( pathAStar.EndTile().furniture == null && pathAStar.EndTile().inventory.objectType == desired.objectType)))`

**Comment by vogonistic** [comment]
Maybe break it out into a couple of different variables?

```cs
bool hasPath = pathAStar != null && pathAStar.EndTile() != null && pathAStar.EndTile().inventory != null;
bool allowedToTakeFromPathTile = ...
...

if (hasPath && allowedToTakeFromPathTile && ...) {
```

**Comment by vogonistic** [comment]
Make sure you add the new null checks, since they were implied in the long if statement. Now you have to do it in each one.

Another option is to add line breaks and comments
```cs
if (
    // Check that we have an end tile and that it has content.
    pathAStar != null && pathAStar.EndTile() != null && pathAStar.EndTile().inventory != null &&
    // Check if it is a stockpile and we are allowed to grab from it
    !(myJob.canTakeFromStockpile == false && pathAStar.EndTile().furniture != null && pathAStar.EndTile().furniture.IsStockpile() == true)
    ....
```

**Comment by koosemose** [comment]
Yeah, I think for now the commented version would be best... maybe. But I think the entire CheckForJobMaterials method might need a cleanup, the entire thing feels convoluted and confusing, at least minimizing nested If/Elses, and perhaps going so far as breaking each part of the check out into separate functions.

**Comment by koosemose** [comment]
Ugh, no wait, my initial idea has an issue, in that it will return true if it's a stockpile and it can take from stockpiles regardless of what's actually in it.

**Comment by koosemose** [comment]
Alright that looks to sort it out, and now picking up all the plates from the asteroids is a lot less painful.

**Comment by WardBenjamin** [comment]
I did like @vogonistic's idea of breaking it out into multiple variables to make it easier to understand, but the comments do almost as well. Looks great!

**Comment by koosemose** [comment]
Yeah, I feel like the primary benefits in this case of breaking it into variables, is that the variables are basically providing commentary on what each section is doing, so going directly with commenting it seems the most logical to me.

**Comment by Mizipzor** [comment]
@koosemose that is awesome. It's a point i constantly bring up during code reviews at work. if you have this complicated expression that you feel you need to write a comment for, break the expression apart into variables and name the variables so that the intention is clear. Much better than code comments.

**Comment by koosemose** [comment]
@Mizipzor I think you may have misparsed my comment, I did pretty much the exact opposite of that. Though each part (or each thing that I interpret as a separate logical part anyways) is separated on a different line, and commented individually, which I think has the same end result. It's in PR #250 if you want to take a look at what I've done. 

I'm not particularly tied to either particular way of doing it, just so long as it's more understandable, should it need to be debugged later, and of course the actual bug is fixed.

**Comment by Mizipzor** [comment]
@koosemose I see. The reason why I prefer it "my" way is that code comments are far too often forgotten when code is changed. So you end up in a situation where the comments no longer reflect what the code does. The code itself however, like variable names, are much more often considered when making changes.

**Comment by vogonistic** [comment]
The variables are slightly more preferable when you need to update one of the conditions in a complicated way. The second line in particular is going to scare off a lot of people.

**Comment by kd7uiy** [comment]
This issue was resolved, it looks much better. Recommend closing.
