### ISSUE TITLE
Opening the project crashes unity

### ISSUE THREAD

**Issue by jamzam90** [TeamPorcupine/ProjectPorcupine#249]
Trying to open the projects scene crashes unity. Also as anyone else had this issue?
Im using unity version 5.3.4f1

**Comment by BeefEX** [comment]
try updating to 5.4

**Comment by NogginBops** [comment]
It's 5.4 that does not have backwards compatible prefabs. Try updating should solve the issue.

**Comment by jamzam90** [comment]
Unity is saying no updates availble as well

**Comment by NogginBops** [comment]
Unity3d.com Try downloading the latest version from here. The in editor updater is buggy.

**Comment by relinu** [comment]
Thats a Unity Bug there is a neuer Version 5.4f3

**Comment by jamzam90** [comment]
Does the 5.4 update screw with older projects any?

**Comment by NogginBops** [comment]
All old unity projects should work fine in 5.4 though the prefabs may become unusable in 5.3

**Comment by jamzam90** [comment]
And now the download wait begins.
