### ISSUE TITLE
Discussion: C# Version

### ISSUE THREAD

**Issue by Grenkin1988** [TeamPorcupine/ProjectPorcupine#252]
What C# version is allowed to use?
C# 6.0, 5.0 ?

**Comment by UnknownSoldier1** [comment]
C# 4.0

**Comment by henninglive** [comment]
Unity uses an old version of Mono runtime which is based on .net3.5. Newer C# language features are therefore not supported in Unity. The C# version in Unity somewhere in between 3.0 and 4.0.

**Comment by Grenkin1988** [comment]
Than this should be included in Contributing somewhere.

**Comment by Mizipzor** [comment]
Don't confuse the C# version with the Framework version, here's a [list on stackoverflow](http://stackoverflow.com/a/247623/56763).

**Comment by Grenkin1988** [comment]
I am asking specifically about C# version not .NET version

**Comment by NogginBops** [comment]
The C# version and .Net version is defined by the unity version so I think it's implicit.

**Comment by henninglive** [comment]
@Mizipzor yes i know. The C# version is determined by the compiler version. The compiler in Unity is outdated and from the .net3.5 era. Therefore you can only C# language features from same era. approximately C# 3.0 - 4.0.

**Comment by Mizipzor** [comment]
Though MonoDevelop includes more recent frameworks. I tried changing to 4.5, recompiled and ran the game in Unity. It worked fine. Is it possible to run with another framework than the one Unity defaults to?

**Comment by WardBenjamin** [comment]
So here's how Unity works with newer C# versions:

As long as your code can be compiled to .NET 3.5, you can use any compiler, because language version is mainly independent from the runtime version. This includes the compiler bundled with VS as well as Mono, which is bundled with MonoDevelop and Xamarin Studio (I would highly, highly, highly, highly (okay that's enough) recommend using Visual Studio). 

Basically, this means that if we were to use Microsoft Roslyn, for example, we could use C# 6.0 features (except for Caller Information, but that should be one of the few exceptions), and any other compiler that supports newer C# features can definitely take advantage of a newer language version as well.

I'd support using C# 4, but the newer the version the better in my opinion, though the downside is that it might need some configuration per IDE.

**Comment by henninglive** [comment]
Shouldn't we use compiler bundled with unity. We don't want to force people to install another compiler to build the project.

**Comment by Grenkin1988** [comment]
As I remember when you install Unity it asks you whether you want to install Visual Studio

**Comment by henninglive** [comment]
What about mac and linux? The Visual Studio compiler is not available there.

**Comment by Grenkin1988** [comment]
Do not use Mac :-)
But than we need to use C#4.0 ?

**Comment by henninglive** [comment]
Take a look at [this summary](http://forum.unity3d.com/threads/unity-c-3-5-or-2-0-net-unityscript-mono-clr-cil-and-assemblies-explained.343450) on the Unity forum. They conclude with C# 3.5 if you use the Unity compiler and partial C# 6.0 if you use the Visual Studio compiler.

**Comment by Mizipzor** [comment]
I vote for using the latest and shiniest. ^^ Even if there would be a manual step you take when setting your environment up, its worth it. Especially as we already have a manual step, where you in MonoDevelop set the code style to Visual Studio style.

**Comment by NogginBops** [comment]
What would be gained by switching compiler? It's just going to create a lot of issues with incorrect setups.

**Comment by henninglive** [comment]
@NogginBops the [newer C# language features](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)#C.23_4.0).

**Comment by NogginBops** [comment]
I'm aware but I don't think that these features are worth the trade-off.

**Comment by henninglive** [comment]
Using Visual Studio compiler the will prevent the project being built on Mac or Linux and using it will only allow use language features that compile down to CLR 2.0 since the runtime only supports CLR 2.0.

**Comment by Grenkin1988** [comment]
@henninglive You are saying that we are not allowed to use Visual Studio at all?

**Comment by henninglive** [comment]
@Grenkin1988 no, use whatever text editor or IDE you like, but we should not change the default compiler in unity.

**Comment by WardBenjamin** [comment]
On Mac or Linux, you would use the latest version of Mono instead of Unity's bundled version, I know Mono supports at least most C# 6 features as well.

**Comment by henninglive** [comment]
@WardBenjamin do you know what C# 6 features that compile down to CLR 2.0. Because we would have to target CLR 2.0 if we want to use the Unity runtime.

**Comment by Grenkin1988** [comment]
@henninglive For example
> For example, C# 6.0's new null-conditional operators and expression bodied functions and properties can be converted to CLR 2.0

**Comment by henninglive** [comment]
@Grenkin1988 yes, but if these are the only features we are gaining, then it is definitely not worth the effort. Also both compiles would have to this.

**Comment by WardBenjamin** [comment]
@henninglive I think pretty much everything other than Caller Information and possibly a few other non-backwards-compatible things should work fine. I don't think *any* compilers fully support that, btw.

To be honest, I think C# 6's properties and nullconditional operators make it totally worth it. Those are both great, simple features that I really like using.

**Comment by Grenkin1988** [comment]
```
// C# 3.5 -> CLR 2.0
public string Name { get; set; }
public string FirstName
{
    get { return Name.Split(' ')[0]; }
}
public string LastName
{
    get { return Name.Split(' ')[1]; }
}
 
// C# 6.0 -> CLR 2.0
// Only works in Unity as a .dll built with Visual Studio 2015 or a roslyn compiler
public string Name {get; set; }
public string FirstName => Name.Split(' ')[0];
public string LastName => Name.Split(' ')[1];
```
This is already a win for readability

And
`int? first = customers?[0].Orders.Count();`
Instead of
```
if(customers!=null && customers.Count !=0 && customers[0]!=null){
 int? first = customers[0].Orders.Count();
}
```

**Comment by henninglive** [comment]
I agree that the language features are really nice, but i still do not think it is worth the effort. It raises the barrier of entry for contributing to the project. Installing and configuring the other compiler might be easy on windows, but we also have to support linux and mac. It might not be as easy there, i don't know. We would also need to add platform specific guides on how to set this up in CONTRIBUTING.md.

**Comment by WardBenjamin** [comment]
> Installing and configuring the other compiler might be easy on windows, but we also have to support linux and mac. 

New versions of Mono both support these features and are fairly easy to install on all three platforms, actually.

**Comment by NogginBops** [comment]
I agree with @henninglive. The barrier that this would create is not worth it. What if we have someone who has only worked with C# in unity. They would not know what the ?. operator means nor how to read it. Plus the setup, it's going to go wrong for a lot of people and they won't know what to do.

**Comment by Grenkin1988** [comment]
> What if we have someone who has only worked with C# in unity.
That would be a great way to leand about new technologies.
This is tutorial as I remember :-)

**Comment by vogonistic** [comment]
What is the requirement for Linux and Mac users to write and run C# 6?

**Comment by WardBenjamin** [comment]
A link for reference: https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/src

**Comment by Kreol-Dev** [comment]
You could just install Unity and use provided IDE (it doesn't force VS on you). Less headache

**Comment by vogonistic** [comment]
I don't think it's worth changing. The tutorial is about building a game, not new C# tech. If @quill18 decides to move to C# 6, he can certainly force the issue. I just don't think it's worth the extra questions, problems and maintenance for community project like this.

Anyone can use any IDE they want, but it needs to work with Unity and MonoDevelop as it ships.

**Comment by quill18** [comment]
"Anyone can use any IDE they want, but it needs to work with Unity and MonoDevelop as it ships."

Exactly.  I myself have played with the mod that makes you able to use C# 6.0 in Unity (for nicer threading), but we are targeting vanilla Unity 5.4 here and it's got to compile in a fresh, unmodified install of that.
