### ISSUE TITLE
Asteroids spawn on top of starting room

### ISSUE THREAD

**Issue by mrDLSable** [TeamPorcupine/ProjectPorcupine#261]
Is this something we should fix or is it working as intended?

![image](https://cloud.githubusercontent.com/assets/1783781/17809388/82816fd2-6616-11e6-9c89-f87e5ec551c7.png)

**Comment by WardBenjamin** [comment]
This is probably something that should be fixed eventually, but I'd rather fix it through making asteroids better (not made out of floor tiles, actual mining, etc) instead of a fix just in the Perlin algorithm that's currently being used.

**Comment by kd7uiy** [comment]
It's probably okay to do this, but it shouldn't put resources inside the wall.

**Comment by vogonistic** [comment]
That's why the ship isn't working very well anymore ;)

**Comment by WardBenjamin** [comment]
This is still an issue

**Comment by mikejbrown** [comment]
Is this still an issue?

**Comment by WardBenjamin** [comment]
Fixed, not perfectly but it works!
