### ISSUE TITLE
Need your ideas on solving a problem

### ISSUE THREAD

**Issue by BeefEX** [TeamPorcupine/ProjectPorcupine#265]
A you maybe know, I am working on the animation system, it will also include rework of XML definitions of images. This rework will allow modder to specify when the sprite will be displayed like this: 
https://github.com/BeefEX/ProjectPorcupine/blob/Animations/Assets/StreamingAssets/Images/Furniture/Door.xml
Where the Atributes are specifyed in the Furniture parameters. Now i am trying to make linkToNeighbour work but after working on it for like 10 hours i am out of ideas. Do you have any ideas on how to do it?

Here is my current code (doesnt work - https://youtu.be/MZ8xcUUSmXg ): https://github.com/BeefEX/ProjectPorcupine/blob/Animations/Assets/Scripts/Controllers/FurnitureSpriteController.cs#L124

**Comment by BeefEX** [comment]
Updated, and learned not to paste XML into comments :D

**Comment by NogginBops** [comment]
I will look at this in  30 minutes when I get home.

**Comment by BeefEX** [comment]
Ok, thanks

**Comment by Mizipzor** [comment]
Youre saying that you try to make it work, but im not sure what its expected to do. What do you want it to do and what does it currently do?

**Comment by BeefEX** [comment]
Look at the video, for what it does now. It is sapposed to connect walls but i dont how to do it now.

**Comment by Mizipzor** [comment]
What the video does looks correct to me. What do you mean by "connecting"?

**Comment by BeefEX** [comment]
I ma talking about texture and those arent correct in video, i am sure the system for getting them is correct, i just need the function to update furnParametres.

**Comment by NogginBops** [comment]
@BeefEX to try and understand your problem I first need to know what changes you have made and what your plan for this feature looks like.

**Comment by BeefEX** [comment]
Take a look at this branch: https://github.com/BeefEX/ProjectPorcupine/tree/Animations
I will be offline for next two days an will finish it later. The system for txtures is finished now i only need the waals to update propely whitch i cant work out.

**Comment by NogginBops** [comment]
@BeefEX I think it could be the min and max in the attributes. Shouldn't it go from min=0 to max=1. A float is by default a zero.

**Comment by BeefEX** [comment]
No, it is >= min, but i waill try that.

**Comment by NogginBops** [comment]
@BeefEX I mean that the xml specifies attributs with a min=1 and a  max=1. I think it should be min=0 and max=1

**Comment by BeefEX** [comment]
No, that didnt fix it, even with only counting **value > min** not **value >= min**

**Comment by BeefEX** [comment]
It gave same result as with min="1" max="1"

**Comment by NogginBops** [comment]
I don't quite understand what you are saying. What did you test?

**Comment by BeefEX** [comment]
Min at 0 wouldnt work since it it checks if value >**=** than min it would always be true.

**Comment by relinu** [comment]
Can you test how many elements there are in the metaTable? Because the sprites with only one attribute seem to work.

**Comment by BeefEX** [comment]
i tried that, didnt work, maybe try to fokr that branch, as i said i will be offline now

**Comment by relinu** [comment]
got it

**Comment by vogonistic** [comment]
I think this is fixed. Reopen if I'm wrong.
