### ISSUE TITLE
Fetch dump Fetch dump build

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#269]
We really should set it up so that if the worker doesn't have enough material to do a job, he should keep getting more material until either there is no more material left, or he has enough to build the job. The fetch dump fetch pattern isn't good.

**Comment by WardBenjamin** [comment]
Is this fixed with #293?

**Comment by kd7uiy** [comment]
No, it's not. Here's an image of the problem that I'm seeing. Note that if you can only pick up, say, 3 steel, it'll pick that up, then dump it at the work site, then go back and pick more up. It's all 1 job, so...

![gif](https://cloud.githubusercontent.com/assets/5951269/17821273/cc3d085e-661e-11e6-8868-2f10893a96e4.gif)

**Comment by WardBenjamin** [comment]
That's definitely an issue. This could possibly be fixed by having a special-case "furniture" that would act as a stockpile that could hold all of the resources required for a job, as well as having the player be able to hold multiple items.

**Comment by vogonistic** [comment]
Closing this in favor of the many discussions on Job systems. #86 #726 #732
