### ISSUE TITLE
Change ISelectableInterface to ISelectable

### ISSUE THREAD

**Issue by Dormanil** [TeamPorcupine/ProjectPorcupine#27]
Okay, this is me being very nitpicky, but oh well... 

I noticed that again after having seen the changes in PR #24. Why does our interface end with "Interface"? Interfaces in C# start with a capital `I` and generally are an adjective ending with `-able`. There should be no need to write "Interface" at the end of the interface, right?

**Comment by SquareMan** [comment]
100% percent agree. I knew wasn't the only one who absolutely hated when quill named that on screen. I understand the need for clarity, but really, thats what the 'I' is for.

**Comment by misspellted** [comment]
Actually, the adjective-ness of the interface name feels like it self-defines as an interface, but that's my internal Java developer talking...

**Comment by quill18** [comment]
Completely agree.  Doing it now.
