### ISSUE TITLE
Pending door replacing pending wall [Easy]

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#272]
A door should be able to replace a pending wall as an object to be built. We can replace an existing wall, why not a wall?

Also, a door shouldn't be free. An upgrade of a door to a wall should cost less than a straight wall, but in general a door should cost more than a wall.

**Comment by vogonistic** [comment]
Is this still the case?

**Comment by kd7uiy** [comment]
I haven't had a chance to check it recently.

**Comment by vogonistic** [comment]
It would probably be an easy thing to fix, but someone needs to know that it still happens before we send a beginner off to work on something that is already fixed.

**Comment by kd7uiy** [comment]
Okay, I've just confirmed that this is still an issue. Sorry, I wasn't in a position to get the latest until now...

**Comment by powli** [comment]
It might actually be useful to give the Furniture model a function like
`public bool canReplace(Furniture furn)` or `public bool isReplaceAbleBy(Furniture furn)` instead of what I did...
