### ISSUE TITLE
[Bug] Stockpile doesn't alway fill up

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#274]
Not quite sure what's causing this, but I noticed that the stockpile wasn't completely full, not sure why.

![capture](https://cloud.githubusercontent.com/assets/5951269/17811817/68f01ae2-65f2-11e6-9260-ab26fcc7fa68.PNG)

**Comment by mikejbrown** [comment]
Is this still an issue?

**Comment by kd7uiy** [comment]
Yes, it is. I'm digging in to it a bit now.

**Comment by kd7uiy** [comment]
Never mind, Ice max stack is 10... Closing.
