### ISSUE TITLE
Room stats don't show oxygen levels (Proposal- Indicate items that don't have power somehow)

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#275]
There's no way to status the health of a room, with things like the proper oxygen levels. This should be addressed.

**Comment by bjubes** [comment]
Mousing over a floor tile in a room won't show the O2 in the bottom right?

**Comment by BeefEX** [comment]
I will try to add it? If it doesnt already say it.

**Comment by bjubes** [comment]
Should this be a beginner bug?

**Comment by kd7uiy** [comment]
@bjubes Yes, this is the idea. I think it used to, not sure why it's not working now.

**Comment by emilkris33** [comment]
@kd7uiy build an O2 gen in a room and a Power Station to generating and then it Will show

**Comment by TheRiven** [comment]
yeah, oxygen is currently the only thing needing power as it does not cause any issue if you don't have it (yet!) and can show that the power system is working when you do.

**Comment by kd7uiy** [comment]
Ahhh, didn't realize it required power... Interesting. Will try.

In that case, there should be a visual indicator on the O2 generator that it doesn't have power. Either it should turn red, or have a lightning bolt symbol on it, or something like that.

**Comment by ComputerOverlord** [comment]
@kd7uiy Haha... But, you probably didn't understand how the generator worked.

**Comment by Tritaris** [comment]
I setup a basic system for displaying a power status icon on furniture that consumes power in PR #350 .

![1a](https://cloud.githubusercontent.com/assets/282954/17829536/8e3f551e-667f-11e6-9e3e-1adbc982cf49.png)
![2a](https://cloud.githubusercontent.com/assets/282954/17829537/8e532f3a-667f-11e6-9b44-e046661f21b0.png)

**Comment by WardBenjamin** [comment]
Fixed! Closing!
