### ISSUE TITLE
Pathfinding throws NullReferenceException

### ISSUE THREAD

**Issue by BeefEX** [TeamPorcupine/ProjectPorcupine#278]
This happens, when while building a job, some parts of it get block by building other parts.

NullReferenceException: Object reference not set to an instance of an object
Character.CheckForJobMaterials () (at Assets/Scripts/Models/Character.cs:195)
Character.Update_DoJob (Single deltaTime) (at Assets/Scripts/Models/Character.cs:170)
Character.Update (Single deltaTime) (at Assets/Scripts/Models/Character.cs:443)
World.Update (Single deltaTime) (at Assets/Scripts/Models/World.cs:161)
WorldController.Update () (at Assets/Scripts/Controllers/WorldController.cs:76)

**Comment by kd7uiy** [comment]
I've seen this happen occasionally myself, it'd be good to track this one down.

**Comment by kd7uiy** [comment]
Bottom line, at the location listed, one should add a check to see if it's null before running the check. If it's null, do something sensible. I don't have the time to fix it, but this would be a good easy fix for someone to do.

**Comment by vogonistic** [comment]
I'm pretty sure this has been fixed.
