### ISSUE TITLE
[Bug] Stockpile is too high of a priority

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#282]
Building should always be higher in priority than filling a stockpile. However, I've found if there's an open stockpile, making sure there's something in every tile seems to be higher priority than building something. This should be addressed.

**Comment by koosemose** [comment]
At present there is no actual priority on jobs (filling stockpiles is a job, just as building furniture is), so a job is just added to a queue and when getting a job it just takes the next off of a queue. So if you have 5 stockpiles, each will add a job to the queue, and a furniture to be constructed will have a job on the queue, the exact order that things happen in will affect the order the jobs are done in, but there will be 5 separate jobs for filling stockpiles (1 for each stockpile) that will each take the nearest stack not in a stockpile, to the one job for constructing the furniture. 

Changing this behavior will require a complete overhaul of the jobs system, which does need to happen, however it is a big job and will take time (both for someone willing to tackle it to decide to do so, and possibly for them to actually complete work on it).

**Comment by kd7uiy** [comment]
Fair enough. I've got a few ideas on where to start with the job priority, namely to start with a priority in mind. There's a fair bit of decision when you have otherwise equal priorities that should be addressed. Hmmm...

**Comment by vogonistic** [comment]
An updated job system is discussed in #86

**Comment by kd7uiy** [comment]
Priorities are set up in https://github.com/TeamPorcupine/ProjectPorcupine/pull/293

**Comment by kd7uiy** [comment]
Closed as the Priorities for a job are now pulled in.
