### ISSUE TITLE
Difference between an Airlock and a Door?

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#284]
First of all, an Airlock should be able to replace a Door as it can replace a Wall, assuming an Airlock is a better door.

Next, why the difference at all? What does an Airlock do that a Door doesn't? Just trying to understand.

**Comment by GamerInspired** [comment]
Maybe airlock doors take longer to open so are use where needed; maybe also they can withstand being on the outside wall. Where as a normal may open faster and can't handle being on a outside wall.

**Comment by koosemose** [comment]
I believe a normal door leaks air.

**Comment by kd7uiy** [comment]
A normal door could vent the atmosphere when it is opened in to space. If it opens to another occupied room, then the two room's gas mix. An airlock won't do either. Sound good?

**Comment by koosemose** [comment]
I believe that is what it is programmed to do at present, if it doesn't then there's an issue with it.

**Comment by koosemose** [comment]
Correction: a normal door always leaks, an airlock door only leaks when open. Presumably intended to be used in a proper airlock, a small room with a door on either side, to minimize the gas that escapes. A more proper name might be pressurized door, but airlock door is technically accurate as well, as it is a door meant for an airlock.

**Comment by GamerInspired** [comment]
Would be awesome to see gas pumps later (a lot later) on to pump the gas out of the small rooms (airlocks).

**Comment by koosemose** [comment]
I suspect (I haven't investigated the related code) that might be a trivial addition, quite possibly making use of the same code that currently causes gas to leak through doors, or at least similar (so direction is forced, rather than from higher pressure to lower pressure)

**Comment by GamerInspired** [comment]
Thinking about you maybe correct there, i'm also looking forward to the possibility of having pipe and cables to move gases and electricity round. This would mean you could pipe the gases to specific areas.

**Comment by WardBenjamin** [comment]
Before this is closed, this should probably be recorded somewhere.

**Comment by vogonistic** [comment]
Maybe someone should write an RFC for a Grand System of Gasses, Leaks and Pumping?

**Comment by kd7uiy** [comment]
This should be added to the Wiki, and there are a few thoughts on what to do with an Airlock and a Door. Also, we should be able to replace a door with an Airlock. Do all of this, and this issue can be closed.

**Comment by vogonistic** [comment]
Closing this since we've created two other issues for managing the actions.
