### ISSUE TITLE
Replacing wall bug (Deconstructing an object should be a job)

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#286]
When a wall is replaced with a door, it instantly can be walked through. It also looses it's room containment. That seems like a poor choice.

**Comment by koosemose** [comment]
The only behavior I see is more because the character builds from on top of the door (as with everything else). And at least to me, losing containment when you knock a hole in the wall to put up a door makes sense.

**Comment by kd7uiy** [comment]
Losing containment when you are building the wall makes sense. Loosing containment when you are planning to build a door, but haven't got there yet, doesn't make sense.

**Comment by koosemose** [comment]
But what you are doing is not simply planning to build a door, but deconstruct the wall so you can build a door. This is less clear at present because currently deconstruction happens automatically rather than having to have the character work at it.

**Comment by kd7uiy** [comment]
Deconstructing then should be a job. Hmmm...
