### ISSUE TITLE
[Bug] Wall edge conditions

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#294]
The wall does weird stuff when you build along the edge of the map.

![capture](https://cloud.githubusercontent.com/assets/5951269/17817291/c07e4a90-660b-11e6-8274-13b381ecc088.PNG)

**Comment by vogonistic** [comment]
Probably shouldn't allow building on the last tiles. That would be a good beginner bug fix. I'll write it up.

**Comment by koosemose** [comment]
For others looking at this, as it's not completely clear what's going on from the picture alone, it appears that walls built along the edge don't show a sprite (they still show up in mouseover info), what can be seen in the picture is the walls connecting to the walls with no sprites.

I suspect it has to do with trying to check outside of the map for neighbors.

**Comment by vogonistic** [comment]
Edges of maps are always problematic, best not to let the users build on the very last tile along the edge.

@kd7uiy Would you rather have a go at fixing it before I put it out as a beginner bug?

**Comment by kd7uiy** [comment]
I'm not planning on fixing it.

The edge tile is a wall, but the sprite doesn't show. I would propose putting it as a sprite.
