### ISSUE TITLE
Discussion: overlays and "tile data"

### ISSUE THREAD

**Issue by FilippoLeon** [TeamPorcupine/ProjectPorcupine#295]
I think the project could benefit of having a series of overlays displaying "color maps" (or heat maps) of many variables that depend on tiles:
- display a color map of the oxygen level
- colorize each room separately
- display temperature, if implemented
- display other variables

I've created a branch:
https://github.com/TeamPorcupine/ProjectPorcupine/compare/master...FilippoLeon:overlay
with some dummy code.

If you want to test, you have to add an object and add the script "OverlayMap" to it.

Mandatory picture:
![overlay_example](https://cloud.githubusercontent.com/assets/21125139/17817586/84c578e6-663f-11e6-9603-1d52cdcc2f65.png)

Let me know if there is interest in this.

(I'm also interested in modelling some variable: like temperature, etc... but I'll open another issue)

**Comment by WardBenjamin** [comment]
I was actually just thinking about this, looks awesome. Overlays like oxygen (maybe a generic "gas" one with a dropdown for any other gases?), temperature, and such would be great.

**Comment by koosemose** [comment]
This seems pretty useful, both to in development and gameplay. Though if what's in the picture is rooms, perhaps room 0 shouldn't have an overlay (or rather have a completely transparent color), since the idea is that it's not a room.

**Comment by FilippoLeon** [comment]
Sorry, picture shows oxygen, but is still a bit wonky.

**Comment by koosemose** [comment]
Ah, was just guessing. Do you intend (once you have it dewonked) to make this accessible from in game, or do you intend it to be a developer only thing that one would control through the object or some other method to be used for debugging?

**Comment by WardBenjamin** [comment]
I think this would be a good in-game tool, if refined enough. I think it would be really useful when doing things like planning where oxygen generators or CO2 scrubbers go, or other use cases. This would also be useful if we added gas piping and other stuff.

**Comment by FilippoLeon** [comment]
Also for end-user. 

For instance. Many times I wished that RimWorld had such a feature for the temperature, so that my colonists woldn't burn alive.

**Comment by koosemose** [comment]
Excellent, lots of fun potential uses for this, such as spotting leaks (presumably a part of mapping gas flows). 

Any idea on the feasibility of making this moddable (interact with LUA and/or xml files) so an end-user could mod in their own heatmap for something they're really interested in?

**Comment by FilippoLeon** [comment]
I will proceed with improvements then.

- For now, everybody could interface the overlay by simply setting the member "valueAt" to a lambda function taking as input the coordinates x and y and returning the value u want to display.
- Toggle on and of the overlay simply by "SetActive".

I do not want to mess with the unity scene too much, but it's easy to add a button and a drop down for toggling and selecting the visualization.

I also need to address the problem of setting colors in a visual appealing manner.

**Comment by FilippoLeon** [comment]
Overlay is in a usable state:
https://github.com/TeamPorcupine/ProjectPorcupine/commit/bd19ca14b39a110990af143aed80d3923148cf4b
Warning: This modifies the scene (we need a dropdown menu and a mesh renderer.

Now: Xml/LUA customizable
Overlays: oxygen and room
Colors: jet and random

Room:
![2](https://cloud.githubusercontent.com/assets/21125139/17822434/63fda06c-6657-11e6-991a-7f237b96cb1f.png)

Oxygen:
![3](https://cloud.githubusercontent.com/assets/21125139/17822439/6d9ccc74-6657-11e6-93a8-974f7676be20.png)
![4](https://cloud.githubusercontent.com/assets/21125139/17822440/6db2a5ee-6657-11e6-9219-7d1d14d1de4f.png)
