### ISSUE TITLE
Discussion: temperature modelling

### ISSUE THREAD

**Issue by FilippoLeon** [TeamPorcupine/ProjectPorcupine#298]
I'm interested in writing code managing the temperature in the game. This is linked to my discussion about overlays:
https://github.com/TeamPorcupine/ProjectPorcupine/issues/295

I see two ways to proceed:
- a room-based temperature system, where "heat" flows to adjacent rooms (faster e.g. trough vents), is created by heaters and reduced by refrigerators, etc.
- my favourite: a tile-based realistic Heat equation modelling. I do this things for a living, so I know it will look awesome. Basically (if you know some of this stuff), we solve a heat equation with variable coefficients using a finite-difference discretization. Kinda expensive, but versatile and awesome looking.

What do you think?

PS: also I would like to see if there is interest in modelling some kind of "radiation" system: have a nuclear generator that emits gamma rays and shields, and solar flares and so on.

**Comment by relinu** [comment]
I think a room based one would be enough for this type of game.

**Comment by behindcurtain3** [comment]
A tile based solution would be awesome, imagine having long hallways or large rooms it would take a bit of time to propagate any changes.

**Comment by satch3l** [comment]
If you do this for a living you probably has the best insight into what will work best. So, as far as I'm concerned, I'd let you choose.

**Comment by FilippoLeon** [comment]
Dunno about how much you know about this stuff. But we can do real fancy stuff:
https://en.wikipedia.org/wiki/Heat_equation

The idea is that at each "time update", we have to loop over each tile and update the value of the temperature from its neighbours. Since we use floats and do not require much precision, we can get away with something rather efficient.

**Comment by WardBenjamin** [comment]
I like the tile-based modeling system, and I think it would be cool for heat and radiation. I think we should probably stick with something like the old system for gases, but a high-coefficient version of this system would also work for this if we wanted to consolidate.

**Comment by FilippoLeon** [comment]
If interested, I will work on the branch https://github.com/FilippoLeon/ProjectPorcupine/tree/temperature_system

**Comment by ComputerOverlord** [comment]
We can have a tile-based heat spreads to colder tiles until equalized.

**Comment by abackwood** [comment]
I don't think a tile-specific temperature model is the most appropriate for a game like this. Barring the odd case where a room is so big that there are meaningful temp differences between two parts of it, air was spread pretty quickly through the room anyway.

It sounds like calculating temperature would become computationally expensive, so it should add a proportional amount to gameplay or it's not worth it.

As a middle ground, maybe some offsets from the average room temperature can be added if a tile is near a place where a lot of heat leaves the room or is close to a heat source. That's easier to compute than realistic heat diffusion.

**Comment by sboigelot** [comment]
@FilippoLeon your branch doesn't exist anymore, does it mean you drop the idea?

Should we discuss this further or did we reach a consensus for now?

**Comment by bjubes** [comment]
@sboigelot that branch was merged in #316. Im not sure how temperature is implemented, but i think @FilippoLeon did a lot of the work in that system - #340

**Comment by kd7uiy** [comment]
There are a couple of interesting ways we could do this.

1. Have the entire room a single temperature, raising/lowering as time progresses (Similar to Gas Levels)
2. "Light" model, where a heater's effects are instant in the area they affect.
3. Physics based movement of temperature based on neighbors.

Personally, I think the second option offers a nice compromise between the very complex third model, and the overly simple first one. In my mind, managing heat where the temperature constantly fluctuates approaches a level of micromanagement that I don't think would be fun. Having been in rooms with lots of machinery and knowing that the temperature in those rooms can vary dramatically, and thinking of making a game whose focus isn't temperature management becoming that level of micromanagement seems tedious to me. But maybe I'm the only one.

**Comment by pderuiter77** [comment]
I think a tile based solution with simple equations would work well.
If a tile changes temp, it will signal the neighbours, who wIll update next tick. 
For temp using the average of the 2 tiles would work well enough to start with, no need for complicated stuff yet. If needed we can add a heatTransfer value to a tiletype/furniture

It would add nice effects if you use it for i.e. smoke as well. You could see it grow.

**Comment by Geoffrotism** [comment]
I can/will take this coding section if no one disagrees. My plan that I came up with in the shower:

1.  On new game creation- choose simple or advanced thermodynamics.
---- simple - do something like the single room temperature calculations.
---- advanced - realistic heat flow though walls, doors, etc. with temperature calculated on a per tile basis. 
-------sub option of advanced would be to turn on or off Z-level heat flow
2. rooms which are suddenly exposed to space would have their temperature halved every second until fixed (temporary solution).
3. ignore items such as chairs etc. when determining heat flow.
4. more of a question - thoughts on objects overheating. 

more details to come.

**Comment by vogonistic** [comment]
I have similar concerns here as I have on #1210. If we go a tile based route we might have a lot of tiles that needs to be updated on every tick. If we then add systems for temperature, gasses, smoke and other systems. A lot of base building games like this have a problem that when the base becomes to big or we have too many characters it slows to a crawl.

With that in mind, I'm not if I see a benefit in knowing the temperature or gas pressure on a tile by tile basis. Smoke might be cool, but that's a temporary effect, just like fire.

**Comment by Geoffrotism** [comment]
@vogonistic  I agree that it could be a problem. I honestly don't mind adding in code to cover both cases though. This would give the user the option to use either and would be great for new players as they wouldnt have to be burdened with learning a new game AND dealing with a finicky temperature conundrum.

**Comment by pderuiter77** [comment]
I hear you. Its just that in my mind a room based solution is too coarse :)

We could combine the systems so a dissipationManager handles the task of signaling tikes to update its syatems like heat, gas, fluid, particle, etc

**Comment by vogonistic** [comment]
I'm ok with an implementation that works both ways as long as it doesn't put a big burden on the furniture and things that care about temperature and pressure to work in either method.

**Comment by mikejbrown** [comment]
If you want to go ahead and do it no one can stop you. :grinning: Maybe put it behind a [feature flag](https://stackoverflow.com/questions/7707383/what-is-a-feature-flag) so people can play with both versions for a while and the community can decide what it wants?

**Comment by FilippoLeon** [comment]
I originally implemented this idea a while a go. Then, things came up and I do not have much time to work on this project.

The tile based temperature modelling is there (or was, at least), so is not too expensive to implement, since is silently running since the beginning.

If you would like to use it, that would be great, maybe I have time to help out.

**Comment by jaselito** [comment]
Indeed, the code (including overlay) is still there and it changes the temperature in a per tile basis when a heater is built.  Right now it seems to be limited to the room where the heater is located.

**Comment by FilippoLeon** [comment]
If you decide to keep this system in place: each furniture shoul have a thermal diffusivity parameter.  Walls and doors currently have 0. By tweaking and adding a minuscule amount (0.0001?), if should leak heat across the furniture. 1 is max and 0 is zero transfer.

**Comment by Geoffrotism** [comment]
I am keeping a lot of what you had. It looked pretty good. but I decided to create a temperature property on Tile objects. that way we even display the temperature of a specific tile if we wanted to. also am creating a helper class of sorts that contains all the formulas for convection/ conduction/ radiation. am incorporating thermal changes due to Z lvl temperatures as well. and finally am ignoring things like chairs and such with these calculations. will simulate the space as if it were just air.

**Comment by koosemose** [comment]
Since this has been implemented, it would be best for any discussions on enhancements to the existing system to take place in an issue dedicated to the enhancement (and attract more attention), closing this issue.
