### ISSUE TITLE
[Beginner] Prevent furniture from being built along the edges of the world

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#300]
Currently, you can build walls on the last tiles on the edge of the world, but it leads to a lot of checks for tiles outside the map. One common way to fix this problem is to not let the user target the tiles on the very edge of the map. 

Edit `DEFAULT__IsValidPosition()` in `Assets/Scripts/Models/Furniture.cs` so that it doesn't let the user build or place anything within 5 tiles to the edge.

Pay attention to the rules in [CONTRIBUTING.md](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/CONTRIBUTING.md)

This bug was originally reported in #294

**Comment by lincore81** [comment]
I've never contributed to a project, I hope this qualifies me as a beginner :~)
https://github.com/TeamPorcupine/ProjectPorcupine/pull/314

**Comment by vogonistic** [comment]
@lincore81 That's exactly what the beginner tasks exists for! Welcome to the fold. =)
