### ISSUE TITLE
[Bug, Easy] Allow for upgrading a door to an Airlock.

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#303]
See https://github.com/TeamPorcupine/ProjectPorcupine/issues/284 .

**Comment by vogonistic** [comment]
Beginner tip: Doors can already replace Walls.

**Comment by ComputerOverlord** [comment]
@vogonistic He said Door to Airlock...

**Comment by vogonistic** [comment]
I don't understand your comment @ComputerOverlord. Looks like the commit allows airlocks to replace doors. 

If you are referring to my comment, it was a tip to whoever attempted to work on it. Something to look into.
