### ISSUE TITLE
[Feature] Power Cells

### ISSUE THREAD

**Issue by Xeni91** [TeamPorcupine/ProjectPorcupine#304]
I would like to implement a new furniture and item.
Specifically a Power cell(idea is the name: Plasma Cell) created from steel and plants.
I don't plan to implement plants yet.
I don't want that the generator runs from nothing so my thought was that at least steel is used.
They pick up steel bring it to the Cell Packager and get a cell.
Would like to hear some opinions.

Edit: Maybe at later stages a jetpackish system will be fueled from it.

**Comment by WardBenjamin** [comment]
Alternatively, we could generate some other kind of material on some asteroids (Uranium, Plutonium, something like that) to construct power cells with.

**Comment by Xeni91** [comment]
Yeah but I did not want to start fideling with map generation yet. It is my first C# project. 
I only programm in PHP and thats kinda different

**Comment by WardBenjamin** [comment]
Remember you don't have to be the one to do everything. :grinning: 

Just add the materials and such, and open an issue, and someone else can pick it up if they want!

**Comment by Xeni91** [comment]
Made my start with #319. Opions and tips are welcome

**Comment by Xeni91** [comment]
Feature is merged
