### ISSUE TITLE
[Low Priority] [Discussion] Cosmetic/Graphics Features

### ISSUE THREAD

**Issue by SteelFall** [TeamPorcupine/ProjectPorcupine#305]
I realise that cosmetic features are not really at the top of the priority list but I reckon that adding some these features could be good for beginners.

What sort of cosmetic features should we have? How do we want to execute them? Who is working on anything of this sort?
If you are working on or have a PR for any feature that could be classed as cosmetic just drop a comment here and I will add you to the list. Any more ideas are also welcome

Current PRs:
- Random Character Colours (#266)

Currently being worked on:
- Characters only wear helmet in O2 poor environments (SteelFall)

Ideas:
- Texture/Sprite packs and selection of the latter
- Characters with different sprites

**Comment by SteelFall** [comment]
Also feel free to tell me whether or not the labels in the title need changing.

**Comment by Xeni91** [comment]
Looks good to me but I think the color of the helmet should stay without color

**Comment by SteelFall** [comment]
@Xeni91 Thank you for the feedback. I will try to get that done now. :)

**Comment by vogonistic** [comment]
I feel like soon we will need to be able to switch from a body with a space suite and one without.

**Comment by Xeni91** [comment]
@vogonistic yeah like if the derp walk into an airlock and maybe a wardrope or spacesuit refueling station is there

**Comment by vogonistic** [comment]
@Xeni91 That would be fantastic, but right now it could just be something we switch when O2 gets low in the current room. Just a visual difference.

**Comment by SteelFall** [comment]
@vogonistic Thank you! Adding that to the OP now.

**Comment by SteelFall** [comment]
Looking at the current character sprites, the only change would be the removal of the helmet.

**Comment by Xeni91** [comment]
@SteelFall sounds legit

**Comment by SteelFall** [comment]
Well I started on that helmet removal but starting a PR will have to wait until my other PR gets accepted as I might just use some features used there. Alternatively I might change the name and scope of my current PR.

**Comment by Ceddini** [comment]
@SteelFall I would change your current PR to something like "Character improvements". This helps with the current amount of PRs that Quill has to go through.

**Comment by SteelFall** [comment]
@Ceddini Ok. Then I will also add a [WIP] after I changed the name.
