### ISSUE TITLE
Unable to remove designation of furniture

### ISSUE THREAD

**Issue by neobonde** [TeamPorcupine/ProjectPorcupine#307]
If you accidentally place a bunch of wall designations, you just have to wait till their are done building, loosing all material in the process.

**Comment by kd7uiy** [comment]
This could be fixed by having the destroy furniture option also destroy pending builds. I don't think that's a feature yet.

**Comment by koosemose** [comment]
Would this perhaps be a beginner worthy bugfix?

**Comment by gunthergun** [comment]
#378 --> fixed this :)

**Comment by gunthergun** [comment]
Please close this issue
