### ISSUE TITLE
[Suggestion] Change floor build order to closest first

### ISSUE THREAD

**Issue by itay347** [TeamPorcupine/ProjectPorcupine#308]
When building more than one floor, if you **start dragging** the cursor **far from the character and stop next to him**, **he will walk that whole distance** to the location where you started dragging and then start building.

Here's a gif for example:

![floorbuildorder](https://cloud.githubusercontent.com/assets/15272275/17821034/355c840c-6658-11e6-8b22-158108811a52.gif)

This is obviously a waste of time and **should be changed that the building process will start with the closest floor and continue from there**.

What do you think?

**Comment by kd7uiy** [comment]
The same thing should apply for the walls.

This is even odder when you build the first row outside of the starting room:-)

**Comment by WardBenjamin** [comment]
Arguably, this shouldn't be changed because... what if you *want* him to build things in a certain order. 

HTN as per #86 would solve this case, because "build floor" would be a goal, and each "build floor tile" job's priority could be set by proximity to player.

**Comment by vogonistic** [comment]
@itay347 It's definitely something that doesn't look right, but @WardBenjamin is correct that It's a known issue that will be fixed in #86.

I'm going to close this issue and add a comment on #86.
