### ISSUE TITLE
Implementing a generalized type for furnitures

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#31]
Certain features will need to care about the general type of a furniture, such as the recently committed replaceable furniture, as it stands it requires each specific furniture to be named, which works for now, but in the future, particularly for modding, it can become overly complex, if not completely unworkable. As an example, if a mod implements a new wall type, and a second mod adds a new door type, the new door would presumably list the current wall as something it can replace, but would be unable to replace the modded wall. 

Now if there were a generalized type for furnitures, such as "Wall" or "Door" rather than "Steel Wall' or "Basic Door", then each new wall and door could simply be told that it is a wall or a door, and if one mod adds a wall, it will be typed as a "Wall", and a mod adding a door (or even the vanilla doors) would simply be told that they can replace any furniture that is a "Wall", and it would just work.

It could also be of potential use for other features as well, if one were to implement a feature akin to Rimworld with raiders breaking down doors to get in or possibly even walls, they could be told to break any objects of types "Door" or "Wall" rather than either breaking any furniture in their way, or having to base the decision on the movement cost/passability of a given furniture.

**Comment by vogonistic** [comment]
(I've only watched the first 28 videos, so this might not reflect the current code base)

An alternative way of solving some of this would be to have a deconstruction cost and what the output of deconstruction is. That way, it doesn't matter if you replace a chair with a door, or a wall with a door. If it can be deconstructed, it can be replaced.

There there might be a good argument for a wall type in case we want to group elements in the UI by type, but naming everything that it can replace might be hard to maintain.

**Comment by koosemose** [comment]
The intention of this proposal is to minimize having to list every single object you can replace (and any other future features that may care about what  types of objects they are interacting with), so rather than listing every wall there is (which as I mentioned won't works so well with mods), but rather just the type, so that you would just list "Wall". The replacing furniture code is already in, I'm just proposing a way to make it (and any future features that care about object type) easier to maintain.

And if a limited set of object groups is established that would further ease maintenance related to this feature, for example "Door", "Wall", "Workstation", and "Decoration" would cover a fair number of needs, perhaps "Chair" and "Table" as well so that future AI could be told to try to find a table to eat at, and find a chair around that table to sit on without having to tell the AI every table and chair that there is (which would likely not work well with modded in tables and chairs).

It doesn't have to be a strictly enforced list of types, just the types that the core game makes use of, that a mod maker can be sure will allow the features of the core game to interact with them, and that a  well made mod will make use of, so mods can have a guarantee of what types work with the core game and each other.

**Comment by RodRitter** [comment]
I like that idea. It makes sense for furniture to inherit base types. So that when default behaviours can be changed and updated, all modded stuff still stays intact and less mod updates need to happen.

In your chair example, if we now have to give AI the ability to pick up a chair, we can update the behaviour in the default class/type and there is no need to go to every single chair mod and update it.

**Comment by koosemose** [comment]
Yeah, something like just having basetype or objectgroup tag in the XML (along with appropriate support in the furniture class) is pretty much all I'm talking about. Though it wouldn't add default behaviors to the object, bit rather define how other things interact with it. So rather than typing something as a generator telling it how to generate stuff, it would be letting everything know it's a generator, so, for example, a generator hating NPC would know it's something he wants to destroy. 

Though default behaviors by base type isn't a bad idea, is beyond the scope of what I'm proposing. But it's certainly something that would benefit from having a base type system implemented, so if you tell something is a door, it will just work (but can be overridden for special purpose), and if the way characters and doors interacts changes, the default behaviors can be changed to match and most doors will just work.

**Comment by NogginBops** [comment]
I like the idea of furniture type tagging. Though with default behaviours I think there could be difficulty with standardization and mod conflicts. What if one mod added a definition for a unice furniture type and implemented standard behaviour for that tag. Then another mod did the same thing but their behaviour is differentialekvationer. What do?

Should a furniture be able to have multiple tags assosiated with it? If yes, how do we handle those cases.

**Comment by koosemose** [comment]
Good points on the potential issues on default behaviours, however that's beyond the scope of what I'm currently proposing, and should probably be left for a separate issue, it was my mistake not staying on topic, and clouding the initial idea.

My current intended implementation is that BaseType is one thing, and one thing only. I don't currently see what benefits multiple tags/BaseTypes would bring to the table to counterbalance any potential issues. If there are potential benefits, it would be trivial to change it to have multiple types. If it is changed to allow multiple types at a future time, then we can figure out how to handle it.

At this time, I think it is probably best to start with the simple version, and only make it more complicated if such complication fills some need.

**Comment by lameox** [comment]
I think in terms of weather we should allow multiple tags or not it basically comes down to where you draw the line between "types" and "behaviour attributes".
i.e. does it make sense to have the "door" and every door can only have this one tag? yes.
does it make sense to have a "powered by electricity" tag and assign that to all consumers of electricity? well, i would say yes. As you can see you get into the multiple inheritance question and i think for our use case it really does make sense as the tag "door" is less of a baseType in the ObjectOriented sense and more of a behavioural aspect, i.e. "you can walk through this thing".

I propose the use of a collection of tags, against which certain functions can be implemented. we can maybe also go one step further, and do something like a very rudimentary "type check". This would mean, that a mod can define its own types, and maybe require that a certain attribute also be present on objects that have this tag. i.e. my custom type "explosive" needs to have an attribute "fuse-time". This would guarantee the consumers of those tags, that actually implement the common functionality for all objects of those types to ensure, that everything they get passed has the required values.

This approach would also make it really easy for mods to integrate with each other, as the would just need to implement each others tags, or maybe even use the same ones, and be done with it. from that point on, both mods could use and integrate with each others objects without problems.

What do you guys think?

**Comment by bjubes** [comment]
This would also make the ui much simpler and more dynamic. Imagine if a modder added a titanium door. If they had this system the ui could be set automatically put all the generic "doors" under the same spot in the ui kinda like Rimworld. Then the modder wouldn't have to bother coding a custom button for every furniture item he creates

**Comment by lameox** [comment]
Hadn't even thought about the UI aspect :D

**Comment by ComputerOverlord** [comment]
This is a great idea! And it'd definitely clean up the UI!

**Comment by lameox** [comment]
@koosemose why did you close this?

**Comment by koosemose** [comment]
Because it was implemented. Should I have left it open for purposes of continued discussion on potential uses of the system? Sorry, I've only ever used git for personal projects and am not completely certain on proper protocol in a team environment. Or perhaps I should have linked to this from the PR (which I'm also not entirely certain how to do) so it was clear that it had been implemented from this side?

**Comment by lameox** [comment]
I think at least link to it from the PR, but this could be a good place to keep the discussion going

**Comment by koosemose** [comment]
I'll go ahead and reopen this for any future discussion. Just to make it clear to anyone who comes along, this has been implemented in #42 , I'm not sure how/if I can add a reference to this from the PR itself now that it is merged .

**Comment by lameox** [comment]
If i understand the code in #42 correctly, you went for the single tag per object solution, right?

**Comment by koosemose** [comment]
Yes, as it seemed to most closely represent the intent of representing what it IS, i.e. a Wooden Door IS a door, as is a steel door. Though I suppose, depending on how you look at it, some thing could be multiple things, like a TV IS an electronic device, and IS an entertainment device.

It should be trivial to alter it to use some form of collection, at a glance HashSet or List look fitting, and just check .contains() rather than a comparison, or perhaps a property that handles it (which could be implemented now, and anything that uses it currently (just replaceable furniture to the best of my knowledge), could be changed to use it, then in the future if it is changed to a list, it should be seamless). 

But as is, I'm not certain how much of a benefit it would actually add.

**Comment by lameox** [comment]
well in terms of mod support and interoperability i think we will need multiple tags at one point or another. I see no harm in implementing them now and having a single tag in each hashset. That way we already cover a future use case. What do you think?

**Comment by koosemose** [comment]
Considering future-proofing was one of my primary reasons for doing this in the first place, yeah. My only problem is that I'm stuck in how I initially envisioned it, so have trouble seeing what the broader uses of it would be. Could you offer an example usecase? An idea of how multiples might be used may also help shape it appropriately. 

Also, I'm not sure baseType will continue being an appropriate name. Do you have any ideas that would be more fitting to something that would cover it potentially being multiple things? I'm not that satisfied with baseType in the first place, but the one I found most fitting "objectType" was already taken.

**Comment by lameox** [comment]
Well i think your TV example works. It could have tags like "ConsumesElectricity" which modders could check against to implement the TV as a consumer in their power mod. It would also have something like "Interactable" which would allow another modder to implement a remote that can turn "Interactable" objects on and off. It maybe also has a "InfluencesMorale" tag together with the "MoraleRate" attribute (maybe even "type checked" like i suggested above) which yet another modder could use to implement something like a mood system for rooms.

**Comment by lameox** [comment]
As for the new name i would suggest something like typeTags?

**Comment by koosemose** [comment]
Hah! I gave my own example for the usecase and didn't even realize it. 

Yeah typeTags, seems reasonable, I could add in a method (I think doing it in a Property might be against c# coding conventions) along the lines of bool hasTypeTag(String), I don't think an outside class has need to directly access the list... though I may be wrong.

**Comment by lameox** [comment]
I think you are on the right track with that

**Comment by koosemose** [comment]
I'll look into the modification, probably sometime tomorrow, so there's time for input from others. But I think I have a pretty good idea of what I need to do to further future-proof this. Though it does occur to me that this works counter to the idea that some people mentioned earlier, regarding using this to sort the UI... or at least it would have some definite ramifications in the UI, such as with the example of the TV, in this case it would be listed under both "Entertainment" and "Electronic". Some might find that not good, though I can see it having advantages, since it would be reasonable to find a TV under both...

**Comment by lameox** [comment]
Well i guess for the sorting of the UI we would either need a separate UI specific tag, or just sort them by one of the tags available. We would have to define a logic for selecting the right tag though. (maybe the first tag encountered? Just a first bad idea :D)

**Comment by koosemose** [comment]
Closing this as all the primary things discussed have been implemented.
