### ISSUE TITLE
Centralized project management

### ISSUE THREAD

**Issue by Fogsight** [TeamPorcupine/ProjectPorcupine#310]
I'm new to team project development, but it seems that we could benefit from some kind of project management software, to have some structure and clear, visualized goals. And a way for people to display the thing they are working on, while minimizing conflicts.

Something like this, maybe? : https://www.quora.com/Which-project-management-tools-are-deeply-integrated-with-GitHub

Maybe Quill will also make a video introducing how to work with one as well, before implementing. That way the project could manage itself for the most part.

**Comment by WardBenjamin** [comment]
Related: #226

**Comment by bjubes** [comment]
Were currently working on better guidelines in #220  but I agree that we eventually need an organized plan for how to proceed building this game, like a queue of features and long term goals.

**Comment by vogonistic** [comment]
I like Waffle.io since it's just an interface on top of github issues. Makes it optional and easy to drop if we decided it's not working for us. Can't start using it without Quill to set it up though. Permissions and stuff.

**Comment by bjubes** [comment]
FYI since this is relevant. The wiki is now up, and it is publicly editable.

**Comment by Mizipzor** [comment]
@bjubes And I've already added, and deleted, the code style page. XD

**Comment by TheAkashicTraveller** [comment]
Looks at all of the UI pull requests, oh hey looks like everyone had the same idea :/ Something like this is needed quite badly to avoid multiple people doing the same thing in different ways.

**Comment by sboigelot** [comment]
Is this issue still relevant?

**Comment by bjubes** [comment]
I think having a 0.1 milestone temporarily solves this issue. I would close this now and open a new one when this problem arises again

**Comment by Fogsight** [comment]
Personally I think this is still relevant. Having the ability to create, assign or reserve smaller tasks would've allowed more people to contribute. 

I, for example, haven't yet found time to go over the whole project in detail, to find the thing I want to contribute. Having definitive tasks that need to be done, set by the people who know the project more intimately would've been very helpful.

**Comment by sboigelot** [comment]
@Fogsight I understand your point, we should setup this for the next milestone. For now, you can look at the bug list.

**Comment by vogonistic** [comment]
With projects added to GitHub and discord, we are pretty much covered. 

I don't think we need to keep this issue open any longer.
