### ISSUE TITLE
Beta Testing "Gatekeepers"

### ISSUE THREAD

**Issue by quill18** [TeamPorcupine/ProjectPorcupine#321]
"Gatekeepers" is a team I just created -- they SHOULD be able to accept Pull Requests.  They SHOULDN'T be able to commit directly to the master branch.

EDIT: Not a team. Teams don't work well AT ALL outside of the organization itself. Which is ridiculous.

I have selected two people somewhat at random from a pool of you I have shortlisted based on your contributions (partially from actual pull requests, but also based on activity in comments on Issues and other PR's).

I am capricious, arbitrary, and very likely likely to change the members of this organization based purely on the phase of the moon. Don't take it personally if I add, don't add, or remove you from this list as we work out the kinks here in the early days.  I'd rather do something slightly wrong now than debate for weeks over the perfect choice.

Most likely gatekeepers will be cycled in and out as people become more or less active on the project (as a result of their personal lives becoming more or less hectic.)

Feel free to nominate others or yourself for addition to my short-list.

**Comment by ComputerOverlord** [comment]
I would join if I could but I can't load Project Porcupine, and even when I do, I get compiler errors.

**Comment by JosephBywater** [comment]
@ComputerOverlord Is it like this: #67 Also, @quill18 the `@TeamPorcupine/gatekeepers` is broken when I click it (intentional?)

**Comment by vogonistic** [comment]
@JosephBywater The public can't see members in groups, but you should still be able to ping them.

**Comment by JosephBywater** [comment]
@vogonistic Do you know who's in @TeamPorcupine/gatekeepers ?

**Comment by bjubes** [comment]
can gatekeepers add labels to pull requests and issues as well? that would be very helpful

**Comment by vogonistic** [comment]
@JosephBywater No, only @quill18 and the members themselves know it.

**Comment by JosephBywater** [comment]
@vogonistic Ok :) I can't tag them... @TeamPorcuping/gatekeepers

**Comment by vogonistic** [comment]
@quill18 It'd be awesome if we have a good spread of timezones so we can get PR's merged all around the clock. Europe, America, Oceania/East Asia for example.

**Comment by quill18** [comment]
Okay, that's really, really dumb.  I guess "Teams" are out, then.  I think I can invite people as "Collaborators" and give them write access that way.

**Comment by vogonistic** [comment]
@quill18 Can you change so that the public can see the members? Testing ping: @TeamPorcupine/gatekeepers

**Comment by JosephBywater** [comment]
I'm GB/Europe! :P

**Comment by vogonistic** [comment]
Ping failed, I'm pretty sure.

**Comment by JosephBywater** [comment]
@vogonistic Yep

**Comment by Mizipzor** [comment]
I would like to volunteer. :)

If you've seen my comments, especially those regarding code style you probably think I'm cynical, hah (I'm old). I just think a rigid structure is beneficial. Especially in a project with this velocity.

I will also help people wrangle Git, but I obviously dont need to be a collaborator for that.

**Comment by Dormanil** [comment]
I'd nominate @vogonistic as a collaborator. I think he'd do a pretty well job, as long as we don't get Vogon poetry in the merge comments. ;)

**Comment by behindcurtain3** [comment]
I second @vogonistic and @Mizipzor

**Comment by vogonistic** [comment]
@Dormanil @JosephBywater I never got the hang of poetry, could barely harm a fellow with it! I'm stick to what I'm good at: smashing delicate creatures with mallets.

@quill18 I think you could probably spend a couple of hours talking about what the git tree looks like so that people understand the difference between `upstream`, `origin` and the 3 potential versions of `master`. It's hard to capture it in just 1h, but you did a pretty good job going through everything. People who have trouble follow it will just have to ask questions.

The biggest omission in the video is that you don't show people how to view what changes will be included in the PR before it is created. On the page where you set the title and body of the PR, below the body text field you can see the commits and the changes included. If more people reviewed that before creating the PR, we'd have less of them with problems.

**Comment by vogonistic** [comment]
@quill18 Collaborators can't currently accept pull requests:

> This pull request can be automatically merged by project collaborators
> Only those with write access to this repository can merge pull requests.

**Comment by vogonistic** [comment]
Btw @Dormanil @behindcurtain3 I really appreciate the nominations!

**Comment by GamerInspired** [comment]
I also nominate @vogonistic

**Comment by SteelFall** [comment]
+1 nomination for @vogonistic

**Comment by ComputerOverlord** [comment]
@JosephBywater it's like this
![screenshot 1](https://cloud.githubusercontent.com/assets/21087045/17826157/de66cdfe-6622-11e6-9176-9a115e58589a.png)

**Comment by vogonistic** [comment]
@GamerInspired @SteelFall You guys are awesome =)

I've actually received an invitation from @quill18. So until I lose them, I wield the amazing powers of.. well, labeling issues for now, but I think later also merge PR's.

Really, really appreciate the nominations and I think that ProjectPorcupine will become something amazing with all the support you guys are pouring in it. =)

**Comment by bjubes** [comment]
@vogonistic  haha get busy labeling!!

**Comment by vogonistic** [comment]
@ComputerOverlord Accidentally posted to the wrong issue? What's going on?

**Comment by bjubes** [comment]
@vogonistic can u add a beginner/easy tag if you have that power?

**Comment by vogonistic** [comment]
Unfortunately I can't. 

@quill18 Can you create the tags `beginner` and `discussion` for now?

**Comment by ComputerOverlord** [comment]
@vogonistic Nope.

> I would join if I could but I can't load Project Porcupine, and even when I do, I get compiler errors.

> @ComputerOverlord Is it like this: #67

**Comment by Fogsight** [comment]
@ComputerOverlord I think you're using older Unity version.

**Comment by ComputerOverlord** [comment]
Makes sense

**Comment by JosephBywater** [comment]
@ComputerOverlord you need 5.4 if it helps.

**Comment by Mizipzor** [comment]
With all due respect, I think this got a bit off topic. :) Maybe create a new issue?

**Comment by ComputerOverlord** [comment]
@JosephBywater I just looked up update. It's installing right now.

**Comment by ComputerOverlord** [comment]
I sign up for Gatekeepers.

**Comment by vogonistic** [comment]
@ComputerOverlord Please create a new issue for the problem with getting ProjectPorcupine running and we'll help you.

As for the Gatekeepers, I'm sure Quill has seen that you volunteered now. At this point the best thing you can do to help yourself become one is to participate in the issues and PR's. Make awesome things and help others do the same. That way you'll look like a great choice when he decides he has had enough of me =)

**Comment by ComputerOverlord** [comment]
@vogonistic I fixed it... I hope.

**Comment by WardBenjamin** [comment]
I volunteer.... as tribute?

My summer job is just about to end, so even with school coming up I should have a ton more time for this project. I'm also way more motivated to work on super-active projects with other people, like this one, so it's a win-win :P

**Comment by quill18** [comment]
@WardBenjamin You were already volunteered by me, before I even posted this Issue.  Have you tried merging any PRs?

**Comment by quill18** [comment]
@vogonistic You *have* write access -- is that really not letting merge PR's? That would be terrible.

![screen shot 2016-08-20 at 12 00 20 am](https://cloud.githubusercontent.com/assets/777633/17828768/2237e946-6669-11e6-8862-ccfde50043b3.png)

**Comment by vogonistic** [comment]
I saw the notification that I now have write access, just can't figure out to what. This is what I see.

<img width="772" alt="screen shot 2016-08-19 at 21 02 13" src="https://cloud.githubusercontent.com/assets/159568/17828787/44c6bb9a-6650-11e6-9261-936a18ad1845.png">

**Comment by quill18** [comment]
@vogonistic Try accepting the organization team request and then see

**Comment by vogonistic** [comment]
@quill18 I did, and verified that I'm listed in the organization, yet I still see that same graphics. Let me try a couple of things.

**Comment by quill18** [comment]
Seriously, Github, WTF?

**Comment by vogonistic** [comment]
@quill18 Can you verify that protected branches is turned off? https://help.github.com/articles/configuring-protected-branches/

**Comment by quill18** [comment]
I **just** turned it off.  Try it now.

**Comment by quill18** [comment]
The way I understood it, you couldn't make a `git push` to a protected branch, but I assumed you could still accept a pull request. But maybe not.

**Comment by vogonistic** [comment]
Boom! Now I have a merge button.

**Comment by vogonistic** [comment]
I think you are right, but it might not work the way we think if you don't have any status checks configured (Like CI builds or syntax checks).

**Comment by quill18** [comment]
Well, that's good -- but I wish Github had more granular permission options.

**Comment by vogonistic** [comment]
Do you want to try out Collaborator again? I'm pretty sure this was the issue.

**Comment by quill18** [comment]
Organization team deleted once more. You are still a collaborator on the project.

**Comment by vogonistic** [comment]
I still have merge. Awesome! I wish they could have told me "You can't merge, because the branch is protected..."

**Comment by quill18** [comment]
Informative error messages are for the weak.

**Comment by RodRitter** [comment]
Awesome, this is great news.

**Comment by bjubes** [comment]
So are they going to be any more gatekeepers for now?

**Comment by WardBenjamin** [comment]
@quill18 Huh. It looks like I don't have any perms still, I wonder what's up.

**Comment by quill18** [comment]
@WardBenjamin Because you still have accepted:

![collab](https://cloud.githubusercontent.com/assets/777633/17831659/cae2d8be-66bc-11e6-949f-28997acd22bf.jpg)

I'll DM you the invite link on Twitter.

**Comment by WardBenjamin** [comment]
@quill18 Huh, thanks. I got the email about the organization, but I don't think I got anything for this one. Accepted anyway, thanks!

**Comment by bjubes** [comment]
So with the new "Review" feature, is it now possible for gatekeepers to be a team inside of TeamPorcupine, since we can "approve" a PR and then merge it despite being a protected branch? If so that would make pinging gatekeepers possible and give them a little badge like quill has on his comments so new members know who we are.

**Comment by bjubes** [comment]
never mind ignore that. I didn't realize that such a system could prevent one gatekeepers outdated request for changes from preventing another from merging a PR.
