### ISSUE TITLE
Discussion: furniture: add categories?

### ISSUE THREAD

**Issue by FilippoLeon** [TeamPorcupine/ProjectPorcupine#324]
As the number of furniture items increases, I wonder if it is the case to add categories and subcategories to the furniture codes.

The xml could look like:
```
<Furnitures>
   <Category name="power">
      <Subcategory name="power_gen">
         <Furniture >....
```

And move the BaseType to a category.

**Comment by buckeyestudios** [comment]
I like this idea.. Should be simple

**Comment by behindcurtain3** [comment]
This is a good idea, mods should be able to specify their own categories as well.

**Comment by vogonistic** [comment]
Question is the closest label I have right now. We'll get a `discussion` created sooner or later.

It'd probably be better if the category and subcategory is described inside the `Furniture` tag so that changing either is just a single line change. We can sort them either way in memory. 

Is a single category and subcategory enough? What exactly are they describing?

**Comment by GamerInspired** [comment]
I think this would be very useful if there was a search feature in game at a later date, so if you wanted to look for all power generates you could and it would display a list of them.

**Comment by gunthergun** [comment]
I agree with @vogonistic ... The UI could also then sort by category only showing the objects of a category as it is getting already a little full.

**Comment by sboigelot** [comment]
I need that for the trading system I'm working on (many PR) but well underway. If it's not there when I implement the TraderVisitEvent I'll add it.

**Comment by sboigelot** [comment]
Categories are now handled by TypeTag, I guess
We can probably close this issue

**Comment by TomMalbran** [comment]
We might still need categories and subcategories for menu organization, since the TypeTags can have multiple values and we might not want to have the furniture in several menus.

**Comment by sboigelot** [comment]
@TomMalbran agreed, but this would be easy and obvious to implement in the PR of a future Build menu, we probably don't need to keep this issue open about it. Issue-pocalypse is upon us.
