### ISSUE TITLE
[Bug, easy] Doors don't update direction if neighbor walls finish after the door is built

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#326]
![gif](https://cloud.githubusercontent.com/assets/5951269/17825727/7d32eac0-6638-11e6-8387-7edcb2b276ba.gif)

**Comment by DevOrc** [comment]
does anyone know where the door rotation code is at?

**Comment by kd7uiy** [comment]
It's a good exercise to find it. I could trace it down, but quite frankly, that's 90% of the effort, figuring out where a bug is. The first contribution I had here was very similar, a 1 line of code change, but quite a while to track it down.

**Comment by vogonistic** [comment]
For beginner bugs, I think it's fair to give people a start on how to search. For someone new to the project that hasn't watched all the tutorials, it's not that easy to know the layout.

**Comment by kd7uiy** [comment]
Fair enough. It's either going to be in the Furniture Sprite Controller, or in the Lua code relating to the door, at least I would guess. That's at least where I would start looking for it.

**Comment by vogonistic** [comment]
@DevOrc Are you working on this bug?

**Comment by koosemose** [comment]
PR #251 is supposed to fix this (along with several related things) but currently has conflicts.

**Comment by kd7uiy** [comment]
Good catch, sigh, all of the good bugs seem to have a commit to fix it already, or at least something close to it.

**Comment by DevOrc** [comment]
yes, I am working on this

**Comment by kd7uiy** [comment]
This is a duplicate. Closing.
