### ISSUE TITLE
the last commit

### ISSUE THREAD

**Issue by ghost** [TeamPorcupine/ProjectPorcupine#327]
is anyone having problem if they do a fresh fork??
Script references missing... having to rebuild asset database???

**Comment by vogonistic** [comment]
Whenever Unity notices that there are files that doesn't match the database/cache, it'll have to rebuild it. Unfortunately, this will happen whenever you pull in the upstream master or switch branches.

**Comment by vogonistic** [comment]
Do you have to manually rebuild it, or are you talking about the automatic rebuild?

**Comment by relinu** [comment]
the only "error" i am getting is that after opening unity  there are a lot of new meta files generated for the languages files

**Comment by buckeyestudios** [comment]
i get 45 meta file which im not worried about but some Game Objects cant find references to scripts witch i am worried about

**Comment by relinu** [comment]
in your project window (where you can see the assets) right-click and do a reimport

**Comment by kd7uiy** [comment]
The meta files were missing, but they were included by mistake when I pushed my changes and did a merge without paying careful attention to what else I was adding... In any case, update and I suspect this will go away.
