### ISSUE TITLE
Discussion: Repository Bloat and git LFS

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#328]
As more UI elements and furniture are added, the repo will grow in size storing all of the binary files for images, sound, and other assets. This is not a problem now, but I can foresee it sneaking up on us if we don't start discussing how to address it.

One solution, that I think is quite elegant, is [Git Large File Storage (LFS).](https://git-lfs.github.com/). It replaces all binary files on the repo with pointers, and stores the binaries somewhere else. It integrates super well with git too, all you have to do is download the file from the website and follow the directions from there. git will automatically download the binaries when you clone and pull, and replace them with pointers when you push. Even github.com works well, as it will show you an image that is stored on git LFS despite the file actually just being a pointer.

The only downside to this approach is that everyone contributing must have git LFS installed, or else they get pointer files when they pull instead of the actual binary. If we did switch to LFS, quill would have to tell everyone to download it immediately or experience some weird side effects.

Anyone have any other ways to store binaries in git? Would you want to use LFS in the future?

**Comment by vogonistic** [comment]
I believe that git-lfs is included by default in the Github Desktop apps, but someone will have to verify. Do you know for sure that `git lfs install` works in `git bash` on Windows?

**Comment by koosemose** [comment]
Running `git lfs` in the git shell opened from GitHub desktop returns a help message for git lfs, so looks like it is in fact installed by default, as I haven't installed anything into it.

**Comment by Dormanil** [comment]
Meanwhile trying to install git-lfs on Ubuntu on Windows fails with these messages:

```
kazumi@DESKTOP-VRDT7VF:/mnt/d/github/ProjectPorcupine$ sudo apt install git-lfs
Reading package lists... Done
Building dependency tree
Reading state information... Done
git-lfs is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up git-lfs (1.4.0) ...
Error getting git version: waitid: invalid argument
dpkg: error processing package git-lfs (--configure):
 subprocess installed post-installation script returned error exit status 2.........................................]
Errors were encountered while processing:
 git-lfs
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Trying to run `git lfs install` ANYWAY results in this:

```
kazumi@DESKTOP-VRDT7VF:/mnt/d/github/ProjectPorcupine$ git lfs install
Error: Failed to call git rev-parse --git-dir --show-toplevel: ""
Error getting git version: waitid: invalid argument
```

And yes, I probably _could_ just use git bash, but I wanted to use _real_ bash instead.

**Comment by vogonistic** [comment]
@Dormanil Not sure if Ubuntu on Windows support is enough to hold this discussion up. =) Can you let us know if you figure out a solution for it?

**Comment by Dormanil** [comment]
I will do my very best, @vogonistic.

**Comment by Dormanil** [comment]
Bad news for everyone using the Windows Subsystem for Linux, Bash on Ubuntu on Windows or whatever you want to call it.

Support for the `waitid` system call (which git-lfs apparently needs) is not yet implemented by the guys over at Microsoft.

**Comment by bjubes** [comment]
Sorry didn't clarify. You have to download one file from the link I originally posted. Follow the directions on the website

**Comment by bjubes** [comment]
And I have tested it with unity on both Mac and Windows and it works very well from my experience

**Comment by WardBenjamin** [comment]
I do like this idea, but I'd argue that we should use a git submodule instead of LFS. LFS is meant to be just that, large file storage, and mostly used for super huge assets (video, etc), and things like binaries of projects. Having a submodule for art and such would introduce a bit of complexity, but I don't think any more than using LFS would.

**Comment by bjubes** [comment]
I think that a sub module would be an equally good solution, so long that it can integrate well with our workflow and prevents repo bloat

**Comment by kd7uiy** [comment]
Is this really that much of a concern? I guess I don't understand what the real root of the problem is. I've used Git for many projects, including with large files, and it doesn't seem to be that much of a concern. Plus, the largest files we are likely to have are sound and images, both of which Github seems to deal with satisfactorily. I suggest we close this issue until we have a case where our current system is strained, which I don't see at the moment.

**Comment by bjubes** [comment]
I think we will have to reexamine how we store binary files later, but for now Ill close this
