### ISSUE TITLE
Create a wiki for developers

### ISSUE THREAD

**Issue by Sommerbo** [TeamPorcupine/ProjectPorcupine#33]
Github has a wiki built in. Might be a good place to consolidate design decisions, code conventions and so on.

Quill has to start it and give out permissions. I think Quill should delegate the job of moderating the wiki to someone he trusts. And that only use the wiki for presenting made decisions.

Thoughts?

**Comment by SquareMan** [comment]
I think for right now the project is small enough that the issues page can be used handle things for now, this was mentioned in #11. A wiki would definitely be useful in the future though!

**Comment by WardBenjamin** [comment]
The wiki has been enabled as per last night!
