### ISSUE TITLE
Strange building patterns with multiple characters

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#335]
![gif](https://cloud.githubusercontent.com/assets/5951269/17827464/6931ce98-664b-11e6-96a3-a0cfaf5adea1.gif)

There's a lot of weird stuff that I see, like gaps in building holes, characters jumping over each other, and generally wasted time. I suspect this will have to wait until the AI system is improved for resolution, but I wanted to get it out there.

**Comment by vogonistic** [comment]
Closing in favor of job system discussions #86 #726 #732
