### ISSUE TITLE
Pathfinding really slow

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#336]
The pathfinding algorithm is really slow if beyond around 20 tiles. This is happening quite frequently with large projects, and multiple characters. We really need to come up with a better system to make this work.

**Comment by kd7uiy** [comment]
![gif](https://cloud.githubusercontent.com/assets/5951269/17827590/3ecdb214-664d-11e6-996e-5e705728e1cb.gif)

Note that after a wall is built there is a noticable lag in the game, every time.

**Comment by FilippoLeon** [comment]
Is this only happening when there is no path, or it's constantly laggy?

**Comment by kd7uiy** [comment]
There is a path, it's just a long path.

No path is also really laggy, but that's another issue.

**Comment by FilippoLeon** [comment]
I've noticed that sometimes there is a spam of logging messages relative to the pathfindig. There, I noticed the lag. It that it or there is something else?

In any case: we should build a graph of rooms: will help pathfinding from far away and no path issues.

**Comment by kd7uiy** [comment]
The latest version improves that considerably, leaving only a single log for each pathfinding event. What I show is just due to that lag.

**Comment by vogonistic** [comment]
When a wall is built, all the path finding nodes and edges are rebuilt. All the 10k edges and 7k nodes.

This could obviously be optimized, but I'm the most excited about per-room path finding. That combined with some optimization to only update part of the graph will be way faster.

**Comment by kd7uiy** [comment]
I will add that if there is no object of that type in existence, the pathfinding is PAINFULLY slow, far beyond this.

**Comment by FilippoLeon** [comment]
Why do we need a separate graph for A* anyways? Can't we just use the underlying function GetNeighbours "within" the algorithm itself?

**Comment by vogonistic** [comment]
@kd7uiy That should have been fixed, but maybe you've found a new condition that triggers it. It'd be an awesome bug to find the cause for. 

@FilippoLeon If you prebuilt it, the path finding is faster. It just depends on how often you have to rebuild it. Consider the current implementation a first to get us going.

**Comment by kd7uiy** [comment]
@vogonistic I only wish I could. Unfortunately I have almost no time left to be working on this, for quite a while...

**Comment by vogonistic** [comment]
When we have per-room path finding, we might do as you say for open space, @FilippoLeon

**Comment by FilippoLeon** [comment]
You think is not more efficient if there are many "blockers"?

Essentially, where the graph is used in A* is in:
`foreach (Path_Edge<Tile> edge_neighbor in current.edges)`

could be replaced by something like:
```
foreach(Tile nhbd in current.GetAllNhbds()) {
    ...
    if( cannnot path to nhbd) continue;
else do your A*
```
There is a bit of redundancy, but most of the times, there is no blocking. Hence there is not that much overhead.

**Comment by vogonistic** [comment]
@kd7uiy Hopefully you'll just be busy for a while. You've been doing a great job here.

**Comment by kd7uiy** [comment]
@vogonistic Just for a week or so. Problem is, this game is causing me to slack on the one that I'm making, that uses some of the same principals from this game... Sigh. You can take a look at what I've done if you like, http://www.kd7uiy.com

**Comment by vogonistic** [comment]
@FilippoLeon You might be right. Want to give changing it an attempt?

**Comment by FilippoLeon** [comment]
I could try, I'll make the changes over https://github.com/TeamPorcupine/ProjectPorcupine/pull/343.

The thing is that the profiler is not clear about where exactly the bottleneck is.

**Comment by WardBenjamin** [comment]
Okay, so this is something that I'm going to put some time into in the next few days. I'd like to implement Jump Point Search as well as multithreading *all of the pathfinding* :P

I know that Unity has some issues with it's API being non-thread-safe, but I have a solution to that that should work well, based off of something I read a while ago.

**Comment by FilippoLeon** [comment]
Was about to write about concurrency! :) If you manage to do it, then it would solve many problems.

**Comment by vogonistic** [comment]
@kd7uiy I'm sure we'll see you around here. Good luck with the game.

@FilippoLeon Have you timed it? Obviously faster to build walls, but what about pathfinding?

**Comment by Mizipzor** [comment]
I had started a branch that makes path finding be done on a separate thread. Now I found this thread and I'm not sure if I should continue, I don't want to step on any toes. Should I proceed?

**Comment by FilippoLeon** [comment]
@vogonistic Is very hard to time consistently, but it seems a wee bit less laggy. Anybody else tested it?

@Mizipzor @WardBenjamin imho, you two should have a shared branch and work together. It's a huge task and sure there is plenty to do for both.

**Comment by Mizipzor** [comment]
@WardBenjamin I think we are in different time zones so I assume it might take a while before I hear from you. I'm gonna go ahead and try to thread the path finding and you can do the jump point thing or improve pathing in general (the actual algorithm shouldnt be changed by my stuff). How does that sound? Should also be noted that I haven't started yet, I might give up. ^^

**Comment by FilippoLeon** [comment]
There is also:

**Comment by Mizipzor** [comment]
Alright. I'll base my stuff in #343. Any ideas on setting up some kind of test bed to test the performance of different path finding approaches? Maybe a different scene. Maybe that would be a good beginner task.

**Comment by UnknownSoldier1** [comment]
Maybe add multithreading to the pathfinding, put it on a seperate thread?

**Comment by WardBenjamin** [comment]
@Mizipzor yo, want to join us on Discord? https://discord.gg/ErwDA

**Comment by Mizipzor** [comment]
@WardBenjamin Sure, but I will be text only. :)

**Comment by cwalker94** [comment]
It might be good to implement parallel bi-directional A* pathfinding. In other words, you have 2 threads working simultaneously. 1 thread is handling start -> end, and the other is handling end -> start. Then, where they merge together, that's your path.

**Comment by vogonistic** [comment]
Those are cool ways of doing it, but I think when we have a pathfinder per room, some caching of normal paths (door 1 -> door 3), and a faster implementation than A*, it'll be blazing fast.

**Comment by kd7uiy** [comment]
I'm going to close this, as things seem to be very much improved with the latest version!
