### ISSUE TITLE
Metal Smelter- Don't steal from one to give to another one

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#339]
![gif](https://cloud.githubusercontent.com/assets/5951269/17827755/86c71ba2-6650-11e6-9854-2b5ff2cffd4c.gif)

**Comment by vogonistic** [comment]
Best bug today! I love it! :D

**Comment by WardBenjamin** [comment]
Nice! :P

**Comment by kd7uiy** [comment]
Considering how many bugs I've reported today, that says a lot!

**Comment by koosemose** [comment]
HAH! Though I would love to see, at some point in time in the future, the possibility of a character with some kind of trait (perhaps Lazy, Greedy, or Thief) where they will gladly take materials someone else has reserved for a job to do their own, if it's closer than any other resource of that type.

**Comment by RodRitter** [comment]
@koosemose That's a very interesting concept

**Comment by UnknownSoldier1** [comment]
Can be closed, this has been fixed with #380.

**Comment by RodRitter** [comment]
Agreed. Closing.
