### ISSUE TITLE
Raycast showing a slowdown

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#345]
![capture](https://cloud.githubusercontent.com/assets/5951269/17828142/53da474e-6657-11e6-82bb-44f5cf37a935.PNG)

Slightly related, the Lua code in Furniture processing can take a while. I can't figure out what it means from the profiler, but I suspect it is the A* pathfinding issue discussed elsewhere.

**Comment by sboigelot** [comment]
@kd7uiy is this still an issue?

**Comment by kd7uiy** [comment]
I actually can't find it anymore, so I guess it's gone away. I'll go ahead and close it for now.
