### ISSUE TITLE
Copyright Notices in source code

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#35]
currently some files (such as tile.cs) have copyright statements that obviously don't agree with the license file. `//================================================================
// Copyright Martin "quill18" Glaude 2015-2016.
//		http://quill18.com
//=================================================================
`
These should be removed, probably by quill for legal reasons

**Comment by quill18** [comment]
Re-doing the headers is definitely on my to-do list, along side properly commenting some of the more sparse files.

**Comment by BeefEX** [comment]
Will files contain list of authors in header? Because that sounds fair.

**Comment by RodRitter** [comment]
Considering there could potentially be dozens of contributors, I don't think that's sustainable.

**Comment by emilkris33** [comment]
@BeefEX Properly better for the header to reference licensing and general author information in dedicated files or on github.

**Comment by JosephBywater** [comment]
I suppose you could reference the github repo and say you can look for contributors of each file?

**Comment by bjubes** [comment]
i agree. Leave names out of the source. GitHub remembers exactly who did every change anyway.

**Comment by vogonistic** [comment]
Headers are all pretty now!
