### ISSUE TITLE
Discussion: World as Singletone

### ISSUE THREAD

**Issue by Grenkin1988** [TeamPorcupine/ProjectPorcupine#351]
Several times on video @quill18 said that probably World should be Singleton.
I would try to do it.

**Comment by vogonistic** [comment]
It might not be a true singleton right now, but effectively it's pretty much there with `World.current`. Any particular benefit you are looking for?

I've been thinking that the map should be decoupled so that we could switch between locations.

**Comment by Grenkin1988** [comment]
Initial goal was to protect `World` from anybody chaging `World.current`.
Or in long run we are aiming on several worlds?

**Comment by vogonistic** [comment]
I don't think it's been discussed. I would like to. It gives the game something extra that other games haven't had.

**Comment by vogonistic** [comment]
I don't think dealing with the world as a singleton is going to be the hardest part about that though. We'd probably keep the world as singleton, just remove the tile data and put that in `Map` something like that. It's a problem for another day though.

**Comment by Grenkin1988** [comment]
OK. Than I am going to do `World` as singleton and split World/Map in different classes

**Comment by vogonistic** [comment]
I think you are going to dislike the second part of it. The pathfinding, tiles and furniture all use `World.current` to then ask for tile information.

If you take on the task, make sure it's two different PR's.

**Comment by Grenkin1988** [comment]
OK

**Comment by vogonistic** [comment]
I started a discussion in #353

**Comment by Grenkin1988** [comment]
As I see right now `World` is nearly just map of all kind of objects.
And with serilization we could not get rid off public constructers...
So.... probably I could not make it Singletone right now :-(
