### ISSUE TITLE
Random.InitState error after fresh pull.

### ISSUE THREAD

**Issue by Bananenspin** [TeamPorcupine/ProjectPorcupine#352]
After pulling the latest files from the repo, unity is telling me the following making it so i cant compile.

`Assets/Scripts/Models/WorldGenerator.cs(18,16): error CS0117: `UnityEngine.Random' does not contain a definition for `InitState'
`

**Comment by vogonistic** [comment]
I've been merging pull requests until very recently, can you make sure you are still on the latest?

If it's still a problem, what version of Unity are you on and have you been able to run it before?

**Comment by Bananenspin** [comment]
Yes i've deleted and re-pulled a few times now so i should be on the latest. Im on version 5.3.5f1 of Unity and no i have not been able to run it before. My first time trying was last night before going to bed, and i just figured ill try again this morning.

Whats happening:
1) Im pulling from the repo
2) I open the project in Unity
3) Unity crashes on me while its trying to import small assests.

From looking at the log files it used to be a problem with it not being able to find a file called MonoDevelop\monodoc.xml. I've  solved this by clearing all the monodevelop roaming data under users and starting up MonoDevelop once again. Now a different reason is crashing my Unity.

```
Unity.exe caused an Access Violation (0xc0000005)
  in module Unity.exe at 0033:40310326.
```

After that crash i can reopen Unity and it will open just 'fine' but shows the following in console:

https://snag.gy/UHVKtp.jpg

**Comment by Tritaris** [comment]
Random.InitState() was added in Unity5.4 you'll have to update if you want to contribute to the project. If you want to clear it out just to mess around you can use `Random.seed = seed;` instead of `Random.InitState(seed)`

**Comment by Bananenspin** [comment]
Look at me not knewing 5.4 was out after been away on vacation... The updater in Unity itself say's i had the latest version. After updating it works fine thanks!
