### ISSUE TITLE
Discussion: Escape menu work and moving buttons around

### ISSUE THREAD

**Issue by jamzam90** [TeamPorcupine/ProjectPorcupine#354]
As i'm working on the GUI I'd like some input from the rest of you on where things should be moved to.
Currently the New world, Save/load, pathing test and the lang selection in my opinion should all be moved into and escape menu as you really don't need them cluttering up the game ui while playing.
Pathing test would get disabled later as well.

**Comment by koosemose** [comment]
Would it be feasible to have the menu togglable to always on? Especially if something like the mockup someone put up a day or two ago with small little image icons that take up a lot less room is used. I know I for one would like the option to have save and load in particular be right there and easily accessible, but obviously not everyone wants that.

**Comment by jamzam90** [comment]
With the way im doing it currently pressing the escape button triggers isModal to turn to true so i dont need to add my own bools to do it heres a screen shot`

![menuscreen](https://cloud.githubusercontent.com/assets/4957600/17829666/3749151a-666b-11e6-85e1-c9dc1e040ac4.png)
`

**Comment by koosemose** [comment]
Yeah, that's a pretty good middle ground. Though at some point we have to look into how were going to handle Kevin's in the long run.

**Comment by jamzam90** [comment]
So ctrl+s for saving and ctrl+l for loading, also should the keybind act as a quick save? So that the save window doesnt show up.

**Comment by koosemose** [comment]
I'm thinking for now, probably not. It would probably be better to do anything beyond the basics in a PR dedicated to the whole keyboard thing.

**Comment by kd7uiy** [comment]
This seems like might be OBE. Should we just close this?
