### ISSUE TITLE
[Suggestion] Remove visible grid

### ISSUE THREAD

**Issue by satch3l** [TeamPorcupine/ProjectPorcupine#357]
I suggest we get rid of the visible grid for a less chess board look.

**Comment by JosephBywater** [comment]
Maybe this could be implemented later on however for testing g purposes I think that the grid is helpful ;)

**Comment by jamzam90** [comment]
The grid is due to the textures on the tiles, so tile art would have to be messed with.

**Comment by Mizipzor** [comment]
Maybe the grid should be implemented as an overlay?

**Comment by kd7uiy** [comment]
For the time being, my preference would be to keep the grid in place. It really helps for development purposes. I think we will get to the point eventually where it might be worth removing it, but for now, I suggest we keep it in play.

**Comment by GamerInspired** [comment]
I like @Mizipzor idea, because then people would have the option to have it on or not. As long as you have have other overlays on at the same time.

**Comment by koosemose** [comment]
Actually a good portion of the grid has came out, due to z-levels quintupling the number of tiles on-screen, so empty tiles no longer are rendered. If we want the grid back everywhere, we need it reimplemented as an overlay of some sort.

**Comment by mikejbrown** [comment]
I think a grid overlay would be useful, but I'm happy if it is off by default.

**Comment by sboigelot** [comment]
As the grid is gone, we can close this issue. Reopen if the current version still annoy you.
