### ISSUE TITLE
Localization Localization

### ISSUE THREAD

**Issue by nsfranklin** [TeamPorcupine/ProjectPorcupine#358]
Probably rather straight forward but the localisation needs Localising. However do we want the name of all the languages to be in the selected language or do we want them always in the language that it is. I prefer the language that it is.

**Comment by koosemose** [comment]
It definitely seems each language being translated to itself would be best, since if you accidentally change languages (or need to change from the default) there is no guarantee you will recognize your own language in that language.

**Comment by quill18** [comment]
@koosemose I agree.

**Comment by nsfranklin** [comment]
Relevant pull request added. #399

**Comment by WardBenjamin** [comment]
I just want to note, this should be "Localization Localization" because we're using en_US in code. Otherwise the PR looks great

**Comment by kd7uiy** [comment]
The PR associated with this issue was closed, is this still a problem, or can we close this issue?

**Comment by koosemose** [comment]
The relevant PR was closed not merged, so I would say this issue is still an issue.

**Comment by UnknownSoldier1** [comment]
Made a pull request over at #1509 for finally closing this.
