### ISSUE TITLE
[Suggestion] Use AssetBundles with new scenes for additional UI and animations

### ISSUE THREAD

**Issue by Kreol-Dev** [TeamPorcupine/ProjectPorcupine#359]
Most of modders anyway would need to set up some sort of DE, so it might be natural to use Unity.

That way, if we'd have a system to load AssetBundles and scenes from them, we could have a normal UI system with visual creation instead of implementing some codedriven one. 

Same goes for animations and sprites, it might be better to use ABs instead of custom file formats, etc.

This bundles can also drag additional DLL's for custom UI behaviours, which would be nice. 

I'm busy working on my own project, but I can provide code examples or advices to anyone who would work on that. 

Plus we could avoid changing main scene from now on.

**Comment by bjubes** [comment]
Quill has stated that the goal of modding is that anyone can mod without needing to install unity or even know how it works.

**Comment by sboigelot** [comment]
The current mod system follow the comment of @bjubes 
We can close this issue
