### ISSUE TITLE
StyleCop SA1122

### ISSUE THREAD

**Issue by Mizipzor** [TeamPorcupine/ProjectPorcupine#360]
Since the StyleCop settings were merged I'm going to start maintaining that settings file and discuss the options as the become relevant. It should also be noted that StyleCop is in no way required, it's only a bonus for those that use it. Rules can be turned off if we dont agree with them.

Here is one rule I disagree with:

`return ""; // SA1122: CSharp.Readability: Use tring.Empty rather than "".`

Instead StyleCop wants:

`return string.Empty; // Correct`

I actually think the latter is more readable, but there's also value in having as few deviations as possible. What do you think? Does it stay or does it go?

**Comment by lameox** [comment]
I think you are right in disagreeing with the rule. I feel string.Empty is more readable

**Comment by Mizipzor** [comment]
Wait, I think we disagree then. Maybe I was unclear. But you **do** prefer `string.Empty` over `""`, correct? You Agree with StyleCop?

**Comment by bjubes** [comment]
Is their any documentation on how to install and use style cop? If not maybe just writing a rough how to on the wiki would allow more people to use it and keep code clean

**Comment by Mizipzor** [comment]
Yes. In a [comment](https://github.com/TeamPorcupine/ProjectPorcupine/pull/158#issuecomment-240778549) on the pull request. But only for Mono. I will move them to the wiki and add visual studio. What are you using? Theres also a command line alternative.

**Comment by lameox** [comment]
@Mizipzor yeah i do like `string.Empty` it better.

**Comment by bjubes** [comment]
Now that the wiki is up I will move your comment to a page if you don't mind

**Comment by Mizipzor** [comment]
@bjubes Oh, I [just did](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/StyleCop) do we have a duplicate now?

**Comment by bjubes** [comment]
No I didn't do it yet your good

**Comment by quill18** [comment]
String.Empty good. Me like. Go do.

**Comment by quill18** [comment]
And I've installed StyleCop myself now and doing a test run on a side project.  With the default settings, it's a bit... overly anal about a couple things, but overall I like it. And very tweakable.

**Comment by Mizipzor** [comment]
@quill18 Are you using Visual Studio or MonoDevelop? If you take #390 you will have the settings automatically applied in Visual Studio as well, I assume you use that.

I agree that with all rules turned on its a bit nutty. But thats the point, we turn off what we want and shouldnt have to figure out how to _add_ rules.

There are three things I want to avoid here:

1. The grey area that comes from a "human style cop" that interprets a rule, leading to endless discussion.
2. Unsure newcomers shouldnt be rejected because of code style, let them experiment and be shunned by a robot instead.
3. Code style checks are boring. Let the robot do it.

**Comment by kd7uiy** [comment]
It seems like this should be closed.

**Comment by vogonistic** [comment]
We've even had #855
