### ISSUE TITLE
[Beginner] Setup test scene

### ISSUE THREAD

**Issue by Mizipzor** [TeamPorcupine/ProjectPorcupine#369]
We need a way to test stuff that might be difficult to setup in the regular game. Specifically, we want a way to run many, many path finding queries to test performance. 

This is most likely easiest to do as a new separate scene and would make for a good introduction to some of the basic part of the game. 

But if you prefer to do it as a new game object with a special controller that could easily be disabled, go ahead. :)

**Comment by FilippoLeon** [comment]
What about a save game? We could a series of save games that are always listed in load, and are never cancelled (some sort of scenarios?)

Relevant to https://github.com/TeamPorcupine/ProjectPorcupine/issues/336.

**Comment by Mizipzor** [comment]
That's another good idea. Maybe I bit more involved. Maybe we end up with all.

**Comment by sboigelot** [comment]
Closing this issue for now, apparently there is not a huge request for it and we are all using specific savegame for specific tests.

**Comment by mikejbrown** [comment]
Maybe a wiki section for useful savegames?
