### ISSUE TITLE
[Bug] ? Character is not MoonsharpUserData

### ISSUE THREAD

**Issue by FilippoLeon** [TeamPorcupine/ProjectPorcupine#371]
A LUA script (cannot find which one) is trying to access the Character class, which is not LUA-UserData.

I think we can safely add [MoonsharpUSerData] to Character, since it makes lots of sense.

**Comment by relinu** [comment]
Fixed in #374

**Comment by FilippoLeon** [comment]
I think this issue has been fixed, right?
