### ISSUE TITLE
Unity scene broken

### ISSUE THREAD

**Issue by Sommerbo** [TeamPorcupine/ProjectPorcupine#377]
I downloaded  a fresh copy of the latest version (at 126 commits) using Download as zip option
First it crashed unity when I double-clicked on the scene. Then I opened unity and tried loading the scene and got these error messages:

![image](https://cloud.githubusercontent.com/assets/21068792/17830745/34429534-66d5-11e6-9ad5-7b14550a73c6.png)

Unity version: 5.3.4f1
And the scene it self doesn't run. Maybe it is just me and I am doing something wrong, but it is probably worth looking into.

**Comment by relinu** [comment]
Update Unity to 45.4f3

**Comment by Sommerbo** [comment]
Thanks.

**Comment by Mizipzor** [comment]
Remember to close this issue if an update solves the problem. :)

**Comment by pjhoodsta** [comment]
Thanks. I also had same problem

**Comment by Sommerbo** [comment]
Now it opens without problems.

But minimum required version of Unity 3D should be shown somewhere.

**Comment by Mizipzor** [comment]
It says so in [CONTRIBUTING.md](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/CONTRIBUTING.md).

**Comment by Sommerbo** [comment]
Oops! My bad, I just glanced at that when Quill first uploaded everything.

**Comment by Mizipzor** [comment]
To be fair, this is probably something you should be told _before_ you start _contributing._

**Comment by Sommerbo** [comment]
To be extra fair. Version info was added/updated less than 24 hours ago. And I wasn't trying to contribute I was trying to run the code.

**Comment by RodRitter** [comment]
Guys, we are in the beginning phase of an awesome project with a lot of contributions happening all the time. Things like this happen.
