### ISSUE TITLE
[Discussion] Allowing furniture to replace furniture of the same type.

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#384]
While updating furniture.xml to include typeTags for everything that was missing it, I realized that with the Door typeTag in place on the Airlock, you could now replace an airlock with an airlock. I'm assuming this would be considered undesirable behaviour for this and any other furniture capable of replacing its own typeTag, but thought it best to ask for opinions, in case there are use cases where this may be a desirable behaviour.

**Comment by RodRitter** [comment]
Definitely undesirable in my opinion. Waste of material

**Comment by gunthergun** [comment]
Is this ever useful ? I think it is always undesirable !

**Comment by koosemose** [comment]
I don't think so, but thought I should ask in case someone has a good use case to consider leaving it as-is for. Keep in mind this could potentially apply to anything... but yeah, I don't expect there to be any good cases for replacing an object with itself.

**Comment by gunthergun** [comment]
I would suggest you just add just a simple check if you try to replace something if it is not the same object ? But I can see you deconstructing an airlock for an normal door if your base has expanded enough and you want to travel faster inside

**Comment by koosemose** [comment]
Yeah, it's a pretty easy check (though I will may invert your logic, and fail if it is the same type). But this solely covers an airlock replacing an airlock (or any other object replacing itself.), otherwise what an object can replace will be controlled by its xml definition.

**Comment by Ceddini** [comment]
A case for this feature comes to my mind: Rimworld godmode.
When you have Godmode enabled, you are able to replace an object with itself or rather you're able to replace any object.
So it is useful for map creators to create custom scenarios and thinks like that.

**Comment by koosemose** [comment]
Alright, that's a good one, though probably best implemented as a separate thing (if godmode or devmode is on, allow anything to replace anything.

**Comment by Tranberry** [comment]
Would this work if I misplaced a furniture (that is bigger than one square)? 
![misplaced](https://cloud.githubusercontent.com/assets/16529/17831583/f7e6f630-66ec-11e6-8a4c-5eeddbcb6e98.png)

**Comment by koosemose** [comment]
Technically it should, but that would require allowing every furniture to replace itself, which would probably be bad. I suspect this would be better served by a separate system (along the lines of Rimworlds reinstall).

**Comment by vogonistic** [comment]
I'd prefer if most replacements were covered by a deconstruct followed by build. There are some special cases, like we might allow one type of pressure door with another without consider it being open.

**Comment by bjubes** [comment]
I think reinstalling and god mode are seperate issues that can override this behavior on their own when implemented. For now don't let an object replace itself

**Comment by kd7uiy** [comment]
It seems this issue is determined to not be desirable. Perhaps add it to the wiki and close this?
