### ISSUE TITLE
[Discussion] Multiplayer, yes or no?

### ISSUE THREAD

**Issue by UnknownSoldier1** [TeamPorcupine/ProjectPorcupine#387]
I'm right now thinking if it makes sense to make a multiplayer for the game. Since I would like such a feature, I would like to see it. I just don't know what the rest of you think.

**Comment by satch3l** [comment]
I'm open for ideas. But I'd wait until, at least, we reach some kind of alpha stage before we decide on what direction we'd like to take regarding multiplayer.

**Comment by Xeni91** [comment]
I think a RTS like multiplayer would be bad. When we're doing one it should be more of a coop-like game like the eu4 one.
Because it is designed for base building not RTS

**Comment by WardBenjamin** [comment]
I'm definitely open to this, but I'd like to keep a focus on singleplayer features, at least until the game is playable in some fashion.

**Comment by UnknownSoldier1** [comment]
Alright, my thoughts just were that it would be easier to implement netcode now, as there would be significantly less to sync right now as if we would integrate it in a much later state of development.

**Comment by Mizipzor** [comment]
I vote no. 

These kind base builder games (Dwarf Fortress, Rim World, Prison Architect) are almost exclusively single player and for good reasons. For example, a "play through" is insanely long, making for awkward multiplayer games.

And its also insanely complicated. Everything you make must be considered how it effects multiplayer. It depends on how you see it, I think this project is mainly about introducing beginners to game development and the actual game is secondary. As such, multiplayer should be skipped. For now.

**Comment by PalRist** [comment]
How about a simcity-approach, allowing for trade between space stations?

**Comment by sboigelot** [comment]
> How about a simcity-approach, allowing for trade between space stations?

Well that idea was a PR this nigth, didn't made the merge : https://github.com/TeamPorcupine/ProjectPorcupine/pull/330

But there was of course still a lot of work to do in the technologies involved.

> These kind base builder games (Dwarf Fortress, Rim World, Prison Architect) are almost exclusively single player and for good reasons. For example, a "play through" is insanely long, making for awkward multiplayer games.

I disagree, I mostly play them along with my gf, on tv, for hours. She is playing rimworld rigth now next ot me. I would love a multiplayer coop aspect to it, but yes, I agree, it a lot of extra work. Maybe it's too early for a real full-on coop multi

**Comment by UnknownSoldier1** [comment]
@Mizipzor Actually, due to how @quill18  made the code for the game, it might even by possible to sync everything between server/client without any extra work. For example, call Lua code only on the server, sync furniture parameters automatically when they get changed, sync the world automatically etc.

**Comment by bjubes** [comment]
If there's multiplayer, how would modding work? Mods have the ability to completely change the value of goods and add new materials, effectively breaking any chance of a  "trade network".

Multiplayer, even at any small scale, would be require lots of effort and yield very little game play value. Better to keep trading as a player-NPC interaction.

**Comment by kd7uiy** [comment]
I suggest we close this for now. I don't think there's a lot of interest in this for the time being, but we can bring it up again later if desired.

**Comment by vogonistic** [comment]
Agreed.
