### ISSUE TITLE
Refactoring: Minimize the use of unity game objects

### ISSUE THREAD

**Issue by ttyz** [TeamPorcupine/ProjectPorcupine#403]
I would propose to do some refactoring. Because editing the scene is quite complicated using version control, it seems like it would be a better idea to make some kind of a `MainController` (may be reuse the `WorldController`), that will instantiate and call the update methods of all the other controllers. This change will allow us to have only one Unity game object in the scene. 

Also then we could eliminate the `World` singleton, and inject the object to the instances that require access to it only. Which is a very good design goal.

**Comment by Mizipzor** [comment]
Good thinking. :)

**Comment by TheAkashicTraveller** [comment]
Sounds good. I just made this about doing similar for the UI https://github.com/TeamPorcupine/ProjectPorcupine/issues/404

**Comment by ttyz** [comment]
@TheAkashicTraveller I have provided a WIP PR #470, to illustrate my thinking. I think it should be possible to start working on UI using similar approach.

**Comment by TheAkashicTraveller** [comment]
I just quickly did it with all of them and the character sprite no longer shows up :/

**Comment by ttyz** [comment]
@TheAkashicTraveller Yes, some are trickier than others. It is a good idea to do them one-by-one.

**Comment by fre-ber** [comment]
I recommend the name "GameController" for the top level since the World is not enough. ;-)

**Comment by ttyz** [comment]
I have finished all of the controllers in #407, it is still rough but much better, as only `WorldController` remains as a `GameObject`. There is still a KeyboardController which I don't understand yet, and some manager classes, that also can be made to non-MonoBehaviour.

@TheAkashicTraveller I've seen your UIController, great job. Personally I think we could stick with a  pure C# class for this one as well, and instantiate it using the `new` keyword, instead of going through Unity, seems much more elegant to me, but it is a matter of personal preference, I suppose.

**Comment by kd7uiy** [comment]
Should this be closed?
