### ISSUE TITLE
Code Driven UI

### ISSUE THREAD

**Issue by TheAkashicTraveller** [TeamPorcupine/ProjectPorcupine#404]
So in this video https://youtu.be/TU0OkwE67hU?t=5m54s Quill mentions wanting to see to UI be more code driven so that changes could be made to it without editing the _SCENE_ file so as to avoid and make it easier to resolve conflicts. A couple of us have actually put some work into this and I had something working for making part of the UI driven from code. Since then new commits have completely changed the UI, still using the scene, and broken that. If we are going to do something in that vane we need to stop posting commits that change the UI in the scene. UI changes can still be made if we put in a UI Controller object and script and set them up from there. If we're going to do this we need to set up the UI Controller ASAP, so empty for now, and put something in CONTRIBUTING.

**Comment by TheAkashicTraveller** [comment]
If we do this and https://github.com/TeamPorcupine/ProjectPorcupine/issues/403 we need to do that first ans ASAP.

**Comment by bjubes** [comment]
I think that people can still ADD to the scene, but can't make any changes or deletions. But I agree, we need to eventually block scene access when we make a new UI system.

**Comment by vogonistic** [comment]
I'd love to see this. It's almost impossible to get scene merges to work and we can't have modders change the scene.

**Comment by dustinwloring1988** [comment]
If no one has started this yet I will take a shoot at it as I did modify the UI and was working on a setting panel. After I was done with the setting I planed on making it all code driven. Just let me know what you think or if anyone has started on this.

**Comment by TheAkashicTraveller** [comment]
I was going to do it myself

**Comment by TheAkashicTraveller** [comment]
So I just made this https://github.com/TeamPorcupine/ProjectPorcupine/pull/420 so that we can get started. If it get's accepted we can work on seperate parts without introducing conflicts.

**Comment by dustinwloring1988** [comment]
OK sounds good..

**Comment by UDXS** [comment]
What if we integrated Awesomium Web Framework for Unity to create a dynamic editable UI.

**Comment by WardBenjamin** [comment]
Awesomeium is a pretty good way to do UI in Unity, I'm a fan if people want to put the work in. It does have some disadvantages since it's not part of Unity natively, but the native UI system really isn't that great.

**Comment by TheAkashicTraveller** [comment]
https://github.com/TeamPorcupine/ProjectPorcupine/pull/420 got merged so if you tell me what you're doing I can work on some other part.

**Comment by dustinwloring1988** [comment]
If you have not started yet I have the basic part of settings done with one last small Scene Change i dont wanna try to commit it unless you havent start

**Comment by dustinwloring1988** [comment]
I will be on for the next 8 hours so feel to to message me back on here or the last pull request i did - https://github.com/TeamPorcupine/ProjectPorcupine/pull/439.

**Comment by TheAkashicTraveller** [comment]
I probably won't be doing anything tonight, it's half 9 where I am.

**Comment by dustinwloring1988** [comment]
OK if they add my commit soon I will start on taking out all the "links" added in the editor for "on click", "on value change" and adding listeners though code.   Hopefully we have good jump on this by tomorrow.

**Comment by TheAkashicTraveller** [comment]
I figured out how to add the listeners when I was doing this for the older UI. `newWorld.GetComponent<Button>().onClick.AddListener(() => worldScript.NewWorld());` Works for buttons though I couldn't figure out a way to reference the dialog box game objects because they start disabled and 'GameObject.Find()' doesn't work with them like that. Which I think is going to be a pain to figure out as we have even more things doing that now.

**Comment by kd7uiy** [comment]
I believe this is already being done, and thus can be closed.
