### ISSUE TITLE
A couple missing script refrances and functionality

### ISSUE THREAD

**Issue by dustinwloring1988** [TeamPorcupine/ProjectPorcupine#412]
Controllers --> WorldController --> Overlay = Missing Script
Controllers --> KeyboardController = Missing Script
Canvas --> Right Menu --> OverlaySelector = No hook up to anything
Canvas --> Settings Menu = Still needs functionality (Im working on this one as we speak)

Also maybe we should combined the trade sample into the main SCENE and just have a dummy object that we click on to active the trade feature for now??

**Comment by FilippoLeon** [comment]
First three are mine and adressed in https://github.com/TeamPorcupine/ProjectPorcupine/pull/340#issuecomment-241212869, wich, depending on how we want to pull, could take a while(still missing features)

**Comment by dustinwloring1988** [comment]
OK thanks
