### ISSUE TITLE
[Localization] en_US localization issuses

### ISSUE THREAD

**Issue by jakebacker** [TeamPorcupine/ProjectPorcupine#417]
There is no localization for raw iron and smelted iron. Also, the un-localized version of raw iron shows up as en_US_en_US_Raw Iron

**Comment by racerand** [comment]
I will look into this

**Comment by WardBenjamin** [comment]
Thanks @racerand!

**Comment by sboigelot** [comment]
#451 & #435 are speaking about the same issue as part of the item Naming Convention & localization.

#505 opened a vote on the issue of item naming and localization

in the PR #633, the CONTRIBUTING.md file has been updated to add guidelines about this topic.

The issue #301 (Missing a ton of localization) sum the whole problem.

I advice to close this issue, #451 #435 and #505 and tag #301 with the localization tag.
