### ISSUE TITLE
Metal smelter doesn't show the raw iron inventory while stockpiling up to the full stack

### ISSUE THREAD

**Issue by WardBenjamin** [TeamPorcupine/ProjectPorcupine#419]
Until the full stack is there, the raw iron stockpile for the metal smelter is there but isn't shown. After there's 50 raw iron, it is shown and decreases correctly.

**Comment by mattpott** [comment]
Is this still open?

**Comment by koosemose** [comment]
This bug no longer seems present. Closing.
