### ISSUE TITLE
Desktop git client. Gitkraken 

### ISSUE THREAD

**Issue by nsfranklin** [TeamPorcupine/ProjectPorcupine#421]
I have been using gitkraken. I would recommend it if anyone wants to avoid using bash. Its more powerful than gitdesktop and it actually works.

**Comment by TheAkashicTraveller** [comment]
There are quite a few out there. Git for windows has one and there's also source tree among others.

**Comment by WardBenjamin** [comment]
(SmartGit is my favorite, but I prefer using Bash because it's way more powerful)

Anyway, this isn't really project-relevant, so closing! You might want @quill18 to talk about it in a video or something, idk.
