### ISSUE TITLE
Slowdown: No tile contains objects of type 'Steel Plate' to satisfy job requirements.

### ISSUE THREAD

**Issue by sboigelot** [TeamPorcupine/ProjectPorcupine#422]
When this condition is met the game almost freeze.

Probably the job is trying to search for the inventory evey tick?

**Comment by satch3l** [comment]
I also reach a point where everything freezes an the fps is plummeting. Nothing I can do but restart. Don't know what causes it though. Maybe this is the answer?

**Comment by WardBenjamin** [comment]
This is probably a pathfinding issue, see #345

**Comment by Mizipzor** [comment]
@WardBenjamin Hold on I believe this one is valid. :) If you place a furniture requiring steel and there is no steel in the world, the log is spammed until there is.

**Comment by WardBenjamin** [comment]
Huh, okay. This is probably still relating to pathfinding in some way though, so the solution might be related/the same. Reopening.

**Comment by Mizipzor** [comment]
Didnt this get rather redundant? 

I thought we common people tagged with [Bug] until you guys could come along and add the label properly and remove the text tag. If not, thats really how it should work in my humble opinion. No need for both. :)

**Comment by WardBenjamin** [comment]
Fair enough!

**Comment by tomik148** [comment]
i have profiler pic here 
![2016-08-20 8](https://cloud.githubusercontent.com/assets/11463094/17833688/0594a57e-6725-11e6-8719-d08d0faeec15.png)

**Comment by bitope** [comment]
I dont think it's a pathfinding issue. It's because jobs are getting aborted and then grabbed again immediately... The character then tries to pathfind to find resources. Just adding a small cooldown to a character when his job gets cancelled fixes the issue.

**Comment by kd7uiy** [comment]
I think this has been resolved.

**Comment by vogonistic** [comment]
Plenty of work that needs to be done for this to be perfect, but the worst offenders are being worked on.
