### ISSUE TITLE
Settings menu and Options menu are not dialogs

### ISSUE THREAD

**Issue by NogginBops** [TeamPorcupine/ProjectPorcupine#423]
This just seems inconsistent as dialogs where inplemented for just this reason.
This would allow them to me modal too.

**Comment by dustinwloring1988** [comment]
OK I can do that. Sorry wasn't think about that when I did it

**Comment by dustinwloring1988** [comment]
They are now :)

**Comment by NogginBops** [comment]
@dustinwloring1988 What PR?

**Comment by dustinwloring1988** [comment]
i dont remember but i submitted it about 16hrs and it was accept about 12hrs ago
