### ISSUE TITLE
[Suggestion] Automatically build walls

### ISSUE THREAD

**Issue by satch3l** [TeamPorcupine/ProjectPorcupine#429]
What do you think about walls being build automatically when placing floors? 

Alternatively it could be added as a feature together with other form floor tools like circles and lines.

**Comment by Mizipzor** [comment]
I prefer some kind of meta tool called **room** that placed floors encircled by wall. Sometimes you want to place just floor, and it wouldnt make sense to have to fight that mechanic.

**Comment by Mizipzor** [comment]
Why close?

**Comment by WardBenjamin** [comment]
@Mizipzor I closed this because people didn't seem to like the feature. I'm opening a new issue (or, actually you can do it), about the room tool suggestion.

**Comment by Mizipzor** [comment]
Fair enough.
