### ISSUE TITLE
Naming standards

### ISSUE THREAD

**Issue by racerand** [TeamPorcupine/ProjectPorcupine#435]
I am working on setting the right text on the different inventory items selection_panel info. This is made hard by their not being a naming convention. Only few inventory items have been added "Steel Plate" and "Raw Iron" but shouldn't they be called "inv_steel_plate" and "inv_raw_iron" in code? As they all will go through the Localization system to have the right UI text, a very informing naming standard in code seems useful.

`Steel Plate=Steel Plate` doesn't feel good in code.

**Comment by Sommerbo** [comment]
Agreed! This needs addressing soon.

**Comment by racerand** [comment]
I am working on implementing it on what already exists, so if this it what people like, the already coded stuff will be done.

**Comment by racerand** [comment]
Could also be "inv_steelWall" as the standard.

**Comment by racerand** [comment]
Or "inv_SteelPlate" which would be same standard as for furniture

**Comment by svmnotn** [comment]
I think we really need to go over what the standards are for code names vs shown names, because as it stands the art uses the en_US names, other things use the objectType, and then the localization uses something entirely different.

**Comment by TomMalbran** [comment]
It might also be a good time to implement an xml with the inventory types metadata (similar to the one for furniture), which for now it might only include the object type ("inv_Name") and the max stack size, and later additional settings per inventory type can be added to that file.

**Comment by racerand** [comment]
I agree with you @svmnotn. The images right now use the en_US names, which is also currently the same as the objectType. Localization right now would match "inv_steel_plate" which I like. But in furniture there is currently no set naming conventions, as quill started with but never fully implemented "furn_SteelWall", and later commits have use "Power Generator". So just in general I think we need to take care of naming standards soon.

**Comment by svmnotn** [comment]
@racerand as do I, thus why #451 was made ;)

**Comment by vogonistic** [comment]
Closing old issues for inactivity
