### ISSUE TITLE
Idea: Technology

### ISSUE THREAD

**Issue by BeefEX** [TeamPorcupine/ProjectPorcupine#44]
I would like to implement technology and science. I am asking here if you would like to see it in the game or if working on it would be pointless :smile: . My idea is that it would work similary to technology trees in KSP or Civ, where you have to unlock technologies one by one. On start player would have basic technology that would unlock few other technologies and so on. Here is my plan.

1.1 - Job priority system (There would be few different categories of jobs and plazer will be able to specify the priority of each one like you can in RimWorld)
1.2 - Custom science job
2 - Implementing furniture unlocking
2.1 - Technology definition file
2.2 - Linking furniture definition files to technology definition files (Every furniture would need to specify the name of technology that unlocks it)
3 - TechTree rendering

What do you think about it?

**Comment by emilkris33** [comment]
I say definitely eventually, but right now? A lot needs to get done before technology would even make sense. At the very least a more game-like game and additional building are necessary for this to work.

But hey maybe laying the ground work early could be good later on.

**Comment by Xeni91** [comment]
I think a research tree like Civ or KSP would be kinda meaningless. They are already in space so it would be more appropriate to implement more like a mission system. Like Housten requests x materials for transport to erath/generic home planet, or we send you 5 more ppl so prepare furniture x 10 times.
But research would, in my eyes, make less sense.

**Comment by BeefEX** [comment]
@emilkris33 thats exactly why i wanted to make it that early
@Xeni91 thats good idea too, but maybe they can be researching techonologies that are not yet researched on earth, or they escaped earth and there is nobody left there and they need to re-research all the technology they had on earth

**Comment by Xeni91** [comment]
@BeefEX Yeah you called it, what setting are we in and what is nessesary to make this setting work. Before we can discuss or decide those things we should get the game in a way that makes more sense. Add more furniture, add events, generate RNG for events. Like groundwork were more people can start of. But for specifics it is way to early.

**Comment by emilkris33** [comment]
I think i will retract the last line of my earlier comment about "early ground work"
A lot of decisions about central game mechanics are necessary to implement this as evidenced by the radically different ideas for a progression system outlined above. So i vote that we wait for more features and a clearer idea of the game before implementing anything like this.
