### ISSUE TITLE
Compiler error when BUILDING

### ISSUE THREAD

**Issue by Sommerbo** [TeamPorcupine/ProjectPorcupine#441]
Error message:
Asset/Script/UI/DialogBox/FileSaveLoad/DialogBoxLoadGame.cs(14,7): error CS0246: The type or namespace name "UnityEditor" could not be found. Are you missing a using directive or an assembly reference? 

Shows up twice. Only happens when building not while running the game in Unity editor.

**Comment by TheRiven** [comment]
I believe you have to remove all the `Using UnityEditor` lines for the actual build to work successfully. I am sure that's something I had to do when building something previously.

**Comment by Sommerbo** [comment]
Can't you use compiler directives? I think I saw something like that earlier today.

**Comment by bjubes** [comment]
http://answers.unity3d.com/questions/316805/unityeditor-namespace-not-found.html

googled and found this. If you make a custom editor it has to be wrapped in preprocessor tags so that it only compiles in the editor.

**Comment by Sommerbo** [comment]
Gah.. I have fixed it but Git is driving bonkers.

**Comment by Sommerbo** [comment]
I finally have PR up #456

**Comment by Sommerbo** [comment]
And now a cleaner PR #463 Removes unnecessary dependency on UnityEditor and reimplements the functionality with standard IO-library

**Comment by kd7uiy** [comment]
I'm relatively certain this one has been resolved, and should be closed.

**Comment by vogonistic** [comment]
Agreed, closing.
