### ISSUE TITLE
Non-Code Naming Standards

### ISSUE THREAD

**Issue by svmnotn** [TeamPorcupine/ProjectPorcupine#451]
Currently nothing really follows any set standard as #435 brought up.
So, here are the ones I'm proposing and lets discuss this:
- Anything inside Furniture.xml is named as follows: `steel_wall` afterwards, in code the `furn_` can be appended at the beginning.
- Lets make something like Furniture.xml for items, so Inventory.xml. The naming here would match furniture, so things inside would be `raw_iron`, and then in code the `inv_` is added.
- For the UI, it is a mess... some of it is doing well and using `menu_` and other parts are not. So let's just use `button_` for all buttons?

Here is also a good place to decide between `furn_SteelWall` and `furn_steel_wall`, as shown I prefer the latter but I can see a lot of the former already in the project (the latter in only in the translation keys).

-------
I will try to update the above as comments come in until this can be formalized into the CONTRIBUTING.md

**Comment by bjubes** [comment]
So any button that opens a menu is prefixed with `menu_` or `button_`?

**Comment by svmnotn** [comment]
... yeah.. I think just changing all buttons to be `button_` will just be easier on translators, and the ones making the buttons

**Comment by bjubes** [comment]
i agree

**Comment by racerand** [comment]
I really like this naming scheme and will begin implementing it for furniture and inventory.

**Comment by racerand** [comment]
Actually, I think the naming scheme should be 100% consistent, so that it will always be 'furn_steel_wall' otherwise I think it might get confusing later on.

**Comment by kd7uiy** [comment]
I believe this was fixed with #855, and this can now be closed.
