### ISSUE TITLE
[Bug] Massive Performance Drop with Tapped Workers

### ISSUE THREAD

**Issue by GamerInspired** [TeamPorcupine/ProjectPorcupine#452]
So I grabbed to latest build to do some play testing, so that I have more of an idea how everything is going. And I found a major issue.

It occurs if you have workers trapped inside a room (this wasn't intentional) and they want to get raw ore from outside it. The error is no path to desired location but it also tanks the frame rate to the point unity crashed.

Also while I'm making this post the metal smelter isn't a job like the mining drone?

Feel free to separate these issues out.

Also sorry for no images, didn't have time to grab any.

**Comment by bjubes** [comment]
does the error spam the log? If so the log may be causing the slowdown/crash, not the actual logic.

**Comment by GamerInspired** [comment]
Forgot to mention that they did have access to a mining drone and a metal smelter (6 metal smelters because I didn't won't to wait for metal plates) inside the room.

**Comment by GamerInspired** [comment]
I couldn't tell you if the error log spammed or not since it was unity that was also dying. It was less than 1fps and I was having trouble trying to close unity.

**Comment by GamerInspired** [comment]
If you need me to get images/ more information I can but will take a little bit.

**Comment by cskiwi** [comment]
Same here, the logging wasn't the issue, and it's already hapening for 2 days for me ...

**Comment by kd7uiy** [comment]
I'm fairly sure this is resolved.
