### ISSUE TITLE
Logger.log doesn't point back to calling line when double clicked 

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#453]
Since `Logger.log`  eventually calls Debug.log, when the debug message is clicked in unity it opens up the line `Debug.Log(message);` in logger.cs. I know that the line that called `logger.log` is in the stack trace, but it requires opening that file and searching for the line, which slows down bug fixes significantly. Is there a way to make the debug log point back to which script called `Logger.log` to save time?

**Comment by NogginBops** [comment]
We would either have to make our own debug window (which I think is on the todo) or append the stack trace to the message.

**Comment by bjubes** [comment]
The stack trace is in the message, but you can't double click the message to jump to that spot

**Comment by Mizipzor** [comment]
Yes, this is one of the main drawbacks of having a custom I didnt think there was a way around it but now that you bring it up I did some googling and there seems to be [some people] that have a custom logger that solved this. I'll look into it. :)

**Comment by bjubes** [comment]
[This asset](https://www.assetstore.unity3d.com/en/#!/content/11521) is exactly what I think this project could use. It has callstack navigation (what i opened this issue to discuss) and custom categories which would fix spam in the log. 

Maybe we could try to make our own version?

**Comment by Tranberry** [comment]
I would stay clear of any paid or not 'free' asset.

**Comment by bjubes** [comment]
YES!
