### ISSUE TITLE
In game FPS counter doens't agree with Unity's FPS counter

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#455]
![FPS-mismatch](https://cloud.githubusercontent.com/assets/7608114/17834160/c2427cec-6701-11e6-91c0-991fced8444b.PNG)

**Comment by zwrawr** [comment]
the in game fps counter is a unity asset (right?).

**Comment by zwrawr** [comment]
```
namespace UnityStandardAssets.Utility
{
    [RequireComponent(typeof (Text))]
    public class FPSCounter : MonoBehaviour
```

So unity is disagreing with unity

**Comment by bjubes** [comment]
knowing unity, probably neither!

**Comment by bjubes** [comment]
Actually, I built the game on #456 and then the FPS stayed around 60. Maybe it works in builds, but not in the editor?

**Comment by zwrawr** [comment]
Editor has to deal with the editor + game + logging so it's normally slower

**Comment by dustinwloring1988** [comment]
Thats a good question

**Comment by bjubes** [comment]
assuming this is because of editor overhead, and as such is a non-issue
