### ISSUE TITLE
Making special floor type only available outside

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#461]
I'm working on a special floor type that lets characters walk around outside the base without floating away (when this eventually gets implemented). A sort of railing/ladder thing that they can climb along.

My problem is making it so that this type of floor can only be built in the outside room. I don't think there is support for that yet? I know that for furniture there is a valid position check, but does the same thing exist for floors?

**Comment by bjubes** [comment]
maybe check if its in room 0, which is reserved for outside?

**Comment by abackwood** [comment]
No I get that. I mean: if this was a furniture I'd make a custom IsValidPosition() method that checks against exactly that and tells the build system it can only build there. But since this is a floor type, the build system doesn't check that.

One option I see is changing the DoBuild() method in BuildModeController, but it feels a bit hacky to change

`if ( 
                t.Type != tileType && 
                t.furniture == null &&
                t.pendingBuildJob == null)
            {
               ...
            }`
`
to add some condition like

`... || (tileType == TileType.SPECIAL_FLOOR && t.Room == OutsideRoom()`

**Comment by svmnotn** [comment]
@abackwood maybe make some sort of extendable `CanBuildHere` function?

**Comment by svmnotn** [comment]
by the way, if you are going to change that file [this line](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/Scripts/Controllers/BuildModeController.cs#L167) has a typo.

**Comment by racerand** [comment]
Maybe now would be the time to maybe move floor type to an xml file? And making custom LUA available for floor? Seems like a thing that could be useful.

**Comment by abackwood** [comment]
I might need some help with connecting to the LUA scripts if i go that route. I followed the tutorials but I'm worried I'll mess something up

**Comment by racerand** [comment]
Try it out and see what happens.
