### ISSUE TITLE
Right Menu is anchored to bottom left :/

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#462]
![capture](https://cloud.githubusercontent.com/assets/7608114/17834274/75c95890-6706-11e6-8775-9bb58e389f9d.PNG)

Obviously this is very easy to fix, but requires modifying the scene. Should this be fixed now or left for now until  #404 is implemented?

**Comment by quill18** [comment]
Yeah, no -- that's incredibly annoying.  Fixed.
