### ISSUE TITLE
[Bug] Floor tile doesn't show when the floor clicked, if furniture is clicked first.

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#468]
It seems like the menu options are click on click off, which is different than the bottom buttons. Ideally it should be the same, toggle between menus.

![gif](https://cloud.githubusercontent.com/assets/5951269/17834700/34bb8de6-671a-11e6-9f11-7d03aab25d2a.gif)

**Comment by Tritaris** [comment]
#447 should fix it when pulled
