### ISSUE TITLE
[Bug] Drag area holds when letting go over UI elements

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#469]
It's a bit hard to see from this, , but I will say that I let up on the dragging over the UI element. Once released, the dragging is still functional in visual, but doesn't actually do anything.

![gif](https://cloud.githubusercontent.com/assets/5951269/17834736/0d2e474e-671c-11e6-8bbb-a286877056d8.gif)

**Comment by Randshot** [comment]
Fixed in #470 pull request
