### ISSUE TITLE
Decide on  a good way of dumping excess inventory

### ISSUE THREAD

**Issue by lameox** [TeamPorcupine/ProjectPorcupine#47]
# Proposal for a System to handle inventory dumping
## The Problem
I just finished a first refactoring pass over the Character's Job handling functions and in doing so also stumbled over a few places where inventory had to be discarded. 

As of now, the Inventory just gets dumped to the floor, and if that does not work, it is just deleted and thus leaked. 

I already laid the foundation for any kind of new system in my first refactoring pass (see #45) by implementing a stubbed out function DumpExcessInventory() and replacing the old discard snippets with it. 

However i did not implement any functionality other than null-ing the inventory, as i feel this is an issue that needs to be discussed first. I have some approaches in mind, that i would like to talk about.

### The simple one
The naive approach, in my oppinion, is looking for the nearest empty tile, going there and dumping the currently held inventory. 

**Advantages**
- Easy to implement
- Easy to understand for new contributors

**Disadvantages**
- Not really flexible/extensible at all
- Clutters the ground with items thus making it visually unappealing
- there needs to be some logic to check, weather the tile we want to dump in is a tile where, i.e. a job is queued. This would lead to suboptimal behaviour of our workers where they would rearrange items on the floor repeatedly in the worst case.

### Integration with the inventory manager
The solution I would like quite a bit more would be some form of integration with the InventoryManager we already have. I would like to have all furnitures and jobs to register at the InventoryManager for items they accept. Then, when a character has inventory to dump, he/she can bring those items to the nearest inventory that accepts those items and only if it cant find any revert to dumping on the floor.

**Advantages**
What i really like about this method, is that quite a few features can be implemented this way:
- Stockpiles that only accept certain items
- Separation of carrying jobs and building jobs. Currently we have no way of letting one character bring ressources for a job and another executing said job, even though that might be quite a bit more efficient
- Designated Carriers and Builders. The carriers would go about and ensure the requested items list stays empty
- Priority system for requesting. An oxygen generator might need batteries more urgently than a stockpile trying to fill up
- Pooling of regionally close requests for the same items (i.e. when building a wall). Carriers could then bring i.e. 20 steel plates at a time and then move about in the destination area, thus fulfilling multiple carrying jobs at once
- Multiple item accepting Systems. There might not always be the need for items to be visible to every other entity on the map. Rather there could be a system the working characters see, one that a automated factories robots can see and so on. This would help relieve cpu stress and also serve to divide up a complex system into smaller manageable ones. This could also be nice for some factorio style logistic robots.
- Based on a system like this there might also be cool interactions for stuff like different maps/regions (maybe we can land on a planet in the future) and easy item transfer between them (a spaceship can see two such systems and thus "link" them)

**Disadvantages**
- Quite a bit more initial work to implement
- Harder to understand as it is more complex
- More edge cases we will have to test when changing something in the future. This should be unit-testable though.

## Final Thoughts
I think the second approach would give us a really solid foundation for future expansions on the inventory system. It also should be less complex in the long run, as we dont have to program each and every new behaviour in by hand but can let the priority and callback system handle them for us. 

I also think, that in doing this, it will be easier to integrate with our lua/xml resources as it mostly comes down to a priority field and one or two scripts.

However the decision to implement such a system should not be made by me but rather the community. Let me know what you think and also if we can find another system that is even better for the problem at hand ;)

Regards,
Jan

**Comment by BeefEX** [comment]
I would vote for Integration with Inventory Manager. If you want to help with implementing i would love to do so.

**Comment by SquareMan** [comment]
I think that the integration with the inventory manager would be the best call. Although it may be more tricky to implement, we'd probably need a similar system eventually anyway.

**Comment by vogonistic** [comment]
I think this is still a relevant issue. Does someone want to have a go at building it?

**Comment by SquareMan** [comment]
I think I'll give it a shot. Might take me a couple days because of school work but I'd like to attempt it.

**Comment by kd7uiy** [comment]
What is the status of this?

**Comment by SquareMan** [comment]
I'm working on this now and have some very basic functionality in place. I didn't start right away because I've been very busy but it should be ready later today or tomorrow, depending on if I run into major issues.

**Comment by vogonistic** [comment]
@SquareMan Got an update on this?

**Comment by SquareMan** [comment]
Sorry been so busy, my car has been broken down, back-up car broke down, tons of work. Haven't been able to do as much work as I would have wanted. What I DO have done is the Character talks to the InventoryManager and can drop extra inventory items on the ground for now. I've got to figure out how to A: Find a path to an accepting inventory, and B: Make the Character go there and deposit the inventory.

**Comment by kd7uiy** [comment]
No worries man, stuff happens. I think just dropping it on the floor is probably fine for now, we can always improve the functionality if we need to.

**Comment by SquareMan** [comment]
Yeah, I think I'm gonna figure out a way for the InventoryManger to store references to accepting inventories, then just make the extra teleport there until the pathing is figured out, but maybe comment it out or disable it somehow so that only dropping on the ground is used.

**Comment by vogonistic** [comment]
#1219 contains a simple DumpState that finds a nearby tile that is either empty or of the same type and where the characters inventory fits.

**Comment by kd7uiy** [comment]
#1393 adds in a function that will dump goods to a nearby tile that is empty or has goods of the same type. It isn't used for dumping goods, but it could be.

**Comment by koosemose** [comment]
#1219 has been merged, so this should be taken care of. Closing.
