### ISSUE TITLE
On high res display UI gets very small

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#471]
I use an old analog monitor as a second display, so when I noticed how big the UI got I tried it the other way around. On a 5K iMac, the UI gets very, very tiny.

<img width="2672" alt="screen shot 2016-08-20 at 9 57 09 pm" src="https://cloud.githubusercontent.com/assets/7608114/17834855/714ffd30-6721-11e6-9563-d5ec4a17137f.png">

hopefully this can be easily fixed when the UI goes code-based.

**Comment by dustinwloring1988** [comment]
I think this is because the canvas is set to scale - constant pixel. Quill18 talked about this in one of his videos. Easy fix though

**Comment by bjubes** [comment]
thats good to hear. I was afraid this would require a hacky workaround

**Comment by Fogsight** [comment]
Setting UI Scale Mode to Constant Physical Size will fix it, as well as fix any text blurriness, as a side effect. If we want to keep Constant Pixel Size setting, UI would have to be resized manually and fonts would have to be bumped up to double the size to fix the blur, (while scaling down text objects).

So I would vote for Constant Physical Size change as a simplest solution to both.

**Comment by ComputerOverlord** [comment]
It was made CPixS to prevnt text bluriness. If we did that we'd get bluriness.

**Comment by Fogsight** [comment]
It is not 100% sharp, but it is not blurry. It is a good trade off, because when you are using resized text to fit it on buttons, it becomes pretty blurry indeed, with Constant Pixel Size.

I think CPS should only be used when catering to specific device with set resolution. There's no other fix for variable resolutions. And it can be made crisp later by using custom 3D font.

**Comment by mikejbrown** [comment]
Is this still a bug?

**Comment by bjubes** [comment]
i think so, unless a PR for CPS snuck by

**Comment by vogonistic** [comment]
Yeah, it's still a problem. All UI is super tiny on my retina display.

**Comment by bjubes** [comment]
so can we just change it to CPS or will that screw up the entire UI in the process?

**Comment by WizzardMaker** [comment]
Its a bit old, but I have a Script that modifies the cameras view rectangle to keep a specific aspect ratio (like 16:9 4:3) which makes the camera always see the same on different resolutions. It scales the canvas to the right size. (the gif is from my game, so dont worry about the game in the background)
![screen](https://cloud.githubusercontent.com/assets/7768485/19093384/34ebd50c-8a8b-11e6-9912-4556157e77d7.gif)

**Comment by mikejbrown** [comment]
@WizzardMaker go ahead an make a PR with it so people can try it out! :grinning:

**Comment by koosemose** [comment]
Solution in place, though it may require a bit more tinkering for perfection, but it is functional at the least. Closing (finally).
