### ISSUE TITLE
[Discussion] Floor tile looks poor

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#474]
![capture](https://cloud.githubusercontent.com/assets/5951269/17834937/f4a886e0-6724-11e6-90b5-f364df902cec.PNG)
It looks to me like compression was turned on for the tile. I suspect this will be a fairly easy fix, it might require writing a custom HTML parser or something similar, I'm not really sure without looking at the details.

**Comment by abackwood** [comment]
Wasn't the jitter added by design as "grime and dirt"?

https://github.com/TeamPorcupine/ProjectPorcupine/pull/424

**Comment by koosemose** [comment]
Perhaps not so much a bug, but perhaps not the best way to have a grime and dirt thing by having it in the image itself. Our bases will always be dirty, plus the jitter and fuzzing regularly repeated does make it look more like just bad image quality.

**Comment by kd7uiy** [comment]
Hadn't realized it was intentional. I suspect the best way is to either make it more obvious, or to not have the effect for the lines. I suspect the latter is the best option, for now.

**Comment by quill18** [comment]
I'm not personally a fan of this particular floor either. I definitely looks more "too much jpeg" rather than just weathered/rusty. That being said, I'm not too stressed over it because I'm sure we'll be replacing almost every are asset at some point in the not-to-distant future.

**Comment by kd7uiy** [comment]
I'm going to close this in favor of https://github.com/TeamPorcupine/ProjectPorcupine/issues/1004 , which proposes a better solution to how the tile should be managed, and will require new tiles anyways.
