### ISSUE TITLE
[Bug] Floor building with PR#267

### ISSUE THREAD

**Issue by Tritaris** [TeamPorcupine/ProjectPorcupine#477]
This merge #267 introduces a bug when building the floor. When placing a row of flooring south from the starting area. The jobs start at the end of the column but are unreachable so they throw an error: `ArgumentNullException: Argument cannot be null.`  in `Character` line 177 and spawns in anyway.

![1b](https://cloud.githubusercontent.com/assets/282954/17835249/6943f488-6731-11e6-94b2-6f4a182e29fe.png)
![2b](https://cloud.githubusercontent.com/assets/282954/17835250/694a673c-6731-11e6-912d-fc791de2ecd6.png)

**Comment by Randshot** [comment]
I found a way to fix this one in 2-4 lines but I don't know if anyone is interested in this one?

**Comment by vogonistic** [comment]
@Randshot I'm making a slightly larger commit that fixes this and another annoyance I've had. I'll add a reference so you can review.

**Comment by vogonistic** [comment]
@Randshot Never mind. I noticed that you had a similar solution that I'll merge. Can you push the PR that fixes this issue?

**Comment by Randshot** [comment]
@vogonistic Ok. Wait a moment.

**Comment by vogonistic** [comment]
Fixed in #481
