### ISSUE TITLE
Removing a furniture doesn't clear it's job

### ISSUE THREAD

**Issue by Xeni91** [TeamPorcupine/ProjectPorcupine#48]
When you place a Mining Drone Station and Deconstruct it the Job remains on the workable tile and the AI is stuck on it.
Trying to figure out where the furniture job may be cancelled or if the job queue should be reset.

**Comment by BeefEX** [comment]
Fixed in #58

**Comment by JosephBywater** [comment]
I believe this can be closed @Xeni91
