### ISSUE TITLE
Issue tracking responsibility

### ISSUE THREAD

**Issue by Grenkin1988** [TeamPorcupine/ProjectPorcupine#496]
Who is responsible for this?
At least to close not relevant issues?
4 pages of issues already :-)

**Comment by Tranberry** [comment]
is this really an issue?

**Comment by Grenkin1988** [comment]
I would say it really hard to track where is real issue and open discussions.

**Comment by gunthergun** [comment]
@Mizipzor suggested an issue tracker in #458 that could help those who are responsible

**Comment by Mizipzor** [comment]
@Grenkin1988 There are four pages of issues because we have that many. The project is young and there's **so** much to do. We have indeed reached the point where no single person can look at every issue. This is to be expected.

@gunthergun This is that issue tracker. :)

**Comment by GamerInspired** [comment]
I have this project being watched, so when anything happens it comes up in the notifications area. I then tick all the localisation issues/PR (unless it looks important). Then I just read through the rest.

It defiantly keeps me busy with the amount that come through.

**Comment by andallas** [comment]
I'm interested in helping with this project, and am going through the issues right now. I agree that help is needed to keep things organized. I don't mind helping and am very familiar with github and C# (C# developer professionally).

**Comment by bjubes** [comment]
Well in don't think anyone but the gatekeepers and OP authors can close issues. So technically it's your responsibility to close your own issue

**Comment by NogginBops** [comment]
@bjubes If someone commits a PR which says "Fixed #xxx" then that issue will close automatically when merged

**Comment by andallas** [comment]
Agreed, but since this project has a lot of people who are new to git and open source projects, mistakes are bound to happen. I think it is reasonable to have 'mods' for a project this size who help out with this.

**Comment by Mizipzor** [comment]
@andallas Theres a handful of them and last I heard @quill18 think thats quite enough. You can help a lot without additional permissions. The project is young, a lot of really eager people is jumping on tasks left and right. There will be chaos for a while. Going through the issues and participate in the discussions and help decisions be made is far more valuable than closing them.

**Comment by bjubes** [comment]
@NogginBops not really.  only if the gatekeeper keeps that "fixes #???" in the PR when they sqash merge, so it's more likely to happen if you put it in the title of the PR

**Comment by Mizipzor** [comment]
@bjubes Although thus far they have kept them, right? If you just accept the pull request on the web interface I *think* it does a rebase rather than a merge, but it doesn't squash. And even if they do remove parts of commit messages I think they are at fault, they shouldn't do that. Auto closing of issues is an awesome feature that should be used.

**Comment by vircung** [comment]
Check out [waffle.io](https://waffle.io/) for https://waffle.io/TeamPorcupine/ProjectPorcupine

**Comment by kd7uiy** [comment]
For the time being, we'll ask for volunteers, who is more than welcome to recruit others, who will keep an eye on issues. See #1088

It's also good to keep an eye on your own issues, and periodically review old issues to see if they can be closed. That's a great thing to do for someone who doesn't want to jump in to coding right away.

Suggest we close this.
