### ISSUE TITLE
[Question] Current status/plans on UI

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#497]
I know there has been a fair amount of work and talk regarding the UI, particularly about going code-based. Is there further work going on in this aspect, particularly code-based UI? 

I'm primarily interested as I need to implement a toggle for Dev Mode in the UI, as opposed to it's current hackish position as a variable that need to be changed manually, and don't want to edit the scene if there's likely to be further work soon to either further refine the UI or make it code-based.

**Comment by Sommerbo** [comment]
If you end up doing this can you add a simple way of either spawning some of all resources or a toggle to ignore material cost for building?
It would help out when testing more than one furniture.

**Comment by koosemose** [comment]
Currently the only function of dev mode is that it automatically builds furnitures and floors, which includes not using materials.

**Comment by sboigelot** [comment]
This has been implemented, we can close the issue
