### ISSUE TITLE
[BUG] Minions Take steel from workshops to stockpiles

### ISSUE THREAD

**Issue by Xeni91** [TeamPorcupine/ProjectPorcupine#499]
I just testet some of the maschines and the power cell from #370 
which needs steel to work. In my test the Minions are looping between stockpile and maschine with the steel.
I made a showcase video: https://youtu.be/mgGTe-ZraXk

**Comment by bjubes** [comment]
I know that the smelter had a similar issue #339 which probably had a fix similar to this one.
Does this bug also happen in the master branch because if not i think this issue should be a comment on the PR.

**Comment by Xeni91** [comment]
Well I was not able to create the scenario in master because I there is no workshop that requires more than 5 steel.

**Comment by sboigelot** [comment]
@Xeni91 is this still an issue? If not, feel free to close it ;)
