### ISSUE TITLE
Walls do not update their graphics when adjacent walls are deconstructed.

### ISSUE THREAD

**Issue by zwrawr** [TeamPorcupine/ProjectPorcupine#50]

**Comment by BeefEX** [comment]
Is anyone working on this?

**Comment by BeefEX** [comment]
Fixed in #56

**Comment by bjarnejorgensen** [comment]
I have an alternative solution ... but somehow it got mingled up in PR #52 

However I am not sure I can get them untangled.

**Comment by gunthergun** [comment]
#442 fixed this please close this issue :)
