### ISSUE TITLE
[Discussion] Lua with needs

### ISSUE THREAD

**Issue by gunthergun** [TeamPorcupine/ProjectPorcupine#501]
I looked at the need system proposed here: #492 and saw that the growth functions were added in via c# which is good for now, for testing. But I think we should let modders decide when and how a need grows with lua code. What do you guys think about this ?

**Comment by quill18** [comment]
:+1: 

Seems like it's just a matter of moving the Need.Update logic to LUA, which is a pretty simple thing to do as a follow-up PR by someone.

**Comment by kd7uiy** [comment]
I believe this should be closed, @vogonistic ? The referenced issue has been merged, so...
