### ISSUE TITLE
[Bug] Menu buttons dont work

### ISSUE THREAD

**Issue by wilcomega** [TeamPorcupine/ProjectPorcupine#503]
The menu buttons at the bottom of the screen just dont do anything

here is the error that i think is related to this issue as its the only one unity gives.
`NullReferenceException: Object reference not set to an instance of an object
MenuController.Start () (at Assets/Scripts/UI/InGameUI/MenuController.cs:31)
`

**Comment by koosemose** [comment]
Are you on the latest commit? Is there anything else that could have gone awry with your local repository? They work fine for me, except for of course World and Work which I'm assuming are just placeholders.

**Comment by Dalfi** [comment]
just checked this too and they work also fine.

**Comment by wilcomega** [comment]
Let me check on master, i am on the latest commit with my own changes, but i didnt change anything about the menus

**Comment by wilcomega** [comment]
IDK why or how but its fixed.....

**Comment by misspellted** [comment]
This experience is pretty much what I go through at least once a week at work. :smile:

**Comment by koosemose** [comment]
If you're using Github desktop, it sometimes gets... weird... I've had things inexplicably fail that I never touched and that should otherwise work in the current build just not work until I force it to reset my repo.

**Comment by wilcomega** [comment]
Thats the thing, i am not using github desktop, i use git bash
