### ISSUE TITLE
[Bug, Easy] Changing menus should drop the active build.

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#508]
If I'm building a furniture, and click on the floor, we should get rid of the furniture building menu.

**Comment by bjubes** [comment]
#447 already done

**Comment by bjubes** [comment]
@quill18  sorry no I messed up. Hes talking about minimizing the menu when you click on the floor, not the floor menu button. 
Please Reopen

**Comment by kd7uiy** [comment]
![gif](https://cloud.githubusercontent.com/assets/5951269/17837837/d74245de-678b-11e6-82b9-aeac57c0c921.gif)

Hopefully this GIF shows the issue a bit better. When the furniture menu is opened, it should cancel the floor building, and visa versa.

**Comment by kd7uiy** [comment]
@vogonistic Perhaps you could re-open this?

**Comment by kd7uiy** [comment]
I'm not sure if this issue was resolved. I'll check this tonight and close it if it has been.

**Comment by kd7uiy** [comment]
This hasn't been resolved yet, but I'll fix it on my own.

**Comment by Grenkin1988** [comment]
@kd7uiy Now I get it.
