### ISSUE TITLE
!GetIsActive() log spam

### ISSUE THREAD

**Issue by fre-ber** [TeamPorcupine/ProjectPorcupine#510]
I am getting this log message spammed a lot, it has no stack trace or any additional information and looks as if this is due to this: https://fogbugz.unity3d.com/default.asp?817637_vtisjldmljj7vsdc 

So it is probably not an issue with this project per-se, but I thought it would be nice to have a notice about it here, both to see if others also have this problem but mainly to give some kind of explanation for it if people come across it.

EDIT: Actually, reading that bug report more carefully, it might not be the same thing, but at least it is stated in there as "Regarding error, it's known issue".

**Comment by kd7uiy** [comment]
Has this been resolved? If so, please close the issue.

**Comment by vogonistic** [comment]
A lot of spam has been fixed. We can open new issues if there are remaining problems.
