### ISSUE TITLE
Localization system documentation?

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#512]
a comment on  #509 told the author to use the localization system, but I realized that there is no obvious information available on how to integrate new changes into the localization system.

I'm sure it exists somewhere, probably in a PR discussion, but could someone move it to either the contributing.md or wiki so that there's a clear reference to point to.

**Comment by UnknownSoldier1** [comment]
Edited the wiki: https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Localisation
