### ISSUE TITLE
Discussion: Furniture events

### ISSUE THREAD

**Issue by FilippoLeon** [TeamPorcupine/ProjectPorcupine#515]
Right now, we can have the furniture items respond to Update() events with an OnUpdate() LUA function.

It is conceivable that a furniture object responds to many different events, such as OnInstall, OnUninstall, OnHitByProjectile?, etc.

I think, right now, there is no plan to change this behaviour. If there is no plan to address this issue I propose the following.

I propose a more flexible way to handle this events, using a generalization of the OnUpdate business.

The Furniture.xml items will have elements of the form
```
<Action event="OnUpdate">callThisLuaFUNC</Action>
<Action event="OnInstall">callThisOtherLuaFUNC</Action>
```

etc.

This is then parsed by the XmlReader and handled in code wherever necessary. We should then offer a documentation on when/how this "events" are triggered.

**Comment by bjubes** [comment]
So you propose we add On"event-name" tags you can put in the furniture XML and then implement them in the XML Parsing code so that lua code can react to different furntiure events? Kinda like:
```

 <OnUpdate FunctionName="OnUpdate_Door" />
 <OnUninstall FunctionName="OnUninstall_Door" />
 <OnDamaged FunctionName="OnDamaged_Door" />

```
If this is what you mean, it sounds good to me!

**Comment by FilippoLeon** [comment]
Forgot to tag the xml code I wrote as code ,fixed now.

The idea precisely that one.

**Comment by FilippoLeon** [comment]
Closed in favor of https://github.com/TeamPorcupine/ProjectPorcupine/pull/682.
