### ISSUE TITLE
Proposed PR convention for changing the scene

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#520]
Let's make it really obvious when there's a PR that changes the scene. Why? The scene doesn't merge well, and as a result any change to it could cause serious issues. So this should be specifically called out in the PR request, so that if someone wants to make a change to the scene, they can look to see if there's already a PR in relation to it.

Let's just put [SCENE] at the beginning of any title for a PR that changes the scene.

**Comment by Kreol-Dev** [comment]
We probably instead of this should decompose the scene into more modular parts, so anyone who want's to add UI, for example, would need to create a new scene, and it will be loaded additively, instead of one blob-scene.

**Comment by kd7uiy** [comment]
I'm not really sure how to do drag and drop scenes. I suppose we could set it all up with prefabs maybe, and that would reduce the need to edit the scene somewhat? Just edit the prefab, not the entire scene, unless you are doing something to the entire scene?

**Comment by Kreol-Dev** [comment]
Create a new scene - add your UI.
Store it in a specified folder.
From the main scene search that folder and call LoadLevelAdditive for each of them.

**Comment by kd7uiy** [comment]
Okay then, let's use this issue to decide how to organize everything. Most
of the Scene is UI, so more organization than that is required.

On Aug 21, 2016 12:36 PM, "Виталий Буланенков" <notifications@github.com>
wrote:

>

> Create a new scene - add your UI.
> Store it in a specified folder.
> From the main scene search that folder and call LoadLevelAdditive for
each of them.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/TeamPorcupine/ProjectPorcupine/issues/520#issuecomment-241267608>,
or mute the thread

**Comment by vogonistic** [comment]
We've merged a PR that removes most controllers from the scene today (#407). I think that's the right path. Load as much as possible through code, including the UI (#537).

Both of these actually help us with modding and testing inside Unity.

**Comment by sboigelot** [comment]
As most SCENE modification are now done via code, we can probably close this issue.
