### ISSUE TITLE
[Discussion] Modding management

### ISSUE THREAD

**Issue by ttyz** [TeamPorcupine/ProjectPorcupine#528]
I have mage a simple modding solution (It just came along, did not plan ahead, so no issue was here before) #522. So may this will be a place to discuss further actions on this topic.

Currently moddable in PR:

- Furniture.xml
- Furniture.lua
- Sprites

Plans

- Localization
- Mod manager (install and update from, probably, GitHub)

**Comment by NogginBops** [comment]
@ttyz Isn't localization already moddable?

**Comment by ttyz** [comment]
@NogginBops Yes, it is on a global scale, But if you create a standalone furniture mod, there will be no localization for it in the game, so you would have to provide your own lang files. There is no support for this yet.

**Comment by NogginBops** [comment]
@ttyz Good point. Didn't think about that.

**Comment by NogginBops** [comment]
@ttyz I'm working on making the localization moddable.

**Comment by ttyz** [comment]
@NogginBops That is great! You might want to wait for PR #522, because it has a class for loading mods in place. You can access it in `WorldController.Instance.modsManager`, `getMods` method will return a list of `DirectoryInfo` objects to look into. You can check it out in my branch.

**Comment by NogginBops** [comment]
@ttyz I was thinking exactly that. :)

**Comment by ttyz** [comment]
@NogginBops It's in the main repo now. I will go on with github integration

**Comment by NogginBops** [comment]
@ttyz Is done! #541

**Comment by ttyz** [comment]
Will wait for #537, before making a PR for github integration, because there will be quite a bit of new UI.

A good new goal would be to make Inventory moddable. I will not be able to start working on this till next weekend, so if anybody is interested, you are welcome :)

**Comment by Tranberry** [comment]
Have we talked about making the core furnitures and materials into a 'core mod'? I might quite possibly be blind.

**Comment by ttyz** [comment]
I  should have missed this discussion also. The idea of a core mod is great and easily implementable at the moment for furniture, so someone can start on this. The only issue is that Mods directory is in `.gitignore` at the moment to prevent somebody from accidentally pushing their mods to the repo, but it is possible to override with the `-f` flag when doing `git add`

**Comment by Tranberry** [comment]
couldn't it essentially be a mob but loaded from elsewhere?

**Comment by svmnotn** [comment]
Well, I was just thinking about this. I thought of making something akin to:
`StreamingAssets/TeamPorcupine`
`StreamingAssets/ModName1`

sort of like KSP does, where all the mods just go in the same folder as the 'official' data.

But how would replacements be handled? if a mod also defines a SteelWall which one do we take? Do we only do the official? do we do the mod? what if 2 mods add the same thing? I think all these questions need to be answered before proper modding support is fully introduced.

I think it would work if we just do something like `ModName_` and then all the relevant `furn_` and `inv_`

**Comment by Tranberry** [comment]
imo, mods should overwrite the core.

**Comment by svmnotn** [comment]
but do mods overwrite each other?

**Comment by Tranberry** [comment]
mods, should throw an error if they conflict. Just not the 'core mod'. But that's just my opinion.

**Comment by vogonistic** [comment]
I think putting furniture, inventory and most graphics in a core mod is a great way to do things. That way we ensure that all the apis exist. 

Other mods should be able to change what is in the code mod or add to it.

**Comment by vircung** [comment]
Another point to think about should be to rules for overwrites.
- what if 2 or more mods changes attributes of item from core
- what if 2 mods defines item with same name but w/o intention of overwrite
- can mod depend on other one

**Comment by svmnotn** [comment]
we need to make sure that we can "call lua across mods" as @vogonistic pointed out on discord.

**Comment by vogonistic** [comment]
Mod dependencies are probably good. Not sure how to track collisions unless they define what they add and overwrite.

**Comment by svmnotn** [comment]
well we could always just keep track of which mod adds what and then have them not collide?

For example `teamporcupine_furn_door` is different from `myawesomemod_furn_door`

**Comment by Grenkin1988** [comment]
A lot of work done for this. Closing for now
