### ISSUE TITLE
Astronauts cannot pathfind through doors or airlocks.

### ISSUE THREAD

**Issue by jakebacker** [TeamPorcupine/ProjectPorcupine#529]
After some time, astronauts just get stuck at doors and don't go anywhere. As soon as the door or airlock is removed, they start moving. When the world was first loaded, they would move through fine but after a bit they would get stuck. If I never removed the doors they wouldn't get stuck.

**Comment by ComputerOverlord** [comment]
It's not a problem with them, It's with the doors.

**Comment by kd7uiy** [comment]
I haven't observed this to be an issue in the latest build. Perhaps this can be closed?

**Comment by vogonistic** [comment]
This works now.
