### ISSUE TITLE
Lighting, Lights and Darkness

### ISSUE THREAD

**Issue by JosephBywater** [TeamPorcupine/ProjectPorcupine#533]
I think that Lighting is going to be a nice feature to have in the game. This issue will be to serve as a discussion about lighting and how it will be implemented I was thinking that we could use Unity's lighting feature however, I think that that is more suited 3d games. 

So, how should we implement lighting and darkness in the game. (I'll make a list here):
1. Unity lighting
2. A mask with different opacity depending on how light the area is.
3. @Sommerbo - https://www.assetstore.unity3d.com/en/#!/content/24083

**Comment by Sommerbo** [comment]
Instead of writing our own we could look at: https://www.assetstore.unity3d.com/en/#!/content/24083

**Comment by Tranberry** [comment]
I'm going to repeat what I said elsewhere; I would think that making things ourself will make us free from any licensing hassles that might occur.

**Comment by FilippoLeon** [comment]
What about the license of that shadow asset? Is see a pro version but cannot figure out what are the limitation of the free version.

In theory it could be used, but maybe implementing from scratch (for a project like this) might be a better solution, if somebody is willing to do it. Even if it means reinventing the wheel.

The idea of adding lighting is a good one.

**Comment by fre-ber** [comment]
One who re-invents the wheel knows much better how the wheel works.

**Comment by Sommerbo** [comment]
I tried finding any info on the license but I failed. Unity's licensing seems very open but still who knows.

**Comment by Sommerbo** [comment]
Heard from developer of 2ddl, it uses MIT license so no problem there.
If we want to use it.
