### ISSUE TITLE
[Question] PRs question

### ISSUE THREAD

**Issue by Grenkin1988** [TeamPorcupine/ProjectPorcupine#539]
I'd really want to know what are general principles on merging PRs. Quite often there are commits with new PRs, and some old one, even without conflicts waiting something.
P.S.: I am not complaining, just interesting to know :-)

**Comment by Tranberry** [comment]
if you where on the discord chat you would probably get an answer faster https://discord.gg/h7erR

**Comment by Grenkin1988** [comment]
@Tranberry Are you kidding? That's involve speaking with real people. That's worse what could happen :-)

**Comment by Tranberry** [comment]
I'm using it only for text, almost like reading a comic. :dart:

**Comment by Randshot** [comment]
@Grenkin1988 You can chat OR use voice communication on Discord servers.
![discord](https://cloud.githubusercontent.com/assets/7832423/17838602/9a0b4792-67d1-11e6-9308-107557ece505.PNG)
