### ISSUE TITLE
Stacking materials

### ISSUE THREAD

**Issue by satch3l** [TeamPorcupine/ProjectPorcupine#54]
If you have a stock pile area with a resource of a non-maximum amount (i.e. 15), when a mining droid have gathered max resources (50) the character will first move to the stock pile and carry the non-max resource (however it will still lie there) then he goes and get the max resource exchange it with what he has in his hand and go back to the stock pile and pile it on the old non-max resource which then dissappears. Then he goes back to fetch the non-max amount which he left at the mining drone.

**Comment by emilkris33** [comment]
I suspect this has already been fixed by #46 and we only have to wait for the pull request to be accepted.

**Comment by satch3l** [comment]
Then this can be closed.

**Comment by QuiZr** [comment]
For now it works like this: https://youtu.be/Q4Hdzo0KaU4 Later character should pickup as much as he can carry and distribute it but for now this is fine (i guess?).

**Comment by emilkris33** [comment]
@QuiZr Short of redoing the entiry stockpile job creation system that is all we can hope for.
