### ISSUE TITLE
[Discussion] Health system

### ISSUE THREAD

**Issue by FilippoLeon** [TeamPorcupine/ProjectPorcupine#544]
I saw talking about needs and enemies. But I searched for health related issues and found no mention of it, so correct me if somebody is working on it/if there is agreement on not working on it right not.

That being said, I'd like to start thinking about an health system. I'd like to work on it, but assemble a team of people to do a cooperative effort.

I have ideas and am willing to work on the health system.

Before I write down my opinions, I'd like to ear from you/get a general idea of interested people and what  is the consensus on how to do the system (and if it is not too early to do so).

**Comment by gunthergun** [comment]
I would gladly help :)

**Comment by MANDAL0R3** [comment]
Currently there is this https://github.com/TeamPorcupine/ProjectPorcupine/pull/135. So there's something begin worked on.

**Comment by FilippoLeon** [comment]
@gunthergun, @BeefEX, would you like to plan something with the temperature system?

**Comment by longtomjr** [comment]
Can we get the status of this please?

**Comment by koosemose** [comment]
We have at least some form of a health system. Closing this now
