### ISSUE TITLE
[Bug] Removing designation removes the designation image but job still exist somewhere

### ISSUE THREAD

**Issue by gunthergun** [TeamPorcupine/ProjectPorcupine#546]
If you setup the designation for a steel wall for example and then remove them. The image goes away but if you don't add any new jobs the characters go and still build those designated walls but we do not see them. I looked into it and see that when CancelJob is called there is no job in the jobqueue when this happens. So that means the job we are trying to cancel cannot be removed from queue, this means probably the character cached it somewhere. The strange part is though that the character does other jobs first. I do not know the code for the character very well but do they plan ahead and keep jobs somewhere as this was working before ?

**Comment by Randshot** [comment]
Hm, that seems interesting.
The character normally caches the job it is currently working on in Character.myJob and also removes the job from the job queue to prevent other characters from also taking this job.
In my last PR #517 I added a waiting queue for jobs for which there aren't enough resources to complete.
Maybe, I missed something there? Still looking into this though.

**Comment by gunthergun** [comment]
Yeah that could be it maybe if we also cancel jobs from the waiting queue as well if we cancel jobs this will solve it

**Comment by Randshot** [comment]
I am currently trying this :)

**Comment by gunthergun** [comment]
I tried it as well and it seems to fix it by adding `World.current.jobWaitingQueue.Remove(this);` to cancel job in job class, but it throws me some errors I think. Please try and look at this because I do not know if you have any flags set when you add something to your waiting queue :)

**Comment by Randshot** [comment]
@gunthergun I can't seem to reproduce your described behavior.
Could you maybe explain it again or make a gif?

**Comment by gunthergun** [comment]
Do you know how to make a gif ?

**Comment by Randshot** [comment]
I have never made one, but you probably make them by recording a video and then converting it into a gif with some online service.

**Comment by gunthergun** [comment]
ok just build a metal smelter and a mining drone... put a designation for some steel walls down where the characters can reach it and then directly afterwards delete those walls. in some time they will be build by the characters.. i will see if I can get a video up

**Comment by gunthergun** [comment]
The video is uploading to youtube :)

**Comment by gunthergun** [comment]
https://www.youtube.com/watch?v=B6wHURZR_O4&feature=youtu.be here you go :)

**Comment by Randshot** [comment]
Thanks. Found the issue and fixed it.
The problem was that in the OnInventoryCreated callback, it tries to access the job which leads to the error.
Will create a PR shortly :)

**Comment by gunthergun** [comment]
Thank you, in the commit put that it fixes this so that it will automatically close if merged :)

**Comment by bjubes** [comment]
That is, if the gatekeeper keeps your wording when they merge
