### ISSUE TITLE
Building in optimized pattern

### ISSUE THREAD

**Issue by satch3l** [TeamPorcupine/ProjectPorcupine#55]
When structuring a stockpile in any size bigger than 2x2 the ai is building from bottom to the top, meaning he is first building the first row then goes back to the bottom to start the second row. A more effective way would be to either build the nearest tiles first or otherwise in a s type manner such as when the ai gets to the end of a row he starts on the top of the next, eliminating the walking time to the bottom of the row.

**Comment by emilkris33** [comment]
Otherwise know as: "The entire job selection system is unoptimal and should be entirely redone."
But yes this is definitely a issue

**Comment by lameox** [comment]
We should probably merge this into #63 and keep that in mind when we (potentially) re-write parts of the job system

**Comment by vogonistic** [comment]
Closing this in favor of #86
