### ISSUE TITLE
Setting up the Project during first installation

### ISSUE THREAD

**Issue by Ferr013** [TeamPorcupine/ProjectPorcupine#550]
Hi, I've encountered a problem when I've tried running the game in Unity 5.3.2f1
There were some issues showing in the console, and when I 've tried to fix those many more came out...
(the first was around the Instantiate method, I added Quaternion.identity as third parameter and things got worse)

I think I should tweak some parameter in the inspector or maybe set up something differently.
I 'm not very experienced neither with programming or english, so I hope I have explained correctly the issue!
It would be nice to have a page on the wiki side to set up the project for quite noobs like me :)

I hope I 'm not abusing this platform, and if there is something to correct don't mind to reprehend me.

Here is the project as I see it when Unity opens:

![screengithub](https://cloud.githubusercontent.com/assets/21153774/17839044/000d90e4-67dd-11e6-8061-ea11c039f030.png)
)

**Comment by zwrawr** [comment]
Update to unity 5.4
Might have to redownload unity

**Comment by Ferr013** [comment]
thank you!!!
I'll try right now :+1:

**Comment by zwrawr** [comment]
What Parameters were in your call to Instantiate () , any of these should work
```
public static Object Instantiate(Object original);
public static Object Instantiate(Object original, Transform parent);
public static Object Instantiate(Object original, Transform parent, bool worldPositionStays);
public static Object Instantiate(Object original, Vector3 position, Quaternion rotation);
public static Object Instantiate(Object original, Vector3 position, Quaternion rotation, Transform parent);
```

**Comment by bjubes** [comment]
If updating unity worked, please close this issue.

**Comment by Ferr013** [comment]
Yes it worked!!!
Thank you again
