### ISSUE TITLE
Move localizations to a separate repository and download them at start of the game.

### ISSUE THREAD

**Issue by QuiZr** [TeamPorcupine/ProjectPorcupine#551]
This will clean up commits in main repo and also ensure that everyone has up-to-date version of localization (as it will be downloaded at runtime).
@quill18 should create a separate repository in TeamPorcupine purely for .lang files (of course if this issue get's nice feedback).

**Comment by QuiZr** [comment]
I don't see any way to assign me to this issue but I will be working on it tommorow (utc time).

**Comment by Mizipzor** [comment]
I dont think the commits are a problem, if you find them noisy its easy to just check the history of one folder (or file). I think people are jumping on the localization tasks because they are very easy to do, little coding required and very easy to get right. And you know what? Thats a good thing. If these are newcomers to opensource projects its perfect to have theses tasks so that they can practice Git and Github.

**Comment by FilippoLeon** [comment]
What we can do is pull all localizations into a separate branch, that gets merged every now and then to master.

**Comment by svmnotn** [comment]
@Mizipzor you are right that commits do not pose too much of an issue, however the second part of the issue (keep localisations up to date) is definitely useful, especially when things are getting added so quickly. And by having them on a separate repo they can be looked at without looking at the other 36 PRs thus changes to that can be done quicker.

**Comment by Mizipzor** [comment]
Hm, and with a separate repository we could be more liberate with write access. I still kinda see it as bureaucratic nonsense but if I'm the only one opposing, well... ^^

Are we linking the repositories with `git submodule`?

**Comment by QuiZr** [comment]
I would just keep them separate and download at build/runtime

**Comment by svmnotn** [comment]
downloading at runtime would be best

**Comment by ttyz** [comment]
it is possible to do via modding, PR #541 should help with that.

**Comment by FilippoLeon** [comment]
I'm not that fond of this idea: it will be an unnecessary layer of extra complexity.

What if there is no connection? + extra strain on servers. + somewhere needs to host this.

**Comment by Tranberry** [comment]
@FilippoLeon wouldn't the last one be cached?

**Comment by ttyz** [comment]
@FilippoLeon mods are installed once and updated occasionally, also those can be hosted on github, just in a personal repo

**Comment by QuiZr** [comment]
Current localization should be added at build time. Every time that there is a connection there should be a check if there are any new changes on repo. If so there should be downloaded and cached locally. For now we can use github just fine.

**Comment by FilippoLeon** [comment]
In that case it should be fine.

**Comment by Mizipzor** [comment]
Surely English are included by default? Or are you trying to turn this into an "always online" game? Cant play if it cant talk to github?

**Comment by NogginBops** [comment]
@Mizipzor English is always available.

**Comment by QuiZr** [comment]
@Mizipzor 

> Current localization should be added at build time.

**Comment by Mizipzor** [comment]
Great! My work here is done. :)

**Comment by vogonistic** [comment]
We could easily cache the localization locally, so you only need it in order to download new localization and anything but the default the first time. We could even bundle it with a version download check and keep a separate version for localization.

Language changes will need to have a separate review since the fact that the text shows up doesn't mean that it was a better description of a Gas Generator in Silvan than what we had before.

**Comment by svmnotn** [comment]
for this we could just do some hash checking? although it might make testing the game with newer lang file difficult...

**Comment by vogonistic** [comment]
We need the release numbers so that we know if it belongs to version `1.1` or `1.2` of the game, so we might as well know that we have localization `1.1.14` installed and `1.1.16` is out.

**Comment by QuiZr** [comment]
I've been working on this over at https://github.com/QuiZr/ProjectPorcupine/tree/download-localization-from-web - My best guess is that the version number will be the branch number in ProjectPorcupineLocalization (or whatever the name ends up being) repo. I don't think that having numeration on specific localization version is necessary (as in current paste it will lead to version numbers like 0.0.9321). imo silently updating at the start of the game with option to disable that in option screen would be best.

**Comment by QuiZr** [comment]
Yeah, after an hour of thinking some sort of localization version number does make a lot of sense >.>
