### ISSUE TITLE
Names starting with an underscore and StyleCop

### ISSUE THREAD

**Issue by zwrawr** [TeamPorcupine/ProjectPorcupine#553]
There are a fair few variables in multiple classes that start with an underscore , StyleCop is currently complaining about these , Which one needs to change

**Comment by Grenkin1988** [comment]
variables

**Comment by Mizipzor** [comment]
Lets take a closer look at some of the rules enforced by StyleCop for fields.

> SA1309 : CSharp.Naming : Field names must not start with an underscore.
> SA1308 : CSharp.Naming : Variable names must not start with 'm_' or 's_'.
> SA1306 : CSharp.Naming : Variable names and private field names must start with a lower-case letter.

However, not all fields are treated alike.

> SA1303 : CSharp.Naming : Constants must start with an upper-case letter.

It's important to remember that we can turn these rules _off_. But not modify or replace them (well technically we can, StyleCop is open source but... lets not even go there). So if we decide on something else we give up a lot, like the automatic checking, the zero room for interpretation and an end to the debate and all that I've already listed in many issues now.

Do I agree with everything StyleCop says? Of course not! No one does, and thats the point, there will be no single set of rules everyone agrees on. Like that thing where it has different rules depending on what kind of field it is, I hate that.

But what is far more important than an objectively _good_ style is a style that is **well defined** and easy to **enforce**.

**Comment by zwrawr** [comment]
Also the current defacto standard for call backs is cbSomeThing which also make StyleCop upset

**Comment by Mizipzor** [comment]
It should be CbSomeThing in that case. Or, rather, CallBackSomeThing to avoid acronyms (its not obvious to everyone). But as a rule, I prefer to avoid hungarian notation prefixes entirely.

**Comment by NogginBops** [comment]
@Mizipzor OnSomeEvent is also an alternative to cbSomeThing

**Comment by Mizipzor** [comment]
@NogginBops Thats another good alternative, I personally only use for the handlers of an event or callback, rather than the event itself. But that splitting hairs now. :)
