### ISSUE TITLE
Private public method ordering and StyleCop

### ISSUE THREAD

**Issue by zwrawr** [TeamPorcupine/ProjectPorcupine#554]
Style cop wants all private methods to come before public methods, this would mess with regions and may stop methods being placed in a logical order. Opinions ?

**Comment by FilippoLeon** [comment]
private before public? I'd rather have public before private. In that case: I wouldn't enforce it, because there may be exceptions, but it should be a "suggestion".

**Comment by NogginBops** [comment]
I don't think that adds to readability. I don't think there could be a rule for this, its too case specific.

**Comment by Mizipzor** [comment]
It's the other way around. Public before private. The rationale is that you read the class from top to bottom trying to understand it and then it makes sense to only show the public first. Only if you dive deeper (quite literally) you see the private methods. 

While grouping methods logically is a good though in spirit its really hard to do well. Methods tend to change a lot and you dont want to move them around much. Not to mention it adds another level of decision you have to take when you write the code.

Another reason, and this is an overall point of StyleCop, is for easy merging. The thought is that if two people write the same class they should look the same and in a perfect world merge flawlessly. 

There is only one single argument really for grouping the methods by category or whatever you would call it (another problem) and that is that if you read or write that logic you only wanna see that code. Theres a _far_ better way to do this, any decent editor allows you to collapse methods to one line. You should be able to see any "grouping" you want in any class in a few clicks.

**Comment by zwrawr** [comment]
*I tottaly get this* mainly making the issue so that people see this and stop doing it , i've just made a pull request to improve styles of models and these were the things that i was seeing that are harder to correct . #558

**Comment by Fogsight** [comment]
I don't think that ordering of methods should be enforced, if there are too many methods in one class it is a sign that it should be refactored into separate classes. This would lessen the probability of conflicts as well.

**Comment by bjubes** [comment]
Maybe do this from now on, but moving methods in previous code will cause needless PR conflicts for almost no gain

**Comment by Mizipzor** [comment]
Even classes with very few methods benefits from structure.

**Comment by quill18** [comment]
I think that as the Porcupine matures a bit and becomes broader, these "base" files will start getting touched less frequently (especially if we avoid making massive classes).  Maybe if a file hasn't been modified in a couple days and has no PRs against it, it'll mean that it's a good contender to be cleaned up to StyleCop standards.

**Comment by Mizipzor** [comment]
@quill18 not to mention that StyleCop fixups are **great** beginner tasks. It requires just the most basic understanding of C# syntax, since StyleCop tells you very specifically what needs to be done. If you just want to try the git/github/pullrequest flow, something like this is great.

**Comment by vogonistic** [comment]
Closing old issues for inactivity
