### ISSUE TITLE
[Bug] Metal Smelter smelts without anyone working it

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#557]
![bug](https://i.gyazo.com/2fb21fad04a7f11b640252ed4b0571ac.gif)

After a character puts 50 Iron in the smelter, it will make plates without anyone working it. Is this supposed to occour?

Also, shouldn't the metal smelter start making plates when the minimum iron is put it (ie 5 not 50)?

**Comment by Mizipzor** [comment]
I thought it was automatic.

**Comment by UnknownSoldier1** [comment]
Yes, the first is intentional. The second is a a bug i think.

**Comment by bjubes** [comment]
okay, ill submit a new issue with just that one then
