### ISSUE TITLE
Metal Smelter only makes plates when full

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#559]
If you put anything less than 50 iron in the smelter, it won't do anything, but once the metal smelter has a full 50 iron, it makes plates until no iron is left

**Comment by zwrawr** [comment]
Betting is related to #419

**Comment by zwrawr** [comment]
after looking at the code , it seems that the input inventory must be nil until it starts smelting which would explain why its not showing any input inventory until it hits 50.
```

function MetalSmelter_UpdateAction(furniture, deltaTime)
	[ ... ]
	if(spawnSpot.inventory == nil) then
		[ ... make job to fill inventory with iorn... ]
		j.RegisterJobCompletedCallback("MetalSmelter_JobComplete")
		furniture.AddJob(j)
	else
		furniture.ChangeParameter("smelttime", deltaTime)
                [ ... smelt stuff ^^^... ]
```

and then in the job complete call back we make an inventory in the spawn spot tile so then that inventory isn't nil anymore

```
function MetalSmelter_JobComplete(j)
        [ ... ]	
	for k, inv in pairs(j.inventoryRequirements) do
		if(inv.stackSize > 0) then
			World.current.inventoryManager.PlaceInventory(spawnSpot, inv)
                        [ ... ^^^ we make the inventory ony once it's filled up ^^^ ... ]
```

I have no clue how to go about fixing this as i'm unsure how a lot of the lua and furniture stuff is working

**Comment by Randshot** [comment]
The issue was that the inventory would only be 'properly' placed after the job was completed and this means a full stack (50) of steel plates:
`Inventory.__new("Raw Iron", 50, 0)`
