### ISSUE TITLE
[Question]Astronauts cant fly around in space?

### ISSUE THREAD

**Issue by Gixen** [TeamPorcupine/ProjectPorcupine#560]
So i forked, downloaded and testet the scene in unity. After a while i was thinking "Why arent the guys getting stuff?" So do they actually need built floors to zip around and collect stuff on "asteroids" because of the pathfinding? Because that would just seem silly.

**Comment by NogginBops** [comment]
@Gixen I think that this is something that is going to change a lot. But right now characters can only walk on floor tiles and empty tiles that have a floor tile adjacent.

**Comment by WardBenjamin** [comment]
Yep! Right now the characters are pretty limited in what they can do, eventually we need to add some kind of gear that enables limited flight, plus vehicles you can construct and stuff. Also the mining drone needs to actually go mine asteroids and ferry items back to you... :P

**Comment by WardBenjamin** [comment]
Feel free to actually make some of these features a reality!
