### ISSUE TITLE
Making Tile types not be hardcoded

### ISSUE THREAD

**Issue by NogginBops** [TeamPorcupine/ProjectPorcupine#563]
I think that it's not a sustainable idea to just have a enum for the tile type. I think that it would be beneficial to be able to define tiles through a .xml file to allow mods to add custom tiles.

This issue relates to #543 and would mean that the build floor menu would have to be created programatically.

**Comment by racerand** [comment]
Sounds great, just do it!!!

**Comment by NogginBops** [comment]
I'm going to bed. If no one has done it when I wake up I'll do it.

**Comment by kd7uiy** [comment]
This should be a pretty easy fix, if someone wants something to start with.

**Comment by b4ux1t3** [comment]
So, I'm looking in to this, and figured I'd share what I came up with so far.

Functionally, you would need to provide a few things in the XML file (Or maybe there would be a single `tiles.xml` file):

- Name
- Enterability
- A reference to a sprite (or multiple sprites in the case of an animated tile)
- Some other info about the tile

As an example:

    <tiles>
        <TileType>
            Floor
        </TileType>
        <sprite name="FloorSprite" type="Unity.Sprite">
            <location>path/to/sprite</location>
        </sprite>
        <enterability>
            Yes
        </enterability>
    </tiles>


Or something along those lines. I'm not super-familiar with XML (json4lyf), and I think I should catch up a bit in the video series to see what he's doing with config files, but I just figured I'd start brainstorming this in case someone else wants to take it and run with it.

**Comment by NogginBops** [comment]
I would like to do it if no one is going to. But I'm going to bed now (after watching youtube for too long) and if anyone is willing to do this then I'm not going to stop them. (I sleeping how do you think I'm going to stop you)

**Comment by bjubes** [comment]
> ```
    <sprite name="FloorSprite" type="Unity.Sprite">
        <location>path/to/sprite</location>
    </sprite>
```



I suggest instead having sprites link to a tile by name, like how they do for furniture.

**Comment by kd7uiy** [comment]
Agree, tiles should look similar to how furniture looks.

**Comment by b4ux1t3** [comment]
That makes sense. Like I said, I'm a bit behind in the project development in the videos.

@nogginbops I wasn't going to try to steal your feature. Just figured I'd start some brainstorming so you're not starting from scratch tomorrow. :)

**Comment by WardBenjamin** [comment]
Sounds good to me! Tiles being hardcoded has bothered me for a while, since basically nothing in our project is. Thanks!

**Comment by NogginBops** [comment]
I'll be working on this in one hour, so consider this task taken.

**Comment by kd7uiy** [comment]
I believe this is complete, but can you confirm?

**Comment by vogonistic** [comment]
@NogginBops remember to close issues when you fix things.

**Comment by NogginBops** [comment]
@vogonistic Sorry! Forgot. :(
