### ISSUE TITLE
Quality in Settings is not functioning correctly (reversed)

### ISSUE THREAD

**Issue by itay347** [TeamPorcupine/ProjectPorcupine#565]
Basically:
# The items in the Quality Dropdown are reversed:

- When **choosing Low** in the Quality setting, it actually **sets to high** quality.
- When **choosing High** in the Quality setting, it actually **sets to low** quality.

## Why is this happening?

In [DialogBoxSettings.cs](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs#L111):
```
public void OnQualityChange()
    {
        gameSettings.qualityIndex = QualitySettings.masterTextureLimit = qualityDropdown.value;
    }
```
[QualitySettings.masterTextureLimit](https://docs.unity3d.com/ScriptReference/QualitySettings-masterTextureLimit.html) is a texture size limit applied to all textures:

- 0 (the default value) = no limit, therefore it sets the highest quality
- Higher value = higher limit, therefore lower quality.

The problem is **qualityDropdown.value** being set like that:

- **Item 0: Low (when 0 is supposed to be high)**
- Item 1: Med
- **Item 2: High (when 2 is supposed to be low)**

![screenshot_1](https://cloud.githubusercontent.com/assets/15272275/17840454/83a05f58-6810-11e6-86eb-c6900c64a457.png)

## How to fix it?

I am sure that by now you got it and know how to fix it...
_Hint: change the order of the items_

The only thing is... **You need to change the** _SCENE_ **file to fix it**, so @quill18 or one of the managers should do it instead of me messing up everything.

Thats it!

_(Please ignore the fact that this issue is too detailed, but thats how I like it...)_

**Comment by Mizipzor** [comment]
It should be detailed, that's a good thing. :)

**Comment by itay347** [comment]
I'm closing this issue. It is no longer relevant due to @zwrawr's new settings system. (#535 #549 #595)
Notice that currently the Quality Setting is not functional, and that might also be the case with the rest of the settings.
But I'm sure we will fix it in future commits.

_Side Note:_
Gotta say, I love this project for helping me with the learning of game development and using git/github.
**Thanks alot @quill18!!!**
