### ISSUE TITLE
Stockpiles totally broken

### ISSUE THREAD

**Issue by WardBenjamin** [TeamPorcupine/ProjectPorcupine#568]
Nice job whoever did this :P

I have a feeling that some work by @kd7uiy or someone else on the job system is related to this.

Symptoms: Characters don't actually put items in stockpiles even when idling.

**Comment by kd7uiy** [comment]
I think I've noticed this, I think it's looking for only a single type of
food, steel plate being the most likely candidate. No idea what that would
be. Can't look right now.

**Comment by bjubes** [comment]
this is why we eventually need unit tests.

**Comment by mikejbrown** [comment]
The problem seems to be the line `return { Inventory.__new("Steel Plate", 50, 0) }` in Stockpile_GetItemsFromFilter() but I'm not sure the best way to fix it.

https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/StreamingAssets/LUA/Furniture.lua#L80

**Comment by kd7uiy** [comment]
So then nothing I did broke it:-) What we should do is what is suggested, have a function in C# code that keeps track of all of the possible materials, and passes that to Lua. You've got the right spot in the code for sure.

**Comment by jdlaroche** [comment]
I'm not sure that the stockpile code really belong to LUA... we will probably need a stockpile manager and a lot of logic around stockpiles. For example, right now, from LUA, how could we tell the character that if we have 2 stockpiles with each 25 steel plates, he should pick all from tile A and move it to tile B at a very low priority...

**Comment by jdlaroche** [comment]
When you create a new stockpile, a character will build it and then it will try to fill it once. After that, it seems to ignore it completely.

**Comment by Sommerbo** [comment]
Stockpiles aren't broken as much as not implemented yet. In `furniture.lua` there is a function that specify which items to stockpile, current only steel plates are there. And it isn't expandable the function just returns "Steel Plates"

**Comment by mikejbrown** [comment]
Don't know if anyone else is working on it at the moment so I've started working on stockpile logic. Will hopefully put up a (probably) [WIP] PR in the next day or two to see if people think its a good start.
