### ISSUE TITLE
[BUG][ERROR] please help [ANWSER FAST PLEASE] [PLEASE]

### ISSUE THREAD

**Issue by tommyb008** [TeamPorcupine/ProjectPorcupine#569]
Assets/Scripts/UI/MenuController.cs(4,14): error CS0101: The namespace `global::' already contains a definition for `MenuController'

**Comment by tommyb008** [comment]
fast please

**Comment by bjubes** [comment]
Are you on the latest version of the project.
Try running `git pull upstream master`

**Comment by WardBenjamin** [comment]
This doesn't occur on latest master. Try updating and restarting Unity.

**Comment by tommyb008** [comment]
how can i use git pull upstream master?
