### ISSUE TITLE
Communication problems - gitter?

### ISSUE THREAD

**Issue by QuiZr** [TeamPorcupine/ProjectPorcupine#57]
Later we will hit lots of issues when 2 or even more people were working on the same issue. Maybe we should also use some kind of real time chat? IRC is a bit archaic now, I personally hate Discord so maybe Gitter? It has a great integration with git (even in the name!) https://gitter.im I haven't ever maintained an opensource project so I don't know how the organization of this should go, and how this will really impact our community.

**Comment by JosephBywater** [comment]
I agree with this. Even a Slack or Discord channel would be nice too though.

**Comment by zerohawk** [comment]
Slack is a nice free to try 1

**Comment by emilkris33** [comment]
We definitely need something that is more of chat. But people should maybe just post an issue proclaiming what they are working on

**Comment by BeefEX** [comment]
Well Discord is for gamers but I use it a lot and it is relliable.

**Comment by emilkris33** [comment]
Though choosing a system is probably something for @quill18

**Comment by BeefEX** [comment]
@emilkris33 thats right

**Comment by zerohawk** [comment]
@emilkris33 Agreed, though... slack easy, free, git hub plugins ??? awesome

**Comment by QuiZr** [comment]
Yeah, Slack is awesome! But we should wait for @quill18 for a comment.

**Comment by JosephBywater** [comment]
And Slack has Github integration too :+1:

**Comment by Dormanil** [comment]
The problem with the free version of Slack is the pesky 10&nbsp;000 messages limit. You'd think that would never become an issue, but believe me, _it most certainly will._

On the other hand, if we were to get Slack Standard, that would be $6.67 per month _per user,_ billed annually. TeamPorcupine currently has 73 forks, so that would result in a whopping **$5842.92** bill on the credit card of whoever would own the Slack Standard team. Even with only half of those forkers in the Slack, that simply is not feasible.

**Comment by JosephBywater** [comment]
@Dormanil That's why I also mentioned Discord :)

**Comment by QuiZr** [comment]
@Dormanil It will store last 10 000 messages in search cache (and you can search only through them) but other than that all of them will be saved, there is no limit.

**Comment by JosephBywater** [comment]
@QuiZr 
![image](https://cloud.githubusercontent.com/assets/5558617/17737098/2c3859e0-6483-11e6-9410-ac69e95914db.png)

**Comment by QuiZr** [comment]
@JosephBywater Ok, that's weird, they must have changed this... Just checked my slack and yeah - 10k is a "hard limit" now :/

**Comment by Dormanil** [comment]
The only way to get messages in the archive that are past the 10k limit is to pin those messages (obviously before they are hidden). You are not able to see them directly, but copying is possible. 

![snippet 01](http://puu.sh/qEvIg/598137ad8e.png)
![snippet 02](http://puu.sh/qEvNd/5402bf1742.png)

This does not help in any way though, if you just don't know that the message might be somewhat important in a week or two. And pinning literally every message would make the pinned message system completely worthless for its original task -- showing people important things.

**Comment by Tranberry** [comment]
I see no real problem with more than one person working on the same 'feature/bug/whatever' separately, the only problem is the hurt feelings and time spent for the one who won't have his or her changes merged.

I would love to know if there are anything worse than that which could happen in a case like this.

There probably will be 'dissent' between opposing opinions and that will _hurt_ the project, but I believe that is unavoidable however this issue will be tackled.

**Comment by lameox** [comment]
I think those issues will more or less be resolved once we have a few people actively managing the project and assigning/tagging issues, removing duplicates, and reviewing code.

**Comment by ulve** [comment]
I think all new features and all bug fixes should be tied to an issue and that issue assigned else it will never work beeing this many developers.

**Comment by emilkris33** [comment]
Yes we need to use the issue system an once there are people who can assign issues and assign labels that will work. But i still think some sort of chat channel where people can discus what they are working on less formally would be great.

**Comment by JosephBywater** [comment]
@quill18 is on now so maybe we could get a Slack or something similar.

**Comment by ulve** [comment]
I think gitter is fine. Maybe not as slick as slack but its free and have a load of [integrations](https://github.com/integrations/gitter). Even if we need the paied features its [$62.50](https://gitter.im/about/early-bird) a year for 1000 people.

**Comment by FraserKillip** [comment]
I personally prefer slack but Gitter looks good also

**Comment by Mizipzor** [comment]
I think Github works fine. ^^

If two people are really gonna work that closely together on a certain feature, let them work out the communication among themselves.

**Comment by emilkris33** [comment]
@Mizipzor I think the idea here is not aimed at people working close together but for people who are working simultaneously to be able to chat less formally. To ask questions, workout more serious conflicts or just well chat while working on the game

**Comment by bjubes** [comment]
personally i prefer gitter after googling "gitter vs slack" and getting [this](https://medium.freecodecamp.com/so-yeah-we-tried-slack-and-we-deeply-regretted-it-391bcc714c81) but regardless I think a chat is needed especially for a project with people who are learning to code. Whats more convenient than opening up a chat window and getting an instant response on, for instance, how to remove a file from a commit or something of that nature without having to pull your PR off topic by discussing your technical problems instead of the actual feature.

**Comment by vogonistic** [comment]
The biggest point of having either is that you can ask questions without creating an issue.

I like slack, don't really care that they have a limit on message history since it's more transient and not there to provide a searchable history of what everything everyone have ever said. I'm sure gitter is cool too.

**Comment by vogonistic** [comment]
@quill18 We need you to setup a gitter.im account if we want it integrated with this repo. It requires permissions that only you currently have.

**Comment by WardBenjamin** [comment]
I personally am a huge fan of Discord because it has (optional) voice, multiple text channels, permissions, and a TON of other features that Gitter doesn't have.

Plus Gitter's desktop client is really buggy.

**Comment by JosephBywater** [comment]
Anyone could make a Discord I suppose (until @quill18 makes a gitter or something)

**Comment by JosephBywater** [comment]
If anyone wants it, I've setup an unofficial Discord. https://discord.gg/68hkpSA

**Comment by vogonistic** [comment]
Can someone create a PR to add the Discord link to the readme?

**Comment by vogonistic** [comment]
With discord in place and active, I'm closing this.
