### ISSUE TITLE
New wall sprites 

### ISSUE THREAD

**Issue by Spool5520** [TeamPorcupine/ProjectPorcupine#571]
So after some feedback on what the sprites should be like I spent a little time today and made a new wall sprite sheet. Same layout just 64 pixels per sprite instead of 32. Here they are https://s10.postimg.org/x4087w655/wallsprites.png

What do you guys think?

**Comment by Spool5520** [comment]
If someone wants to download the spritesheet from that link and put it in go for it. Im not really sure how to do it.

**Comment by ComputerOverlord** [comment]
Rating ++=

**Comment by Spool5520** [comment]
Im working on electrical cables running along the tops of the walls like in a data center or what ever
You like them though? :)

**Comment by ComputerOverlord** [comment]
@Spool5520 Yeah, I like them.

**Comment by SquareMan** [comment]
Watch quill's new video, it'll teach you how to setup git for this project. Then just replace the old wall sprite with that one (and open unity to make sure the metadata gets updated) and then make a PR.

**Comment by Spool5520** [comment]
Ah ok didnt know he made a new video >.< will do.
