### ISSUE TITLE
StyleCop SA1400: Methods must have access modifiers

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#572]
I dont know how people feel about this one, but personally 
```

void Update() {
    // code
}

```
feels very normal for unity and can be kept as is

**Comment by Mizipzor** [comment]
It's for readability. Not everyone knows the default access. And if you put the access modifier on everything, it kinda aligns better, especially for fields. And you dont have to remember when you need access modifiers and when they can be skipped, StyleCop wants it on everything. I think the rule should stay.

**Comment by fre-ber** [comment]
I vote for keeping this rule.
