### ISSUE TITLE
[Bug] Metal smelter job 'weirdness'

### ISSUE THREAD

**Issue by Randshot** [TeamPorcupine/ProjectPorcupine#577]
This bug was introduced in PR #567.
I can't really describe it, but the smelter job does not seem to get removed or something similar to this.
Also, somehow, the registration for the jobWorked callback went missing, don't ask me how.

I am filing this issue mostly for myself, so that I remember what I was working on.

**Comment by gunthergun** [comment]
Shouldn't this be fixed now as the fix has been merged --> so please close this issue

**Comment by Randshot** [comment]
Oh, sorry. Thought that a mod would have closed it.
