### ISSUE TITLE
[Discussion] Unit Tests

### ISSUE THREAD

**Issue by b4ux1t3** [TeamPorcupine/ProjectPorcupine#578]
So, while I'm catching up with the videos, I'm thinking about all the things that would go so much smoother if we just had unit tests. Then I checked out the issue list and, lo and behold, no discussion on unit tests!

So I'm going to start writing some basic unit tests over the next couple days. If you have a specific _thing_ you'd like me to build a test for, let me know. In the mean time, I'm just going to start from the top of the list of models and work my way down.

**Comment by vogonistic** [comment]
It'd be extremely welcome! Keep us in the loop of progress. There are plenty of people who like to see early versions and have opinions. =)

**Comment by svmnotn** [comment]
please test all the things! it would be awesome if we could auto test PRs so... keep that in mind?

**Comment by ttyz** [comment]
Unit test are awesome, but most of the project is not very test-friendly, because it relies on static calls and public properties, I am trying to fix those. Also it might be a good idea to move all the instantiations to Fabric classes, and may be move most of the dependencies on Unity API to one class that can be mocked in tests.

**Comment by Mizipzor** [comment]
Of course we are going to have (or at least want) unit tests. Thats not even a discussion as far as Im concerned. :)

**Comment by Grenkin1988** [comment]
@b4ux1t3 What test framework are you going to use. I was going to try xUnit, but it tured out it is for .NET4.5

**Comment by b4ux1t3** [comment]
@Grenkin1988 In the short term I was just going to write some basic tests by hand. @ttyz pointed out that a lot of the project is not very testable, so I think a more targeted approach would be beneficial for the time being. 

Specifically, I'm thinking of the stockpile situation (#568). Rather than just writing tests for everything, like I said last night, I'm probably going to start with things that are actually broken, so that those who are working on them have some kind of metric on how they are doing.

Once the project starts to shake out some of its kinks, I'm thinking it would be best to use something like the [Unity Test Tools](https://www.assetstore.unity3d.com/en/#!/content/13802). While I think it is outdated (It looks like it only supports Unity 4.X, unless they just haven't updated the README), I'm sure it can probably be tweaked to work well enough in 5. 

The other option is to just write our own framework. The game, in the end, isn't actually that complicated. Everything is already broken down into nice little units.

Considering I've never done testing on a video game before, I'd love to get input before we get to the point where we need an overarching test framework. For instance, I'm not even sure how I'd go about testing pathfinding.

**Comment by sboigelot** [comment]
Unity support natively NUnit unit test framework,, see https://docs.unity3d.com/Manual/testing-editortestsrunner.html

Also this seems cool: 
https://unity3d.com/learn/tutorials/topics/production/unity-test-tools
https://www.assetstore.unity3d.com/en/#!/content/13802

**Comment by b4ux1t3** [comment]
@sboigelot the fact that it supports nunit is great!  The Unity Test Tools seem great, but it looks like they're tuned for Unity 4.x according to their Readme. I'll do a bit more research when I get back home.

**Comment by sboigelot** [comment]
@b4ux1t3 too bad for the asset, but the first link about NUnit is already great, we can probably hook the NUnit test in a continous integration system too

**Comment by b4ux1t3** [comment]
At home now, did a bit of research. It seems like Unity Test Tools will work with some tweaking, and there are a few tweaks out there already. But NUnit will probably be better, and easier to use on some of our, er, "non-Unity" scripts.

I'm actually in my final week of class this quarter, so I won't have a whole lot of time this week to test them both out. But, I'll do what I can and report back.

**Comment by sboigelot** [comment]
If you have to prioritize because of lack of time, just worry about the NUnit.
Provide just one small PR with on unit test that does nothing, like checking that true == true.
It will already be great and provide an exemple for other devs to extend.

And if you don't have time, don't worry too much :) School and life comes first

**Comment by mikejbrown** [comment]
Unit tests for the Parameter class: #773 using Unity Editor tests (built in since at least Unity 5.3) which is based on NUnit. Thoughts?

**Comment by sboigelot** [comment]
I :heart: it, great work!

**Comment by b4ux1t3** [comment]
@mikejbrown They look great! The only problem I'm having is getting NUnit to actually install. Ran in to the problem a few days ago and haven't had a chance to work on it since then. Did you run in to an error along the lines of:

    Could not install package 'NUnit 3.4.1'. You are trying to install this package into a project 
    that targets '.NETFramework,Version=v3.5,Profile=Unity Full v3.5', but the package does
    not contain any assembly references or content files that are compatible with that framework.

NUnit.Console installed fine, but NuGet doesn't like the base NUnit for some reason. I've checked the docs and googled the error, but the best I can find is "Download the DLL and link directly to that". That might work (I haven't actually tried), but it's hardly a solution, at least for a project like this.

**Comment by Grenkin1988** [comment]
@b4ux1t3 But there is already NUnit in our projects. Specifically in Editor project.

**Comment by b4ux1t3** [comment]
@Grenkin1988 That's what I get for not opening up the project in Unity first. I tried to open it in Visual Studio first (because I already have it open, it's as easy as opening the solution), and it didn't recognize NUnit as being installed. Opened up Unity, bam, NUnit is working perfectly.

@mikejbrown Great job! Thanks for getting us started! Tests look good from what I can see, and run fine now that I'm not being an idiot.

**Comment by sboigelot** [comment]
Unit tests are up and running. We don't have much of them yet, but I think we can safely close this issue.
