### ISSUE TITLE
[Question] Common inventory data in separate class or should every inventory carry the data ?

### ISSUE THREAD

**Issue by gunthergun** [TeamPorcupine/ProjectPorcupine#588]
With common inventory data I mean:
maxStackSize
Price
Name
Description
Things that are common among all the Items with the same name

**Comment by NogginBops** [comment]
This is a interesting issue, if no one has a reason not to I don't see why not.

**Comment by sboigelot** [comment]
InventoryCommon has been implemented, we can close this issue
