### ISSUE TITLE
We need a european gatekeeper.

### ISSUE THREAD

**Issue by NogginBops** [TeamPorcupine/ProjectPorcupine#589]
Right now the three gatekeepers we have are not able to be active during european hours. This creates a lot of pull requests during european hours and when the gatekeepers wake up and starts to accept PRs conflicts are created that will have to wait until the PRs owner wakes up when the gatekeeper is sleeping.

@quill18 What do you think about this?

**Comment by Sommerbo** [comment]
I agree there should be a gatekeeper active during CET hours.
It could be good to have an Australian gatekeeper too. But gatekeepers should not be selected only by timezone.

**Comment by NogginBops** [comment]
@Sommerbo That's true, butI think timezone should be a factor.

**Comment by Xeni91** [comment]
Well this is a Problem we have to endure at the Moment.  The gatekeeper system is a test and it works fine.  To complain about it because time zones conflict with each other is a bit high level complains.

**Comment by Tranberry** [comment]
@Xeni91 if Quill thought he had gatekeepers dispersed around the globe, but don't - would it not be nice to let him know that?

I'm not sure how Quill like the gatekeepers to be managed.

**Comment by Mizipzor** [comment]
Sweden reporting in! :)

I can definitely tell theres more activity during the American hours. It kinda makes then sense to have more gate keepers in that time zone as well. 

The project is so young and is moving so insanely fast, I dont think I have been part of something quite like this. Desiring around the clock gate keeper presence might be asking for too much. Say we get one in each time zone, would we then require them to be online every day?

**Comment by NogginBops** [comment]
@Mizipor Good questions. I don't think we can expect gatekeepers to always be available, but so think we should maximize the times a getekeeper might be available.

**Comment by koosemose** [comment]
If I were more confident in my git skills I'd volunteer... not european, but I keep European hours most of the time.

**Comment by Tranberry** [comment]
Maybe @RodRitter fills this 'gap' who knows?

**Comment by NogginBops** [comment]
I volunteer if that was not apparent from this post... :P

**Comment by Mizipzor** [comment]
Everyone does. ;)

**Comment by Tranberry** [comment]
Not me, I'm not experienced enough with C# nor git.

**Comment by Sommerbo** [comment]
Leave me out please!
While I could probably do it, I don't want to. :)

**Comment by Grenkin1988** [comment]
Me neither :-) Merge all this pull requests is nightmare

**Comment by JosephBywater** [comment]
Me neither :P Too many PRs!

**Comment by Xeni91** [comment]
I can't do it between work and sleep there is not much time, so I could only help at weekends. Besides C# is not my strong point.

**Comment by Mizipzor** [comment]
Well then, I was clearly wrong. ^^

**Comment by quill18** [comment]
I do want to keep the set of collaborators relatively small at any given time, so that it's easier for each of them to keep track of what's been merged or not, but this is a reasonable suggestion.

Pulled the next name off my arbitrarily-ordered shortlist: Mizipor!
