### ISSUE TITLE
[Bug] Error in Metal Smelter

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#593]
In the latest master project version (as of 22 August, 10:56 GMT) I get this error every time a charrie brings raw iron to the metal smelter:

`InvalidOperationException: Collection was modified; enumeration operation may not execute`

Near as I can tell from the call stack, the problem is with Job.cs line 232, the foreach header in:
`foreach (string luaFunc in cbJobCompletedLua)
            {
                FurnitureActions.CallFunction(luaFunc, this);
            }`

**Comment by abackwood** [comment]
Probably fixed by #587?

**Comment by NogginBops** [comment]
@abckwood Yes #587 fixes this.

**Comment by bjubes** [comment]
@abackwood you can also refer to the project's "version" by naming how many commits appear in the master branch, so its time zone independent and easier to see how may changes have occoured since then.

**Comment by Randshot** [comment]
Maybe close this one?
