### ISSUE TITLE
[Attention] A lot of new stuff is added not implementing the new naming scheme #505

### ISSUE THREAD

**Issue by racerand** [TeamPorcupine/ProjectPorcupine#594]
I'm working on creating a naming scheme for our inventory and furniture at the moment but a lot of new features is added not using this. My pr #505 is WIP because I want feedback and for people to comment on how it  should be. New content being added adds a lot of work for the implementation so would you please stop this until it's in. More comments mean faster implementation. The only reason I haven't removed WIP yet is because I have not gotten the feedback I was looking for yet, and then this morning many new features have been added leading to a lot of time used to change names/objectTypes of newly added stuff. Also removing localization stuff from the furniture.xml as it's was just a stupid work around.

**Comment by Tranberry** [comment]
Sorry for my lazy research: Is this added to the documentation (contributing.md, readme.md, wiki and so on). If not it should be added ASAP.

To bad that there are no gatekeepers active now #589

**Comment by racerand** [comment]
Added to working on in wiki now. I have an updated CONTRIBUTING.md in my pr, but it's far from done, need to merge in the changing from last 8 hours. Maybe I should just make a pr with the updated CONTRIBUTIN.md...

**Comment by Tranberry** [comment]
I think that the consesus was small more PRs , but don't quote me on that. So a new PR is what I would have done.

**Comment by racerand** [comment]
yeah, I know, the PR got a bit bigger than it should have been.

**Comment by racerand** [comment]
Also the problem is I haven't completely finished how the naming standards should be.

**Comment by racerand** [comment]
There are now some polls in #505 for the last parts of the namings standards.

**Comment by kd7uiy** [comment]
Is this still an issue?

**Comment by bjubes** [comment]
the changes to contributing were merged, so ill close this until more specific examples arises again
