### ISSUE TITLE
[Bug] Power generator drop power immediately

### ISSUE THREAD

**Issue by Grenkin1988** [TeamPorcupine/ProjectPorcupine#598]
Power generator should be refilled before it has no fuel at all.
Right now it looks like:
1. Bring fuel
2. Operate and give power to power grid
3. No fuel
4. No power in grid
5. Ask for fuel
Related to #524
Should be fixed after #596

**Comment by Xeni91** [comment]
maybe we should implement an internal buffer for the generator, which only depletes when the power is activly used

**Comment by Grenkin1988** [comment]
You mean accumulate power?

**Comment by Xeni91** [comment]
yes

**Comment by Grenkin1988** [comment]
Issue solved with battery implementation. #1079
