### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by Don42** [TeamPorcupine/ProjectPorcupine#6]
The standard way to document the workflow to contribute to a project is a `CONTRIBUTING` file as described in [0]. Going forward this would probably be the best way to let new developers know how to
contribute to this project and also help them learn where this information can be found in other projects.

[0] https://github.com/blog/1184-contributing-guidelines

**Comment by AE40** [comment]
I agree, as quill has many subscribers that will want to contribute we have to keep it organized or the project will fail to develop

**Comment by zwrawr** [comment]
#10 Added a pull request with a CONTRIBUTING.md

**Comment by quill18** [comment]
Merged #10
