### ISSUE TITLE
[Suggestion/Discussion] "Spawn Inventory" dev tool

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#603]
With new types of inventory being added every day and furniture more and more being dependent on it, I'd like to work on a dev tool that lets you spawn inventory by clicks to make testing things easier.

For example, I now have to spend some time waiting for steel to be produced to build my walls to test some objects that are dependent on rooms being there.

For this to work, I need a UI that makes a selectable list of inventory types (maybe read from XML, as in #597). When you have that selected, it adds inventory to the clicked tile.

Is the code-based UI at a point where this can be done without disrupting the scene?

**Comment by mikejbrown** [comment]
Related PR: #612
