### ISSUE TITLE
Missing Artwork for Version 0.1

### ISSUE THREAD

**Issue by quill18** [TeamPorcupine/ProjectPorcupine#607]
The following art is required to be done/redone for the Version 0.1 milestone:

- [x] Character (Kenney's art is good, and CC0, but I think it would be best if all of our assets were "custom")
- [x] Metal Smelter
- [x] O2 Generator
- [x] Wall
- [x] Door
- [x] Floor

These furniture pieces do have art, but we'll need to verify that they all look consistent with our style:
- [ ] Cloning Pod
- [ ] Power Cell Press
- [x] Power Generator (I particularly like the look of this)

Inventory Resources need to be made consistent in look. Maybe that means we keep some, or maybe that means we replace them all:
- [ ] Copper Wire
- [ ] Raw Iron
- [ ] Steel Plate
- [ ] Ice
- [ ] Uranium

**Comment by zwrawr** [comment]
Looks like Tranberry (TRBRY) is on the Character art
![](https://cdn.discordapp.com/attachments/216936858528120832/217274349114097674/spaceFarer.png)
*from the art channel in the [discord chat](discord.projectporcupine.com)*

**Comment by Mizipzor** [comment]
Should we add a label for these meta/todo issues? I would imagine that each checkbos gets an issue link behind it that would contain the details. Though I absolutely agree with having the list here, rather than in the wiki or somewhere else.

**Comment by JosephBywater** [comment]
Also, we want an Art style that is easy to replicate so as not to dissuade people from creating art because it looks too hard!

**Comment by Sommerbo** [comment]
Um, no, @zwrawr I just pointed out that the airlock graphics is the wrong perspective. I am horrible at art. So I am not the one make any graphics.

**Comment by JosephBywater** [comment]
I believe that it was actually @YourShadow.

**Comment by Tranberry** [comment]
Oh my, that's embarrassing.

**Comment by JosephBywater** [comment]
@Tranberry Why's that embarrassing?

**Comment by Tranberry** [comment]
I guess it's like very badly written code on display. But I can handle it.

**Comment by TheRiven** [comment]
What's that! you want some more Programmer pixel art! welllll ok then :laughing:  
![oresmelter-64bit](https://cloud.githubusercontent.com/assets/3747487/17859077/2c9cbce0-6880-11e6-9956-ba74b58582bc.png)

**Comment by WardBenjamin** [comment]
@TheRiven wow dude, that looks fantastic. Do more plsthx 

Seriously though, looks great!

**Comment by Mizipzor** [comment]
I think it looks awesome. Kinda clashes with the style of the character though.

**Comment by RodRitter** [comment]
That's amazing. Although I'm not sure if we want to keep the art style uniform throughout the game?

**Comment by NogginBops** [comment]
@RodRitter I think so, we have a whole bunch of art people trying to organize themselves. It's a discussion in the discord chat if you want in. There will be some issues poster later I think.

**Comment by ComputerOverlord** [comment]
Do we go with @TheRiven or with @Tranberry

**Comment by RodRitter** [comment]
@NogginBops Sure, I'll join as soon as I have a gap.

**Comment by Tranberry** [comment]
@Mizipzor I'm not sure it's a clash even with the outlines. Anyhow I'm not claiming anything my character will be done in the likes of the sprite-sheet that @Raketfart did.

**Comment by JosephBywater** [comment]
What should the wires look like? Should they have a casing around them, here are some things that I made in a matter of milliseconds. Oh yeah, they're not the right dimensions either 👍 
![screen shot 2016-08-22 at 17 03 07](https://cloud.githubusercontent.com/assets/5558617/17861833/86592a0c-688a-11e6-9597-0d3f5b822d93.png)
![screen shot 2016-08-22 at 17 00 20](https://cloud.githubusercontent.com/assets/5558617/17861831/8655169c-688a-11e6-9e88-9a67d9896474.png)

**Comment by Yourshadowq** [comment]
I think the wires should look a little thicker maybe like this![wire](https://cloud.githubusercontent.com/assets/17286353/17862900/eb924530-685c-11e6-83a0-764ea00213d4.png)

**Comment by ComputerOverlord** [comment]
The style of @Tranberry is good, but pixel art, like @TheRiven Is growing on me.

**Comment by NogginBops** [comment]
I think the wires should be shown in a overlay, that way we have more freedom with the direction we want to take them. e.g. putting them in the middle of the tile.

**Comment by Tranberry** [comment]
On the topic of art style;

I prefer a style that many can mimic for a project like this. And as most here have a decent hand at making pixel sprites that seems like the obvious route.

**Comment by ComputerOverlord** [comment]
Most of my experience with pixel sprites:
(Sort of a civ style tileset)
![tileset](https://cloud.githubusercontent.com/assets/21087045/17864017/067dba84-6851-11e6-8940-f95ca9136e1c.png)

**Comment by Spool5520** [comment]
I'm working on a full tile set ATM for all current sprites in the game I plan on pushing them all at once

**Comment by Spool5520** [comment]
Here is the new walls I did https://s10.postimg.io/x4087w655/wallsprites.png

**Comment by ComputerOverlord** [comment]
Character I made:
![station worker](https://cloud.githubusercontent.com/assets/21087045/17864463/0e5f731c-6853-11e6-8d25-0ddda08ebbb5.png)

**Comment by Tranberry** [comment]
@Spool5520 is there a overhang on the top of the wall, or are my eyes deceiving me?

**Comment by quill18** [comment]
i lyk dis

Good progress!

**Comment by Spool5520** [comment]
On the ends where the walls go east and west yes there is a one pixel overhang and I've tried to add this to the project but I cannot get the XML to work right. If someone would be willing to explain the process to me or be willing to download my sprites from dropbox and put them in yourself would be really great. I'm not worried about credit for the art just doing it for fun.

**Comment by TheRiven** [comment]
The smelter is hungry....
![smelteranimation1](https://cloud.githubusercontent.com/assets/3747487/17866406/4d52c4d4-689e-11e6-888e-a44b1723cb66.gif)

**Comment by Spool5520** [comment]
@TheRiven I like that generator. What does the generator in-game use for fuel?

**Comment by TheRiven** [comment]
I believe it has been set to use uranium as fuel

**Comment by Spool5520** [comment]
Maybe we could use that one for a coal generator or something? It looks amazing. Maybe we should do something a little more nuclear? I'm at work right now but when I get home I'm going to work on the sprites some more. The perspective and everything is perfect in your sprite by the way :)

**Comment by TheRiven** [comment]
ahh I think there is a slight misunderstanding, that sprite is for the smelter not the power generator :smile:

**Comment by TheRiven** [comment]
Although I do need to go back and redo the power generator as I did not know what fuel it would run on when I made it.

**Comment by Spool5520** [comment]
Oh I'm sorry, my bad. Never mind then >.<

**Comment by Tranberry** [comment]
![third_01](https://cloud.githubusercontent.com/assets/16529/17867922/b7102746-68ac-11e6-9a99-7bc9559ef2ab.png)

Would this style do?

**Comment by Spool5520** [comment]
That looks great

**Comment by RodRitter** [comment]
Thats awesome. I actually prefer that pixelated look over the clean one. Just my opinion though.

**Comment by Tranberry** [comment]
@RodRitter well it takes about twice the time to make so I hope it's at least a tiny bit better ;D

**Comment by quill18** [comment]
Oof, that's a tough call. I actually really liked the vector-art looking one too.  A lot.

**Comment by quill18** [comment]
@TheRiven Love the smelter.

**Comment by ComputerOverlord** [comment]
@TheRiven Yeah, It's more of a fission station thing. Also the smelter should use fuel.

**Comment by brlodi** [comment]
Perhaps if done carefully the pawn and dropped object graphics could be the clean vector-style, while terrain and placed objects are the grittier pixellated type? I'm envisioning a similar feel to classic Disney, Looney Tunes, and Hanna-Barbera cartoons where very painterly backgrounds were paired with simple cell animation characters and props. They'd have to be appropriately color-matched but I think it could be a neat and unique artistic flair.

**Comment by Jorchay** [comment]
Hey guys, first poster here.

Just as a suggestion, we could look into another game to get reference, this game is: _Space Station 13_

They have a pretty cool system of atmospherics, I could link to some of the wiki of how it works, but just as a preview this is the power system it haves:
![image](https://cloud.githubusercontent.com/assets/8218098/17889745/220c0382-6932-11e6-92ec-50a383c0e54c.png)

And it's atmospherics:
![image](https://cloud.githubusercontent.com/assets/8218098/17889765/32c71392-6932-11e6-8448-63ddb856a657.png)

Tell me what you guys think of this!

**Comment by Mizipzor** [comment]
Wow those graphics are amazing!

**Comment by Tranberry** [comment]
@Mizipzor you don't suggest we steal art from another game right?

**Comment by Mizipzor** [comment]
@Tranberry No, I was commenting on how good they are. As in, both clear an interesting. When it comes to stuff I appreciate, stealing is not my default position.

**Comment by Spool5520** [comment]
I'm working on something similar for the game right now. Graphics wise. Hopefully be done with the tile set tomorrow.

**Comment by quill18** [comment]
Flagging the smelter as done.  @TheRiven Please make a PR for it when you can!

@Tranberry How's the status of your character?    What do you think about making versions for facing left/right/up?

**Comment by Spool5520** [comment]
My only concern with having wires and pipes and what ever else we end up adding, running on the floor is that the screen gets cluttered really fast and it becomes hard to see what your doing and making it look cool or pretty becomes very hard. I was thinking about the idea of having utility lines,wires ect be toggled in and out of view by the user so you can see it when you need to and not just all the time.

**Comment by Tranberry** [comment]
@quill18 like this? 
![spacefarerpiskelmasked](https://cloud.githubusercontent.com/assets/16529/17896262/42f515d4-6950-11e6-9bc9-58f59baa07a9.png)

**Comment by Spool5520** [comment]
That looks great!

**Comment by TheRiven** [comment]
@quill18 Will do :smiley: 
I also have this for consideration:
![o2gen-animation](https://cloud.githubusercontent.com/assets/3747487/17896436/8e8c66f8-6948-11e6-9af0-4026da3a099d.gif)

**Comment by Spool5520** [comment]
@quill18 I watched your video but I just can't seem to make the new art work in unity. Would you be willing to add them for me if I sent you a zip file with all the sprites in it?

**Comment by Tranberry** [comment]
@Spool5520 you should probably join the discord chat if you want quick help with anything

**Comment by GamerInspired** [comment]
Just need to ask are @TheRiven and @Tranberry our artists now? :stuck_out_tongue_closed_eyes:

**Comment by Spool5520** [comment]
@Tranberry I'll go on there after work today. Didn't know we had one thanks.

**Comment by Spool5520** [comment]
I use monogame with vs 2015 for my game so Unity is a bit different for me >.<

**Comment by Tranberry** [comment]
if #684 gets merged we will almost have ticked of the first check on this list.

**Comment by Spool5520** [comment]
The origin for the x,y is the top left of the image right? (for walls)

**Comment by Spool5520** [comment]
![wall](https://cloud.githubusercontent.com/assets/13977485/17915338/a03ca096-695e-11e6-8dc6-4be3839394ec.png)

so going from a 64x64 sprite and a 512x832 image SteelWall_NEW would be x256 y64 w64 h64 right?

**Comment by quill18** [comment]
#684 merged and checked off!

**Comment by TheRiven** [comment]
Here are some options for Iron/Steel and Uranium. 

The sprite sheets are in order of Mining "point", ore form and processed form. Currently not all of these would be used but they are there for the future.

Iron/Steel:
![ironset](https://cloud.githubusercontent.com/assets/3747487/18014406/af78dcce-6bba-11e6-91d7-eaea8a451a70.png)

Uranium:
![uraniumset](https://cloud.githubusercontent.com/assets/3747487/18014409/b244bb6c-6bba-11e6-9f03-a88c1bdfdcd4.png)

and an ice cube for fun!
![iceset](https://cloud.githubusercontent.com/assets/3747487/18014502/1e5651da-6bbb-11e6-9456-c0378cb4ef50.png)

**Comment by Yurgeta** [comment]
A different kind of power generation maybe ?? [ Solar panels ]
![solar_panels](https://cloud.githubusercontent.com/assets/329655/18017055/7f0fb654-6bc7-11e6-86f4-243b306f0515.png)
i made these awhile ago and was going to submit them but forgot to see if quill would of liked them so here i am, there are 3 sizes (32x32 / 64x64 / 64x96 ) when i was fallowing the games tutorials i was thinking the games art / look was going to be top down like Rimworlds style so that's why i made them flat. if this is not the case i can always remake them in a 3/4 perspective

**Comment by Tranberry** [comment]
![cloning1](https://cloud.githubusercontent.com/assets/16529/18028095/7325328e-6c75-11e6-8b75-8da1a1515693.png)
![cloning2](https://cloud.githubusercontent.com/assets/16529/18028098/7551da3a-6c75-11e6-9e37-b86a002d5552.png)

Made some cloning thing..

**Comment by Yurgeta** [comment]
![copper wire](https://cloud.githubusercontent.com/assets/329655/18028152/c6fd3296-6c6e-11e6-9b13-5c345fca1b4c.png)
copper wire... 5 colour pallet looks detailed alot due to my shadows and highlights but trust me this isnt that good..

**Comment by Tranberry** [comment]
![cloning](https://cloud.githubusercontent.com/assets/16529/18028579/f3c25f18-6c82-11e6-8ce2-0ca5c6ecd056.gif)

**Comment by Spool5520** [comment]
Those all look amazing. Good work :D

**Comment by Spool5520** [comment]
New Power Generator 
![power generator](https://cloud.githubusercontent.com/assets/13977485/18029065/b29f4f4a-6c42-11e6-8608-3149dbb32da1.png)

**Comment by Tranberry** [comment]
So everything except the press is 'made'?

**Comment by Spool5520** [comment]
Yeah I think so, is the Mining Drone still old?

**Comment by Spool5520** [comment]
What is the press for?

**Comment by Tranberry** [comment]
> What is the press for?

That's the question holding us back atm in [#art ](https://discord.gg/BhWXg)over in discord.

**Comment by Spool5520** [comment]
ah ok

**Comment by Yurgeta** [comment]
![compressor_oxygen](https://cloud.githubusercontent.com/assets/329655/18029348/bee6b75c-6c8d-11e6-9b3f-20edf40c6346.png) new oxegen tank machine

![airlock](https://cloud.githubusercontent.com/assets/329655/18029350/c8a5d962-6c8d-11e6-843d-57c8c2f074da.png)
new airlock door sprite (side view still needs alot of work but its animated at least in a basic sprite for now)
will work on some more stuff later on tonight at the moment im working on getting some information together for helping anyone who wants to make art for the game as well as making all my color pallets available so people can make there work match with the same colors

**Comment by Tranberry** [comment]
![64x64tim 4](https://cloud.githubusercontent.com/assets/16529/18166119/95cdc8f0-7049-11e6-9dc6-c336d53e3b2d.png)

To adhere to the 64x64 px = 1 u eg  PPU 64. I would like some input on this 1x1u character/npc/toon. Shall I continue this or shall I bin<sup>(throw it in the trash)</sup> it?

**Comment by vogonistic** [comment]
I would need to see the character in game to judge that.

**Comment by Tranberry** [comment]
@vogonistic the question is: should the character fit in one unit (1u).

**Comment by koosemose** [comment]
I personally think the 1u high character looks really bad (not from an art standpoint, just "in the game"), it makes it look like a little kid.

**Comment by Grenkin1988** [comment]
So, now we have sprite for kids. Someone was already talking about dating simulator :-) Result of it already here :-)

**Comment by koosemose** [comment]
Oh, you don't even know what you've done @Grenkin1988 ... considering most of that conversation was between me & @Tranberry , one of these days you're going to come here and it's going to be nothing but cat girls, space octopii and pirates dating.

**Comment by Sommerbo** [comment]
I like the new smaller astro-sprite

**Comment by vogonistic** [comment]
I like it in terms of kids, but I'd rather have taller characters. It'd look hilarious if a 1u character character carries an object who's sprite takes up the whole tile.

**Comment by longtomjr** [comment]
**For a more up to date version please see the [wiki](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Milestone-0.1#artwork)**

**Comment by mikejbrown** [comment]
Closing since the discussion has moved on.
