### ISSUE TITLE
Missing MonoBehaviours

### ISSUE THREAD

**Issue by WardBenjamin** [TeamPorcupine/ProjectPorcupine#611]
I don't know how we missed this, but there's 2 missing Behaviours right now. 
![capture](https://cloud.githubusercontent.com/assets/4739008/17859676/9826ecc4-6858-11e6-8831-4ed1e7625e38.PNG)

You can see them in the image, but we're missing the KeyboardController and the overlay is broken.

The scripts for the overlay seem to be there still, but I have no idea how they're used. If the KeyboardController script was removed but not the object, I can fix that.

**Comment by RodRitter** [comment]
If the game is working as is, my suggestion is that we remove those references to keep it clean.

**Comment by NogginBops** [comment]
I think the overlay is being worked on in #340

**Comment by sboigelot** [comment]
@WardBenjamin is this still an issue for you? Otherwise I think we can close this issue
