### ISSUE TITLE
Music - background (help)

### ISSUE THREAD

**Issue by Ferr013** [TeamPorcupine/ProjectPorcupine#614]
Hi, I wanted to contribute in some way to this project, but probably I haven't enough programming skills for now, so I decided to try pick up the guitar and make some kind of backing track.

I already registered something (it's not great at all, but I'll try to improve it in the future), and I wanted to attach it to the game. First I imported the track in Resources/Music and then I wrote this code (being inspired from the SoundController) and referenced it to the WorldController. 
The MusicController here works with the code you see commented out, but doesn't loop.
![screenmusic1](https://cloud.githubusercontent.com/assets/21153774/17861101/099060f2-6890-11e6-8d8c-b9c40e335a66.png)
![screenmusic2](https://cloud.githubusercontent.com/assets/21153774/17861100/098ee416-6890-11e6-86a5-f68f78d54e92.png)

Could someone help me sort it out, please?
I know that code-driven things are preferred and  I don't want to screw up anything, so any advice will be really appreciated!

**Comment by Mizipzor** [comment]
Screenshots of code now that's something  :)

You should either just post the code you've got, there is code tags for that. 

Or, what I think is better, just commit and push what you've got. You can then link to specific lines in your pull request.

**Comment by UnknownSoldier1** [comment]
From what I see the code you have in place there throws a null reference exception. Is that right? If so, add the following code to your MusicController class:
`void Awake()`
`{`
`backgroundMusic = GetComponent<AudioSource>();`
`}`

This code will only work though if your MusicController is a MonoBehaviour and if it's attached to the same GameObject as your AudioSource.

**Comment by Ferr013** [comment]
@Mizipzor Ahah your right! I didn't commit it to avoid pushing something that doesn't work at all, but if I can't solve it today I'll commit it :+1: 

@UnknownSoldier1 At first I've tryied with [RequireComponent] but without being a Monobehaviour... Another question: is it fine to create a new object, or is better (if possible, I don't now) to complete the task using only c# code?

**Comment by Mizipzor** [comment]
@Ferr013 Heres the thing though... I'm not sure how much Git you know. But you would basically upload code to only your special copy of the game. We wont see it (unless we look). You would then, when youre done, formally request us to accept your stuff. And we click a button and it happens. :)

**Comment by Ferr013** [comment]
@UnknownSoldier1  Yes, because I don't know how to commit the GameObject (named MusicController), while I should be able to commit music and the code.
Anyway, I followed your advice (modified the MusicController, attached it to an EmptyGameObject and removed the WorldController stuff) and now it works!
Thank you :)


`using UnityEngine;
using System.Collections;

[RequireComponent (typeof (AudioSource))]
public class MusicController : MonoBehaviour
{
    AudioSource backgroundMusic;

	void Awake ()
    {
        backgroundMusic = GetComponent<AudioSource>();
        AudioClip ac = Resources.Load<AudioClip>("Music/SpaceTheme");
        backgroundMusic.clip = ac;
        backgroundMusic.loop = true;
        backgroundMusic.Play();

	}
}`

**Comment by UnknownSoldier1** [comment]
@Ferr013 Good that it works now! The GameObject will be commited like every other thing in Git. Basically, it will show you that the scene file has been changed. You have to include that in your Pull Request.

**Comment by Ferr013** [comment]
@Mizipzor Ok I get it, could you explain me how to upload correctly my work?
From quill video I would
create a new branch 
git add <musicFile>
git add <codeFile>
git add <objectFile> (I dont know where to find it)
git commit -m "description"
git push origin testbranch
 and then from GitHub site ask for Pull Request

Is it wright?

**Comment by NogginBops** [comment]
git push -u origin testbranch
I think would be better to save origin as upsteam.

**Comment by Ferr013** [comment]
committed it, thank you all again!
