### ISSUE TITLE
[Discussion] How high should a stack be?

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#617]
I think this is a good question. Should it be..
- 50
- 64
- 100
- 200?

**Comment by gunthergun** [comment]
500? who can raise the stakes 😂😂

**Comment by UnknownSoldier1** [comment]
Go Rust style and do 1000, thats my opinion ;)

**Comment by gunthergun** [comment]
I like having high numbers but we should probably keep it with just 3 numbers --> so 999 then :)

**Comment by UnknownSoldier1** [comment]
999 would be fine too.

**Comment by ComputerOverlord** [comment]
I'm having a hard time telling if you are being serious or not.
Either way... Closing for now.

**Comment by gunthergun** [comment]
I was being serious just found it funny that you did small numbers... @ComputerOverlord I hope I did not offend you :/

**Comment by ComputerOverlord** [comment]
@gunthergun It's a pointless issue anyway.
