### ISSUE TITLE
Building and removing floors

### ISSUE THREAD

**Issue by JosephBywater** [TeamPorcupine/ProjectPorcupine#62]
When building or removing floors, there is no 'overlay' to show which floor tiles have been selected, like when you add or remove walls and furniture. This means that it's unclear whether or not you have actually selected the floor. Also, when removing furniture, there is not 'overlay' to see what you have selected to delete. When deleting, the overlay should be red, not green I think.

**Comment by emilkris33** [comment]
Possible #26 solves this
