### ISSUE TITLE
Move localization offline

### ISSUE THREAD

**Issue by Dan54** [TeamPorcupine/ProjectPorcupine#621]
The online localization makes new adding furniture more difficult.

**Comment by Mizipzor** [comment]
You should be able to add furniture and then localize it later. You arguably should anyway, in case the furniture dont work out. Cant you?

**Comment by Dan54** [comment]
It's just more complex and means that the player must always have an internet connection. Also, what benefit does it give?

**Comment by Mizipzor** [comment]
For the record I was against it. :) I assume the relevant people will pop up here explaining.

**Comment by TomMalbran** [comment]
I guess that when we make a release version, we could just pack the localizations in it, so that you don't need to download it later.

**Comment by bjubes** [comment]
I think the point is so that you dont need to push an update every time you add a localization change when the game "ships". I was under the impression that localization downloads once, and checks for updates, but if you dont have internet it will use the potentially outdated version.

**Comment by Dan54** [comment]
@bjubes has a good point - closing.
