### ISSUE TITLE
My art

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#624]
I decided why not. Let's post my art ideas for this game.
Character:
![worker_station](https://cloud.githubusercontent.com/assets/21087045/17864712/120ff774-6854-11e6-9624-a66542e18f63.png)
Fusion pump - make alloys?
![pump_fusion](https://cloud.githubusercontent.com/assets/21087045/17864733/20d2a8ba-6854-11e6-9183-5255e1b1fb9e.png)

**Comment by RodRitter** [comment]
![image](https://cloud.githubusercontent.com/assets/4159679/17864815/f2add2ce-689f-11e6-93e8-f0458d861ef2.png)

**Comment by ComputerOverlord** [comment]
raw materials:
![iron_raw](https://cloud.githubusercontent.com/assets/21087045/17866176/5d28c316-685a-11e6-987b-30e6036bd4e8.png)
![copper_raw](https://cloud.githubusercontent.com/assets/21087045/17866177/604c2bf0-685a-11e6-9b8f-95bb65c36329.png)

**Comment by RodRitter** [comment]
I'm not sure if you've notice that your images are minuscule

**Comment by ComputerOverlord** [comment]
@RodRitter I do. But how am I supposed to scale them up in here?

**Comment by RodRitter** [comment]
@ComputerOverlord I don't think you can. You need to scale it up in an editor. Screenshotting/Snipping previews is also a good way to paste your stuff here.

**Comment by ComputerOverlord** [comment]
Materials:
![mat_sprite-sheet](https://cloud.githubusercontent.com/assets/21087045/17914333/fd7bc22c-6955-11e6-83e8-4f515888172c.png)

**Comment by ComputerOverlord** [comment]
I decided to open this back up. I can't use these (password problems...), but maybe someone else can.

**Comment by ComputerOverlord** [comment]
I decided to open this back up. I can't use these (password problems...), but maybe someone else can.\
NEVERMIND - I am working on it right now. Having problems actually editing to my branch, though
