### ISSUE TITLE
Rename FurnitureActions to LuaActions

### ISSUE THREAD

**Issue by NogginBops** [TeamPorcupine/ProjectPorcupine#626]
I think we need a lua utility file for lua calls and such. I think FurnitureActions is a good candidate for this. Just rename and add some methods.

**Comment by bjubes** [comment]
do u mean like a layer conncting unity c# funcs and lua calls so that functions like mathf dont have to be rewritten in lua?

**Comment by NogginBops** [comment]
Kind of, but also like utility functions to interface with lua and moonsharp. Like right now we have FurnitureActions.CallFunction(string, params object[]) to call a lua function. I think we need more lua utilities for e.g. loading files ect.
