### ISSUE TITLE
Reworking the job system

### ISSUE THREAD

**Issue by NogginBops** [TeamPorcupine/ProjectPorcupine#63]
Some people me included have expressed concern that the job system needs reworking. Both to allow more features, better performance and api. I have a idea about the implementation already. Will make a more detail description in a fem minutes.

**Comment by NogginBops** [comment]
Some people me included have expressed concern that the job system needs reworking. Both to allow more features, better performance and api. I have a idea about the implementation already. Will make a more detail description in a fem minutes.

**Comment by JosephBywater** [comment]
#60

**Comment by lameox** [comment]
Will quote my post from the other issue here:

> This sounds good. I think in the same turn we should also update the movement system. I want something like MoveTo(Tile) and the move to become a separate job. this should make writing any future additions a lot simpler as we wont have to roll the same path checks and stuff everywhere. Also having moves become separate jobs will allow us to write a job system akin to Linq. I had syntax in mind like

>Character.MoveTo(stockpile).PickUp("Iron", 3).PickUp("Aluminum", 2).MoveTo(workbench).Craft("door").MoveTo(stockpile).Drop("door").QueueJob();

>I dont know if that would be feasible but i think if we generate the right extension methods, writing jobs should become really intuitive for programmers and modders alike. What do you thnk?

**Comment by BeefEX** [comment]
if any help is needed i will be happy to help, just tell me what to do

**Comment by NogginBops** [comment]
Are we thinking of moving all of the job functionality into lua code?

@lameox did you have any thoughts on my idea of job bundles?

**Comment by lameox** [comment]
Hey @NogginBops i just updated my above post. I think we could get a lot more done by doing jobs not as bundles as they were created but as bundles in the sense of "smallest number of jobs that need to be executed in that order by the same character". This way we can have one giant input stream of commands that can be broken down into small packets executed by individual characters. What do you think?

**Comment by BeefEX** [comment]
@lameox maybe the character job queue would only contain reference to the job in the global job queue?

**Comment by lameox** [comment]
Also i think moving all job functionality into lua is a bad idea. We should have an api that can be called from lua, but most of the logic and scheduling should happen in c#. 
We should expose base building blocks like waiting moving deciding on what to do next and so on to lua and then we can write the actual jobs out of those simpler commands.

**Comment by lameox** [comment]
@BeefEX i think that is a bad idea. The global job queue and anyone consuming it does not need to know about a characters jobs. it should be the characters decision if it needs to take from global or own queue. Also this avoids cluttering the global queue with jobs that cannot be done by all characters and thus requires a lot more iteration when a character asks for a job. I think it is best if a character only ever sees jobs he is allowed to do.

**Comment by NogginBops** [comment]
Ok, so my idea is this. Have a centralized job management system that is queriable based on different parameters, e.g location profession and priorities (or whatever). That should be easy to use and LUA friendly.

**Comment by NogginBops** [comment]
@lameox Yeah, the job bundle was me trying to over think the problem and adding unnecessary complexity to the problem.

**Comment by lameox** [comment]
Do you think its a good idea to have jobs available in Lua? I feel it is best to only allow for queueing jobs, aborting the current job and so on, but now actually see the jobqueue/manager/whatever from lua. I feel this system is too important to expose in lua and i dont really see the use case tbh

**Comment by NogginBops** [comment]
I was thinking synthesizing jobs should be easy in lua.

**Comment by lameox** [comment]
On that i agree. This, i thought, would be nice with the above mentioned Linq-like API. This API would be callable from Lua but wouldn't actually expose the internals of the Job system to Lua.

**Comment by NogginBops** [comment]
I think the linq-style is a good idea if done right.

**Comment by lameox** [comment]
I think i will write up a more formal Proposal, with all the functions i think we need for a start, and how they would be chain-able. This could potentially be completely separate from the actual Jobsystem, if we redesign that with the right interfaces in mid. I would include those in the proposal as well.

**Comment by NogginBops** [comment]
With the new job system I think there is a need for queriability for suitable jobs for a specific character. For this the job itself needs to contain metadata that is:
1. Easily extendable
2. Easily queriable

My suggestion is having a kind of suitability index be calculated for each job and return the most suitable job for the character.

**Comment by lameox** [comment]
Hmm. I think we could shoot ourselves in the foot by tagging too much metadata to a job. As we want our jobs as little as possible we would generate quite a bit of Objects that the GC needs to clean up. I think a better way would be, to have a global Weight System for jobs and the job only carries some Kind of Tag(s) with which it can look up its viability functions in the Wight table. That way we dont have to generate nearly as much garbage. 

Also we should consider how this extansability works. Do you just want:
- a List of strings/objects that are your job's tags
- Interfaces implemented by the Job that signal different behaviour
- an inheritance tree that signals different behaviour

I think all three solutions have their advantages, but we should probably do something like a List of special Tag objects, as to have type safety at compile time.

**Comment by NogginBops** [comment]
I also think that having a global weight table is a good idea. I think a list of strings is a good solution, trying to create some kind of inheritance tree could get out of hand really fast.

**Comment by NogginBops** [comment]
I also think having data like a description of the job would be a good idea as we might want to show some of that data to the user.

**Comment by lameox** [comment]
I agree on the Inheritance tree for sure, but i am not really convinced between List of strings/Tags and Interfaces yet. If we do the List thing, that means, that our jobs cannot contain any logic themselves, but rather we need a consumer class that inspects our List and decides how we proceed. We could maybe have a hybrid Soultion where jobs implement a CalculateWeight and then look at the Weighttable themselves. This would allow Certain special jobs to Override CalculateWeight. i.e. All Characters should always move away from a leak in the hull asap and with highest priority.

**Comment by BeefEX** [comment]
I was thinking about categories of jobs. Than player can specify character-specific weight list.

**Comment by NogginBops** [comment]
I think that the scenario that you are describing should be handled in another way than you are proposing, If a leak is detected I think there needs to be some kind of broadcast that there is a urgent job that cancels the existing job and does the new one. Though the implementation details of that are not clear.

**Comment by lameox** [comment]
Is this something the Player should really have to specify?

Or do we have a preset for all doctors, mechanics, whatever and the player can then choose to fine tune them? 

We should keep in mind that everthing the player has direct control over also needs to have some form of UI, Localization and more. I think this should be a future goal but is not really necessary atm.

**Comment by JosephBywater** [comment]
So an urgency tag?

**Comment by NogginBops** [comment]
But I can agree with you. I like the idea that there could be job specific weights, though I do not know for what they would be used.

**Comment by lameox** [comment]
We could have stuff like all characters can and will carry stuff around, if they absolutely have nothing else to do, but a designated carrier might have his likeliness for choosing a carry job multiplied by, say, 16.

**Comment by BeefEX** [comment]
Player would be able to specify it like in RimWorld.

**Comment by NogginBops** [comment]
@JosephBywater Possibly but that would mean that the job system would have to have a special case for a specific tag. I don't like that idea, I woulds like it to be something like a function in the job system 'broadcastUrgent(Job, Room)' or something.

**Comment by NogginBops** [comment]
@lameox I was also thinking about a intention system where a job could have a intention, like "Picking up gun" to "kill alien monster". This would mean that the job would have a reference to its intended followup job. Though that job might not necessarily be the next job depending on circumstances.

**Comment by lameox** [comment]
@NogginBops while i like the thought i think this would be really, really terrible in the long run. If we do this we are back to Callbacks and followup jobs. I would much rather have the "There is an alien monster" condition spawn the AttackOrPickupWeapon job for all near characters. This way the system stays reactionary. 
I would like this better because we would not need extra logic for the event where you pick up the weapon and the monster is dead. The worker would just not receive another AttackOrPickupWeapon job and thus continue on with his business, whereas in your proposal we would need special logic in the followup job.

**Comment by NogginBops** [comment]
@lameox What you are saying is true. It would probably be better to just rely on the weighting system to do its job and give the right job to the right character.

**Comment by lameox** [comment]
@NogginBops Well i think the intentions are a good thought but we should implement them in a different way. However as you said this would mostly be done by the weighting System and would only really be useful for UI stuff, e.g. showing the user what the character wants to do next. 

I think we could go the other way round and derive Intentions by inspecting the Jobqueue and Weighting system.

**Comment by NogginBops** [comment]
@lameox Deriving intentions could be really weird and complex, though who knows that might work.

**Comment by lameox** [comment]
I think we would not need to be 100% accurate here as it is only for UI purposes. This would allow a Sims like job queue, where interruptions could easily be made visible to the user

**Comment by NogginBops** [comment]
Yeah, and it could add a little humours moments to the game when the intention system fails miserably. :)

**Comment by NogginBops** [comment]
I am testing a implementation of this right now but I'm looking for input on how to handle the character attributes/tags like profession etc. I'm thinking a table like this 'Dictionary<string, string>' where the key is the attribute name and the value could be something like "Medic" or "Angry" depending on the attribute.

**Comment by vogonistic** [comment]
I'd also prefer a job system that is based around the desired output or intentions.

That works well for things like building wall can't be completed because of lack of steel, so a requests for steel to be created and if there are scraps that might be smelted, it'll be fulfilled by someone. It also works well with modding, because we could add hooks to fulfill criteria in interesting ways.

If the jobs are too detailed, they also fail when the dependencies fail, but if the dependencies can be calculated or created, then they can be recreated again if they fail because of details.

**Comment by lameox** [comment]
I wrote up a V0.1 of a proposal that should encompass most of the stuff we talked about so far. See #75
