### ISSUE TITLE
[BUG] Can't run latest build

### ISSUE THREAD

**Issue by GamerInspired** [TeamPorcupine/ProjectPorcupine#636]
Here is an image of the error that's preventing me from running the game.

![ss 2016-08-22 at 09 44 06](https://cloud.githubusercontent.com/assets/8201304/17871040/c7cc131a-68b1-11e6-941f-9cc05f8fec65.png)

This is the zip build, I have done nothing to it. (Just clarifying). Also sorry if this has already been mentioned.

**Comment by GamerInspired** [comment]
Issue fixed in #638

**Comment by FilippoLeon** [comment]
Use this, will create a PR:
[fix_dbg.zip](https://github.com/TeamPorcupine/ProjectPorcupine/files/431139/fix_dbg.zip)
