### ISSUE TITLE
Game is slowed significantly be current path-finding implementation

### ISSUE THREAD

**Issue by emilkris33** [TeamPorcupine/ProjectPorcupine#64]
As it is currently the game has to generate the entire A*graph every time a floor tile or a piece of furniture is constructed. On my computer this causes very visible slowdown. As shown below my computer uses almost 3 full seconds regenerating the graph.
![image](https://cloud.githubusercontent.com/assets/1301554/17737902/753e84d2-648f-11e6-9098-53b50ea63b07.png)

I am not really sure how to go about improving this so any suggestions would be greatly appreciated

**Comment by NogginBops** [comment]
@quill18 was thinking about a D* lite implementation because easier updating. I don't know the workings of D* but could be worth looking into.

**Comment by JosephBywater** [comment]
Does the current pathfinding take into account the time/cost of opening doors?

**Comment by emilkris33** [comment]
@JosephBywater I am fairly sure i does not take that into account, but honestly i can't think of many situations where it would make a difference.

**Comment by QuiZr** [comment]
@emilkris33 
![image](https://cloud.githubusercontent.com/assets/9101486/17739058/0edf0428-6494-11e6-8432-e3bad910829e.png)

**Comment by JosephBywater** [comment]
If someone did this :P 
![image](https://cloud.githubusercontent.com/assets/5558617/17739046/a3057438-648b-11e6-8468-f855b43c4a65.png) Sometimes it was going through doors even though it would be faster to go around them (when it was being built).

**Comment by emilkris33** [comment]
@QuiZr Point taken. Especially if airlock eventually take significant time to open.,

@JosephBywater Also good point though maybe preventing people doing that belongs on some sort of todo?

**Comment by quill18** [comment]
I think doors are currently weighted the same as empty territory, but we definitely will want to weight them more going forward.  Even something like 25% more than empty terrain would be sufficient to path around pathological cases.

There's a TON of possibilities for optimization of the pathfinding.  The existing A* implementation can likely be optimized (very likely that there's a bunch of list manipulation that we could tune out).  We can build a graph out of rooms and pathfind through that first (which is the Rimworld solution, and it works very well there).  We can generate pathfinding maps (dijkstra map or D*LIte) for each type of resource (though we have to make sure it gets updated every time something in a stockpile gets moved and I suspect that the "win" won't be there).

**Comment by SquareMan** [comment]
I don't see why we can't just update existing nodes with new information when the change. I'm sure it would require more work and thought then just regenerating the entire graph, but it would be MUCH faster, and have the advantage of not slowing down even more if/when larger maps are implemented.

**Comment by emilkris33** [comment]
Closing this as it has been fixed in #139

**Comment by Mizipzor** [comment]
You should only close this once the pull request has been merged. In fact. this will happen automatically since you write "Fixes #XXX" in your commit message! :)

**Comment by emilkris33** [comment]
@Mizipzor Thanks. I will remember that for the future.

I was just attempting to minimize the growing issue list

**Comment by Mizipzor** [comment]
I'd rather have too many open issues rather than a few closed ones that should have been kept open. Right now someone can come across this bug, look at the issue list to see if it's been reported, but since it's not in the list a duplicate might be created. Consider reopening.

**Comment by Mizipzor** [comment]
@emilkris33 did you see that? Automagic!

**Comment by emilkris33** [comment]
@Mizipzor I do. I did not know git did that. I just wrote "fixes #64" for other people convenience. But nice to know git understands that.
