### ISSUE TITLE
Path finding logging noise

### ISSUE THREAD

**Issue by GamerInspired** [TeamPorcupine/ProjectPorcupine#640]
I'm currently expeniencing the odd time here and there where the game just hang/freezes. FPS looks is fine, including the fps in the stats area.

Also whenever a character goes of to get something from a distance the fps drop to arround 20fps then bounces back to 60fps.

EDIT:  it's not just the game, unity is freezing with the game. Trying to find out what the debug says at the moment.

EDIT 2: The log seems to be being spammed with these log messages and not just a little bit (see image below):
    - "Standing on Tile Check"
    - "Walk to the stuff"
    - "True"
    - "No neighbouring floor tiles! Abandoning job"

![ss 2016-08-22 at 10 18 22](https://cloud.githubusercontent.com/assets/8201304/17872094/6a5e4702-68b6-11e6-86d9-b82fb74dadbd.png)

I know this could probably be fixed by removing the lines with the log on, however I need to go and I don't know the code well enough to know if thats the only thing that needs doing (is it just the log spam).

**Comment by brlodi** [comment]
These were quieted down by the changes in #329. You've still got an old version.

**Comment by GamerInspired** [comment]
At the time of the creation of this issue it was the latest build.

**Comment by brlodi** [comment]
Ah you're right those changes were effectively reverted by #609. My apologies. This is now again a relatively minor but certainly slightly annoying issue.

**Comment by GamerInspired** [comment]
I'll leave this issue open, unless a gatekeeper believe it's ok to close.

**Comment by Mizipzor** [comment]
With the now system we can add all path finding logging to a certain channel and then hide that channel. Ill leave this open until that happens.

**Comment by kd7uiy** [comment]
It seems to me this has now happened, and this issue can be closed.

**Comment by bjubes** [comment]
Uberlogger closed this issue
