### ISSUE TITLE
Unity (Crash after download files)

### ISSUE THREAD

**Issue by LukeDavies367** [TeamPorcupine/ProjectPorcupine#643]
Hello, I'm new & wanna try this great project after i saw it on youtube, Problem i'm having at the moment is i can download it from here: http://quill18.com/porcupine/ (Link as from the youtube desc) works without problems but it's few days old now...

But when i go here:
https://github.com/TeamPorcupine/ProjectPorcupine *& download it i keep getting a crash log, I've do everything i know i can (I'm also up to date with Unity)

Is there any fix around this?
Thank you for your time/help
Luke

**Comment by mikejbrown** [comment]
Can you give any details of the error message? Either a log or a screen shot?

**Comment by GamerInspired** [comment]
What version of unity are you running? As if you aren't on the latest then it will crash when it try's to load the scene.

Believe the last is version 4.4. And you will need to install the latest manually as the unity check for updates doesn't seem to work.

**Comment by NogginBops** [comment]
@GamerInspired 5.4 :)

**Comment by LukeDavies367** [comment]
It's working now. I wasn't updated (Which wired cuz unity said i was on correct version, :)
