### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#648]
Unity has a standardized unit test system that we should really add. I don't think @quill18 has done a video on this subject, but it would be a great thing to add soon. We really need to come up with a standardized set of unit tests to ensure that new features don't break old features. I think since 5.3 you don't need to get anything from the Asset store, it is built in. Take a look at the video at https://unity3d.com/learn/tutorials/topics/production/unity-test-tools , but we really should do some work on this.

**Comment by Mizipzor** [comment]
Why close?

**Comment by kd7uiy** [comment]
I opened two by mistake.
