### ISSUE TITLE
Rework GetSpriteForFurniture to be less hard coded

### ISSUE THREAD

**Issue by mikejbrown** [TeamPorcupine/ProjectPorcupine#657]
Right now it has some pretty ugly `if (furn.objectType == "Door")`, `if (furn.objectType == "Airlock")` and similar nastiness that should go for the sake of moddability.

@TomMalbran had ideas how to do this on PR #644, but the changes probably belong on another PR.
Quote:
> For GetSpriteForFurniture() I think that the best solution is to make it part of the Furniture prototype, and make it possible to be changed as a LUA function. So:
> 
> The furniture would have a GetSpriteName() function, and a string property getSpriteNameAction (or something like that) with the name of a LUA function. In GetSpriteName() it will ask if getSpriteNameAction is set and if it is, it will call it and return the result, and if not it can return the objectType.
> 
> Then we can set the GetSpriteName as a property on the xml and have a GetSpriteName_DoorLUA function that can return the sprite name depending on the furniture parameters.
> 
> Maybe this would be for a separate PR.

**Comment by sboigelot** [comment]
This issue can be close as 660 is merged
