### ISSUE TITLE
Comparing strings

### ISSUE THREAD

**Issue by DeShrike** [TeamPorcupine/ProjectPorcupine#661]
I always use string.equals when comparing strings.

if (someString.Equals("someValue", StringComparison.OrdinalIgnoreCase) )
instead of 
if (someString == "someValue")

What do you all think about this ?

**Comment by Sommerbo** [comment]
I like Equals because it is more flexible.

**Comment by Mizipzor** [comment]
Other than style, what's the difference?

**Comment by spexiono** [comment]
Which one is more commonly taught in beginner tutorials? 
I'm used to more used to `if (a == "string")` from scripting languages like Lua and Python.

But also it would be nice to hear Quill's thoughts and what he'll use in the C# tutorial coming.

**Comment by looperhacks** [comment]
@Mizipzor Equals is more flexible, because you can provide some options (like ignoring case). MSDN recommends avoiding == and != for string comparison: https://msdn.microsoft.com/en-us/library/cc165449.aspx

However, using == with null values works, while using .Equals with null values will throw an exception.

**Comment by Mizipzor** [comment]
Then surely `string.Equals(s1, s2)` is better so you dont have to check for null?

**Comment by spexiono** [comment]
@Mizipzor
" .Equals with null values will throw an exception." 
Do you mean ==? Or am I confused :P

**Comment by looperhacks** [comment]
@spexiono 

That's what I meant:

    string s1 = null;
    string s2 = null;
    bool eq = s1 == s2; // works
    eq = s1.Equals(s2); // crashes

**Comment by Mizipzor** [comment]
I mean like this:

            string s1 = null;
            string s2 = null;
            var b = string.Equals(s1, s2); // true

If you would insist on using this:

            s1.Equals(s2);

You need to check for null. And you end up with something like this (which is how i think the other method is implemented).

            if (s1 == null)
            {
                return s2 == null;
            }
            else
            {
                return s1.Equals(s2);
            }

Not pretty at all. 

I'm completely fine with `s1 == s2` and `string.Equals(s1, s2)` but **definately against** doing `s1.Equals(s2)`.

**Comment by misspellted** [comment]
switch (method):
        case ".Equals":
            displayMessage("Used when one string is known to be non-null.");
            break;

    default:
        refactor();

**Comment by DeShrike** [comment]
if you do 
`if (s1.Equals("   "))`
and s1 can be null at this point, then you have other issues. This usualy means that something went wrong before this point.
You should have checked for null before coming to this point.

It's a good practice to always first check parameters in functions:
```

public void DoSomething(Furniture furn, string param1)
{
  if (furn == null)
  {
      throw new ArgumentNullException("furn");
  }

  if (string.IsNullOrEmpty(param1))
  {
      throw new ArgumentNullException("param1");
  }

  if (param1.Equals("xyz", StringComparison.OrdinalIgnoreCase))
  {
     ...
  }
}

```
Just my 2 cents ....

**Comment by Mizipzor** [comment]
If you dont want to allow the first paramter to be null, then you should do that. But people here really push back in exceptions, something I dont agree with. Log an error to return null is far more common. 

I think this is just one of the cases where it will be up to the individual developer writing that code. One way will throw exceptions if value is null, the other will not.

**Comment by bjubes** [comment]
IMO `name == "me"` is the shortest and makes a lot of sense to read over. I don't think any meaning is lost this way, so maybe only use `string.Equals` when extra options like ignore case are required

**Comment by Sommerbo** [comment]
Seems like the main argument for == over Equals() is that == works with null-strings. I always disliked when null is a valid data for anything. A null should be just that null/nothing/uninitialized not a valid option to carry data.

If you have to compare a null string to anything I would say you have made a mistake. But that is just like my opinion, dude.

**Comment by Mizipzor** [comment]
@Sommerbo I would like that that was the case. It was discussed before, instead of throwing exception you log an error and return null. I disagree quite strongly with this, I prefer to crash if theres bad data. But as long as null is returned left and right, it has to be taken into consideration.

**Comment by Fogsight** [comment]
I would go with more readable option. You can spot `==` at glance.

**Comment by mikejbrown** [comment]
My opinion coming from python FWIW: if you know it is invalid for null to be passed to your function check that case early and explicitly throw an exception for it, then you can use the readable `==` option. Readability + explicit checking beats weird method call syntax + helpful side effect any day.

Of course `.Equals` is a documented and stable API so this really is just a discretionary opinion on my part.
