### ISSUE TITLE
'Color' Versus 'Colour'

### ISSUE THREAD

**Issue by misspellted** [TeamPorcupine/ProjectPorcupine#663]
Has this discussion occurred yet? If so, I didn't see/read it yet, so I apologize in advance/hindsight.

I don't think it's strictly a coding concern, so it wouldn't fall under those conventions.

If a decision is made, is there a need for a PR? I'm assuming it will affect translations...

**Comment by Tranberry** [comment]
I'm pretty sure we will us US English.

**Comment by Mizipzor** [comment]
US English as default, UK as a localization. We use US spelling in the code as well.

**Comment by ComputerOverlord** [comment]
@misspellted Yes, it has been dissucssed before

**Comment by misspellted** [comment]
Well, if discussed, I'm going to close it then.
