### ISSUE TITLE
Xml Elements & Attributes Naming _conVenTions

### ISSUE THREAD

**Issue by sboigelot** [TeamPorcupine/ProjectPorcupine#664]
We currrently have a lot of inconsistency in the structure and naming convention of elements and attributes in XML.

This is a non-issue for now, but as the code base grows, a lot of error may arise from it. (and this will also confuse moders a lot)

![image](https://cloud.githubusercontent.com/assets/6545998/17885307/fec2c9de-691c-11e6-8fd6-32d6bb8c9465.png)

Do we have a naming (and structure?) convention from XML file? If not, should we have one?

**Comment by Tranberry** [comment]
I who thought that pascal case was camel case and vice versa.

**Comment by sboigelot** [comment]
Yep reverse it, dyslexia kills my brain sometimes, but the concept stay the same :)

**Comment by koosemose** [comment]
Yeah you've got your camelCase and PascalCase switched. But yeah consistency is important, particularly in the names  and casing. I tend to prefer Pascal for Elements, and camel for Attributes (as it is in Furnitures).

I'm not sure what you mean with the SubElement part, but I've solely had my nose stuck in Furnitures for a while, and am quite a few commits back where I'm working. Could you provide a bit more of an example of what you mean on the SubElements?

**Comment by sboigelot** [comment]
It's hard to explain, let's say you have a room with furniture in it

You can represent it by

(my naming: flat structure)
```
[room]
    [furniture name="n1"/]
    [furniture name="n1"/]
    [furniture name="n1"/]
[/room]
```

or

(my naming: elementParent_subElement)
```
[room]
    [room_furniture name="n1"/]
    [room_furniture name="n1"/]
    [room_furniture name="n1"/]
[/room]
```

or

(my naming and my personal :heart:  favorite: SubElement)
```
[room]
    [furnitures]
        [furniture name="n1"/]
        [furniture name="n1"/]
        [furniture name="n1"/]
    [/furnitures]
[/room]
```

**Comment by koosemose** [comment]
Ahh I see, I think I am also fond of the SubElement version. Furnitures seems to match that style (though I may have overlooked something), it just has a large number of singular unrelated elements in it.

**Comment by sboigelot** [comment]
@koosemose furniture is a mix bag

For instance the onUpdate lua Function are "flat structure"

**Comment by koosemose** [comment]
Ah hah, I'd missed that one... and looking through it, it quickly becomes obvious how/why it's that way, since originally OnUpdate was a singular SubElement, and then a second OnUpdate was added to door. It would probably be a good idea to try to do a bit of forward thinking on some of these things and try to decide if it's reasonable for there to be multiple of a particular element (or closely related elements), and if so put them in an appropriate containing element, so, hopefully, it doesn't need restructured everytime someone decides to add another element of a type that was previously singular (with appropriate alterations to the readers).

**Comment by sboigelot** [comment]
If we adopt the SubElement method, I don't think we need to keep bothering ourself with unsafe-ish code like the xml reader etc.

We can just use a simple .net xml serialization
Somthing like that:
```
public void Serialize<T>(Stream stream, T value) where T : class
        {
            using (var writer = new StreamWriter(stream))
            {
                var serializer = new XmlSerializer(value.GetType());
                serializer.Serialize(writer, value);
                writer.Flush();
            }
        }

        public void Serialize<T>(StreamWriter writer, T value) where T : class
        {
            var serializer = new XmlSerializer(value.GetType());
            serializer.Serialize(writer, value);
            writer.Flush();
        }

        public T DeSerialize<T>(Stream stream) where T : class
        {
            var serializer = new XmlSerializer(typeof (T));
            return serializer.Deserialize(stream) as T;
        }
```

**Comment by TomMalbran** [comment]
We are using PascalCase for both classes and properties/methods in C#, so I think that we probably should just use PascalCase for both elements and attributes, for consistency.

**Comment by koosemose** [comment]
However, we use camelCase for variables and a property is more analogous to a variable.

**Comment by Grenkin1988** [comment]
There are still a lot of inconsistency

**Comment by sboigelot** [comment]
@Grenkin1988 This issue is paused until we figure out the [Discussion] Switching our data format language.

**Comment by TomMalbran** [comment]
That makes sense. For some reason I forgot about that.

**Comment by bjubes** [comment]
the conventions like camel/pascal case will be needed regardless of data language so we can at least decide on those in the meantime

**Comment by sboigelot** [comment]
for me it's simple: we should follow the same as what we do in c# for consistency

**Comment by TomMalbran** [comment]
Well. if we go for JSON, Yaml, SKON I would argue to use PascalCase for all the keys. If we use XML, i wouldn't mind to keep camelCase for attributes, but I agree that we should keep it consistent with C#, so PascalCase for everything might be better.
