### ISSUE TITLE
UberLogger

### ISSUE THREAD

**Issue by Fogsight** [TeamPorcupine/ProjectPorcupine#665]
Can it be setup to point to an error when you click on the message in the console, like default behavior? I find it very inconveniencing to have to manually dig out where the error points to.

It is easily disabled by temporary deleting its folder, I'm not against its presence, but how useful is it?

**Comment by Mizipzor** [comment]
I though it did that. Or it did for me. Any ideas of what I could be doing that you are not?

**Comment by Fogsight** [comment]
Maybe something didn't get through? All I get is every error points to UberLogger.cs:491

**Comment by Mizipzor** [comment]
In the menu bar if you do Window -> Show Uber Console. Its supposed to replace the default console. Are you using the regular one?

**Comment by Fogsight** [comment]
Yep, found it, Uber Console points correctly. 

Needs some disclaimer on how to use it, otherwise you just get half featured default one and doesn't know what happens. Probably a good idea to leave a comment about it near UberLogger.cs:491.

**Comment by Mizipzor** [comment]
Good idea. I was wondering how people would find a wiki page.

**Comment by Fogsight** [comment]
@Mizipzor Doing awesome job, BTW! I was afraid I was coming off a bit dry. My sleep schedule screwed up, and I might behave like a zombie.

**Comment by Mizipzor** [comment]
@Fogsight No worries man. :)
