### ISSUE TITLE
Project not loading in Unity

### ISSUE THREAD

**Issue by JosephBywater** [TeamPorcupine/ProjectPorcupine#67]
I just updated my fork to the master ProjectPorcupine branch and now when I try to load the project in Unity, it doesn't load and I get NullReferenceException errors. Before I updated my Fork, it loaded just fine. I'm on Unity 5.4 
![image](https://cloud.githubusercontent.com/assets/5558617/17739952/bed8374c-648e-11e6-8870-5c508f2f65fb.png)

**Comment by BeefEX** [comment]
Have you loaded _SCENE_.unity?

**Comment by JosephBywater** [comment]
@BeefEX _SCENE_.unity?

**Comment by JosephBywater** [comment]
@BeefEX That still doesn't work :/ I don't know why it's not working now, because it did before!

**Comment by quill18** [comment]
@JosephBywater I just updated and it seems to be fine here.  Try quitting out of Unity, then deleting the "Library" folder in your project directory. This is not part of the actual project data -- Unity generates this automatically at your end.  That might reset things for you.

**Comment by quill18** [comment]
A quick Google suggests that the fix is to tell Unity to reset your layout:

http://answers.unity3d.com/questions/422278/how-do-i-find-what-causes-nullreferenceexception.html

(This isn't a problem with the project.)

**Comment by JosephBywater** [comment]
@quill18 I must have done the wrong google search :P Anyway, it works now :)
