### ISSUE TITLE
Game broken?

### ISSUE THREAD

**Issue by zleeoo** [TeamPorcupine/ProjectPorcupine#680]
I've just downloaded the game and it appears to be completly broken to me.
It's only my problem?

**Comment by RodRitter** [comment]
Latest master works fine. What isn't working for you? Any error messages?

**Comment by FilippoLeon** [comment]
You may need to reload the scene or clean your git copy.

**Comment by zleeoo** [comment]
I'll try again cleaning my folder and re-downloading the entire project, Thanks!

**Comment by Mizipzor** [comment]
Maybe wrong Unity version?

**Comment by Tranberry** [comment]
If you tell us what the error was maybe someone else would benefit from that. @gatekeepers what's your thoughts on this?
