### ISSUE TITLE
Discussion: Damage value

### ISSUE THREAD

**Issue by FilippoLeon** [TeamPorcupine/ProjectPorcupine#689]
Looking at the sprite controller, I see that there are many "hardcoded" specific handles for the sprites (cf. https://github.com/TeamPorcupine/ProjectPorcupine/issues/657)

I think we should have some more flexibility for the system.

In particular: animations and damage value.

Currently we have code like this:

```
            if (furn.objectType == "Airlock")
            {
                if (furn.GetParameter("openness") < 0.1f)
                {
                    // Airlock is closed
                    spriteName = "Airlock";
                }
                else if (furn.GetParameter("openness") < 0.5f)
                {
                    // Airlock is a bit open
                    spriteName = "Airlock_openness_1";
                }
                else if (furn.GetParameter("openness") < 0.9f)
                {
                    // Airlock is a lot open
                    spriteName = "Airlock_openness_2";
                }
                else
                {
                    // Airlock is a fully open
                    spriteName = "Airlock_openness_3";
                }
                //Debug.Log(spriteName);
            }
```

However, we could generalize the system by implementing a damage value system. I'm opening a discussion to see implementation ideas and see if there is interest.

Each furniture could have a generic "damage value", that would determine the looks of the sprite. All should be done mainly with XML structure and LUA code.

Example:
 - door opening with "damage value"
 - wall damage
 - machine animation (on/off) etc.

**Comment by mikejbrown** [comment]
For reference why this has closed: #657 has now been closed with PR #660. With the new system this should be pretty simple to implement. All that hard coding is replaced by a `<GetSpriteName FunctionName="GetSpriteName_Door" />` XML tag and matching LUA function

```
function GetSpriteName_Door( furniture )
	-- Door is closed
	if (furniture.GetParameter("openness") < 0.1) then
		return "Door"
	end
	-- Door is a bit open
	if (furniture.GetParameter("openness") < 0.5) then
		return "Door_openness_1"
	end
	-- Door is a lot open
	if (furniture.GetParameter("openness") < 0.9) then
		return "Door_openness_2"
	end
	-- Door is a fully open
	return "Door_openness_3"
end
```

So it's easy to change furniture sprites arbitrarily through LUA now!
