### ISSUE TITLE
[Question] Power cell size?

### ISSUE THREAD

**Issue by GamerInspired** [TeamPorcupine/ProjectPorcupine#690]
Is the power cell meant to be that big?

![ss 2016-08-23 at 09 01 36](https://cloud.githubusercontent.com/assets/8201304/17907701/f9f442f4-6974-11e6-9845-6d72809a85d0.png)

**Comment by ComputerOverlord** [comment]
no... I don't think so...

**Comment by dusho** [comment]
should be fixed by #1047

**Comment by sboigelot** [comment]
Current master behavior
![image](https://cloud.githubusercontent.com/assets/6545998/18418161/6e132396-7841-11e6-8b54-a775ecbb00b3.png)
is this consider fixed? It still feels odd to me that it goes out of a tile

**Comment by Tranberry** [comment]
it needs a new 1u sprite.

**Comment by dusho** [comment]
it should get new art with my #1084 , whenever that manages to get merged...

**Comment by Tranberry** [comment]
there seems to be conflicts in that PR :(

**Comment by dusho** [comment]
#1084 is merged to master now, this can be closed
