### ISSUE TITLE
Flooring Tip

### ISSUE THREAD

**Issue by GamerInspired** [TeamPorcupine/ProjectPorcupine#691]
I highly recommend that no one trys to queue up the entire map to be floored all at once. As when I did this semi by accident and semi on purpose, found that the game will hang for a long time.

**Comment by Tranberry** [comment]
Sounds like something solved with a restriction.

**Comment by GamerInspired** [comment]
All I did was click one corner then went to check another window, came back clicked the other corner and wondered why the game was hanging, to then find out that I had just queued up the entire map to be floored.

**Comment by kd7uiy** [comment]
Just tested this, it works just fine so far as I'm concerned, I recommend closing.
