### ISSUE TITLE
Unity freezes when the Power generator is fed

### ISSUE THREAD

**Issue by svmnotn** [TeamPorcupine/ProjectPorcupine#696]
This is happening in the latest unity build for linux, I'm running the latest kernel using Arch. The last commit of master was: 5fe9990

**Comment by mattpott** [comment]
Is this still the case? Have you check the unity debugger to see what is happening?

**Comment by svmnotn** [comment]
I'll have to check

**Comment by Grenkin1988** [comment]
Should be fixed. Closing. If still exists, open new please
