### ISSUE TITLE
[BUG] [Latest] NullReferenceException in Character

### ISSUE THREAD

**Issue by sboigelot** [TeamPorcupine/ProjectPorcupine#702]
```
NullReferenceException: Object reference not set to an instance of an object
Character.GetNewJob () (at Assets/Scripts/Models/Character.cs:246)
Character.Update_DoJob (Single deltaTime) (at Assets/Scripts/Models/Character.cs:292)
Character.Update (Single deltaTime) (at Assets/Scripts/Models/Character.cs:652)
World.Update (Single deltaTime) (at Assets/Scripts/Models/World.cs:180)
WorldController.Update () (at Assets/Scripts/Controllers/WorldController.cs:123)

```

To Reproduce just build this scene:

![image](https://cloud.githubusercontent.com/assets/6545998/17912903/eb960fc2-6996-11e6-879c-b39e6ca25dc7.png)

**Comment by sboigelot** [comment]
maybe related to #699 ?

**Comment by mikejbrown** [comment]
I can't seem to reproduce this. Is it still an issue?

**Comment by bjubes** [comment]
If anyone gets this to reproduce, please make a save and upload it here

**Comment by sboigelot** [comment]
Let's close this ticket for now, I didn't see it happen since a long long time (related to the lifespan of the development).

If it arise again, someone will make a new ticket.
