### ISSUE TITLE
Pipes and Vents

### ISSUE THREAD

**Issue by SteelFall** [TeamPorcupine/ProjectPorcupine#704]
Hey there!
**Pipes**
I was going to start to work on pipes and vents but I am really unsure about the way that pipes should be. Here are the two of "styles" I was thinking about:

- Pipes will be a type of visible furniture (which may make more sense once we have some world layers)
- Pipes will be beneath the floor and they are visible without a floor (ie Prison Architect)

**Vents**
Vents should be able to be opened and closes (in case combat-related wall breaches become a thing). This will also allow players to build vents in position for a new room which can then be filled with O2 quicker. Vents may also have settings:

Room A -> Room B
Room A <- Room B
Room A <> Room B (equalise gas levels)

Feedback and alternative ideas are greatly appreciated.

**Comment by sboigelot** [comment]
Another suggestion is:

Visible pipes ouside of room
Invisible (under floor) pipes indoors (turn visible on build mode)

**Comment by SteelFall** [comment]
@sboigelot Ah yes! Good idea!

**Comment by SteelFall** [comment]
Updated the description as I have forgotten to talk about the vents. :/

**Comment by GamerInspired** [comment]
I think I prefer the idea of having them visible (but able to walk through them for now) for when we have multiple levels. Would be cools to see the pipes run outside the base.

**Comment by vogonistic** [comment]
It'll be important to be able to see when pipes and connections that goes outside the base breaks, so it might be good to show them in some way at all times.

**Comment by GamerInspired** [comment]
We will also need to make sure that pipes can go through walls? With breaching it so that the room stays a room; maybe by using a wall-pipe or something.

**Comment by vogonistic** [comment]
I think we might need a new layer, so we get this stack: `tile`, `furniture`, `pipes`, `inventory`

**Comment by sboigelot** [comment]
We should probably also be able to build multiple pipes on the same tile:

For instance, power, water, gaz

In order to not make the pipe building too tedious

**Comment by GamerInspired** [comment]
@vogonistic so getting the z-level started?

**Comment by vogonistic** [comment]
I think z-level is separate, but we might be able to pipe between connected levels. =)

**Comment by GamerInspired** [comment]
@vogonistic In my opinion that's fine as long as you are still able to have them on the same level as the workers; would look cool to have the workers walk past steaming pipes or something.

**Comment by GamerInspired** [comment]
@sboigelot I also think that's a good idea, don't want to have to spaghetti the pipes/wires to much.

**Comment by Tritaris** [comment]
abackwood: but I think then what we'd need is gas tanks
abackwood: that function as "genertators" when set to do so
Tritaris: yeah i have been thinking about that myself. it makes sense to make it from ice . Tanks could come once we start on the piping and vent system
abackwood: if (gasPressure <  THRESHOLD) exude gas else store gas
abackwood: for now they could take it from the room they're in
abackwood: it's just because what if you're in a palce where ice is far away
abackwood: don't want your dudes to suffocate
Tritaris: like  a compressor

**Comment by vogonistic** [comment]
It'll probably be important to be able to set a color that automatically gets used for everything connected to it, so you can follow your pipes more easily.

**Comment by SteelFall** [comment]
That might be a good idea.

**Comment by neobonde** [comment]
What if you could choose what layer pipes where to be placed on? One layer visible(Above flooring) and an other one not visible(Under flooring).

**Comment by SteelFall** [comment]
That could be a good idea at a later stage. I am currently still trying to get the basic pipe layer sorted out. :)

**Comment by vogonistic** [comment]
I'd prefer an ability to turn off rendering of the entire pipe layer rather than having multiple places to put them.

**Comment by abackwood** [comment]
That compressor has since been added

**Comment by SteelFall** [comment]
Just added a PR to establish utility items in general (#759). It is mostly the furniture classes where "furniture" is replaced with "utility" until we find out what to keep and what to remove.

**Comment by SteelFall** [comment]
The previous PR did not go too well so I have made a new one: #821!

**Comment by koosemose** [comment]
Closing this as we have a basic system in place, only need to have systems start hooking into it (and develop said systems.
