### ISSUE TITLE
[WIP - UI] Need some input

### ISSUE THREAD

**Issue by dustinwloring1988** [TeamPorcupine/ProjectPorcupine#706]
Here is what the Hierarchy in unity will look like on this PR -will submit after my current PR is meged

![hierarchy](https://cloud.githubusercontent.com/assets/21135165/17914328/1ca27196-696f-11e6-950b-70786b2344ee.png)

Game play in the Editor

![grid](https://cloud.githubusercontent.com/assets/21135165/17914331/1d9b45f0-696f-11e6-8a5c-d148a6c5adf2.png)

Now all the Dialog Boxes and Menus are loaded at runtime this will be easy to change almost any UI object and not have to touch the _SCENE_ file.

Do you like the use of the Grid View?

**Comment by sboigelot** [comment]
yes if the column count is not restricted

**Comment by bjubes** [comment]
i think the grid view is a bit crowded, especially on low res displays, but the scene looks very clean

**Comment by bjubes** [comment]
also you may want to add the PR number to your OP

**Comment by dustinwloring1988** [comment]
I will when I submit it working one a couple more bugs. 
Thanks for the input guys.

I really just did things like this as a "place holder" until we get a better UI system in place. I know the way I have it is not the best. But it keeps us out of the _SCENE_ file for the most part.

**Comment by dustinwloring1988** [comment]
https://github.com/TeamPorcupine/ProjectPorcupine/pull/707

**Comment by vogonistic** [comment]
I'm not a fan of the column view.

**Comment by jamzam90** [comment]
I find it that I need to dig around to find the furnitures it took me a minute to figure out that work does nothing and construction is what i need with the current ui. The grid form would be nice especially if you add scroll bars for when there are way more object.

**Comment by jamzam90** [comment]
Also instead of a button make it so that the sprite for the furniture object shows up, with a tool tip or text someware on the sprite to know what it's called, more or less like prison architects item menu.

**Comment by Grenkin1988** [comment]
@dustinwloring1988 Is this an open issue still?

**Comment by koosemose** [comment]
The current UI has at least changed beyond what this was looking to alter. Closing. Feel free to open a separate issue if you have a proposal for altering the UI from its current state.
