### ISSUE TITLE
[WIP, Concept] Art for Uranium 

### ISSUE THREAD

**Issue by AaronBuckles** [TeamPorcupine/ProjectPorcupine#709]
I just came up with a concept for the Uranium.  Is the black outline a good idea?  I figured it would match the rest of the art in the game.  Can be removed though.  I plan on keeping a consistent look for other resources.  Please give any suggestions.
![uranium_concept](https://cloud.githubusercontent.com/assets/21068682/17917572/84e7ccee-6972-11e6-8ad3-b0241f183db2.PNG)

**Comment by Raketfart** [comment]
I think the black outline fits nicely with the new character sprite

**Comment by TheRiven** [comment]
It does fit but I do feel that dumping lumps of uranium into the reactor does not seem like the safest way to run such a machine. :laughing: 

but then it is the future :thought_balloon:

**Comment by GamerInspired** [comment]
Maybe we need to process it before hand?

**Comment by TheRiven** [comment]
Probably something like that

**Comment by AaronBuckles** [comment]
Ok, I will try to make some sprites more after school today.

**Comment by kd7uiy** [comment]
We have new sprites for Uranium. Is there any reason to still keep this issue opened?

**Comment by sboigelot** [comment]
Alternate options for sprites are not a bad thing. We should allow artist to submit what they think is an improvement then the community can decide which sprite to use. The non selected sprite can still be used later on a texture pack of for another item

**Comment by Tranberry** [comment]
now with z-levels being a thing the ore probably needs a 'wall sprite' and a floor sprite too.

**Comment by koosemose** [comment]
Closing this as the original author hasn't seemed to have came back to do anything further with this.
