### ISSUE TITLE
Logspam and Uberlogger

### ISSUE THREAD

**Issue by Sommerbo** [TeamPorcupine/ProjectPorcupine#710]
We should aim to reduce log spam since right now it is ridiculous. Log spamming reduces the usefulness of the log and degrades performance. A lot of `Debug.Log` calls are inside loops and that is their main problem additionally quite a lot of the debug log-messages contain no information besides the fact that it was run, while this is useful for debugging those calls should be removed before pushing.

And we should include channel specific logging afforded by Uberlogger where appropriate, Currently only `Tiletype.cs` does this. Using channels isn't hard and doesn't affect the Unity log console but it nicely 
groups log messages in the Uberlogger console, use menus `Windows -> Show Uber console` to see it. 

The difference in the code is as follows:
`Debug.ULogChannel("TileType", "Read tileType: " + type.Name + "!");`
Replaces
`Debug.Log("Read tileType: " + type.Name + "!");`

The first argument is the name of the "Channel" you want to use, it can be anything it just creates a button in the uber console. I would advice to use the name of the class as channel-name to group related log messages together.

`Debug.ULogWarningChannel` and `Debug.ULogErrorChannel` gives the appropriate loglevels

**Comment by vogonistic** [comment]
Everybody is waiting for someone else to break eye contact first and have to fix it. I would love to see this, especially for Jobs and Pathfinding.

**Comment by Fogsight** [comment]
Now you can appreciate full amount of spam in real-time :) #718

**Comment by Sommerbo** [comment]
Slowly fixing these. Worst spam already removed

**Comment by bjubes** [comment]
Thanks for this issue, I think most people (me included) havent used UberLogger before so we aren't using channels because of it. hopefully from now on more PRs put this in initially.

**Comment by mikejbrown** [comment]
Since it is hard to tell atm where people are working I announce my intent to start work on the controllers... If somebody out there is already working on them please let me know so I don't stomp all over your toes. :smile:

**Comment by vogonistic** [comment]
@mikejbrown It's easier for us to accept the PR's if they are limited in scope, so don't fix all of them in a single PR.

**Comment by mikejbrown** [comment]
I'll go alphabetically down the list: BuildModeController, CharacterSpriteController, ...
Do you want each file in a separate PR or is it ok to combine a few? Some especially don't have many calls to fix.

**Comment by Sommerbo** [comment]
Go for it, @mikejbrown

**Comment by Grenkin1988** [comment]
@Sommerbo Is this an issue still?

**Comment by mikejbrown** [comment]
Hmm... at the moment I count 16 instances of Debug.Log in the code outside of UberLogger itself...

**Comment by Grenkin1988** [comment]
@mikejbrown Where can you find them?

**Comment by mikejbrown** [comment]
@Grenkin1988 

![untitled2](https://cloud.githubusercontent.com/assets/855931/18279027/7db0946c-7497-11e6-83c7-ff3520ec3374.png)

**Comment by Grenkin1988** [comment]
@mikejbrown They are all "our" `Debug.Log`

**Comment by Sommerbo** [comment]
Well yes and no. I did a while back and moved over all debug calls except the ones known to be multiline. So in that way the issue is closed, but since people keep changing back to regular debug syntax or writing new debug calls it is still an open issue.

**Comment by koosemose** [comment]
Closing this, as it's already in Contributing.MD, and if it's not followed from there a month old issue isn't likely to make a difference.
