### ISSUE TITLE
Fix spelling error in ContextMenuAction and related places

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#712]
ContextMenuAction has a spelling error in one of the fields. Find and replace `RequiereCharacterSelected` with `RequireCharacterSelected` where you can find it.

Follow the style guidelines in [CONTRIBUTING.md](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/CONTRIBUTING.md)

**Comment by sboigelot** [comment]
Oups sorry, I'm not a native speaker and sometimes I get confused with English :'(

**Comment by vogonistic** [comment]
@sboigelot It's no big deal. It created a nice beginners task.

**Comment by Tritaris** [comment]
#825 fixed this.

**Comment by sboigelot** [comment]
We can close this issue.
