### ISSUE TITLE
Suggestion: Create beginner tasks

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#72]
Since this was created as a Unity tutorial, it'd be great for beginners (of Unity, programming or otherwise) if we created a set of tasks, labelled them "Beginner" and discouraged people with experience from just solving them. It would serve as an easy way for someone to get introduced to the pull requests, doing something that helps and finding something that they can work on.

I've seen it on many other projects and it seems to be a good way to get people involved.

There might not be any right now, but this can serve as a place to discuss it.

**Comment by NogginBops** [comment]
Really think this is a good idea!

**Comment by Tranberry** [comment]
I would be a target for this kind of initiative. But I don't quite get how this would work, will there be some 'no issue' thing that would be easy to solve but left hanging for us not so experienced coders?

**Comment by NogginBops** [comment]
I think that's the idea, to keep the experienced coders for stealing the easy stuff. To make the experienced coders leave certain features to the beginners. Though as you said, there might not be that many issues fitting for this.

**Comment by vogonistic** [comment]
There might not be a lot of issues now, but they will show up along the road. I just wanted to get people to think about it.

**Comment by Mizipzor** [comment]
A beginner label sounds awesome. Githubs label support is great, make it happen!

**Comment by lameox** [comment]
Love the idea. However i think this idea only has merit once one or more community managers are named that can take over (some of) the administrative tasks from quill.

**Comment by Mizipzor** [comment]
@lameox Is there a discussion ongoing regarding that? I would like to volunteer.

**Comment by ComputerOverlord** [comment]
Good Idea! Maybe when Quill gets to the Issues...

**Comment by lameox** [comment]
Well i think we open issues and pullrequests too fast atm for quill to realistically handle all of them in the precious time he has each day

**Comment by WardBenjamin** [comment]
Once @quill18 appoints more maintainers/managers/whatever-he-wants-to-call-them, we can use Github's label system for this.

**Comment by vogonistic** [comment]
It would be nice to be able to use labels. I created a beginner task #300. Let me know if you think the format looks alright, or if you think it's unclear. Do we need people to claim them?

**Comment by WardBenjamin** [comment]
I would prefer people claimed them so we don't have 5+ duplicate pull requests like we did for the PowerGen localization, but other than that I like it.

**Comment by vogonistic** [comment]
I agree, claiming and then having a moderator assigning the bugs would be good.

**Comment by vogonistic** [comment]
I'm closing this. We've tried it a couple of times and it works well, we just need to identify which bugs are good starters and label them.
