### ISSUE TITLE
Error: Downloading Localization

### ISSUE THREAD

**Issue by RodRitter** [TeamPorcupine/ProjectPorcupine#721]
I seem to be getting an error about 2 seconds into my game regarding the LocalizationDownloader.

![image](https://cloud.githubusercontent.com/assets/4159679/17920289/faedc81a-69d3-11e6-8810-24bae54e0e49.png)

**Comment by sboigelot** [comment]
Confirm having the same issue

**Comment by vogonistic** [comment]
It must be something with #667

**Comment by RodRitter** [comment]
Perhaps people with firewalls will have trouble with this? I see localization is being downloaded from https://github.com/QuiZr/ProjectPorcupineLocalization/archive/[version].zip

**Comment by Sommerbo** [comment]
It also happens when `curr.ver` file is missing. That should fixed.
Try deleting all files in `/Assets/StreamingAssets/Localization` and re run

**Comment by RodRitter** [comment]
That indeed fixes it.
