### ISSUE TITLE
[BUG] KeyNotFoundException in Parameter.cs

### ISSUE THREAD

**Issue by mikejbrown** [TeamPorcupine/ProjectPorcupine#725]
Getting this whenever building the metal smelter:

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2<string, Parameter>.get_Item (string) <0x00341>
Parameter.get_Item (string) (at Assets/Scripts/Models/Parameter.cs:62)
(wrapper dynamic-method) System.Runtime.CompilerServices.ExecutionScope.lambda_method (System.Runtime.CompilerServices.ExecutionScope,object,object[]) <IL 0x00020, 0x000ed>
MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute (MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) <IL 0x00049, 0x00231>
MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor.PerformOverloadedCall (MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) <IL 0x00050, 0x0028e>
MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor/<>c__DisplayClass33_0.<GetCallback>b__0 (MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) <IL 0x00014, 0x00075>
MoonSharp.Interpreter.Interop.BasicDescriptors.DispatchingUserDataDescriptor.ExecuteIndexer (MoonSharp.Interpreter.Interop.BasicDescriptors.IMemberDescriptor,MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.DynValue,MoonSharp.Interpreter.DynValue) <IL 0x000aa, 0x006c2>
MoonSharp.Interpreter.Interop.BasicDescriptors.DispatchingUserDataDescriptor.Index (MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.DynValue,bool) <IL 0x00024, 0x0013f>
MoonSharp.Interpreter.Execution.VM.Processor.ExecIndex (MoonSharp.Interpreter.Execution.VM.Instruction,int) <IL 0x000f9, 0x007a1>
MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop (int) <IL 0x00572, 0x01d21>
MoonSharp.Interpreter.Execution.VM.Processor.Call (MoonSharp.Interpreter.DynValue,MoonSharp.Interpreter.DynValue[]) <IL 0x00077, 0x00388>
MoonSharp.Interpreter.Script.Call (MoonSharp.Interpreter.DynValue,MoonSharp.Interpreter.DynValue[]) <IL 0x000a4, 0x00594>
MoonSharp.Interpreter.Script.Call (MoonSharp.Interpreter.DynValue,object[]) <IL 0x00026, 0x001af>
MoonSharp.Interpreter.Script.Call (object,object[]) <IL 0x00009, 0x0008c>
FurnitureActions.CallFunctionsWithFurniture (string[],Furniture,single) (at Assets/Scripts/Models/FurnitureActions.cs:61)
Furniture.Update (single) (at Assets/Scripts/Models/Furniture.cs:110)
World.Update (single) (at Assets/Scripts/Models/World.cs:230)
WorldController.Update () (at Assets/Scripts/Controllers/WorldController.cs:127)
```

Refers to the return line here:

```
    // Iterator to simplify usage, this works properly in Lua
    public Parameter this[string key]
    {
        get
        {
            return contents[key];
        }
```
Should there be a default value here?

**Comment by koosemose** [comment]
I'm not a huge fan of defaults (at least defaults not set by the caller), but since the actual fault is user modifiable code, and we can't give proper error messages from Lua, it's probably reasonable to have some form of defaults so one bad mod doesn't bring the entire thing crashing down.

**Comment by mikejbrown** [comment]
Yep... that's what it is. I put `Debug.ULogWarningChannel("Parameter", "Accessing key: " + key);` above the return statement and when it throws the error it is `Accessing key: smelting` which doesn't exist in the XML but is (or, rather, was previously) created in code a runtime. So it is not getting created.

If furniture continues to use the params for the equivalent of local instance variables then perhaps we should live with default values and lazy creation? Otherwise we should formalize a convention that params can only be defined in XML.

**Comment by koosemose** [comment]
Yeah, unfortunately I'm not sure if there's any reasonable way to have local instance variables in the Lua with the way it is set up, I'm pretty sure with how it is now any variables would be shared between all furniture, or at the very least all furniture that uses that function if there's a way to make a local scope to that function call. I'm not familiar enough with Lua to know if there's a way to do even that much let alone each piece of furniture having its own variables.

**Comment by mikejbrown** [comment]
So the metal smelter doesn't throw this after #688. But it would still be good to establish what happens when someone accesses a parameter key that is not defined. Should we let an exception be thrown (keep in mind this could be from code in mods) or specify a default value or enforce something more Lua-centric?

**Comment by koosemose** [comment]
The exception as is is simply unacceptable, at the very least we need a more explicit error (at the very minimum something along the lines of what you used for debugging), something more Lua-centric would be preferable in my opinion, if we could get an actual Lua line number for the error would be great so that if we decide to lay the bug at the Lua script's feet, it can be shown where it is. If neither of those are desired I can put in the default value system (after having slept I know how to implement it). Though I'll probably look into implementing a default value system anyways, but if it's not needed to keep Lua from crashing horribly, I'll likely make it only work for explicit calls for a default.

**Comment by mikejbrown** [comment]
#746 is a first pass. Thoughts?
