### ISSUE TITLE
[Discussion/Enhancement] Gas Compressors

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#729]
There has been some talk of making the O2-Generator require ice to operate. I think that makes a lot of sense and is cool. However, that could leave the player with no way to produce oxygen at the start if there is no ie nearby. It would be lame for the characters to suffocate so quickly.

Therefore, I was thinking of adding Gas Compressors. They are essentially big tanks that release their gas into the air when there is too little and slowly refills when there is enough. In vacuum they lock down and don't release anything.

The starting ship/station would then have a compressor filled with O2, given the player a grace period to set up production while they live off the reserves.

Thoughts?

**Comment by GamerInspired** [comment]
Seems like a good idea to me, would also other uses later on, as it sounds like you could pump gas into it later on (once pipes are in) making it more of a gas tank.

**Comment by abackwood** [comment]
That's my thought too. It could be tied into the pipe system. But while that's not there (or as default behaviour) it works locally

**Comment by GamerInspired** [comment]
I think once pipes are in then there should be a separate furniture that does the releasing of gas. But maybe also having a early game all in one system would be a good start but also nice to have for progression sake.

**Comment by vogonistic** [comment]
Sounds like what we are going to need in airlocks too. When you want to go out, we pump the gas into a tank and when the outer door is closed, we can put it back.

**Comment by abackwood** [comment]
I considered making a general compressor that just takes "air" instead of O2, but I wanted to see if this worked first before diving into it.

For the airlock, that general one would be needed, and it needs to be changeable by the characters. They press a button and the room is sucked into the tank.

**Comment by sboigelot** [comment]
As oxygen compressor are in the game now, should we close this issue? There is also many issue about how should the airlock work.
