### ISSUE TITLE
[Bug] UI doesn't fit on screen

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#730]
SOme o the UI seems to be falling off my screen since commit #716. Does anyone else have this happen to them? I can hardly see some of the border UI elements.

![uitoobig](https://cloud.githubusercontent.com/assets/6920426/17924400/cda564ac-69e8-11e6-996b-cc98d3bf0c49.png)

**Comment by Fogsight** [comment]
Scale on the screen set to 1.1, roll back a mouse wheel a bit :)
