### ISSUE TITLE
Any thoughts about adding simple GAB

### ISSUE THREAD

**Issue by yonner** [TeamPorcupine/ProjectPorcupine#732]
Hi Porcupiners,

First let my start by saying I don't want to steel anyone else's thunder if some else's is planning to implement a GAB (goal-driven agent behavior) system or some other form of AI for this game. Please point me to the relevant issues or pull requests if stuff like this is already in motion.

So I have been watching the progress on project porcupine since it first started and I cant believe the progress made so far. Before I started watching these youtube tutorials I was already trying to understand GOAP and GAB [GOAP web site](http://alumni.media.mit.edu/~jorkin/goap.html) (this is a pretty good resource for all information related to GOAP) and how to apply it to my own Unity projects.

After Quill18 released his project to the world via Git I wanted to contribute in some way, so I thought I would have a go at implementing GOAP / GAB for this project. I don't have a lot of time on my hands but I think I could add a basic start to GAB where AI Agents (the space men) would try to satisfy 4 simple goals, explore, get food, sleep or sleep in habitat (Most of these ideas would be borrowed from this book :-  [AI book](https://www.amazon.co.uk/Programming-Example-Wordware-Developers-Library/dp/1556220782) which is pretty good).

Over time these requirements would reduce and then the impact of these requirements would be recalculated eg if sleep is needed, should the agent rest here or walk to the nearest bed to get proper rest. The system would then generate a series of actions which either consist of an atomic task or a composite of tasks to satisfy the current need.

Obviously this is a very broad explanation of what I have planned, what do people think of this approach and what else do I need to detail in order to start development of this and issue pull requests etc..?

Sorry if this post seems like rambling, I am very new to the whole community contribution thing.

Jase

**Comment by mmooxy** [comment]
#86 #726

**Comment by MSigma** [comment]
Requesting that this issue be closed as we're already discussing this type of system in #726.

**Comment by yonner** [comment]
Leave a comment
