### ISSUE TITLE
How to submit RAW image files. (.svg, .piskel etc.)

### ISSUE THREAD

**Issue by longtomjr** [TeamPorcupine/ProjectPorcupine#734]
How do you think should we go about submitting our raw image files. I was thinking branch, but I am not sure. What do you guys think

**Comment by bjubes** [comment]
I don't think raw files belong on the repo. lets say a 5MB raw file is uploaded, then changed 3 times, that 20MB. multiply for 30 images/sounds and that's 600MB out of 1024MBfree. Binaries that aren't required for the game to run have to be stored either off the repo in some dropbox like system so that we don't run out of room on github for texted based assets

**Comment by JosephBywater** [comment]
I have unlimited storage in my Google Drive (2 petabytes or something crazy ;) )

**Comment by longtomjr** [comment]
I was thinking raw data files. Like .piskel and .svg. Both of those are text. So they should not be more than like 50kb at most. It is just files that can be opened to make changes to the art.

**Comment by bjubes** [comment]
okay since their text based maybe those can be included then in a new directory? Idk this is probably one for @quill18, but large binaries like gimp and photoshop files should not be in the repo at all if possible

**Comment by bjubes** [comment]
also just checked out piskel files, they are techincally json, but they store the image in base64 so you end up with a text file like this
```
{"modelVersion":2,"piskel":{"name":"TradeShip","description":"","fps":6,"height":192,"width":192,"layers":
["{\"name\":\"Ship\",\"opacity\":1,\"frameCount\":1,\"base64PNG
\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAOEUlEQV
R4Xu2dL5IlNxLGa9BAmy0Z0AfwBfoCTX2ARQ9sR5gss+nE0DVb4ohe0GgPYDoXmAv4AA1MzNbQqDdU
/fRGT08lZaYy9afqe7BbSqU+5a9SUqmq3i34QYEDK
/DuwH1H16HAAgAQBIdWgAPAayOlOD41cgnN7FUBTrC9fvr0yVyHjx8
/hm1w/DP3DQ3sTwFqgF0FfxSkqqqEkJ3bofqo6geMHUMBanBdAHh5eVmen5+XL1++mCh0f39
/setgCGCj+mriF4zuUwFqUDUDIJTZweAzArLBPgOwd6+GBsCJ4zMCskHvUNln+8MD4GVHNthnAPbu1TQ
A+GyAKVHvkNlX...
```

**Comment by Grenkin1988** [comment]
@longtomjr This is open question?

**Comment by longtomjr** [comment]
We have not reached a conclusion, but I assume that this is not a concern for now
