### ISSUE TITLE
Local instance variables in Lua

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#743]
Currently, when a Lua function needs a variable that is persistent between calls to that function and exclusive to that particular piece of furniture, the convention seems to be to set a Parameter, and the way it's usually implemented is just to try to use it, and if it isn't there it relies on the old default values (which aren't present at the moment), which now causes an error (#740 & #725).

This seems a hackish solution, is there a way to define variables in such a way in Lua that they would only be for that particular instance of the furniture and persist between calls to the function, so that this can be handled in a more appropriate manner?

**Comment by Randshot** [comment]
I don't know if the Lua state is kept alive or created anew for every call, but if it is kept alive, then it is possible to define Lua intern tables to keep track of values or such.
You won't have access to the xml values with this method though.

**Comment by koosemose** [comment]
... and that means it wouldn't persist across saves... dangit.

**Comment by Randshot** [comment]
Just tried it and it doesn't seem to work anyways.

**Comment by mikejbrown** [comment]
An advantage of the Parameter system is that it is easily saveable in the XML without any modifications to the system.

A problem with the Parameter system (apart from the KeyNotFoundException bug which exists at the moment) is that the parameters are effectively static "class" level variables (think of furniture types as a class and specific instances of furniture as objects). So if you want to implement member variables you have to spoof them with something like `furniture.Parameters["member_variable"][objectId]` where objectId is something like a hash you can easily and uniquely generate from a particular `furniture` instance. Ugly...

**Comment by koosemose** [comment]
Parameters should be individual to a piece of furniture, I know openness for doors is, because I had a bug when I was working on Parameters and it wasn't. Once a piece of furniture is cloned from the prototype it gets its own copy of the Parameters with a deep clone of all the inner bits.

**Comment by FilippoLeon** [comment]
I think the Parameters are perfect for that. All LUA codes for Furniture act as "Member" function of the furniture, just that is implemented in lua. All parameters (Param) act as storage (i.e. like c# class parameters) and represent the state of the FRurniture object, exposing the Parameters to both c# and LUA

**Comment by koosemose** [comment]
My issue is only with default values when not requested by the caller, in that they can mask bugs.

If I try to access `openness` but instead type `openess`, getting an error (that can actually track down the error rather than the current Lua errors) seems preferable to silently giving me a 0. Whereas if I have to explicitly ask for a default, I'm only going to get a default value when I want it, rather than every time I type something wrong, or misremember the proper key.

**Comment by FilippoLeon** [comment]
We should change things like:

```

        this.name = other.GetName();
        if (other.HasContents())
        {
            this.contents = other.GetDictionary();
        }
        this.value = other.ToString();
```
To 

```

        this.name = other.GetName();
        if (other.HasContents())
        {
            this.contents = new Dictionary<blabla>(other.GetDictionary());
        }
        this.value = other.ToString();
```

**Comment by mikejbrown** [comment]
@koosemose I stand corrected. If parameters are local then they are the perfect solution. We just need better debugging options for lua code.

**Comment by koosemose** [comment]
@FilippoLeon Your solution will make them no longer separate, trust me, that is exactly the code I originally had, a dictionary copy constructor doesn't make a deep copy, so all the Parameters it contains are referencing the exact same Parameters the original did.

I implemented the GetDictionary function precisely to create a proper clone of the dictionary (though the name could perhaps be more explicit)

**Comment by FilippoLeon** [comment]
Sorry I thought GetDictionary returned the dictionary. So, if you perform a deep copy, the Params act as a non-static property, right?

Btw, You could make param a struct.

**Comment by koosemose** [comment]
Correct. Yeah, that's why I should probably have had a different name for GetDictionary, so it's clear even from the caller what it's doing.

**Comment by mikejbrown** [comment]
Development on this happening in #746 and https://github.com/mikejbrown/ProjectPorcupine/pull/4 which is a PR on #746

**Comment by mikejbrown** [comment]
@koosemose @FilippoLeon Since the name `GetDictionary` is misleading and it's a private method I just renamed it to `DeepCloneDictionary` in #746. Okay with that:question:

**Comment by koosemose** [comment]
Sounds good to me.

**Comment by koosemose** [comment]
Closing this as we seem to have gotten it handled in a satisfactory manner
