### ISSUE TITLE
Selection tooltip (ISelectable)

### ISSUE THREAD

**Issue by jdlaroche** [TeamPorcupine/ProjectPorcupine#744]
In one of the last tutorials, Quill created the ISelectable interface that is used to populate the selection tooltip. Right now, the ISelectable interface has 4 methods. GetName, GetDescription, GetHitPointString and GetJobDescription.

The last one is a method I added to be able to display the job owned by a character in the tooltip.

When I added that, my initial idea was to also display the job owned by a furniture in the tooltip, but a furniture can own multiple jobs, so it couldn't fit in a method that only return a string... For now... this method returns an empty string for everything except a character. It mades me wonder if that interface was the right tool for the job or if we need to redesign this solution.

I think it might make sense to have an ISelectable interface, but I really don't know how we could handle the fact that different objects have different informations that should be displayed in that tooltip without adding UI related logic in the model classes...

It is also annoying to have to go in each classes to add a method that won't be used because the interface forces us to do it. 

It might not be the best solution, but right now I think my best idea would be to replace the ISelectable interface by a Selectable parent class that would be extended by all the classes that currently implements ISelectable. That class would have a boolean saying if that object should display a specific field (ie JobDescription) and overridable methods to return the value.

Something like this (note that there are multiple options on how to tell the parent class what should be displayed)

```c#
public class Selectable {
  public bool DisplayHitPoints {get; protected set}
  public virtual string getHitPointString()
  {
    return ""
  }
}

public class Character : Selectable {
  public Character() {
   DisplayHitPoints = true;
  }

  public override string getHitPointString() {
    return "18/18";
  }
}
```

This solution would avoid having to modify each class of the model for a property that is only useful for 1 type of object...

What do you think... Do you have any better idea on how we could do this?

**Comment by sboigelot** [comment]
#1216 solved this
