### ISSUE TITLE
Localization downloader throws non-error errors

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#745]
Right now, the Localization table will throw errors if new Localization is downloaded or when a key is not present. This seems overly dramatic. Errors are problems that mean the program is not running well. "Hey a new localization has been downloaded" is working as designed and doesn't need the game to pause to make me check what's wrong?

Same with missing loc keys. It's not game-breaking if there isn't a text available for some new furniture I'm implementing.

Just throw a warning for both or something.
Or am I not understanding what Errors and Warnings are supposed to be. I am open to correction.

**Comment by bjubes** [comment]
those should probably be warnings/info, and should be under the localization tab in uberlogger so you don't have to see them

**Comment by UnknownSoldier1** [comment]
The warning that a key doesn't exist is meant for those who make localizations, that they can see immediately what's missing in the localization file.

**Comment by vogonistic** [comment]
Was this solved with #720?

**Comment by abackwood** [comment]
No. It happened because I added a new furn, which of course had no localization set for it. The LocalizationTable counts that as an error

**Comment by vogonistic** [comment]
I'd accept a PR that lowers the messages to info when I'm merging PRs later. I'm sure the others would too.

**Comment by Ohda** [comment]
I will do it, just for aovoiding error level actually.
