### ISSUE TITLE
Proposal for a new Job API

### ISSUE THREAD

**Issue by lameox** [TeamPorcupine/ProjectPorcupine#75]
# Proposal to rewrite parts of the Job API
## Motivation
While discussing the current codebase with other members of the community today we stumbled upon the current jobsystem many a time as a System that needed tweaking. Throughout the day we were discussing ways to improve on the current system, and it became increasingly clear, that the current system would need some work. We Proposed a partial rewrite in #63. This proposal is an attempt to write a more formal outline of what we think must be done, what should optionally be done and the reasons for doing so. It also describes a proposed Solution we should then talk about.

## The Problems
1. Only one global job queue. This leads to dirty hacks like local jobs for a character (fetching of materials) that never even hit the global queue and are difficult for a newcomer to understand.
2. No division of jobs. a worker could have his friend move the materials in place and then just has to come up and build them, rather than doing the whole job himself
3. No good way of doing priorities on a per-character level. This would allow for professions for characters, as well as designated workers.
4. No easy way to compose new Jobs. Currently it is a whole mess of callbacks, subjobs, nested ifs and more.
5. The scope/meaning of a job is too macroscopic. A simple "Build" job might entail several moves, pickups, works and more. This makes it difficult to reason about and debug.
6. Jobs don't expose any real metadata, neither for UI nor programming purposes.
7. No way to react to events. New jobs are only ever taken from the queue when an old one finishes.
8. No way to reserve resources for a job, which might lead to resource contention.
9. No good way to queue jobs from Lua and thus mods.

## What must be done
- [ ] Characters have their own job queue. When deciding on a job they look at the best candidate from their local and the global queue and decide on one
- [ ] Jobs need to be divided into many smaller jobs. At the least the following should be separate Jobs:
  - Moving
  - Waiting
  - Picking/Placing items
  - Interacting with appropriate Objects (We suggest a new IInteractable interface)
  - Deciding on a Followup Job

 This should make composing complex jobs easier.
- [ ] Jobs need to be interruptible at any point. They should then be added back to the respecitve queue
- [ ] Jobs need to  be taggable with metadata. We suggest an IMetadata Interface. This interface should also specify if the job can be executed out of order, concurrently and/or by a different character.
- [ ] A extensible priority system needs to be in place. We suggest a global table of weighting functions a job can call against, based on a number of tags the job might posess in its metadata.

## What should be done
We suggest a Linq - Like API based on the changes above, that makes composing jobs easy. This API should partly be exposed to Lua as well.

### Needed Functions
All the below functions are just an initial proposal i came up with. I might not have thought about every use case we might want to cover so feel free to append to it.

**Selectors**
Callable On: Initial Method
Returned Interface: IActorCollection 
Those select one or more characters that will be appropriate for the job. Selection should expose the following Selections:
 - GetNearestCharacter(Tile t) => selects the nearest character
 - GetNearestCharacters(Tile t, int count) => selects the \<count\> nearest characters
 - GetNearestCharacters(Tile t, float distance) => selects the nearest characters withind \<distance\>
 - GetAll(Profession p) => Selects all characters of profession p
 - GetAll(Predicate<IMetadata> selector) => Selects all characters where the passed predicate returns true.

**Functions**
Callable On: IActorCollection, IJobFunction
Returned Interface: IJobFunction
Functions should be the main method of composing jobs. They are chainable and should allow for easy Syntax. The following are the proposed initial Functions:
 - MoveTo(Tile t) => The selected actor(s) move to this tile
 - MoveRelative(int deltaX, deltaY) => The selected actor(s) move relative to their current tile
 - PickUp (Item desiredItem, int desiredAmount) => The selected actor(s) try to pick up the provided item at their current location
 - PlaceDown(int desiredAmount) => The selected actor(s) place the desired amount of their currently held items on the floor at their current position
 - Interact() => The selected actor(s) call the IInteractable.Interact() method on the Tile in front of them, if possible
 - Build (Template t) => The selected actor(s) try to build the template at their current position. The required materials must be in place.
 - Repeat(int amount) => The selected actor(s) repeat all commands chained before this one \<amount\> times
- RepeatUntil(Predicate<IMetadata> prdicate) => The selected actor(s) repeat all commands chained until \<prdicate\> returns true
 - Trigger (IEvent event) => The selected actor(s) trigger the provided event when they reach this function.

**Triggers**
Callable On: IJobFunction
Returned Interface: ITriggeredAction => can be used to revoke an active.
They might react to events or just server as a final call to a composition. 
 - OnEvent (IEvent event) => Triggers when the event occurs
 - OnTimer (int milliseconds) => Triggers cyclically after the amount of \<milliseconds\>
 - Queue () => Triggers instantly thus queueing the job

**Modifiers**
Callable On: ITriggeredAction
Returned Interface: IJobDefinition
This allows us to tag a job with metadata. This is the function that will cause the actual queueing of the job. 
 - WithMetadata(IMetadata meta) => Decorates the job with the appropriate metadata

# Sample
A sample snippet for the Proposed API would be
```
Character.NearestCharacter(trashcan).MoveTo(trashcan).PickUp("Trash", -1).MoveTo("AirLock").Drop("Trash", -1).Interact().RepeatUntil(m => trashcan.IsEmpty).Queue().WithMetadata(meta)
``` 
which would queue a job on the nearest character to jettison the trash from the trashcan.

# Final Thoughts
I think the proposed API would server really well for composing jobs on the Fly and especially from Lua code. It should also be intuitive for anyone that worked with Linq before and will also be really extensible.
However this is a version 0.1 of the proposal that i just quickly typed down. Any feedback and criticism would be apprciated.

Regards,
Jan

**Comment by vogonistic** [comment]
Those are very specific tasks. How does that work with modding and individual tasks failing? If the airlock is destroyed or malfunctions while the character is on it's way, does it understand just to repeat part of it? What if someone mods in a disintegrator, how does that job get changed to allow either?

**Comment by NogginBops** [comment]
I think this solution which you are suggesting with these interfaces just adds a lot of complexity to not so complex problem.

**Comment by vogonistic** [comment]
`You` being me or @lameox?

**Comment by NogginBops** [comment]
@lameox

**Comment by vogonistic** [comment]
Ah. I didn't pay attention to the fact that the proposed solution was based entirely on interfaces.

**Comment by lameox** [comment]
To adress @vogonistic I think weather the Job is continued, aborted, requeued or whatever else should be specified in the Metadata passed in the creation.

@NogginBops I think it is not too complex and assures, that The functions can only be chained in the right order. It also assures, that a chain is complete when .Queue() is called. I took some inspiration from Linq. If you look in the Internals of Linq, it is done the same way there. 

What would you suggest as the alternative?

**Comment by NogginBops** [comment]
@lameox I don't see the benefit of this solution, there is already a system where a character decides when it can accept a job, which I like as that models more accurately what is happening. With this there is no need to get a character. There is times though where a character needs to be notified of a urgent job, but I think a better solution is to have something like a `broadcastUrgent(Job, Room)` that cancels active jobs for the different characters.

The same functionality that you propose could be implemented by creating a linq-style wrapper for the whole api the behind the scenes that just synthesizes jobs in the background. Letting the weighting system do its job without interference.

Advantages would be that understanding how Linq operates is not a necessity and creates opportunities for more custom jobs. Plus what is the point of having a fitness function if all jobs are meant to be chained? The problem of job dependency would be handled in the fitness function.

Another idea is to only expose the linq wrapper to lua.

Creating a job could then look like this (in C#):
`
Job j = new Job(... actionWorked, actionCompleted, jobAborted, tags ...);
JobManager.addJobb(j);
`
or via the linq-style wrapper (in lua or C#):
`
<wrapper>.MoveTo(trashcan).PickUp("Trash", -1).MoveTo("AirLock").Drop("Trash", -1).Interact().RepeatUntil(m => trashcan.IsEmpty).Queue();
`

**Comment by emilkris33** [comment]
How would a job to build a wall look in this system. Would you not have to decide the exact stack of materials to use when creating the job?

**Comment by NogginBops** [comment]
@emilkris33 That's what I was thinking about. My implementation idea is half GOAP and I think that that's what I want it to be. I think that that is a more versatile, extendable and modifiable job system.

**Comment by lameox** [comment]
@emilkris33 you are right. we would also need selectors for objects. seems like i forgot those :D

@NogginBops I think i dont fully follow. All this proposed wrapper will do is queue a bunch of jobs on the Underlying weighting system. I would do it this way, because if we want to go the way of atomic jobs, than writing `Job j = new Job(... actionWorked, actionCompleted, jobAborted, tags ...); JobManager.addJobb(j);` for every move, pickup, whatever will get really cumbersome. Thats why I proposed a linq style wrapper in the first place. Also you will not be able to marry your C# example with the LinqStyle wrapper in a nice way.

I think you wont need an understanding for Linq at all. You could just look at existing code and go from there. 

Also i dont understand what you talk about when you say fitness function and how you want to resolve job dependencies with it. Could you elaborate a bit?

**Comment by NogginBops** [comment]
@lameox I was conflicted when I was writing the my previous suggestions. What I wanted was a GOAP (Goal Oriented Action Programming) style job system, where you specify a wanted result and the underlying system figured out a way to make it happen. The reason I was conflicted was that I didn't want to drop the old job system completely. But after some thinking I really think GOAP is the way to go. It really simplifies the way modders would interact with the api.

What a GOAP job system would mean is that a modder would specify a number of actions a character could take and that the prerequisites, cost and result of that action would be and then when something should be done you only specify the desired result and the system figures out a minimum cost solution to execute,

This is good because modders only need to worry about the actions a character can take and the end result. Not the nitty gritty details of what order or what depends on what. This allows mods to work together, if one mod specifies a way to craft a steel plate that is really efficient and another mod requires steel plates then the efficient way would be used without the modders to care about adding any cross mod support,

It also greatly simplifies the api, unly needing to state the intended goal and not the whole chain of dependancies.

GOAP resources:
[A GOAP rescource website](http://alumni.media.mit.edu/~jorkin/goap.html)
[TheHappieCats video](https://www.youtube.com/watch?v=n6vn7d5R_2c)
[Quill18s video](https://www.youtube.com/watch?v=bc86es4YOoc)

**Comment by lameox** [comment]
@NogginBops I really like the sound of that. As you might have guessed already, i am no game developer, and thus did never really use GOAP but after reading up on it, it really sounds like the man for the job. I guess our priority/weight system would then produce the next desired goals instead of jobs?

**Comment by NogginBops** [comment]
@lameox Exactly, you would specify a goal. Then the system would see what actions that produce that result and check that actions cost. It would then sum the up the cost of every branch and pick the cheapest solution. The cost of the different actions could also be influenced be different user specified values such as Efficiency vs. Speed. Does the user case only about speed or is efficiency more important,

**Comment by lameox** [comment]
Well i guess we have our solution. Would you write up a new Issue and i will close this one and reference the new one in the OP.

**Comment by NogginBops** [comment]
Sure, though mine probably won't be as pretty as yours... :P

**Comment by emilkris33** [comment]
+infinity to GOAP. Never used it before but it looks very good

**Comment by lameox** [comment]
@NogginBops No worries :D

**Comment by lameox** [comment]
Discussion Continues in #86
