### ISSUE TITLE
[Bug?] Unlimited Panning

### ISSUE THREAD

**Issue by RodRitter** [TeamPorcupine/ProjectPorcupine#752]
Hello everyone,

One thing I've noticed while testing other PR's, is that I can pan way off the map. Is this intentional?

**Comment by vogonistic** [comment]
I don't recall it ever coming up. Should we limit it so that you can only go a little bit outside the world?

**Comment by FilippoLeon** [comment]
Definitely, otherwise you can easily get lost :).

**Comment by FilippoLeon** [comment]
```
    void UpdateBoundCamera()
    {
        Vector3 oldPos = Camera.main.transform.position;

        oldPos.x = Mathf.Clamp(oldPos.x, xMin, xMax);
        oldPos.y = Mathf.Clamp(oldPos.y, yMin, yMax);

        Camera.main.transform.position = oldPos;
    }
```

Figuring out good min max values is annoying tough. I guess the centre of the camera should be at most at the corners?

so min = 0 max = world.current.width?

**Comment by RodRitter** [comment]
I've defnitely glitched out before, where my camera ended up way off the map. 

@FilippoLeon Yea, you can just use something like `float xMax = (float)World.width` since every tile is 1 unit.
