### ISSUE TITLE
[Discussion] Room Purpose/Function

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#782]
What are people's thoughts on having some way to designate a room's function (or having a room be able to figure out what its function is based on what's in it). This would allow room's to have a cohesive set of furniture that works in a specific way. 

The primary example of this would be an airlock, rather than having a single very large piece of furniture that handles everything, you would have room designated as an airlock with at least two airlock doors, a gas pump, and possibly spacesuit lockers (maybe this could be an optional thing that would be connected to the room's function if present, otherwise the character using it would be required to have a spacesuit on before the outer door is opened) and would then only allow one door to be open at a time and pump the air out before opening the outer door.

This would allow rooms such as the airlock to be built piecemeal and customized, such as building a larger airlock that will empty slower, but allow more people to exit at one time, or a smaller room that could fit fewer people but cycle faster, and also allow it to be upgraded piecemeal, with stronger doors or a better pump without having to have completely dedicated airlocks for each stage.

**Comment by Raketfart** [comment]
I would really like the airlock to be like you described it. I think that would feel much better to build it yourself.
If a character want to go outside, he would have to pick up a spacesuit. Doesn't have to be in the airlock - you could have a changing room somewhere else. 
The outer airlock door could require everyone to wear spacesuits and air pressure to be low before opening. The inner door would require air pressure to be high. The doors could the ask the gas pump to raise or lower pressure. 

We could probably do room designation like prison architecht, but I would prefer the room could figure out it's functions automatically. That would leave more creativity to players in designing their base. They could have a giant dininghall+bedroom+toilet if they wanted, or indiviual apartments with private toilets and baths.
If I remember correctly, Rimworld has no room designations, and that feels freeing to me.

**Comment by GamerInspired** [comment]
I love the idea of being able to designate rooms such as the airlock, however I also like idea of putting whatever I want into a room, so maybe you have a mix of functional room designations and a aesthetics designation.

Or maybe as @Raketfart said having some way of conditioning things, like with the airlock and telling the outer door to only open when the people in the room have space suits on and the room is at a low pressure.

Otherwise I think there are a few ways of doing this and it will the require more discussion.

**Comment by koosemose** [comment]
Yeah I definitely would prefer the room be able to do it itself, I'm just not sure how feasible that would be.

The idea is that room designations wouldn't limit you from putting things in a room, but rather, as long as the room has the appropriate basic things (airlock doors and pump for airlock), it would just tell those basic parts how to work together (with the possibility of looking for certain optional things that could also work together with the basics). So if you wanted a toilet in your airlock (never go on a spacewalk with a full bladder) you can do that. It doesn't even have to be exclusive (in theory) you could designate your airlock to also be a dining hall if you really want.

**Comment by Raketfart** [comment]
The airlock doesn't even have to have an inner door, if you want to build a portapotty near your outside work area. Just a single disconnected room with airlock, gas pump and toilet.
