### ISSUE TITLE
Manual setting of job priority?

### ISSUE THREAD

**Issue by Randshot** [TeamPorcupine/ProjectPorcupine#786]
I just thought that it would be nice to be able to manually set the priority of (maybe just current) jobs. Something similar to RimWorlds approach maybe?
This should also include manually canceling jobs.
I don't have the time to do this right now, but maybe someone else does?
Input would be nice 😄

**Comment by svmnotn** [comment]
more things to do for #726?

**Comment by vogonistic** [comment]
We already have priority in the current job system, so we could implement it now. It'll have to be added in #726 regardless.

**Comment by vogonistic** [comment]
Meaning, someone can implement it now!

**Comment by MANDAL0R3** [comment]
Actually i have this past hour been implementing manual job priority. I only have one question. Should i remove the right clicking to deconstruct furniture that needs to be built so instead we can right click to assign priority?

**Comment by vogonistic** [comment]
Removing the job/construction should be an option in the contextual menu.

**Comment by MANDAL0R3** [comment]
True, you gave me a better idea on what to do. Thanks

**Comment by MANDAL0R3** [comment]
So i have it working were you have to right click on anything that is a pending build job then click cancel to cancel the job, and i also have it where you can click to prioritize instead. I'm thinking that with this, it might be helpful to have a drag remove for pending job builds but that might be better in a different PR.

**Comment by MANDAL0R3** [comment]
I have finally finished working on the manual job priority, https://github.com/TeamPorcupine/ProjectPorcupine/pull/825.

**Comment by Randshot** [comment]
It seems like we have a solution, so I will close this issue.
