### ISSUE TITLE
[Bug] mouseController is null - The order of GameObject initialisation in the scene

### ISSUE THREAD

**Issue by fre-ber** [TeamPorcupine/ProjectPorcupine#788]
The current version is broken - spam with null pointer reference errors. 

I think that the problem is that the order of game object initialisation is not reliable and, in this case, the game object that the MouseOverFurnitureTypeText script is attacted to is instantiated before the WorldController.

This problem could possibly be solved by moving stuff from Start to OnEnable or Awake in WorldController and always use Start in all other classes.

Another way to solve this, and this is what I did in my own project, is to make the WorldController wait until all the other MonoBehaviours are instantiated befor creating the world.

I have a GameController that is the top level controller, I suppose that this would be the WorldController in PP.
In GameController (Or WorldController)
```
    public static bool isReadyForInit = true;
    public static List<MonoBehaviour> waitingList = new List<MonoBehaviour>();
    public static void WaitFor(MonoBehaviour b) { waitingList.Add(b); isReadyForInit = false; }
    public static void IsReady(MonoBehaviour b) { waitingList.Remove(b); isReadyForInit = waitingList.Count == 0; }
    ...
	void Awake()
    {
        ...
        fixtureDB   = new FixtureDatabase();
        inventoryDB = new InventoryDatabase();
        jobDB       = new JobDatabase();
        siteManager = new SiteManager();
        ...
    }
    ....
    void Update()
    {
        if (isReadyForInit) // Wait for all registered objects to be ready. 
        {
            siteManager.BuildEmptySite();
            isReadyForInit = false; // We have now initialised, we don't need to init again.
        }
    }
```

In another class deriving from MonoBehaviour that wants to access things in the Site (World) and therefore has to wait for this to be constructed:
```
    void Awake()
    {
        GameController.WaitFor(this);
    }
    void Start()
    {
        GameController.instance.siteManager.RegistersiteReplacedAction(OnSiteReplaced); // TODO: This is never unregistered
        GameController.IsReady(this);
	}
    protected void OnSiteReplaced (Site oldSite, Site newSite)
    {
        if (oldSite != null)
        {
            oldSite.fixtureManager.UnregisterFixtureInstalledAction(OnFixtureInstalled);
            oldSite.UnregisterTileChangedAction(OnTileChanged);
        }

        if (newSite != null)
        {
            newSite.fixtureManager.RegisterFixtureInstalledAction(OnFixtureInstalled);
            newSite.RegisterTileChangedAction(OnTileChanged);
        }
    }
```

I may have missed a few bits in this explanation, but the idea is that the GameController (WorldController) waits for the other controllers to have been Start()-ed before setting things up, and also that the MonoBehaviours don't actually try to access things before they have received an event message that tells them that the thing is ready to be used.

1) The static methods can be invoked at any time, to regardless of the order of init, the call `GameController.WaitFor (this);` will always work.
2) Awake() is called before every Start(), so all the managers I set up in my WorldController are guaranteed to be created before any Start method is called.
3) The Start() method can safely reference the managers in the GameController to set up event listeners.
4) The Update() method of the GameController waits until everyone is finished before creating the world in the SiteManager and the SiteManager will trigger an event when it replaces the non-existend Site with a new one.
5) The event triggers the other controllers and lets them start doing things.

I hope that this long post makes some sense to someone and that an informed decision can be made on how to handle this - if this actually is what is causing the complete fail of the current build.

**Comment by fre-ber** [comment]
Interesting, the problem only happened the first time I started the game. Still, the issue might be something we have to consider.

**Comment by Mizipzor** [comment]
Should we assume that this was a one-off random fluke and close this? :)

**Comment by fre-ber** [comment]
Yes, close it. If it was related to the issue I suggested a solution to it would probably happen every time, so it was probably something else.

Perhaps it might be worthwhile to look through all the MonoBehaviours to see if any of them reference stuff before they are created though. If they do, something should be done about that. I am too lazy to do it right now, though.

**Comment by fre-ber** [comment]
Oh, I can do that myself? 

Closed, if it happens again we might want to re-open.
