### ISSUE TITLE
How to increase pull request throughput

### ISSUE THREAD

**Issue by Mizipzor** [TeamPorcupine/ProjectPorcupine#794]
I would like to consider ways of increasing the number of pull requests that get accepted each day. I've briefly talked about this on Discord, but I would like to implement a system where anyone can [look at someones pull request](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Working-with-Someone-Else's-Pull-Request) and then, after testing, _formally_ vouch for it in the comments. If theres two people vouching, a gate keeper should be allowed to merge without additional testing.

This allows for greater throughput without having to increase the number of gate keepers. I also introduces people to work with each others branches, which is a good thing.

@quill18 @vogonistic @RodRitter @WardBenjamin Feedback? Would you be comfortable with this?

This discussion is obviously not limited to the people above! Weigh in. :)

**Comment by Sommerbo** [comment]
I think it is a good idea it also is a good way for beginners to get to understand the code. As testing and looking at existing code is simpler and less intimidating.

**Comment by quill18** [comment]
Definitely agree.

Something as simple as:

:+1: Tested and is working on my machine.

**Comment by vogonistic** [comment]
I'd love for more people to start testing and signing off. It'd also be helpful that when people have done a code review and they don't find anything to also mention that.

**Comment by Mizipzor** [comment]
@vogonistic I want to be clear that there are two paths here. You can look at the code and review that way. You can also pull the branch and run the game. You can do either or, you dont need to do both.

@quill18 I think there's an excellent opportunity here. The angle of "you can contribute to the project without neither writing nor reading a single line of code". Maybe I humbly suggest a video showing people how to:

1. Pull a branch.
2. Maybe merge with master.
3. Run the game. 
4. Do something in the game that relates to whatever the pull request was about.

If the point here is to get beginners involved in game development, this is something very basic that anyone can do.

**Comment by vogonistic** [comment]
@Mizipzor I agree that no individual that helps out need to do both.

**Comment by quill18** [comment]
@Mizipzor Added to my TODO!

**Comment by Mizipzor** [comment]
In the meantime Im trying to find a place where those steps can be added. The contributing.md seems aimed towards coders, someone that cant code might very well just stop reading that file when finding it. Maybe the wiki? But not many people look there. Ideas?

**Comment by bjubes** [comment]
I like the idea of non-gatekeepers reviewing and testing code before merging, but I think it should formally be the gatekeepers job to ensure that a PR is functioning regardless of how many people vouch for it, otherwise we risk breaking the current master which is more of a setback than having PRs on a backlog.

PRs have already been approved despite overriding someone else's changes.  #400, #478 for example were examples of my own changes that have since been undone current master. Obviously these examples are nit picky, but it goes to show that even in our current system, new PRs sneak through that break functionality. Showing and encouraging non-gatekeepers to test PRs is a great way to prevent this, but having gatekeepers blindly merge because of a "it works" in the comments without testing it themselves makes this problem worse, not better.

**Comment by RodRitter** [comment]
I love this idea. I'd still suggest gatekeepers pull and test that the game can run without any error logs. Also it will be nice that the community starts recognizing people who are trusted testers.

**Comment by FilippoLeon** [comment]
I like the idea.

However, we generally have 20-ish PR and they are generally pending due to conflict.

We can speed up the process, but I suggest going easy, at least at the beginning.

What about having whitelisted people, that can vouch for PR to be merged? Otherwise anyone can vouch, even if they joined the project right that moment.

**Comment by mikejbrown** [comment]
This might be helped by a concerted effort to develop automated tests. While I get that a lot of things in the game don't immediately lend themselves to unit testing or TDD, whether the tests are formal unit/integration tests is less important than having _some_ kind of built in sanity checks available for most sub-systems.

**Comment by Sommerbo** [comment]
I for one would be interested in a unit test introvideo by @quill18 and to learn by reading code for the unit tests.

**Comment by mikejbrown** [comment]
Everybody please :+1: @Sommerbo's idea for a @quill18 unit testing video ^^^ :smile:

**Comment by mikejbrown** [comment]
Another great thing about unit tests is, as long as they are passing, they provide proven and up to date documentation on how to use all the classes written in the only language that really matters: code.

**Comment by sboigelot** [comment]
We should ask every c#/lua PR to have unit tests for new piece of code. I know it's a lot more work (and I'm guilty of not doing it too) but it may help

**Comment by sboigelot** [comment]
Also I'm willing to review code and post a comment when I do it, I often read the code of pending PR anyway already. Just to keep in touch with the part of the codebase I'm not working on.

**Comment by abackwood** [comment]
@sboigelot Before we start demanding that everyone use unit testing, we should at least have a tutorial or explanation somewhere how that works. I for one have little idea of what they are, and this project is supposed to be part tutorial anyway

**Comment by Mizipzor** [comment]
Lets have the unit testing discussion in #578. :)

**Comment by kd7uiy** [comment]
I have in mind that something like this would be good for a group of people designated the "Test Team" or something else to do, basically organize however desired a loose group of people who try to do all of the testing required for PRs. But in general, I think we are doing a lot better about this now than we have in the past, based on the number of PRs that are coming through.

**Comment by sboigelot** [comment]
I think we can close this issue for now, what do you think?

**Comment by mikejbrown** [comment]
Yeah. Closing.
