### ISSUE TITLE
Audio File Formats [WAV, MP3, OGG]

### ISSUE THREAD

**Issue by quill18** [TeamPorcupine/ProjectPorcupine#795]
I'm going to suggest that, like the issue with Photoshop files vs PNGs, that uncompressed sound files (i.e. .WAV) not be added to the project repository, to reduce bloat.  Especially when it comes to music, we could find ourselves with hundreds and hundreds of megs of uncompressed sound files.

Instead, I think the only thing that should be checked in are compressed sound files. Unity can decompress this at program launch (for very frequently used, but short, sound effects) or at the time the sound is played (for music).

a) Does this seem good?

b) Do we want to standardize on MP3 (most common, but less open-sourcish -- though that's mostly a problem of the past) or OGG (more open-sourcish, but less common).

**Comment by vogonistic** [comment]
Since it's next to impossible to ever get rid of a large file from a git repo, I think it's a great idea. Not sure where the right place to keep the originals are though.

I have no opinion on which format we choose.

**Comment by longtomjr** [comment]
a) Yes, I don't think uncompressed files is necessary.
b) My vote is for OGG, it is more in the spirit of the project. Also when using Open Source software to make sounds etc, you might need to get Lame to be able to encode to mp3. Ogg will almost always be built in.

**Comment by Sommerbo** [comment]
+1 for ogg for the same reasons @longtomjr stated.

**Comment by quill18** [comment]
Yeah, that seems like "sound" reasoning.

**Comment by Mizipzor** [comment]
Sounds good. All of it.

**Comment by MANDAL0R3** [comment]
I vote for ogg, same as @Sommerbo

**Comment by quill18** [comment]
Okay, OGG it is!  We'll consider this Issue closed.
