### ISSUE TITLE
Add a key to reset the camera position to the center.

### ISSUE THREAD

**Issue by quill18** [TeamPorcupine/ProjectPorcupine#798]
#756 made sure we couldn't get lost anymore -- but it also might be nice to be able to reset the view to the original position of the camera when the game was launched.

This should be a very easy project for a beginner to tackle.

**Comment by nigelbarink** [comment]
I'll try that in my personal copy, if it turns out great i will send it in. (I am Beginner / Average, somewhere in between )

**Comment by mattpott** [comment]
@nigelbarink how have you gotten on with this?

**Comment by Tranberry** [comment]
A follow character camera mode would be nice, I've been away for a day and a half might have missed that.

**Comment by nigelbarink** [comment]
@mattpott I am thinking saving the position of the camera when the game starts in a variable. Then maybe if someone saves the game, write the current camera position to the file aswell so it can later be loaded on startup

**Comment by quill18** [comment]
That also sounds like a good idea!

**Comment by Ralathor** [comment]
Are anybody currently working on this one? Because if not, I think I'll give it a shot.

**Comment by nigelbarink** [comment]
@Ralathor  I got half of it down , Only need to look into saving it with the rest of the map. If you want i could share the code.

**Comment by sboigelot** [comment]
@nigelbarink what is the status of this? Should someone else look into it?

**Comment by nigelbarink** [comment]
@sboigelot If you want go ahead. I only got the point where when pressed X the camera was set to its original  position. Then school started and was to busy to spend time on this project.

**Comment by nigelbarink** [comment]
Apologies  for my bad communication  and the delay on this simple thing

**Comment by sboigelot** [comment]
@nigelbarink No problem, school comes first. Yes we will probably have to do it from scratch as the codebase changed A LOT since 17 days, mostly for handling the keyboard. Someone should pick it up one day, but it's good to know the status. thanks

**Comment by GamerInspired** [comment]
Would be cool later on to be able to have a button to reset camera position and then have some way of saving other camera positions and then be able to jump to them.

**Comment by nigelbarink** [comment]
@GamerInspired That could easily be done by saving an array of vectors as a variable instead of just one. Then write the array out in the save file for later use. Just a quick sketch  lf how I would write that

**Comment by jaselito** [comment]
I've been working on this one; practically done.  Will create PR tomorrow after some refactoring / commenting.
