### ISSUE TITLE
FunctionName or functionName?

### ISSUE THREAD

**Issue by TheRiven** [TeamPorcupine/ProjectPorcupine#799]
I noticed in the `Furniture.xml` that both forms of `functionName` are used. I thought it would be a simple change to that file and the `Furniture.cs` to make them all use the same, but both forms are actually used in quite a few files.

Maybe we should settle on just one? :smile:

**Comment by FilippoLeon** [comment]
In fact FunctionName should't even work. But for me it is the same, which one you prefer.

**Comment by NogginBops** [comment]
It should be functionName. That is xml standard.

**Comment by FilippoLeon** [comment]
Nah, I'm pretty sure xml doesn't mandate any particular style. But I still prefer functionName.

**Comment by TomMalbran** [comment]
In issue #664 there is a discussion about the XML Elements & Attributes Naming conventions which we really don't have right now, and should be fixed.

**Comment by sboigelot** [comment]
As this is tackle in #664, I think it's safe to close this issue.
