### ISSUE TITLE
Unity almost crash after remove Mining Drone

### ISSUE THREAD

**Issue by rfmsimoes** [TeamPorcupine/ProjectPorcupine#80]
Hi guys,

Don't know if you tried the same...

    1 - Start the game
    2 - Pathfinding Test
    3 - Create Mining Drone
    4 - Wait for the first 10 steel plates
    5 - Create a stock pile
    6 - When character moves towards the stock pile delete the Mining Drone

And you will see the unity freezes like hell! !

Anyone had the same issue ?

**Comment by SanteriHetekivi** [comment]
Same here, whole game freezes:
![image](https://cloud.githubusercontent.com/assets/9454417/17746552/2bb6b648-64b9-11e6-8d2b-08fbbec6900b.png)

**Comment by AE40** [comment]
I Might Have Something Similar: #81

**Comment by rfmsimoes** [comment]
@AE40  Yes it seems related to stock pile probably

@quill18  Did you know if someone changes the behaviour of the stock pile or change the JobQueue?

**Comment by QuiZr** [comment]
Should be fixed in #79

**Comment by rfmsimoes** [comment]
@QuiZr  Sorry I didn't noticed that my issue is related with yours.

Thanks for help. :)
