### ISSUE TITLE
Adding Items To Stockpile Freezes Game

### ISSUE THREAD

**Issue by AE40** [TeamPorcupine/ProjectPorcupine#81]
Building the stockpile is fine, but at the second the player adds to it the game freezes.

[Example](https://youtu.be/W3lvv2vK_NI)

No Idea if this is something on my end, And honnesly propably is. 
Any confirmation would be great.

**Comment by QuiZr** [comment]
Should be fixed in #79

**Comment by SquareMan** [comment]
Upon further testing it appears that it only happens when there is more than one empty stockpile. If there is only one stockpile location it will place the inventory and continue along just fine.

**Comment by QuiZr** [comment]
@SquareMan test in #46 branch, those issues are fixed. There still are some problems with performance (i.e. flood fill) but there is no point in fixing that right now - whole jobs system will be rewrited from scratch anyway.

**Comment by lameox** [comment]
As @QuiZr said, this can be closed as it was fixed in #46 .
