### ISSUE TITLE
Room and Furniture awareness of each other

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#814]
I think it would be very useful for Furniture to know not only what room it is in through tile, but in the case of furnitures that enclose rooms (and therefore won't actually be in a room) to know what rooms they border, so that, for example, an airlock door could only open when pressures are equal without having to manually search through its neighbors every time.

Additionally, if a room could be aware of what furniture it contains (and borders, perhaps separately) without having to search through every tile for a furniture, it would simplify furnitures in a room working together, without any additional special code (such as room designations), so using an airlock as an example, an airlock door could ask for any air pumps in either adjacent room (perhaps ignoring the outside room) when someone requests that it open, and pump air in or out until pressure equalises between it's two sides.

I feel reasonably confident that a room could get it's initial furniture when flood filling, and then when non-enclosing furniture is added, it could register itself with rooms as appropriate (if I understand the system properly, enclosing furniture shouldn't need to do it special since it should always cause a flood fill, but I haven't really looked deep into that code, other than when quill did it in the tutorial).

**Comment by b4ux1t3** [comment]
With regard to the airlock behavior, I think that the airlock itself should test the pressures of the rooms it connects, and then inform the rooms. There's not much reason for a room to know what's outside of it unless absolutely necessary, like if a wall breaks and the room is exposed to a lower pressure. Though maybe I'm just not understanding well enough how airlocks function. If I'm off base, let me know and I'll check the code.

That said, you're right about rooms knowing what is inside of them. It might benefit in the long run. For example, if there were a thing about to explode in the room, it might be worth it for the room to "prepare" for the explosion in some way.

In a way, though, a room already knows what furniture is inside of it through the tiles.

I dunno, though. I just figured I'd toss my two cents in to get the conversation started.

**Comment by koosemose** [comment]
What I mean with regard to the airlock, is that if the airlock wants to know what the pressures are on either side, as is it needs to find each room, as room's already know what their own pressure is, and it would be more efficient and direct if the airlock door already knew what rooms it connected, so it didn't have to search  all adjacent tiles. Not a huge time savings, but it would still be cleaner to just be able to have a field that stored adjacent rooms. So the intent isn't about it informing the rooms what the air pressure is, but rather knowing what the rooms are, so it can ask each room what it's own air pressure is.

And as I said, a room would benefit from having a direct list of all of its furniture, rather than every time I want, for example an air pump or air compressor, having to search through every tile to see if it has furniture, and then see if that furniture is what I want.

To further demonstrate what I mean, let me run through someone exiting the station through an airlock:

Character tries to open airlock door.
door queries adjacent rooms, sees that they have equal pressure, and begins to open.
Character tries to exit other door
door queries adjacent rooms, sees that pressure is different.
door queries adjacent rooms for an air pump.
door activates air pump.
once room atmo matches outside atmo (i.e. vacuum) the outer door opens.

Of course there should probably be further checks for only one door being open, and only one trying to open at the time (so two characters don't get an airlock stuck toggling the air pump back and forth as they try to pass through different doors), but that's the basic idea.

**Comment by vogonistic** [comment]
I can see the value for the airlock, but I'm not sure if that is enough of a use case for the room to always start tracking all the furniture directly.

Sounds like what you actually need is some instance variables for that particular airlock so that it only has to look up once what the two rooms are.

**Comment by koosemose** [comment]
Would it be that costly for a room to keep track of it's furniture? I would assume that while floodfilling for a room it could just check if the tile being checked has furniture, and if it does (and will be in the room) add it to a List. 

Alternatively would it be feasible to notify the doors when the rooms change (add furniture or room is split or joined)? Just an instance variable by itself won't do since the room may change, similarly with the furniture, so it would have to search every time. Once I'm done tracking down the bug in one of my PRs I'll see if I can come up with other use cases that we might want to implement in the future that would justify tracking some of this information.

Or would this be easier/less costly if we had a room designation system, so that, for example, only a room marked as an airlock needs to keep track of the information, and any other room designations will keep track of whatever information they need specifically?

**Comment by vogonistic** [comment]
It's not very costly to keep the reference, but it's another place where we have to keep track of things. If only one type of furniture actually needs it, and it's just an optimization, it might be worth seeing if there are other ways to implement it.

Doors and walls are an interesting special case when it comes to rooms too because they don't belong to either of the rooms. I just remembered that with #760, the rooms will know about all the exits. Maybe we just need to be able to ask the room graph for the Room_Edge for the door and you should be able to get both rooms that it belongs to.

An `OnRoomsChanged` event might be a good idea regardless.

**Comment by vogonistic** [comment]
Can't believe that I didn't think of the room graph earlier. It's going to be a cornerstone in speeding up pathfinding as well.

**Comment by koosemose** [comment]
Of course, that's why this is a discussion, I am mostly unfamiliar with how rooms work, and figure that others who may be more familiar can help reach a satisfactory point, so that it's possible to get the information I want/think will be useful, without me having to brute force it because I don't know my way around rooms.

**Comment by vogonistic** [comment]
You should comment on that PR and let him know that you would appreciate an API to look up the rooms that are connected from that door.

**Comment by mattpott** [comment]
@koosemose I have added a branch from my original pull request as I didn't want to pollute the pull request with my untested sudo code. Will check it out when I get home tonight and then merge everything back in.

**Comment by mattpott** [comment]
@vogonistic  @koosemose  this has been added and I think the PR is working.

**Comment by koosemose** [comment]
This is achievable through RoomBehaviors, and should be merged soon.
