### ISSUE TITLE
Using proper C# events for callbacks

### ISSUE THREAD

**Issue by NogginBops** [TeamPorcupine/ProjectPorcupine#82]
The event keyword exists for a reason.

**Comment by Tranberry** [comment]
for us novices, care to elaborate a bit?

**Comment by QuiZr** [comment]
@Tranberry A nice video tutorial here: https://youtu.be/G5R4C8BLEOc

**Comment by vogonistic** [comment]
Since `Action` and `Func` are based on events. It seems like the code is already down the right path, unless it changes in the videos I haven't watched yet.

**Comment by NogginBops** [comment]
This has now been done in #97.
