### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by mikejbrown** [TeamPorcupine/ProjectPorcupine#829]
Right now it seems that cooldown logic is implemented in multiple places and it is possible, for instance, for Lua functions to get called hundreds of times a second with an enormous overhead (e.g. #796). Would people like to have a generic scheduler? Something like `GameEvent` (possibly extending `GameEvent`) only with the ability to be used by C# events as well.

Basically I'm talking about an object, probably owned by WorldController, which can register arbitrary C# and Lua events which can fire on a one shot, repeated `n` times or endlessly on an adjustable cooldown. It would track the cooldown individually for each event, handling time warp as well. It would also provide a central place to implement a policy on how often Lua calls could be scheduled, perhaps eventually even adjusting them adaptively based on performance. Maybe even some of the job code could be refactored into this (especially furniture jobs).

Thoughts?

**Comment by Fatalexceptionz** [comment]
I was just thinking about suggesting this myself.

**Comment by sboigelot** [comment]
That's a very good idea. Just be sure to have the scheduled call serializable, serialized in the save game and loaded back onLoad.

**Comment by Fatalexceptionz** [comment]
Perhaps in future we could maintain an estimated completion time for job tasks and do some look-ahead with task assignments? For example, we could schedule resource hauling for just-in-time production or something. Just spitballing here.
