### ISSUE TITLE
Should Settings.xml be checked into the repository?

### ISSUE THREAD

**Issue by mikejbrown** [TeamPorcupine/ProjectPorcupine#836]
I can see something like `DefaultSettings.xml` being checked in, but not the file that is actually modified for saving and loading settings. This means that ` git checkout -- Assets/StreamingAssets/Settings/Settings.xml` is necessary every time someone wants to switch branches after making settings changes for testing things. Or git stash and apply, but that's still hassle.

So could we have a `DefaultSettings.xml` which is checked into the repo and loaded first by the game, then a `Settings.xml` or `UserSettings.xml` which is overridden by that and not tracked by git?

**Comment by Mizipzor** [comment]
I dont think it should be checked in. And sensible defaults should be part of the source code of the settings class.

**Comment by sboigelot** [comment]
I constantly have the issue of the Settings.xml meta file being generated, I ignore it on my commit by not staging it but should we add it to the git.ignore?

**Comment by TomMalbran** [comment]
The settings should be saved outside of the project files, inside the user computer, same as the saves. We can save it at Application.persistentDataPath

And in settings we should have default values. We don't really need an xml for those, it could just be set inside the code, but an xml can work.

**Comment by mikejbrown** [comment]
@TomMalbran Well, I just added a PR which does most of that. #843 But I didn't think of `Application.persistentDataPath`. If people want to change to that I'm fine with it.

**Comment by TomMalbran** [comment]
I saw it. I added a comment here since we should change the saving path instead of adding it to gitignore. StreamingAssets is not the place for user generated files.

**Comment by mikejbrown** [comment]
@TomMalbran As I think about it, you suggestion is better. Modders will be able to add default settings for their mods that way. Want to make a PR on my PR?

**Comment by mikejbrown** [comment]
@TomMalbran Updated the PR. Care to vet it?
