### ISSUE TITLE
Doors are not updating if walls are placed after doors

### ISSUE THREAD

**Issue by Raketfart** [TeamPorcupine/ProjectPorcupine#85]
If you place the door first, then the walls, the door is never properly rotated.
I think placing a piece of furniture should always call update on surrounding furnite, regardless if the furniture has LinksToNeighbours set to true.
That way, a door can re-orient, if walls are placed adjacent.
I've started working on a pull request on for this.

**Comment by Raketfart** [comment]
Put a pull request #92 that should fix it for now.
I know others have fiddled with updating surrounding furniture, but none of those will work with furniture larger than 1x1, and none will update a door because it doesnt connect to neighbours and is a different type than the walls.

**Comment by Raketfart** [comment]
The issue is hot-fixed for now, but i wonder about the correct way to implement doors and similar furniture.
1. Should we move this logic to Lua and have a OnChange Lua function on all furniture? Then "wall connect logic", "door connect logic" and eventually things like "shelves orienting to walls"/"miningdrill aligning to adjacent rock". 
2. Is it better to have the user rotate objects when placing them, and then doors simply won't close off rooms if they are placed wrong?

**Comment by Raketfart** [comment]
Fixed again in PR #442.

**Comment by vogonistic** [comment]
Closing this issue since it's fixed.
