### ISSUE TITLE
Solar Panels

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#850]
What do people think about having solar panels as a second source of energy?

I envision them as fairly space-inefficient 2x3 contraptions that produce maybe 3 power. The reactor is better but requires infrastructure to provide a constant stream of resources.

**Comment by vogonistic** [comment]
And the panels should be possible to build on ladders outside, so when we start using resource cost for floors, ladders and walls, it'll be really useful

**Comment by abackwood** [comment]
Ooph. Giving me an extra challenge to implement. Nice Vogonistic :smile:

**Comment by Yurgeta** [comment]
ive already posted a work in progress sprite sheet for solar panels in this thread [https://github.com/TeamPorcupine/ProjectPorcupine/issues/607](url) it contains various sized sprites, any feedback would be helpful on improvements or changes that could be made to them to match any ideas you all come up with

here is the image
![solar_panels](https://cloud.githubusercontent.com/assets/329655/18019894/438ba372-6bd6-11e6-93dc-cd1b4497b9c4.png)

**Comment by abackwood** [comment]
Can I use those? They look cool :)

**Comment by Yurgeta** [comment]
sure thing use them... thats why i made them for the project.. im still learning how to add them on my side of the project files so if u beat me to it then thats a bonus i can see how you do it lol

**Comment by Grenkin1988** [comment]
@abackwood This could be closed? Or you are going to do something more?

**Comment by vogonistic** [comment]
Lets open a new issue if we want to improve the panels.
