### ISSUE TITLE
Unreachable Jobs

### ISSUE THREAD

**Issue by afstew** [TeamPorcupine/ProjectPorcupine#851]
Currently, if a job is requested in an unreachable area the game hangs. It seems like the game is stuck in a loop trying to figure out how to path to the job. Currently, in Path_AStar.cs there is no code for a fail state. I'm not sure of the best implementation for a fix, but there could be a check on jobs for pathing, that if the code gets to Line 148 the job is marked unreachable and dequeued. In other similar games the prototype would be marked in red with an X over it, indicating that the job cannot be completed.

**Comment by mikejbrown** [comment]
Okay, here's an idea: give Jobs a flag saying whether they are unreachable or not (defaults false). When a Character first fails to path to a Job they toggle this flag. Then any time the pathfinding system regenerates the tile graph the flags on all existing Jobs are reset. Probably easiest to implement this with a callback.

**Comment by vogonistic** [comment]
Eventually, we'll have a Job system that understands rooms. This will be fixed, in the glorious future. Not sure if this workaround is going to help or not.

**Comment by Grenkin1988** [comment]
Close for now.
