### ISSUE TITLE
Pausing bug

### ISSUE THREAD

**Issue by dustinwloring1988** [TeamPorcupine/ProjectPorcupine#853]
When you pause the game all of the characters within view of the camera pause but some outside of the camera view do not. Also the animations seem to keep playing, please let me know if someone else has the same problem.

**Comment by Raketfart** [comment]
I think WorldController has
world.UpdateCharacters(deltaTime); 
outside the "IsPaused" check. 
That might be why.

**Comment by mikejbrown** [comment]
Maybe that fix could be a [beginner] task?
