### ISSUE TITLE
STYLECOP SATURDAY IS ON!

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#855]
During this Saturday, it has been decided that all the StyleCop warnings will be fixed. All of them. Every single one of the 1000+ warnings will be individually hunted down and caged.

Please join us in Discord for the festivities and see what has been claimed and not. We can use all the help we can get.

People will also be available to help you fix your merge conflicts so that we can all live in harmony after the festival.

@Mizipzor @WardBenjamin @RodRitter @longtomjr @Grenkin1988 @bjubes 

File list have been moved to [wiki:StyleCop Saturday](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/StyleCop-Saturday)

**Comment by Grenkin1988** [comment]
Tile class - done #852

**Comment by JosephBywater** [comment]
Woo!

**Comment by vogonistic** [comment]
This is what crazy people do when others do Ludum Dare

**Comment by Randshot** [comment]
I am done with Character.cs!

**Comment by Grenkin1988** [comment]
Please inform herу if you are cleaning any file

**Comment by vogonistic** [comment]
Someone gatekeeper will have the fun job of updating the list above

**Comment by Dormanil** [comment]
Fixed these:
- Assets/Scripts/Controllers/BuildModeController.cs
- Assets/Scripts/Controllers/MouseController.cs
- Assets/Scripts/Controllers/WorldController.cs
- Assets/Scripts/Models/FurnitureActions.cs
- Assets/Scripts/Models/GameEventActions.cs
- Assets/Scripts/UI/CursorInfoDisplay.cs
- Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxSaveGame.cs

**Comment by vogonistic** [comment]
@Dormanil You fixed everything in those files?

**Comment by Dormanil** [comment]
@vogonistic Aye. Meant to change WorldController, but had to refactor some fields, so I fixed everything else in the files affected by the refactor as well.

**Comment by Dormanil** [comment]
I claim `Assets/Scripts/Models/World.cs` then, and will see if I have to do the refactor thing again.

**Comment by mikejbrown** [comment]
Claiming

* /Assets/Scripts/Models/Quest/Quest.cs
* /Assets/Scripts/Models/Quest/QuestGoal.cs
* /Assets/Scripts/Models/Quest/QuestReward.cs
* /Assets/Scripts/Models/QuestActions.cs

**Comment by Randshot** [comment]
Please claim your files [here](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/StyleCop-Saturday).

**Comment by mikejbrown** [comment]
@Randshot I can't tick the checkboxes there for some reason. I've edited the Markdown.

**Comment by Randshot** [comment]
@mikejbrown That's how you are supposed to do it :D

**Comment by mikejbrown** [comment]
@Randshot Ah, ok. I was under the impression they were supposed to be checkable. :derp:

**Comment by Randshot** [comment]
53 files to go 😄

**Comment by Randshot** [comment]
30 more to go :D

**Comment by Randshot** [comment]
20 more to go...

**Comment by Randshot** [comment]
DONE. (waiting for 2 PRs)

**Comment by MANDAL0R3** [comment]
So is a gatekeeper going to have to check all 68 (give or take 1) PR's?

**Comment by izik1** [comment]
You guys are so fast :D i was gonna help out put i only just got everything set up.

**Comment by mikejbrown** [comment]
Running StyleCop on the current `master`:
```
------ StyleCop completed ------

========== Violation Count: 0 ==========
```
:tada:

**Comment by vogonistic** [comment]
For anyone reading this, there are remaining bugs in the Lua code that still needs fixing and merging at this point.

**Comment by Grenkin1988** [comment]
```
public event Action<Furniture> CbOnChanged;
public event Action<Furniture> CbOnRemoved;
```
Part of Furniture.cs
Someone did this wrong

**Comment by Grenkin1988** [comment]
@vogonistic @Mizipzor @Randshot I do not think that we finished. There are a lot of such things is code left. If StyleCop is OK with code, that's good, But that's not end

**Comment by Grenkin1988** [comment]
Fixed some Furniture staff #940

**Comment by Mizipzor** [comment]
I fixed two remaining violations, now at zero (again?). 

Ive also gone through the pull requests and tagged the ones with conflicts. 

@Grenkin1988 I think this should be the end. Now we can start enforcing StyleCop on pull requests, if we want to. But going beyond that, making code "even more clean" is a can of worms. There will be discussions and disagreement regarding the things that are fixed that StyleCop didnt flag. Getting rid of those debates were one of the primary reasons I introduced it in the first place.

**Comment by Grenkin1988** [comment]
@Mizipzor What is better?
`Furniture f;` or `Furniture furniture;`
Why StyleCop don't care for public fields?

**Comment by Mizipzor** [comment]
> Furniture f; or Furniture furniture;

The latter, absolutely.

> Why StyleCop don't care for public fields?

It was one of the rules explicitly allowed in our project. Im actually looking at reenabling that rule.

In these cases it's clear to me, but it isnt always that. I admire your efforts to keep the code clean. I just wanted to avoid sparking a holy war, thats all. :)

**Comment by Mizipzor** [comment]
Enabling StyleCop `SA1401: FieldsMustBePrivate` yields 261 warnings. You think its worth it?

**Comment by Grenkin1988** [comment]
Than decision is on your hands. If this is it, than close PR #940

**Comment by Grenkin1988** [comment]
We are going to enforce no public fields rule and fix this now Begin: #943

**Comment by Randshot** [comment]
I just want you to remember that when you refactor any public fields related to Inventory, Room, World, Furniture or Job, to also check the Lua files for possible changes.
It is PITA to do that afterwards, especially if you don't even know what was changed, since the error messages that pop up aren't really that helpful.

**Comment by Mizipzor** [comment]
@Randshot Yes, I agree, doing this and avoiding breaking lua will be hard.

**Comment by vogonistic** [comment]
If we ran NUnit tests that called the lua, would we be able to pick up the errors and fail the tests?

**Comment by Mizipzor** [comment]
I just found something that lets us divide this problem.

> [SA1307: AccessibleFieldsMustBeginWithUpperCaseLetter](http://stylecop.soyuz5.com/SA1307.html).

It would allow public fields, but they must start with a capital character. This would allow us to keep public fields for unity editor gui. But change all lua code to access with capital. Then, once we replace all fields with properties, lua needs no changing.

**Comment by kd7uiy** [comment]
Isn't this complete?

**Comment by vogonistic** [comment]
Yeah. The event itself is over. We should open new issues with follow up problems.
