### ISSUE TITLE
Idea: Trading

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#88]
KR is a government-based currency that you get for completing missions, however this is useless for anything other than trading with the government. You use a furniture (called KR Exchange?) to buy stuff (You can't sell stuff for KR--That's like being a freeloader!)

This could also evolve into some sort of Diplomacy system with SETI and stuff like that.

**Comment by bjubes** [comment]
Trading would be cool, but so far all we could trade is steel plates...

**Comment by emilkris33** [comment]
But @bjubes would you not like to trade 50 of your boring steel plates for 5 of my premium steel plates that are totally not exactly the same.

On a more serious node i think we need a lot more items and buildings before figuring out how a trade economy might work.

**Comment by ComputerOverlord** [comment]
Haha. I get it but even here a system for trading useless KR for plates might be nice...

Yeah, it might be a while.

**Comment by sboigelot** [comment]
@ComputerOverlord what is the real words for the KR acronym?
