### ISSUE TITLE
Insufficient Graphics Scheme

### ISSUE THREAD

**Issue by AE40** [TeamPorcupine/ProjectPorcupine#9]
As the game will evolve we will need a system for requesting graphics, these any person artist or none artist can contribute to and the best graphic will be selected by the requestor. This can probably be accomplished by opening issues explaining the graphic needed, I would suggest a naming scheme of something along the lines of 'Graphic Request: [graphic name]' or 'Graphic Needed: [graphic name]' or 'Graphic Missing: [graphic name]'

**Comment by NogginBops** [comment]
We could use a custom lables for this type of issues. Then the name could just contain the name of the graphic needed/requested/missing. Though that might be hard to read through. (But that's why we have tag filters :D)

**Comment by NogginBops** [comment]
This scheme could (and probably should) also be extended to other types of assets as well. For example, sound and music.

**Comment by quill18** [comment]
I like the label idea -- especially since issues can be filtered by them.

**Comment by quill18** [comment]
I have labelled this discussion with an example.  Let me know what you think!

**Comment by NogginBops** [comment]
Looks good! Really starting to feel this project now! :smile:

**Comment by quill18** [comment]
Great!  I'll hold off on labels for other assets (like sounds) as it's a bit early for that -- but the graphic requests might come in handy.
