### ISSUE TITLE
Improvement to Uberloggers message handling.

### ISSUE THREAD

**Issue by Sommerbo** [TeamPorcupine/ProjectPorcupine#939]
Since we are mostly using UberLogger now we should address the two fairly significant flaws with UberLogger. 
1. Uberlogger should forward logmessages to Unity's console it doesn't seems to be a logic error in `/Assets/UberLogger/UberLogger.cs` in function "Log" starting on row 421.

**Update**
This was wrong, it seems to forward messages but still message count is higher in UberLoggers console than Unitys.

2. Multiline messages only shows the first line but based on the position of the severity icon I think the entire message is printed but the row isn't expanded to show it.

**Update**
On line 296 in `UberLogger.cs` it should "fix" multiline messages, but it doesn't. Included the relevant code:

`showMessage = showMessage.Replace(System.Environment.NewLine, " ");`

**Comment by Mizipzor** [comment]
I'm starting to wonder if that logger was a mistake. Did I rush into it? :/

**Comment by vogonistic** [comment]
I think UberLogger is better than the console logger, but it's not perfect. If someone is willing to do the job, I'm sure they'll review and/or include it.

**Comment by Sommerbo** [comment]
Fixed in #1016 mostly
