### ISSUE TITLE
Reduce UberLogger channel button clutter

### ISSUE THREAD

**Issue by Sommerbo** [TeamPorcupine/ProjectPorcupine#941]
The more channels we use for logging the smaller the buttons become one way around that is to switch to a dropdown if there are over a certain number of channels. Or to switch to a dropdown regardless of the number of channels. Or some other clever solution.
Buttons are drawn in `Assets/UberLogger/UberLoggerAppWindow.cs` starting on line 209.

**Comment by vogonistic** [comment]
Since there can only be one selection, a dropdown might make sense. We might also want to use slightly broader channels for Uber to avoid making the dropdown or the button count extreme. Like putting all the Job-related logs in `Jobs`

**Comment by Fatalexceptionz** [comment]
Maybe implementing another level of hierarchy might be a better solution -- **Category**, with **Channel**s as children.

That way you can have the broader categories, but still restrict your log spam to a specific method if required.

**Comment by mikejbrown** [comment]
Fixed by #1335
