### ISSUE TITLE
[Bug] Dev mode blocks furniture building

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#945]
When in dev mode, furniture and floors are built instantly. But a job is still created, just not added to the job queue. This means that no furniture can be built on insta-created floors because the BMC thinks there is still pending jobs there.

Am I the only one experiencing this?

**Comment by MANDAL0R3** [comment]
No your not. In my PR https://github.com/TeamPorcupine/ProjectPorcupine/pull/825, if dev mode is turned on and your have a character selected, then right click on a furniture, it still shows the "Prioritize Job" and "Cancel Job".
