### ISSUE TITLE
[WIP] UI Redesign

### ISSUE THREAD

**Issue by alexfriesen** [TeamPorcupine/ProjectPorcupine#956]
I started working on a new UI Design.

I am aiming for a slim sci-fi look.

This is the current state of the main menu. what do you think?

![pp_menu_closed](https://cloud.githubusercontent.com/assets/1307706/18029190/ae61c508-6c91-11e6-805c-97c5e2b42a3e.jpg)
![pp_menu_open](https://cloud.githubusercontent.com/assets/1307706/18029189/ae60f7b8-6c91-11e6-9879-9d296a8b8294.jpg)

**Comment by vogonistic** [comment]
That is pretty slick!

**Comment by Tranberry** [comment]
looks good, but how big are these buttons?

**Comment by alexfriesen** [comment]
The current menu will be 90px high and the width depends on items in the menu ;)
A single button is about 98x75px.

**Comment by Yurgeta** [comment]
this was something i was going to suggest / mock up in the near future because the amount of text buttons is growing fast its starting to clutter the screen a little so using picture representation for things now could save us some trouble later on.. maybe add a tool tip to the bottom so it gives the name above or something so people know what it is if they cant figure out the pictures

**Comment by Mizipzor** [comment]
Doesnt it kinda clash with the pixel art? Its so smooth. Hard to tell.

**Comment by Ajapeu** [comment]
@Mizipzor It might conflict a bit. That said... desperately needed, and getting to a more organized slick UI is really going to help when new features start coming in. Probably needs to happen now anyway. 

@alexfriesen This looks really nice.

**Comment by Tranberry** [comment]
IMO that's pretty huge on any screen with less than 1080p resolution. It would be nice if it could scale..

**Comment by alexfriesen** [comment]
Thanks for the feedback. 
I made the borders thicker and less transparent. 

With the thicker lines I would be possible to scale the menu down.

Here the reworked bottom menu
![pp_menu_main_closed](https://cloud.githubusercontent.com/assets/1307706/18034330/43f04786-6d3a-11e6-8911-f08a661f4a69.jpeg)
![pp_menu_main_open](https://cloud.githubusercontent.com/assets/1307706/18034329/43eced66-6d3a-11e6-9580-d0f0013432b6.jpeg)

The Options menu: 
![pp_menu_options](https://cloud.githubusercontent.com/assets/1307706/18034335/6bfd17ea-6d3a-11e6-87d3-e1ed6065d46e.jpeg)

And the build/furniture selection: 
![pp_menu_build_selection](https://cloud.githubusercontent.com/assets/1307706/18034341/7da0dc5c-6d3a-11e6-934a-5aa2e13a634e.jpeg)


Full scene:
![pp_menu](https://cloud.githubusercontent.com/assets/1307706/18034389/bf8692e6-6d3b-11e6-84f9-136f7322706c.jpg)

**Comment by Dormanil** [comment]
Now all that's left is a font that feels proper in this look and feel, but I definitely enjoy the slickness of this UI.

**Comment by vogonistic** [comment]
Hey @alexfriesen, have you seen the #art room in Discord?

**Comment by Tranberry** [comment]
here is a link [#art](https://discord.gg/BhWXg)

**Comment by dustinwloring1988** [comment]
Nice, cant wait for it to be done.

**Comment by Raketfart** [comment]
Oh man, I'd loove for this to be in the game. If we're going for a non-pixelated UI, I like this direction.
I have a couple of thoughts.
Whenever the gui shows text, I think we need to use elements that can stretch - maybe not 9 sliced, but at least easily stretch along x for localized text. Just so we avoid having to redo art for every size of dialogue box.

Maybe we could use less saturated colors, and some subtle gradients/glows can make this feel a bit more sci-fi. I made a crude example on top of yours, to show what i mean.
![modified](https://cloud.githubusercontent.com/assets/7031323/18035789/d49998b0-6d5c-11e6-90d9-40d6e25417f2.png)

**Comment by alexfriesen** [comment]
Great Ideas!

I would love to use some gradients, but I don't really know how to do it in Unity when everything needs to be able to stretch. 
But I'm going to investigate in your glow idea.

**Comment by Tranberry** [comment]
Will you make UI elements for others to make their own UI for features currently not in the game?

**Comment by alexfriesen** [comment]
I could do that, if i have some time left.

**Comment by TomMalbran** [comment]
This looks great. For windows we could also have some transparency, while trying to keep the text readable.

**Comment by alexfriesen** [comment]
BTW: I think the Settings Button can go to the Options Menu

**Comment by TomMalbran** [comment]
@alexfriesen I agree.and if we keep adding test maps, maybe we need a debug/test dialog that can be open from the options dialog.

**Comment by vringar** [comment]
@alexfriesen would you mind creating a [WIP] PR so others could join/help/have a look at it?

**Comment by kd7uiy** [comment]
How is this going so far?

**Comment by alexfriesen** [comment]
Hi, this is still happening ;-) I have been very busy lately and didn't had a lot of time to work on this.
In #999 I started with the settings menu. 

The construction menu should sit at the left corner of the screen and contains a scrollable list of all furniture.

Feel free to start working on some of the pieces, I think the screenshots will show how I imagined the UI to look like.

**Comment by sboigelot** [comment]
We can come up with a temporary ui fix if we need. It would be easy enough to have 2 columns until @alexfriesen PR is ready

**Comment by bjubes** [comment]
see #1500 for UI redesign for version 0.1 -> 0.2
