### ISSUE TITLE
New StyleCop format for properties is weird

### ISSUE THREAD

**Issue by FilippoLeon** [TeamPorcupine/ProjectPorcupine#958]
Is it just me that finds:
`public Furniture Furniture { get; private set; }`

too odd?

I really prefer the old style with a minuscule first letter of a property.

Let's say in  the code I want to use

`Furniture.Deconstruct()`

Am I calling a static Deconstruct method of Furniture or a Deconstruct of the instance Furniture?

On a related note: shall we really strictly enforce all the style cops rules?

Do not get me wrong, it is most of the time useful. But I think we should be more "relaxed" in enforcing its suggestions.

I know that many are useful. But like: enforcing certain amount of spaces after brackets, explicitly add access modifiers, or forbidding public fields, to me seems a bit too much.

**Comment by Grenkin1988** [comment]
Explicitly add access modifiers - it is so hard for you to write down one more word? IDE would write it for you after couple of letters.
Forbidding public fields - this is not a rule for StyleCop, but this is one of fundamental paradigma of OOP - encapsulation.
Spaces after brackets - seems not very important, but it really important to have code readable for everyone, not just for you right now.

**Comment by Mizipzor** [comment]
@Grenkin1988 It actually is a rule for StyleCop, [SA1401: FieldsMustBePrivate](http://stylecop.soyuz5.com/SA1401.html), we just have an override for it. Was that what you meant? I want to re-enable that. But between the public fields for lua and the public fields for the editor gui I dont see that happening just yet.

**Comment by FilippoLeon** [comment]
@Grenkin1988 Forbidding public fields is a question of style.

For me is not about writing time, is about verbosity and bloating of the code. Sometimes things are better if unsaid. But that's just a personal rant against the Style Cop. :)

My main point is the first part.

**Comment by Mizipzor** [comment]
@FilippoLeon Its not odd. If the following confuses you:

    Furniture.Deconstruct()

Your IDE should highlight (instance-) variables and types differently, so you should know. If not, see if you can find another color scheme in settings. Or if you prefer colorless, use a "go to definition" hotkey if youre unsure.

And regarding this:

    public Furniture Furniture { get; private set; }

Its actually semi-recommended by the [Microsoft Naming Guidelines](https://msdn.microsoft.com/en-us/library/ms229012(v=vs.110).aspx):

> ✓ CONSIDER giving a property the same name as its type.
> For example, the following property correctly gets and sets an enum value named Color, so the property is named Color:

```
public enum Color {...}
public class Control {
    public Color Color { get {...} set {...} }
}
```

If your class has a Furniture, it makes perfect sense, to me, to call it Furniture.

**Comment by FilippoLeon** [comment]
`If your class has a Furniture, it makes perfect sense, to me, to call it Furniture.`

That indeed, but to me `furniture` would be even clearer, even if (god forbids) I open the file with notepad: that's a variable, not a method.

**Comment by Mizipzor** [comment]
To me it can be both. If its a publicly accessible field/property then its `Furniture`, if its a private field its `furniture`.

These discussions tend to be endless, and for any given rule we would probably find half of our contributors in favor and the other half not so much. I've said it before, I think its more important to be _consistent_ rather than _good_.
