### ISSUE TITLE
Allow multiple Furnitures in one tile.

### ISSUE THREAD

**Issue by FilippoLeon** [TeamPorcupine/ProjectPorcupine#959]
as the title says, what is you take on that?

**Comment by vogonistic** [comment]
Can you give us an example where this would be useful?

**Comment by FilippoLeon** [comment]
Say we have a table, we could have object on that table. Or say carpet (without messing with floor).

One thing I was particularly interested is a fire mechanic. A "Fire" could be a piece of furniture (yeah, I know, but it would be extremely easy to implement), but it should be able to share tile with furniture.

**Comment by Mizipzor** [comment]
I think it makes way more sense to talk about "layers". You cant have multiple furniture on a tile, if you could, i would put *everything* in the corner to save space. You can, however, have say a rug under the bed on one tile. But not two beds on that tile.

**Comment by FilippoLeon** [comment]
Yes, of course there must be restrictions.

A layer system and maybe some sort of flag (like: furniture that is Unique, means that no matter what, it cannot share a space, furniture that is "Invisible": no matter what it can be placed, and furniture that can Share a tile)

**Comment by Mizipzor** [comment]
@FilippoLeon You seem to have good ideas, wanna try implement this? :)

**Comment by vogonistic** [comment]
@FilippoLeon The object on the table would be inventory and I think it's been whispered in the hallways that furniture that isn't installed is also inventory.

The carpet might be interesting, but we might need a different system for that. We need to figure out how sticky and dirty floor works as well. Is that the same system?

**Comment by FilippoLeon** [comment]
@Mizipzor If there is interest and I have time (will take time to implement without breaking the "API" too much).

@vogonistic I'm sure there are many other use-cases that will come up once is there ;)

**Comment by bjubes** [comment]
I think a specific layer would be good. Like a layer for flooring, fire, even utility so that a water pipe can be "in the ceiling"

**Comment by FilippoLeon** [comment]
@bjubes Oh yes, there it is, other application is pipes, cables and ceiling lamp

**Comment by sboigelot** [comment]
Does the Z level of tile allow us to close this issue?

**Comment by TomMalbran** [comment]
@sboigelot I don't think so. If fire was a furniture, then it needs to go on top of another furniture. Same with other effects like smoke. Maybe those should be effects and not Furniture.

We have also things like wires and pipes and vents that can go on walls, or under the floor, and could also be furniture, or we can have those as Utilities.

It will depend if we want to have layers of furniture or different types. I think that layers with types will work good.

**Comment by sboigelot** [comment]
I don't know how we handle z index for now, but I assume we use integer value in a float.
We could have sub-level for piping etc, like level 0.1 0.2...

**Comment by TomMalbran** [comment]
I don't think that the layers will work for it. I think that we should replace the furniture inside a tile for a dictionary, where the key is the layer. Or just have different classes for Furniture, Decorations, Utilities and Effects.
