### ISSUE TITLE
Unity creating files. What to do?

### ISSUE THREAD

**Issue by emilkris33** [TeamPorcupine/ProjectPorcupine#96]
Every time i start unity it seams to make these changes:
![image](https://cloud.githubusercontent.com/assets/1301554/17752415/02bd2ad4-64cc-11e6-84c8-f00a00885076.png)

The question is it is something that should be added to .gitignore or do someone just need to push this to the master once and problem solved.

I have so far been unchecking them from my commits. Are you all seeing the same? And what are you guys doing with them?

**Comment by NogginBops** [comment]
@emilkris33 I'm getting the same and I'm pretty sure they should get merged in to the main branch. I think somebody added or moved a file and committed without opening unity. I think we need a edit to the contribution guidelines that you should open the project in unity before creating a PR.

**Comment by bjubes** [comment]
Ive been resetting them before each commit, or unchecking the box every time if using GUI

**Comment by SquareMan** [comment]
There was some talk about adding ProjectSettings to the gitignore, as it has a tendency to change everytime a different person opens the project (#17) As for the meta data, #53 added those folders, I'm guess the author just never actually opened the project. Someone should probably commit those to a new branch and pull request them. Not sure about the GraphicsSettings, its probably a very similar situation to ProjectSettings and should just be ignored.

**Comment by emilkris33** [comment]
@satch3l It seams that your #53 has caused part of this do to you not opening unity (and letting it create .meta files) after adding those folders. Just tagging you FIY so we can all try to avoid similar issues in the future. And so you can tell us if we are totally wrong about you not opening unity and we have to look for another cause.

**Comment by satch3l** [comment]
@emilkris33 I'm pretty new to the whole git work environment. I had no idea that changes made outside of coding, or unity related, needed unity to be opened anyways for it to "work".  I'll definately keep that in mind next time!
