### ISSUE TITLE
How do you test out someone's pull request?

### ISSUE THREAD

**Issue by herrflockig** [TeamPorcupine/ProjectPorcupine#964]
The way I've been doing it is this:
I use git bash.

I cd into my project directory, checkout the master branch. I then make sure I'm updated on all my branches (particularly the master branch), update my local with upstream, then my remote with local.

```
cd C:/path/to/project/
git checkout master
git pull upstream master
git push origin master
```

Then I download the patch file that differs it from the master branch.

```
curl $(curl "https://github.com/TeamPorcupine/ProjectPorcupine/pull/[[the pull request number]].patch" 2>/dev/null | awk.exe -F'"' '{print $2}') > patch.patch
```

*note: replace ```[[the pull request number]]``` with the pull request number you want to test out.

I then apply it to my project
```
git apply patch.patch
```

I can then try out the code, have fun, judge them harshly on their programming.

Then when I'm done I just

```
rm patch.patch
git reset --hard HEAD
```

then go about on my merry way.

P.S. is there an easier way than this???

**Comment by TomMalbran** [comment]
Here is the documentation from the Wiki
https://github.com/TeamPorcupine/ProjectPorcupine/wiki/How-to-Test-a-Pull-Request

**Comment by herrflockig** [comment]
Oh, haha. That makes the git flow much better.

**Comment by TomMalbran** [comment]
@herrflockig if that solved your question, you can close this issue.

**Comment by kd7uiy** [comment]
@vogonistic This one is pretty clearly documented in the wiki, I suggest closing it.
