### ISSUE TITLE
[Crazy Ideas][Discussion] Procedural texture generation / Marching Squares-like walls.

### ISSUE THREAD

**Issue by Fatalexceptionz** [TeamPorcupine/ProjectPorcupine#967]
We were talking in the Art channel on Discord about extending the wall and stockpile spritesheets and associated implementation to cover the full range of 3x3 permutations.

Which got me thinking about ways to procedurally create walls from a set of supplied base textures, and maybe a shadow/highlight map.

Now, I'm not seriously suggesting that we go down this route, I just thought it'd be interesting to stimulate some discussion.

Feel free to nix this if it's too off the wall or whatever.

**Comment by Sommerbo** [comment]
It could be done with shader(s) if the base graphics is light enough

**Comment by koosemose** [comment]
This was just to stimulate discussion, and no discussion was stimulated, closing.
