### ISSUE TITLE
Art PR Guideline?

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#971]
I don't think there is an official standard for submitting PRs concerning art changes.

My two suggestions for guidelines, if it doesn't exist yet, is at least the following:
- Only one sprite should be changed per PR. This allows a case-by-case decision.
- If it changes something that isn't obviously a placeholder, some word should be given to how it improves upon the old one. Better lighting? More in line with style? More in line with the function of the furniture it depicts?

**Comment by Tranberry** [comment]
I would like to have a prefix to placeholder images like` ph_imagename.ext` ..

**Comment by abackwood** [comment]
Wouldn't that break the naming standard? Images are searched for by objectType

**Comment by Raketfart** [comment]
File names are irrelevant - as we search for the name attribute in the xml files.

**Comment by Dormanil** [comment]
So as long as an xml file exists, we're golden.

**Comment by longtomjr** [comment]
OK Here is my thoughts on this: We are not at the moment at a place to replace any art. We don't have proper art, or even art at all, for a lot of the stuff. We can later discuss changes to art and if a consensus is reached we can work on changing it, but we are not there already. (This is just my opinion on this)

I also think you can be at liberty to change someone's art if they agree with it. For example: If @Tranberry  asks me if he can make better doors, and I say: "go for it," he can change the doors without any problem.
This is not a perfect solution, but I think in the current standing of the project we should allow this, especially if someone is using your old work to make better sprites. :)

**Comment by longtomjr** [comment]
We also will need general guidelines to how we create the art. I suggest we discuss that here as wel. This includes but not limited to: Shading, Pallet, Sprite Size (details and ppu) etc.
Any consensus reached should be posted here please:
https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Standards-and-Conventions#artwork

**Comment by Tranberry** [comment]
To add to that **light direction**, there is no 'better' or 'worse' light direction only different angles.

**Comment by Dormanil** [comment]
Some discussion to that was in PR #969, if I recall correctly the consensus there was a common base resolution for all sprites (i. e. 32 * 2<sup>x</sup> ppu and no sprites inbetween tile sizes).

**Comment by Mizipzor** [comment]
I think there are two discussions here.

* When art is changed it should be easy to evaluate and merge, so one image per pull request and good description and be mindful about light direction and stuff like that.

* What if I deem someone else's art not satisfactory? How and when am I allowed to replace it?

The latter is the difficult one, probably sparked by #966. This is a beginner project, so beginner level stuff should be welcome. I reason the same way with code pull requests, so what if it's a bit crude and maybe has bugs? If Quill created this project specifically to introduce beginners to game development then that is to be expected. 

I remember way back when I got my first contribution accepted into an open source project. It's a huge fucking thing. And if someone soon after comes and does and overhaul, no matter how much better it gets, it might be a very sensitive discussion.

**Comment by Dormanil** [comment]
But that's also what Open Source is about, @Mizipzor: Everyone is allowed to improve everyone's code. For code, it is way easier to decide what's better code and should be kept, but nonetheless, hard feelings are here just as misguided as in a Closed Source project of a business.

**Comment by Mizipzor** [comment]
At the same time, if a talented artist comes along and is willing to work on every sprite in the game to make awesome and consistent art than I absolutely want to use that as well. The correct way to handle that is to add support for tilesets, or whatever we should call them, a mod that changes sprites.

But we are not there yet. And until we are I think we need to keep the look of the art very simple. Everyone has their own "style" and it might be difficult to look at existing stuff and adapt to it, especially if youre a beginner, and a simple style helps with that.

**Comment by Mizipzor** [comment]
@Dormanil you are correct, I'm not saying that it is _forbidden_, just that it is _sensitive_. And that we need some guidelines established so that both parties in that situation knows what to expects. :)

**Comment by longtomjr** [comment]
Just throwing it in here #197

**Comment by longtomjr** [comment]
@Dormanil @Mizipzor I think art should only be replaced when we have consensus that a sprite is outdated, does not fit etc. We will not be able to have a consistent art feel, style etc because we do not have an artist that is doing all of the art. I think for artist that want to should have the option to create tile-sets as a mod. This way you can modify your game's art as you feel and if one person puts out a gfx replacement mod it will be consistent and probably better than what we have atm, but because we cannot have only one artist work on the gfx for the project because the quality will just fall when that person stops.

**Comment by Tranberry** [comment]
Adding on that, we should make it clear that art that is  provided before v1.0 or similar is bound to be changed and maybe replaced.

**Comment by Mizipzor** [comment]
Could we also make a list of every sprite that is a place-holder (please replace asap) and not a place-holder (please have good reason to change).

**Comment by longtomjr** [comment]
@Mizipzor look https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Milestone-0.1#artwork
That is what we have for 0.1

**Comment by vogonistic** [comment]
When this discussion has come to a conclusion, I would appreciate a comment on #966

**Comment by bjubes** [comment]
I think we should have an "art gatekeeper", maybe someone like @Tranberry or @TheRiven (ive just seen you guys in art discord alot) who has a sort of authority over what spirtes are good for now, and what needs replacing. They wouldn't have any special power like gatekeepers, just agreed upon authority over the art style.

**Comment by abackwood** [comment]
So to summarise what seems to be the consensus on Art PRs:
We'd like sprite changes to follow the rules:
1) One sprite at a time
2) Only replace sprites that are one of ...
- placeholders
- outdated in function
- jarringly inconsistent with other sprites
3) You need the original author's consent. Placeholders imply consent for any change.

Does that sound about right?

**Comment by Tranberry** [comment]
to be clear, that means one PR per sprite?

**Comment by Ajapeu** [comment]
Should we try to use the wiki to collect what the current sprites are? Is that even possible? Might solve some of what Mizipzor is looking for?

**Comment by abackwood** [comment]
@Ajapeu we could make a table of all tile types and furniture types with their properties, including the commit where their current sprites were added

**Comment by NogginBops** [comment]
I don't think the "... original authour's consent" is good, I think it should be "... if the general consensus is that it should be replaced" or something like that. I think it's good to talk to the original author but I think that it might become unsustainable.

**Comment by Tranberry** [comment]
I'm with nogginbops here, all art should be considered placeholder until at least v0.1 and perhaps even v1.0

**Comment by bjubes** [comment]
I agree with community consensus as opposed to the authors consent. Usually both will agree but there's a chance that the original author my become inactive or just refuse to remove their work

**Comment by longtomjr** [comment]
Community consensus! So we all agree, as a community :)

**Comment by TheRiven** [comment]
I am fine with Community consensus, if enough people feel that the new sprite is more suitable then the old one then its probably the better choice.

Also as @Tranberry said, its far to early for any art to be considered anything other then placeholder as for all we know most of the things currently in may be replaced or changed completely later on.

So long as it fits the current style and looks like it could be the thing its representing then for now its all good :smiley:

**Comment by abackwood** [comment]
Revised guidelines based on comments:

1) One sprite at a time

2) Until further notice, all sprites are liable to be replaced. However, when replacing a sprite that is not an obvious placeholder, give some indication why your sprite is better than what's in place. Art is subjective so it's worth making your case to convince unbelievers.
2a) Sprites are not likely to be replaced unless they are ...
... placeholders
... outdated in function
... jarringly inconsistent with other sprites

3) The community is king. If there is a community consensus that the sprite you made is better, then it'll be merged even if the old sprite wasn't obsolete. **So show your artwork!**
3a) As a common courtesy, if they are still around, it's good to discuss with the author of the old sprite.

**Comment by Mizipzor** [comment]
No responses to that, I assume discussion is over. Put that last post in the wiki. We can always reopen if there's more to be said.
