### ISSUE TITLE
[Bug] Iron Ore disappears

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#973]
![gif](https://cloud.githubusercontent.com/assets/5951269/18033523/90040904-6cf5-11e6-8a15-eecfcb04d3f3.gif)

Note, 50 was picked up, placed on a stack of 45, and 50 was left. It seems a bit off...

Also, if we prioritize jobs, it seems like that should be a lower priority, but that's a more complex issue...

**Comment by Grenkin1988** [comment]
It is not visible how many it was

**Comment by kd7uiy** [comment]
Sorry about that, trust me when I say it was 50... I'll try and get a better image of this soon.

**Comment by kd7uiy** [comment]
This might be related to https://github.com/TeamPorcupine/ProjectPorcupine/issues/47

**Comment by SquareMan** [comment]
I've been working a bit on #47, I think that the Metal Smelter itself may be responsible for eating the entire stack. I'm not %100 sure yet though.

**Comment by SquareMan** [comment]
Still digging on this issue, through much debugging (apparently a pain in the ass with dictionaries) , I've discovered that the stackSize is not being set correctly for the metal smelter job. In your image, it should be 45, but instead it's always 0. Currently still not sure if this is an error in this specific job code, or a general error across all jobs.
