### ISSUE TITLE
[Enhancement] Quillcorp Newspaper/Announcements

### ISSUE THREAD

**Issue by koosemose** [TeamPorcupine/ProjectPorcupine#982]
We need a Quillcorp newpaper (and possibly one or two other more generalized papers) that pops up or otherwise becomes periodically available. Even though it started as a joke in #art on Discord, it's a great way to introduce some of the flavor of the setting, along with some random humor. It could even be used to give advance warning of some events (Get news about increase in space pirates prior to space pirate attack, etc...)

Example (from #art):
@WardBenjamin , The CEO of Quillcorp, has announced that it main and only shareholder is still the main and only shareholder, Quill18.

Notice: Quillcorp has placed an embargo on "Chairs", any Quillcorp Basic Utility Station found in possession of this illegal contraband will be fined 2 million Quillbucks.

**Comment by longtomjr** [comment]
I love this idea! I am imagining a Sim City Style ticker that just have a bunch of jokes and sometimes something important :) (Thinking of sim city 3000 specifically)

**Comment by abackwood** [comment]
"Introducing the MagBlast 2200 magnetic rifle. 70% of the time, it hits *every* time."
"Thinktank finds something that could go wrong. Head of QuillCorp not availble for comment"

**Comment by sboigelot** [comment]
A QuillCorp newspaper... for free? That's insane :dancer: 
A let's make it cost something :D (Auto deducted from your credit balance of course, atonement is mandatory)

**Comment by longtomjr** [comment]
It comes for "free" with your monthly generous Quillcorp "Protection" fee :P

**Comment by kd7uiy** [comment]
I suggest it be free, with in app purchases (Or "donations") that unlock certain features. Maybe unlock an economic section, or something.

**Comment by kd7uiy** [comment]
If no one else is working on it, I'm going to work on a backend for this. The backend will allow for subscribing to updates, and periodically send out a news update to be read by some front end that someone will develop. 

I will set it up such that certain conditions either have to be met to include an item, or it is automatically unlocked. The update rate will be random, as configured by the XML file giving the text to include.

**Comment by kd7uiy** [comment]
Put the start of this in #1033 , note that it's only a rather weak backend, but it's a start. I added the two examples given above. It should be fairly easy to extend from there, let me know if you have any issues!

**Comment by kd7uiy** [comment]
Okay, so I've started the backend and submitted it, but there's some desire to have at least someone commit to doing the front end before they will accept the PR. Anyone want to commit to doing that?

**Comment by kd7uiy** [comment]
This one is complete, more headlines can be added, but...

**Comment by TomMalbran** [comment]
Phase 1 is done. We can come with more things to add for Phase 2.

**Comment by bjubes** [comment]
If you want to continue into "phase 2" then open a new issue at that time
