### ISSUE TITLE
Proposal- Convert building names to icons

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#985]
It seems like using icons would be a good way to shorten the list of available items to build. When hovering over an icon, a tooltip like display could show the name, features, and a description of each item. I think that'd be easier than the current system, and look nicer. It's also similar to most other games of the type. Thoughts?

**Comment by Ajapeu** [comment]
See #956 for a potential way to do this.

**Comment by Tranberry** [comment]
I think I agree with this, but this part seems odd 

> It seems like using **icons** would be a good way to shorten the list of available **icons**.

Shorten what icons?

**Comment by kd7uiy** [comment]
@Tranberry Sorry, long car trip yesterday, I think my mind hasn't yet arrived...

**Comment by kd7uiy** [comment]
Closing as a duplicate of https://github.com/TeamPorcupine/ProjectPorcupine/issues/956, which has a more detailed proposal.
