### ISSUE TITLE
[Announcement]We Have a WIKI! Please Use it and Contribute :)

### ISSUE THREAD

**Issue by longtomjr** [TeamPorcupine/ProjectPorcupine#988]
## **Just want to make sure that everyone knows we have a wiki now that aims to ease the development**  
# We have:
* [Roadmaps](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Roadmap)  
* Explanations of [systems](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Systems), and [features](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Features)  
* [Standards and Conventions](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Standards-and-Conventions)
* [A section for all your Git needs and troubleshooting](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Git-Problems-and-Fixes)
* And Many more

Be sure to check out the wiki. ( ~~Not affiliated with Quillcorp~~ **Affiliated with Quillcorp**)

**Comment by WardBenjamin** [comment]
+1 for "Affiliated with Quillcorp"

**Comment by longtomjr** [comment]
^The CEO of Quillcorp approves this post!

**Comment by Ajapeu** [comment]
@longtomjr Love this. Will contribute with editing and design thoughts when possible. Nicely done!

**Comment by mikejbrown** [comment]
@longtomjr Wait, the CEO of Quillcorp isn't Quill? :scream: :confounded:

**Comment by longtomjr** [comment]
@Ajapeu Thanks!

@mikejbrown Quill is the main and only shareholder of Quillcorp!

**Comment by FilippoLeon** [comment]
Wanna move https://github.com/TeamPorcupine/ProjectPorcupine/wiki/How-does-it-work%3F to https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Systems?

**Comment by bjubes** [comment]
I think eventually the _how does it work_ page should be its own heading in the sidebar, with each system having its own page. Right now its a bit cluttered and half-empty but ¯\_(ツ)_/¯

**Comment by longtomjr** [comment]
If you think you can improve the wiki, go for it. It is meant to be a tool for all of us. :)
At the moment though we don't think everything should have one page because that will be for a larger wiki. :)

**Comment by sboigelot** [comment]
How and when will we be able to close this issue? Should we have a new text in the README.md saying something about the wiki?

**Comment by longtomjr** [comment]
Closing the issue, please continue to use the wiki and remind people that is exists!
