### ISSUE TITLE
Each Job should have a "Can I complete this task given the current world state" function

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#991]
Don't know what to call it, but it would be very helpful. For instance, is there enough steel in the world to do this job? If not, skip that task and do the next one. If so, drop the "global" count and take the job. I would guess that World would have to know anytime a resource is created or consumed, but there might be a better way. This would probably help to some extend with stockpiling as well.

**Comment by mikejbrown** [comment]
I agree this sort of functionality is good but it might be worth waiting for the new job system to go in first. ?

At the moment `Character` has a method which does pretty much what you want:
```
/// <summary>
/// Fulfillable inventory requirements for job.
/// </summary>
/// <returns>A list of (string) objectTypes for job inventory requirements that can be met. Returns null if the job requires materials which do not exist on the map.</returns>
private List<string> FulfillableInventoryRequirements(Job job)
```
This could probably use a refactoring onto `Job` and be made public.

**Comment by mikejbrown** [comment]
That should do it. :smile:
